### PR TITLE
Implement Font properties in PickerHandlers

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Implement `Font` property in PickerHandlers.

Related issue https://github.com/dotnet/maui/issues/477

### Platforms Affected ### 

- Core
- iOS
- Android

### PR Checklist ###

- [x] Targets the correct branch 
- [x] Tests are passing (or failures are unrelated)
- [x] Targets a single property for a single control (or intertwined few properties)
- [x] Adds the property to the appropriate interface
- [x] Avoids any changes not essential to the handler property
- [x] Adds the mapping to the PropertyMapper in the handler
- [x] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [x] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [x] Tags ported renderer methods with [PortHandler]
- [x] Adds an example of the property to the sample project (MainPage)
- [x] Adds the property to the stub class
- [x] Implements basic property tests in DeviceTests

### CODE REVIEW

**Review by quasialaw — APPROVED** [review]

**Review by quasialaw — APPROVED** [review]

**Review by rachelkang — APPROVED** [review]
Android tests all passing, and sample looks good
Still need to test on iOS

**Comment by mattleibow** [comment]
Moved this to draft so we don't accidentally merge this one until we switch the base back to main. That other branch has a good few fixes that this might conflict with if we merge this first.

**Comment by mattleibow** [comment]
I observed this bug https://github.com/dotnet/maui/issues/672 when reviewing this PR. I believe it is unrelated because we never set the placeholder at all.

**Pull request merged**
