### PR TITLE
Manual update for .net8 sdk and workloads

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change

Manual updates to get net8 building

### CODE REVIEW

**Review by rolfbjarne — APPROVED** [review]

**Comment by jonathanpeppers** [comment]
@grendello I think there might be an issue with the latest marshal methods changes?

Some builds are failing with:
```
D:\a\_work\1\s\bin\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.1.50\tools\Xamarin.Android.Common.targets(1717,3): error XAGPM7009: System.InvalidOperationException: Unable to translate assembly name 'Xamarin.GooglePlayServices.Base' to its index [D:\a\_work\1\s\src\BlazorWebView\tests\MauiDeviceTests\MauiBlazorWebView.DeviceTests.csproj::TargetFramework=net8.0-android] 
D:\a\_work\1\s\bin\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.1.50\tools\Xamarin.Android.Common.targets(1717,3): error XAGPM7009: at Xamarin.Android.Tasks.MarshalMethodsNativeAssemblyGenerator.WriteNativeMethods(LlvmIrGenerator generator, Dictionary`2 asmNameToIndex, LlvmIrVariableReference get_function_pointer_ref) [D:\a\_work\1\s\src\BlazorWebView\tests\MauiDeviceTests\MauiBlazorWebView.DeviceTests.csproj::TargetFramework=net8.0-android] 
D:\a\_work\1\s\bin\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.1.50\tools\Xamarin.Android.Common.targets(1717,3): error XAGPM7009: at Xamarin.Android.Tasks.MarshalMethodsNativeAssemblyGenerator.Write(LlvmIrGenerator generator) [D:\a\_work\1\s\src\BlazorWebView\tests\MauiDeviceTests\MauiBlazorWebView.DeviceTests.csproj::TargetFramework=net8.0-android] 
D:\a\_work\1\s\bin\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.1.50\tools\Xamarin.Android.Common.targets(1717,3): error XAGPM7009: at Xamarin.Android.Tasks.LLVMIR.LlvmIrComposer.Write(AndroidTargetArch arch, StreamWriter output, String fileName) [D:\a\_work\1\s\src\BlazorWebView\tests\MauiDeviceTests\MauiBlazorWebView.DeviceTests.csproj::TargetFramework=net8.0-android] 
D:\a\_work\1\s\bin\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.1.50\tools\Xamarin.Android.Common.targets(1717,3): error XAGPM7009: at Xamarin.Android.Tasks.GeneratePackageManagerJava.AddEnvironment() [D:\a\_work\1\s\src\BlazorWebView\tests\MauiDeviceTests\MauiBlazorWebView.DeviceTests.csproj::TargetFramework=net8.0-android] 
D:\a\_work\1\s\bin\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.1.50\tools\Xamarin.Android.Common.targets(1717,3): error XAGPM7009: at Xamarin.Android.Tasks.GeneratePackageManagerJava.RunTask() [D:\a\_work\1\s\src\BlazorWebView\tests\MauiDeviceTests\MauiBlazorWebView.DeviceTests.csproj::TargetFramework=net8.0-android] 
D:\a\_work\1\s\bin\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.1.50\tools\Xamarin.Android.Common.targets(1717,3): error XAGPM7009: at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 22 [D:\a\_work\1\s\src\BlazorWebView\tests\MauiDeviceTests\MauiBlazorWebView.DeviceTests.csproj::TargetFramework=net8.0-android] 
D:\a\_work\1\s\bin\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.1.50\tools\Xamarin.Android.Common.targets(1717,3): error XAGPM7009: System.InvalidOperationException: Unable to translate assembly name 'Xamarin.AndroidX.Activity' to its index [D:\a\_work\1\s\src\Graphics\samples\GraphicsTester.Android\GraphicsTester.Android.csproj] 
D:\a\_work\1\s\bin\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.1.50\tools\Xamarin.Android.Common.targets(1717,3): error XAGPM7009: at Xamarin.Android.Tasks.MarshalMethodsNativeAssemblyGenerator.WriteNativeMethods(LlvmIrGenerator generator, Dictionary`2 asmNameToIndex, LlvmIrVariableReference get_function_pointer_ref) [D:\a\_work\1\s\src\Graphics\samples\GraphicsTester.Android\GraphicsTester.Android.csproj] 
D:\a\_work\1\s\bin\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.1.50\tools\Xamarin.Android.Common.targets(1717,3): error XAGPM7009: at Xamarin.Android.Tasks.MarshalMethodsNativeAssemblyGenerator.Write(LlvmIrGenerator generator) [D:\a\_work\1\s\src\Graphics\samples\GraphicsTester.Android\GraphicsTester.Android.csproj] 
D:\a\_work\1\s\bin\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.1.50\tools\Xamarin.Android.Common.targets(1717,3): error XAGPM7009: at Xamarin.Android.Tasks.LLVMIR.LlvmIrComposer.Write(AndroidTargetArch arch, StreamWriter output, String fileName) [D:\a\_work\1\s\src\Graphics\samples\GraphicsTester.Android\GraphicsTester.Android.csproj] 
D:\a\_work\1\s\bin\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.1.50\tools\Xamarin.Android.Common.targets(1717,3): error XAGPM7009: at Xamarin.Android.Tasks.GeneratePackageManagerJava.AddEnvironment() [D:\a\_work\1\s\src\Graphics\samples\GraphicsTester.Android\GraphicsTester.Android.csproj] 
D:\a\_work\1\s\bin\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.1.50\tools\Xamarin.Android.Common.targets(1717,3): error XAGPM7009: at Xamarin.Android.Tasks.GeneratePackageManagerJava.RunTask() [D:\a\_work\1\s\src\Graphics\samples\GraphicsTester.Android\GraphicsTester.Android.csproj] 
D:\a\_work\1\s\bin\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.0-preview.1.50\tools\Xamarin.Android.Common.targets(1717,3): error XAGPM7009: at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 22 [D:\a\_work\1\s\src\Graphics\samples\GraphicsTester.Android\GraphicsTester.Android.csproj] 
 290 Warning(s) 
```

The `.binlog` is too large to attach here, but you can find it on:

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6977948&view=artifacts&pathAsName=false&type=publishedArtifacts

`build-windows` or `build-mac`, the `logs/Microsoft.Maui-Release-Build-msbuild.binlog` file.

**Comment by grendello** [comment]
@jonathanpeppers the generator is invoked from the `GeneratePackageManagerJava` and it is passed a list of unique assembly names, generated from the `ResolvedAssemblies` task parameter. It appears that out of 5 invocations of `GeneratePackageManagerJava` in the binlog, only the last one doesn't throw the error - it's the only one that is passed the assembly in question. It is also the only one that's passed assemblies from the `obj/*/assets/` folder, the others get assemblies from the `obj/*/linked/` folder. Perhaps it's a matter of the linker somehow "ignoring" that assembly and not copying it to `obj/*/linked`? The assembly has a marshal method in it (as found while scanning over assemblies with the JI type scanner) and with the way we invoke wrapped methods, the generator needs to know internal index into the array where assembly containing the marshal method is stored.

**Comment by jonathanpeppers** [comment]
@rmarinho help?

**Review by Redth — APPROVED** [review]

**Pull request merged**
