### PR TITLE
[android] update to latest AndroidX packages

### LINKED ISSUE #1904: Update to newer AndroidX packages with net6 support
There are now AndroidX bindings on NuGet with net6.0-android30.0 assets.  We need to update MAUI to use them.  This may help reduce the legacy assemblies brought in as well.

### PR DESCRIPTION
**Pull request by jonathanpeppers**
### Description of Change ###

Fixes: https://github.com/dotnet/maui/issues/1904

This partially reverts d2d7176c.

There are a few API changes in the updates.

1. `AdapterPosition` is obsolete. Use `BindingAdapterPosition` instead.

2. `IOnNavigationItemSelectedListener` is obsolete use
   `IOnItemSelectedListener` instead.

https://stackoverflow.com/questions/67641594/bottomnavigation-view-onnavigationitemselectedlistener-is-deprecated

### PR Checklist ###

- [ ] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [ ] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [ ] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [ ] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?

No

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
I see this locally, too:
```
javac error JAVAC0000:  error: ShellItemRenderer is not abstract and does not override abstract method onNavigationItemSelected(MenuItem) in OnItemSelectedListener
```
Maybe I should just ignore the obsolete API here.

**Comment by jonathanpeppers** [comment]
Related: https://github.com/xamarin/AndroidX/issues/335

Latest Material 1.4 has obsoleted this member:
```csharp
[Obsolete("This class is obsoleted in this android platform")]        [Register("com/google/android/material/bottomnavigation/BottomNavigationView$OnNavigationItemSelectedListener", "", "Google.Android.Material.BottomNavigation.BottomNavigationView/IOnNavigationItemSelectedListenerInvoker")]
public interface IOnNavigationItemSelectedListener : IOnItemSelectedListener, IJavaObject, IDisposable, IJavaPeerable
{
}
```

But even if you use `IOnItemSelectedListener`, you run into an error like:
```
(_CompileJava target) ->
  obj\Debug\net6.0-android\android\src\crc643f46942d9dd1fff9\ShellItemRenderer.java(4,8): javac.exe error JAVAC0000:  error: ShellItemRenderer is not abstract and does not override abstract method onNavigationItemSelected(MenuItem) in OnItemSelectedListener
```

I think we'll need to investigate what's happening here...

**Comment by mattleibow** [comment]
The .NET 6 PR was just merged, and thus there should be no reference to Xamarin.Forms at all

**Comment by jonathanpeppers** [comment]
@mattleibow @PureWeen

Apps seem like they generally work, but someone might build this and check that UI looks right with the latest Material libraries.

**Review by mattleibow — APPROVED** [review]

**Comment by jonathanantoine** [comment]
@jonathanpeppers it looks like the same issue is happening for the re-selection listener https://github.com/xamarin/Xamarin.Forms/issues/14692

**Pull request merged**
