### PR TITLE
Android Ecosystem updates - AndroidX

### PR DESCRIPTION
**Pull request by moljac**
### Description of Change

Android Ecosystem updates: Bumped AndroidX nugets 

Bumps the androidx group with 5 updates:

| Package | From | To |
| --- | --- | --- |
| [Xamarin.AndroidX.AppCompat.AppCompatResources](https://github.com/xamarin/AndroidX) | `1.6.1.4` | `1.6.1.5` |
| [Xamarin.AndroidX.SwipeRefreshLayout](https://github.com/xamarin/AndroidX) | `1.1.0.14` | `1.1.0.15` |
| [Xamarin.AndroidX.Lifecycle.LiveData](https://github.com/xamarin/AndroidX) | `2.6.1.3` | `2.6.2.1` |
| [Xamarin.AndroidX.Navigation.UI](https://github.com/xamarin/AndroidX) | `2.6.0.1` | `2.7.2.1` |
| [Xamarin.AndroidX.Navigation.Fragment](https://github.com/xamarin/AndroidX) | `2.6.0.1` | `2.7.2.1` |
| [Xamarin.AndroidX.Navigation.Runtime](https://github.com/xamarin/AndroidX) | `2.6.0.1` | `2.7.2.1` |
| [Xamarin.AndroidX.Navigation.Common](https://github.com/xamarin/AndroidX) | `2.6.0.1` | `2.7.2.1` |
| [Xamarin.AndroidX.Browser](https://github.com/xamarin/AndroidX) | `1.5.0.3` | `1.6.0.1` |
| [Xamarin.AndroidX.MediaRouter](https://github.com/xamarin/AndroidX) | `1.4.0.2` | `1.4.0.3` |
| [Xamarin.AndroidX.Palette](https://github.com/xamarin/AndroidX) | `1.0.0.19` | `1.0.0.20` |
| [Xamarin.AndroidX.RecyclerView](https://github.com/xamarin/AndroidX) | `1.3.1` | `1.3.1.1` |
| [Xamarin.Google.Android.Material](https://github.com/xamarin/AndroidX) | `1.9.0.2` | `1.9.0.1` |
| [Xamarin.AndroidX.Window.WindowJava](https://github.com/xamarin/AndroidX) | `1.1.0.1` | `1.1.0.2` |

### CODE REVIEW

**Comment by mattleibow** [comment]
I think the robot does this now: https://github.com/dotnet/maui/pull/17322

AI and machines taking all our work away.

**Comment by moljac** [comment]
NuGet NU1102 errors for new packages

```
2023-09-20T00:50:37.7441600Z /Users/builder/azdo/_work/2/s/src/Core/src/Core.csproj : error NU1102: Unable to find package Xamarin.AndroidX.Lifecycle.LiveData with version (>= 2.7.2.1) [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7443820Z /Users/builder/azdo/_work/2/s/src/Core/src/Core.csproj : error NU1102:   - Found 39 version(s) in dotnet-public [ Nearest version: 2.6.2.1 ] [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7445580Z /Users/builder/azdo/_work/2/s/src/Core/src/Core.csproj : error NU1102:   - Found 0 version(s) in benchmark-dotnet-prerelease [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7446890Z /Users/builder/azdo/_work/2/s/src/Core/src/Core.csproj : error NU1102:   - Found 0 version(s) in darc-pub-dotnet-emsdk-fcd8602 [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7447990Z /Users/builder/azdo/_work/2/s/src/Core/src/Core.csproj : error NU1102:   - Found 0 version(s) in darc-pub-dotnet-runtime-0ece505 [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7449290Z /Users/builder/azdo/_work/2/s/src/Core/src/Core.csproj : error NU1102:   - Found 0 version(s) in dotnet-eng [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7450700Z /Users/builder/azdo/_work/2/s/src/Core/src/Core.csproj : error NU1102:   - Found 0 version(s) in dotnet6 [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7451840Z /Users/builder/azdo/_work/2/s/src/Core/src/Core.csproj : error NU1102:   - Found 0 version(s) in dotnet7 [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7453550Z /Users/builder/azdo/_work/2/s/src/Core/src/Core.csproj : error NU1102:   - Found 0 version(s) in skiasharp [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7454420Z /Users/builder/azdo/_work/2/s/src/Controls/src/Xaml/Controls.Xaml.csproj : error NU1102: Unable to find package Xamarin.AndroidX.Lifecycle.LiveData with version (>= 2.7.2.1) [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7455970Z /Users/builder/azdo/_work/2/s/src/Controls/src/Xaml/Controls.Xaml.csproj : error NU1102:   - Found 39 version(s) in dotnet-public [ Nearest version: 2.6.2.1 ] [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7457310Z /Users/builder/azdo/_work/2/s/src/Controls/src/Xaml/Controls.Xaml.csproj : error NU1102:   - Found 0 version(s) in benchmark-dotnet-prerelease [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7458490Z /Users/builder/azdo/_work/2/s/src/Controls/src/Xaml/Controls.Xaml.csproj : error NU1102:   - Found 0 version(s) in darc-pub-dotnet-emsdk-fcd8602 [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7459720Z /Users/builder/azdo/_work/2/s/src/Controls/src/Xaml/Controls.Xaml.csproj : error NU1102:   - Found 0 version(s) in darc-pub-dotnet-runtime-0ece505 [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7461010Z /Users/builder/azdo/_work/2/s/src/Controls/src/Xaml/Controls.Xaml.csproj : error NU1102:   - Found 0 version(s) in dotnet-eng [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7462670Z /Users/builder/azdo/_work/2/s/src/Controls/src/Xaml/Controls.Xaml.csproj : error NU1102:   - Found 0 version(s) in dotnet6 [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7464400Z /Users/builder/azdo/_work/2/s/src/Controls/src/Xaml/Controls.Xaml.csproj : error NU1102:   - Found 0 version(s) in dotnet7 [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7466100Z /Users/builder/azdo/_work/2/s/src/Controls/src/Xaml/Controls.Xaml.csproj : error NU1102:   - Found 0 version(s) in skiasharp [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7467370Z /Users/builder/azdo/_work/2/s/src/Controls/src/Core/Controls.Core.csproj : error NU1102: Unable to find package Xamarin.AndroidX.Lifecycle.LiveData with version (>= 2.7.2.1) [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7469360Z /Users/builder/azdo/_work/2/s/src/Controls/src/Core/Controls.Core.csproj : error NU1102:   - Found 39 version(s) in dotnet-public [ Nearest version: 2.6.2.1 ] [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7470760Z /Users/builder/azdo/_work/2/s/src/Controls/src/Core/Controls.Core.csproj : error NU1102:   - Found 0 version(s) in benchmark-dotnet-prerelease [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7471890Z /Users/builder/azdo/_work/2/s/src/Controls/src/Core/Controls.Core.csproj : error NU1102:   - Found 0 version(s) in darc-pub-dotnet-emsdk-fcd8602 [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7473040Z /Users/builder/azdo/_work/2/s/src/Controls/src/Core/Controls.Core.csproj : error NU1102:   - Found 0 version(s) in darc-pub-dotnet-runtime-0ece505 [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7474190Z /Users/builder/azdo/_work/2/s/src/Controls/src/Core/Controls.Core.csproj : error NU1102:   - Found 0 version(s) in dotnet-eng [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7475220Z /Users/builder/azdo/_work/2/s/src/Controls/src/Core/Controls.Core.csproj : error NU1102:   - Found 0 version(s) in dotnet6 [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7476210Z /Users/builder/azdo/_work/2/s/src/Controls/src/Core/Controls.Core.csproj : error NU1102:   - Found 0 version(s) in dotnet7 [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
2023-09-20T00:50:37.7477660Z /Users/builder/azdo/_work/2/s/src/Controls/src/Core/Controls.Core.csproj : error NU1102:   - Found 0 version(s) in skiasharp [/Users/builder/azdo/_work/2/s/Microsoft.Maui.BuildTasks.slnf]
```

**Comment by moljac** [comment]
adb errors for MAUI-DeviceTests-public

```
2023-09-21T05:02:33.4669830Z WARNING | Please update the emulator to one that supports the feature(s): Vulkan
2023-09-21T05:02:33.5423660Z WARNING | Failed to process .ini file /Users/builder/.android/avd/DEVICE_TESTS_EMULATOR.avd/quickbootChoice.ini for reading.
2023-09-21T05:02:33.7759450Z   Determining projects to restore...
2023-09-21T05:02:34.1556140Z ERROR   | Unable to connect to adb daemon on port: 5037
2023-09-21T05:02:34.1980820Z WARNING | cannot add library /Users/builder/Library/Developer/Xamarin/android-sdk-macosx/emulator/qemu/darwin-x86_64/lib64/vulkan/libvulkan.dylib: failed
2023-09-21T05:02:34.7037400Z WARNING | *** No gRPC protection active, consider launching with the -grpc-use-jwt flag.***
```

**Comment by mattleibow** [comment]
I think we also need to update all the other projects: https://github.com/dotnet/maui/pull/17793/files

Unfortunately, not all the projects are using the Versions.props, so they need to be updated too. Or, we need to make those projects use the Versions.props.

**Review by Gdakgdak22 — APPROVED** [review]

**Comment by moljac** [comment]
superseded by https://github.com/dotnet/maui/pull/20783

closing this issue

**Pull request closed without merging**
