### PR TITLE
Try work around a hang in MSBuild

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change ###

This might fix our hanging builds.

https://github.com/dotnet/msbuild/issues/6753

### Additions made ###

* Adds 

### PR Checklist ###

- [ ] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [ ] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [ ] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [ ] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- [ ] Does this PR introduce a new control? (If yes, add an example using SemanticProperties to the SemanticsPage)
- [ ] APIs that modify focusability?
- [ ] APIs that modify any text property on a control?
- [ ] Does this PR modify view nesting or view arrangement in anyway?
- [ ] Is there the smallest possibility that your PR will change accessibility? 
- [ ] I'm not sure, please help me

If any of the above checkboxes apply to your PR, then the PR will need to provide testing to demonstrate that accessibility still works.

### CODE REVIEW

**Comment by Eilon** [comment]
Looks like it hung after 2 hours again 😿

**Comment by rmarinho** [comment]
Yeah .. 
https://dev.azure.com/xamarin/public/_build/results?buildId=44263&view=logs&s=117c6b5e-2c00-53b3-a67c-769fc88a90f0&j=fa3a712a-8c2e-56c6-8f3b-fe1acd0c488a

**Comment by mattleibow** [comment]
This might have fixed it! #2103

**Comment by mattleibow** [comment]
lols

**Pull request closed without merging**
