### PR TITLE
Shadows & Gradients don't work with a list view's header/footer - fix

### LINKED ISSUE #26636: [Android & iOS] Shadows & Gradients don't work with a list view's header/footer
### Description

The following code doesn't work as expected, and like the collection view does:

```
<ListView
        VerticalOptions="Center"
        HeightRequest="300">
        <ListView.Header>
                <Label 
                        FontSize="16"
                        AutomationId="HeaderLabel"
                        HorizontalTextAlignment="Center"
                        Text="(Header) This is a border with shadows">
                        <Label.Background>
                                <LinearGradientBrush
                                        StartPoint="0, 0"
                                        EndPoint="1, 1">
                                        <LinearGradientBrush.GradientStops>
                                                <GradientStop Color="#8A2387"
                                                                Offset="0.1"/>
                                                <GradientStop Color="#E94057"
                                                                Offset="0.6"/>
                                                <GradientStop Color="#F27121"
                                                                Offset="1.0"/>
                                        </LinearGradientBrush.GradientStops>
                                </LinearGradientBrush>
                        </Label.Background>
                </Label>
        </ListView.Header>
        <ListView.Footer>
                <Label
                        FontSize="16"
                        HorizontalTextAlignment="Center"
                        Text="(Footer) This is a label with shadows">
                        <Label.Shadow>
                                <Shadow
                                        Brush="Green"
                                        Radius="4"
                                        Offset="0,4"/>
                        </Label.Shadow>
                </Label>
        </ListView.Footer>
</ListView>
```

### Steps to Reproduce

_No response_

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.21 SR2.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by kubaflo**
### Description of Change

Replaced `.PlatformView` with `.ToPlatform()` to respect a `wrapperView`

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/26636

|Before|After|
|--|--|
|||

### CODE REVIEW

**Review by rmarinho — APPROVED** [review]

**Review by rmarinho — CHANGES_REQUESTED** [review]
Test seem to be failing on Android

**Comment by kubaflo** [comment]
> Test seem to be failing on Android

Is this test related to these changes?

**Review by rmarinho — APPROVED** [review]
Yeah I double check and these test failed in main also randomly . So this os good to go

**Review by rmarinho — APPROVED** [review]

**Comment by kubaflo** [comment]
> Yeah I double check and these test failed in main also randomly . So this os good to go

This should help: https://github.com/dotnet/maui/pull/26657

**Pull request merged**
