### PR TITLE
Fix format

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change

Just running dotnet format on the sln

### CODE REVIEW

**Comment by mattleibow** [comment]
Why is this so different to the bot that is supposed to be formatting out code on a regular basis? Is that just going to undo all this?

**Comment by rmarinho** [comment]
@mattleibow i thin kthe bot is just doing whitespaces

**Comment by rmarinho** [comment]
https://github.com/dotnet/maui/blob/main/.github/workflows/dotnet-format-daily.yml#L21

**Comment by hartez** [comment]
If we're going to do something like this, it should be done by a robot and regularly, not by a human. Can we just change the robot parameters?

**Comment by rmarinho** [comment]
Yeah i will try to update the script

**Pull request closed without merging**
