### PR TITLE
[Windows] Remove workaround for label text decorations

### PR DESCRIPTION
**Pull request by MartyIX**
### Description of Change

According to https://github.com/microsoft/microsoft-ui-xaml/issues/1093#issuecomment-1699855331 the issue https://github.com/microsoft/microsoft-ui-xaml/issues/1093 should be fixed in [WinUI 3 in WinAppSDK 1.4](https://github.com/microsoft/microsoft-ui-xaml/milestone/19?closed=1). Removed code was added in #726 which was three years ago. The issue was fixed last year.

### Performance impact

Two measurements for `main` branch:

* [Maui.Controls.Sample.Sandbox.exe_20240526_100801.speedscope.MAIN1.json](https://github.com/dotnet/maui/files/15446750/Maui.Controls.Sample.Sandbox.exe_20240526_100801.speedscope.MAIN1.json)
* [Maui.Controls.Sample.Sandbox.exe_20240526_101614.speedscope.MAIN2.json](https://github.com/dotnet/maui/files/15446742/Maui.Controls.Sample.Sandbox.exe_20240526_101614.speedscope.MAIN2.json)

Two measurements for the PR branch:

* [Maui.Controls.Sample.Sandbox.exe_20240526_101123.speedscope.PR1.json](https://github.com/dotnet/maui/files/15446744/Maui.Controls.Sample.Sandbox.exe_20240526_101123.speedscope.PR1.json)
* [Maui.Controls.Sample.Sandbox.exe_20240526_101346.speedscope.PR2.json](https://github.com/dotnet/maui/files/15446741/Maui.Controls.Sample.Sandbox.exe_20240526_101346.speedscope.PR2.json)

image

-> 98% improvement. It's really big so that's why I did second measurements but it appears that it really has big impact (on all labels). Anyway, even the measurements were wrong, from performance point of view *doing less takes less time*.

### Issues Fixed

Contributes to #21787

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
> I have verified that the code still works using sandbox ([branch](https://github.com/MartyIX/maui/tree/feature/2024-05-26-TextDecorations-sandbox), [MartyIX@b9c7f17](https://github.com/MartyIX/maui/commit/b9c7f17476ed6861b548f11445791b749fd3fcb4)) which simply does:
> 
> `MainPage.xaml.cs`
> 
> ```
> <ContentPage
>     xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
>     xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
>     x:Class="Maui.Controls.Sample.MainPage"
>     xmlns:local="clr-namespace:Maui.Controls.Sample">
>   <VerticalStackLayout>
>     <Label x:Name="myLabel" Text="This is the text"/>
>     <Button Text="Click me" Clicked="Button_Clicked"/>
>   </VerticalStackLayout>
> </ContentPage>
> ```
> 
> `MainPage.cs`
> 
> ```cs
> using System;
> using System.Collections.ObjectModel;
> using System.Diagnostics;
> using Microsoft.Extensions.DependencyInjection;
> using Microsoft.Maui;
> using Microsoft.Maui.Controls;
> using Microsoft.Maui.Graphics;
> 
> namespace Maui.Controls.Sample
> {
> 	public partial class MainPage : ContentPage
> 	{
> 		private int i = 0;
> 
> 		public MainPage()
> 		{
> 			InitializeComponent();
> 		}
> 
> 		private void Button_Clicked(object sender, EventArgs e)
> 		{
> 			i++;
> 			if (i % 2 == 1)
> 			{
> 				myLabel.TextDecorations = TextDecorations.Underline | TextDecorations.Strikethrough;
> 			}
> 			else
> 			{
> 				myLabel.TextDecorations = TextDecorations.None;
> 			}
> 		}
>     }
> }
> ```

Used to include an UITest.

**Review by jsuarezruiz — APPROVED** [review]

**Review by Foda — APPROVED** [review]
Great contribution! Thank you!

**Pull request merged**
