### PR TITLE
Update Windows App SDK

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change

New things! WASDK [1.4.230628000-preview1](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.4.230628000-preview1)

### CODE REVIEW

**Review by jsuarezruiz — DISMISSED** [review]

**Comment by mattleibow** [comment]
Still under a bit of discussion. We want to make sure all the tools are still good and we want to make sure we get a stable 1.4 by the time we GA. So far, things are on track. I also may wait for p2 as I hear that is coming very soon. But at least I want to test that all seems good.

**Comment by mattleibow** [comment]
Is there a particular reason you ask?

**Comment by mattleibow** [comment]
I am seeing issues with the titlebar, so pausing this for now.

**Comment by mattleibow** [comment]
Duplicate of https://github.com/dotnet/maui/pull/17104

**Pull request closed without merging**
