### PR TITLE
Account for spacing when determining available space for star rows/columns

### LINKED ISSUE #3545: GridLayout.RowSpacing is not removed from available space when doing calculations
### Description

I have a GridLayout with some rows and RowSpacing. When I add items to the grid, the bottom starts to get cut off on the screen.

Observe the button at the bottom of the page:

image

image

### Steps to Reproduce

```xaml

    <GridLayout
        RowDefinitions="Auto,*,Auto">

        <GridLayout GridLayout.Row="2" HeightRequest="100">
            <Button Text="Go To Blazor" Margin="0" Padding="20"/>
        </GridLayout>

    </GridLayout>

```

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 30

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #3853: Grid Column Content Cut Off / Width Incorrect.
### Description

ContentPage with the following code:

```
<Grid RowDefinitions="Auto" ColumnDefinitions="Auto, *, Auto" ColumnSpacing="8" BackgroundColor="Black" GridLayout.Row="0" Margin="8">
    <HorizontalStackLayout GridLayout.Row="0" GridLayout.Column="0" BackgroundColor="Pink">
        <Label>TopBar</Label>
    </HorizontalStackLayout>
    <HorizontalStackLayout GridLayout.Row="0" GridLayout.Column="2" BackgroundColor="Red">
        <Label>TopBar</Label>
    </HorizontalStackLayout>
</Grid>
```

or

```
<Grid RowDefinitions="Auto" ColumnDefinitions="Auto, *, Auto" ColumnSpacing="8" BackgroundColor="Black" GridLayout.Row="0" Margin="8">
    <Frame GridLayout.Row="0" GridLayout.Column="0" BackgroundColor="Pink">
        <Label>TopBar</Label>
    </Frame>
    <Frame GridLayout.Row="0" GridLayout.Column="2" BackgroundColor="Red">
        <Label>TopBar</Label>
    </Frame>
</Grid>
```
stack
image
frame win
image
frame android
image

### Steps to Reproduce

Copy code above into any contentpage

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 11, Windows

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by hartez**
Fixes #3853
Fixes #3545

### CODE REVIEW

**Review by rachelkang — CHANGES_REQUESTED** [review]
AFAICT this doesn't fix the issue :(

https://drive.google.com/file/d/1xb5FGcZ7CFrYgcocV5VQpfkUqfyAZ30n/view?usp=sharing

I don't think this has to do with the * as much as it has to do with `Auto`

**Comment by rachelkang** [comment]
I put this sample code directly in my local version of the control gallery sample:

```xaml
﻿<views:BasePage
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="Maui.Controls.Sample.Pages.GridPage"
    xmlns:views="clr-namespace:Maui.Controls.Sample.Pages.Base"
    Title="Grid">
    <views:BasePage.Content>
        <GridLayout RowDefinitions="Auto,*, Auto">

            <Label Text="First label" />
            <StackLayout GridLayout.Row="0" x:Name="layoutSample" />
            <Button GridLayout.Row="1" Text="Add control" Clicked="Button_Clicked" Margin="0" Padding="20"/>

        </GridLayout>
    </views:BasePage.Content>
</views:BasePage>
```

```cs
﻿using Microsoft.Maui.Controls;

namespace Maui.Controls.Sample.Pages
{
	public partial class GridPage
	{
		public GridPage()
		{
			InitializeComponent();
		}

	        private void Button_Clicked(object sender, System.EventArgs e)
	        {
		        layoutSample.Children.Add(new Label() { Text = "random label", HeightRequest = 100 });
	        }
	}
}
```

**Comment by hartez** [comment]
@rachelkang I think your test XAML has some errors. Both the `Label` with the text "First Label" and the `StackLayout` are in row 0 of the Grid, and the `Button` is in row 1; the last row is empty.

**Review by rachelkang — APPROVED** [review]

**Pull request merged**
