### PR TITLE
Feature/entry verticaltextalignment

### PR DESCRIPTION
**Pull request by ionixjunior**
### Description of Change ###

Implements #372

### Additions made ###

- Adds `VerticalTextAlignment` property to the `ITextAlignment` interface
- Adds `VerticalTextAlignment` to the PropertyMapper
- Adds `VerticalTextAlignment` mapping methods for Android and iOS
- Adds extension methods to apply `VerticalTextAlignment` on Android and iOS
- Adds `VerticalTextAlignment` in `Label` and `SearchBar` stubs
- Adds DeviceTests for initial `VerticalTextAlignment` values on Android and iOS

### PR Checklist ###

- [x] Targets the correct branch 
- [x] Tests are passing (or failures are unrelated)
- [x] Targets a single property for a single control (or intertwined few properties)
- [x] Adds the property to the appropriate interface
- [x] Avoids any changes not essential to the handler property
- [x] Adds the mapping to the PropertyMapper in the handler
- [x] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [x] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [x] Tags ported renderer methods with [PortHandler]
- [x] Adds an example of the property to the sample project (MainPage)
- [x] Adds the property to the stub class
- [x] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might effect accessibility?
- [ ] APIs that modify focusability?
- [ ] APIs that modify any text property on a control?
- [ ] Does this PR modify view nesting or view arragement in anyway?
- [ ] Is there the smallest possibility that your PR will change accessibility? 
- [ ] I'm not sure, please help me

If any of the above checkboxes apply to your PR then the PR will need to provide testing to demonstrate that accessibility still works.

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
Similar to https://github.com/dotnet/maui/pull/661
I am going to mark 661 as duplicate and close it.

**Comment by ionixjunior** [comment]
@jsuarezruiz sorry about that.

**Comment by jsuarezruiz** [comment]
@ionixjunior Oh, nothing to be sorry. Thanks for the contribution.

**Review by jsuarezruiz — APPROVED** [review]

**Review by Redth — APPROVED** [review]

**Comment by rmarinho** [comment]
Build is failing,  Can you fix that please? 

```
  D:\agent\1\s\src\Core\tests\DeviceTests\Stubs\PickerStub.cs(7,46): error CS0535: 'PickerStub' does not implement interface member 'ITextAlignment.VerticalTextAlignment' [D:\agent\1\s\src\Core\tests\DeviceTests\Core.DeviceTests.csproj]
```

Thanks

**Comment by ionixjunior** [comment]
@rmarinho sure. I'll rebase this branch and fix this as soon as possible.

**Comment by ionixjunior** [comment]
@rmarinho fixed and rebased.

**Comment by rmarinho** [comment]
It's now failing because it lacks the WINUI part.. can you do it ? 

```
  D:\agent\1\s\src\Core\src\Handlers\Entry\EntryHandler.cs(15,45): error CS0103: The name 'MapVerticalTextAlignment' does not exist in the current context [D:\agent\1\s\src\Core\src\Core-net6.csproj]
```

**Comment by ionixjunior** [comment]
@rmarinho I can't build on Windows to test it, but I saw in `EntryHandler.Windows.cs` exists some mapped properties with `MissingMapper` annotation. Could I map the `MapVerticalTextAlignment` property with this annotation for someone to implement it in the future?

**Comment by rmarinho** [comment]
@ionixjunior  yes.

**Comment by ionixjunior** [comment]
@rmarinho done!

**Pull request merged**
