### PR TITLE
Grid distribution fix

### LINKED ISSUE #16857: Grid rows not sizing properly on Windows
### Description

The vertical sizing of rows in a Grid is not sizing properly, this occurs especially when the Grid is within another Grid (though it has been observed in limited sizes with just one Grid, it's much easier to reproduce when nested). At certain sizes, the auto-sized rows have the correct, and at others they have the incorrect size.

For example, the following has the correct sizing:
correct

And the following size gives incorrect sizing:
incorrect

### Steps to Reproduce

1. Create a new .NET MAUI Project
2. Delete code from MainPage.xaml.cs (remove OnCounterClicked method).
3. Paste the following into the MainPage.xaml (replacing the ScrollView code entirely):

 ```
   <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="1*"/>
            <RowDefinition Height="100*"/>
        </Grid.RowDefinitions>

        <Grid Grid.Row="1">
            <Grid.RowDefinitions>
                <RowDefinition Height="5*"/>
                <RowDefinition Height="1*"/>
                <RowDefinition Height="14*"/>
                <RowDefinition Height="1*"/>
                <RowDefinition Height="5*"/>
            </Grid.RowDefinitions>

            <Rectangle Grid.Row="0" Grid.RowSpan="1" Background="Red" />
            <Rectangle Grid.Row="1" Grid.RowSpan="1" Background="Blue" />
            <Rectangle Grid.Row="3" Grid.RowSpan="1" Background="Blue" />
        </Grid>
    </Grid>
```

4. Run the project, and resize the vertical size to see the improper sizes.

### Link to public reproduction project repository

_No response_

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 12.0, Windows 11

### Did you find any workaround?

No, though it works better without nesting.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by john-hollander**
### Description of Change

Modifies the GridLayoutManager to fix an issue that occurs when the minimum size of one of the star definitions is larger than the star size that would be allocated to it under optimal conditions. In the previous implementation, the sizes are adjusted to make them as evenly distributed as possible, which does not fit well with the expectations for a star row/column, where the user will expect the sizes to be as close to the proportions given by the stars as possible. The current implementation uses the a similar adjustment as before, but according to the amount that the minimum differs from the target, in order to reach a value that approximates the target as closely as possible.

### Issues Fixed

Fixes #16857

### CODE REVIEW

**Comment by john-hollander** [comment]
@microsoft-github-policy-service agree

**Comment by john-hollander** [comment]
@microsoft-github-policy-service agree [company=""]

**Comment by john-hollander** [comment]
There was an error when I tried to accept the CLA the first time and now I don't see the comment that gives me the option to accept anymore. What do I need to do to be able to accept the CLA? I tried adding:
@microsoft-github-policy-service agree
@microsoft-github-policy-service agree [company=""]

**Comment by john-hollander** [comment]
@microsoft-github-policy-service agree

**Comment by john-hollander** [comment]
@microsoft-github-policy-service agree

**Comment by john-hollander** [comment]
@dotnet-policy-service agree

**Review by mattleibow — APPROVED** [review]

**Pull request merged**
