### PR TITLE
[Windows] Apply different brushes by state (Normal, PointerOver, etc)

### LINKED ISSUE #9552: Changing button background removes hover and touch down effects on Windows
### Description

I am not sure if this is intended behavior or not but when a button background is changed all of the button states are removed on windows leaving it as the same color when being hovered and pressed. I found the responsible code below. Is there a way to preserve these effects or style them without using handlers? All of our button styles are applied via global styles, so it was a bit shocking when I loaded up Maui and found that all the hover effects were gone. I couldn't find any related issues to this specifically, only some where hover effects were not going away so I imagine maybe the current status quo was a way to counter that.

[ButtonExtensions.cs](https://github.com/dotnet/maui/blob/6e851bfcf8eede68aefe301db6fa85426727e673/src/Core/src/Platform/Windows/ButtonExtensions.cs#L78)

```
		public static void UpdateBackground(this Button platformButton, IButton button)
		{
			var brush = button.Background?.ToPlatform();

			if (brush is null)
			{
				platformButton.Resources.Remove("ButtonBackground");
				platformButton.Resources.Remove("ButtonBackgroundPointerOver");
				platformButton.Resources.Remove("ButtonBackgroundPressed");
				platformButton.Resources.Remove("ButtonBackgroundDisabled");

				platformButton.ClearValue(Button.BackgroundProperty);
			}
			else
			{
				platformButton.Resources["ButtonBackground"] = brush;
				platformButton.Resources["ButtonBackgroundPointerOver"] = brush;
				platformButton.Resources["ButtonBackgroundPressed"] = brush;
				platformButton.Resources["ButtonBackgroundDisabled"] = brush;

				platformButton.Background = brush;
			}
		}`

### Steps to Reproduce

Running on windows, change any button's color and the hover and press effects will no longer set.

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

Using `ModifyMapping` for the `Background` and `TextColor` allows you to circumvent the code that removes button hover and click effects.

`            //Modify standard mapper because it ruins all on hover effects
            Microsoft.Maui.Handlers.ButtonHandler.Mapper.ModifyMapping(nameof(Microsoft.Maui.Controls.Button.Background),
                (handler, button, originalMapper) =>
                {
                    handler.PlatformView.Background = button.Background.ToColor().ToPlatform();
                });`

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Apply different brushes by state (Normal, PointerOver, etc) on Windows. 

We only have one Brush to apply to the Background and for that reason, it was also applied to the rest of the visual states (PointerOver, Focused etc). This pretty much suppresses the visual effect when moving the mouse over the control or setting focus. In this PR we apply changes to generate lighter or darker colors or brushes that we use in different states. 
fix-9552

button-brushes-tests

### Issues Fixed

Fixes #9552

### CODE REVIEW

**Review by PureWeen — CHANGES_REQUESTED** [review]
Can this be achieved purely through our XPLAT VSM vs applying assumptions into core?

I think we need to discuss and flesh out these issues
https://github.com/dotnet/maui/issues/8210
https://github.com/dotnet/maui/issues/7800

Before we do something like this

**Comment by jsuarezruiz** [comment]
To help focus and move faster, we're going to have fewer open PRs and focus on the ones we'll be working on in each release. This PR is not included in the next release so I close it for now. I will reopen it and adapt to changes later.

**Comment by jsuarezruiz** [comment]
Reopened this fix related with a Button issue.

**Review by mandel-macaque — APPROVED** [review]

**Comment by mattleibow** [comment]
I know we did the opposite of this before for some control as there was no way to properly control the disabled state. Can we just do this in the templates with _our_ VSM?

**Comment by jsuarezruiz** [comment]
> I know we did the opposite of this before for some control as there was no way to properly control the disabled state. Can we just do this in the templates with _our_ VSM?

Yes, could be another approach but that will not work removing the default Style.
https://github.com/dotnet/maui/pull/10782#issuecomment-1479920851

**Comment by rmarinho** [comment]
Yeah I think if users don0t use our style then is up to them to fix this. Is it possible for a User to provide its own style key on WINUI to override our native template?

**Comment by rmarinho** [comment]
I guess they just need to provide `ButtonBorderBrushPressed` my only question is that we also override those, so what's the  right time a user can provide its own keys ? any idea @PureWeen  ?

**Comment by PureWeen** [comment]
> But, as soon as create a custom Style for the button (without inherit from the default one, that is, without the VisualStates), we only have a Background property to set the background color and so far we have assigned and used it in all the states of the native control.

I think we still need to discuss and decide on this https://github.com/dotnet/maui/issues/7800 before taking this PR.

I like the approach of us eventually just including styles/themes as defaults that ship with the library (not the templates) then everything is setup with VSMs all the time. If the user just sets "Background" on a button, then we can mimic how windows works and this only applies to the normal state and users have to supply a VSM to change the other states. 

Wouldn't this also be a pretty big breaking change from NET7?

**Comment by jsuarezruiz** [comment]
> > But, as soon as create a custom Style for the button (without inherit from the default one, that is, without the VisualStates), we only have a Background property to set the background color and so far we have assigned and used it in all the states of the native control.
> 
> I think we still need to discuss and decide on this #7800 before taking this PR.
> 
> I like the approach of us eventually just including styles/themes as defaults that ship with the library (not the templates) then everything is setup with VSMs all the time. If the user just set "Background" on a button, then we can mimic how windows works and this only applies to the normal state and users have to supply a VSM to change the other states.
> 
> Wouldn't this also be a pretty big breaking change from NET7?

Ok, closing it for now until we review https://github.com/dotnet/maui/issues/7800

**Pull request closed without merging**
