### PR TITLE
[Tizen] Add Label TextType

### PR DESCRIPTION
**Pull request by JoonghyunCho**
### Description of Change

This PR adds
- handling Label.TextType features including FormattedText and Html type of text.
- updating Font loading process to include MauiFont as a custom font path.

At this point, Tizen.UIExtensions package which actually process the `span` creates a new line for each spans. This will be fixed in Tizen.UIExtensions package.
<image src="https://user-images.githubusercontent.com/14328614/199875898-ec0e58b3-4eb0-46f4-9aaa-6318269975c5.png" width="300" />

### CODE REVIEW

**Comment by rookiejava** [comment]
@rmarinho In addition to this PR, I think there are a few more PRs that need backporting to `net7.0`. I'll backport manually all at once soon.

**Review by rookiejava — APPROVED** [review]

**Comment by JoonghyunCho** [comment]
remake the PR https://github.com/dotnet/maui/pull/11389 against main branch

**Pull request closed without merging**
