### PR TITLE
Implement IsTextPredictionEnabled in WinUI Entry

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Implement `IsTextPredictionEnabled` in WinUI Entry.

### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [x] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [x] Avoids any changes not essential to the handler property
- [x] Adds the mapping to the PropertyMapper in the handler
- [x] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [x] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [x] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- No

### CODE REVIEW

**Review by rachelkang — COMMENTED** [review]
I'm getting a bunch of NREs thrown on MauiTextBox, which is preventing the app from deploying properly and preventing me from testing properly. Is there another PR addressing this? Or is there some added step I'm missing?

**Review by rmarinho — APPROVED** [review]

**Review by rachelkang — COMMENTED** [review]
hitting NRE and crashing as in https://github.com/dotnet/maui/pull/1149#pullrequestreview-763361655

**Comment by rmarinho** [comment]
@rachelkang  you can try again, i fixed that on main, and merged now on this branch

**Review by rachelkang — APPROVED** [review]
LGTM

**Pull request merged**
