### PR TITLE
Enable Windows device tests on net7.0

### PR DESCRIPTION
**Pull request by jfversluis**
### Description of Change

This brings #15629 and #15885 to net7.0 as well and enabled running the device tests on Windows for the .NET 7 branch. This has already been enabled for  the main branch (currently .NET 8)

### CODE REVIEW

**Comment by jfversluis** [comment]
Back to draft for a little while I figure the last bits out

**Comment by jfversluis** [comment]
Apart from the failing test that is unrelated and a more general problem, this one is good now!

**Review by rmarinho — APPROVED** [review]

**Review by samhouts — APPROVED** [review]

**Pull request merged**
