### PR TITLE
[net9.0] Update preview7 packages

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change

Updated via `darc update-dependencies --channel ".NET 9 Preview 7"`

### CODE REVIEW

**Comment by rmarinho** [comment]
What's this @jonathanpeppers  not updating android here ? thats why?
```
ILLink : error IL2122: Xamarin.Kotlin.StdLib: Type 'Xamarin.Kotlin.Resource' is not assembly qualified. Type name strings used for dynamically accessing a type should be assembly qualified. [/Users/builder/azdo/_work/2/s/src/Core/tests/DeviceTests/Core.DeviceTests.csproj::TargetFramework=net9.0-android]
ILLink : error IL2122: Xamarin.Kotlin.StdLib: Type 'Xamarin.Kotlin.Resource' is not assembly qualified. Type name strings used for dynamically accessing a type should be assembly qualified. [/Users/builder/azdo/_work/2/s/src/Core/tests/DeviceTests/Core.DeviceTests.csproj::TargetFramework=net9.0-android]
/Users/builder/.nuget/packages/microsoft.net.illink.tasks/9.0.0-preview.7.24366.18/build/Microsoft.NET.ILLink.targets(96,5): error NETSDK1144: Optimizing assemblies for size failed. [/Users/builder/azdo/_work/2/s/src/Core/tests/DeviceTests/Core.DeviceTests.csproj::TargetFramework=net9.0-android]
/Users/builder/.nuget/packages/microsoft.net.illink.tasks/9.0.0-preview.7.24366.18/build/Microsoft.NET.ILLink.targets(96,5): error NETSDK1144: Optimizing assemblies for size failed. [/Users/builder/azdo/_work/2/s/src/Core/tests/DeviceTests/Core.DeviceTests.csproj::TargetFramework=net9.0-android]
ILLink : error IL2122: Xamarin.Kotlin.StdLib: Type 'Xamarin.Kotlin.Resource' is not assembly qualified. Type name strings used for dynamically accessing a type should be assembly qualified. [/Users/builder/azdo/_work/2/s/src/Core/tests/DeviceTests/Core.DeviceTests.csproj::TargetFramework=net9.0-android]
/Users/builder/.nuget/packages/microsoft.net.illink.tasks/9.0.0-preview.7.24366.18/build/Microsoft.NET.ILLink.targets(96,5): error NETSDK1144: Optimizing assemblies for size failed. [/Users/builder/azdo/_work/2/s/src/Core/tests/DeviceTests/Core.DeviceTests.csproj::TargetFramework=net9.0-android]
ILLink : error IL2122: Xamarin.Kotlin.StdLib: Type 'Xamarin.Kotlin.Resource' is not assembly qualified. Type name strings used for dynamically accessing a type should be assembly qualified. [/Users/builder/azdo/_work/2/s/src/Core/tests/DeviceTests/Core.DeviceTests.csproj::TargetFramework=net9.0-android]
/Users/builder/.nuget/packages/microsoft.net.illink.tasks/9.0.0-preview.7.24366.18/build/Microsoft.NET.ILLink.targets(96,5): error NETSDK1144: Optimizing assemblies for size failed. [/Users/builder/azdo/_work/2/s/src/Core/tests/DeviceTests/Core.DeviceTests.csproj::TargetFramework=net9.0-android]
```

**Comment by rmarinho** [comment]
@Eilon seems we need to update something no? 

```
D:\a\1\s\artifacts\obj\Maui.Controls.Sample\Release\net9.0-windows10.0.19041\win10-x64\intermediatexaml\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Main_razor.g.cs(81,55): error CS0618: 'Router.PreferExactMatches' is obsolete: 'This property is obsolete and configuring it has not effect.' [D:\a\1\s\src\Controls\samples\Controls.Sample\Maui.Controls.Sample.csproj::TargetFramework=net9.0-windows10.0.19041]
D:\a\1\s\artifacts\obj\Maui.Controls.Sample\Release\net9.0-windows10.0.20348\win10-x64\intermediatexaml\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Main_razor.g.cs(81,55): error CS0618: 'Router.PreferExactMatches' is obsolete: 'This property is obsolete and configuring it has not effect.' [D:\a\1\s\src\Controls\samples\Controls.Sample\Maui.Controls.Sample.csproj::TargetFramework=net9.0-windows10.0.20348]
D:\a\1\s\artifacts\obj\Maui.Controls.Sample\Release\net9.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Main_razor.g.cs(81,55): error CS0618: 'Router.PreferExactMatches' is obsolete: 'This property is obsolete and configuring it has not effect.' [D:\a\1\s\src\Controls\samples\Controls.Sample\Maui.Controls.Sample.csproj::TargetFramework=net9.0]
    54 Warning(s)
    3 Error(s)

```

**Comment by jonathanpeppers** [comment]
`IL2122` issue is:
* https://github.com/dotnet/runtime/issues/105044

So is it fixed with a runtime that includes https://github.com/dotnet/runtime/commit/2b48fcddc6d8c611784d7b63189abf3d4b446c97?

**Comment by jonathanpeppers** [comment]
As a baby step you might want to merge this one first:
* https://github.com/dotnet/maui/pull/23694

**Comment by rmarinho** [comment]
> As a baby step you might want to merge this one first:
> 
> * [[net9.0] Update dependencies from dotnet/android #23694](https://github.com/dotnet/maui/pull/23694)

ok new one , missing a feed ?

```
  Workload installation failed: Version 8.0.8 of package microsoft.netcore.app.runtime.mono.android-arm is not found in NuGet feeds https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/benchmark-dotnet-prerelease/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/xamarin/public/_packaging/SkiaSharp/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-919e5b2b/nuget/v3/index.json.
```

**Comment by Eilon** [comment]
@javiercn / @MackinnonBuck / @halter73 - any idea about these Razor warnings we're starting to see in net9? Do we need to update or change something?

**Comment by jonathanpeppers** [comment]
I put a NoWarn for the Blazor/Razor issue in https://github.com/dotnet/maui/pull/23809/commits/2657e970f44b14b9e9d52acdda5feba4acfea05c, but you can see the warnings listed there.

I also updated to the latest .NET 9 Preview 7 builds of xamarin/xamarin-macios. So maybe that will fix the `clang`++ errors like:
```
Xamarin.Shared.Sdk.targets(1629,3): error : clang++ exited with code 1
```

**Comment by jonathanpeppers** [comment]
Ok, looks like Apple obsoleted some APIs:
```
/Users/builder/azdo/_work/1/s/src/Essentials/src/Connectivity/Connectivity.ios.tvos.macos.reachability.cs(146,4): error CA1422: This call site is reachable on: 'MacCatalyst' 15.0 and later. 'NetworkReachability.Schedule(CFRunLoop, string)' is obsoleted on: 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-maccatalyst]
/Users/builder/azdo/_work/1/s/src/Essentials/src/Connectivity/Connectivity.ios.tvos.macos.reachability.cs(154,4): error CA1422: This call site is reachable on: 'MacCatalyst' 15.0 and later. 'NetworkReachability.SetNotification(NetworkReachability.Notification)' is obsoleted on: 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-maccatalyst]
/Users/builder/azdo/_work/1/s/src/Essentials/src/Connectivity/Connectivity.ios.tvos.macos.reachability.cs(145,4): error CA1422: This call site is reachable on: 'MacCatalyst' 15.0 and later. 'NetworkReachability.SetNotification(NetworkReachability.Notification)' is obsoleted on: 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-maccatalyst]
/Users/builder/azdo/_work/1/s/src/Essentials/src/Connectivity/Connectivity.ios.tvos.macos.reachability.cs(155,4): error CA1422: This call site is reachable on: 'MacCatalyst' 15.0 and later. 'NetworkReachability.Schedule(CFRunLoop, string)' is obsoleted on: 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-maccatalyst]
/Users/builder/azdo/_work/1/s/src/Essentials/src/WebAuthenticator/WebAuthenticator.ios.tvos.cs(75,11): error CA1422: This call site is reachable on: 'MacCatalyst' 12.0 and later. 'ASWebAuthenticationSession' is obsoleted on: 'maccatalyst' 17.4 and later (Use the 'ASWebAuthenticationSessionCallback' overload instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-maccatalyst]
/Users/builder/azdo/_work/1/s/src/Essentials/src/HapticFeedback/HapticFeedback.ios.cs(32,17): error CA1422: This call site is reachable on: 'MacCatalyst' 15.0 and later. 'UIImpactFeedbackGenerator' is obsoleted on: 'maccatalyst' 17.5 and later (Use 'GetFeedbackGenerator' method instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-maccatalyst]
/Users/builder/azdo/_work/1/s/src/Essentials/src/HapticFeedback/HapticFeedback.ios.cs(24,17): error CA1422: This call site is reachable on: 'MacCatalyst' 15.0 and later. 'UIImpactFeedbackGenerator' is obsoleted on: 'maccatalyst' 17.5 and later (Use 'GetFeedbackGenerator' method instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-maccatalyst]
/Users/builder/azdo/_work/1/s/src/Essentials/src/Connectivity/Connectivity.ios.tvos.macos.reachability.cs(155,4): error CA1422: This call site is reachable on: 'iOS' 13.0 and later, 'maccatalyst' 13.0 and later. 'NetworkReachability.Schedule(CFRunLoop, string)' is obsoleted on: 'ios' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-ios]
/Users/builder/azdo/_work/1/s/src/Essentials/src/Connectivity/Connectivity.ios.tvos.macos.reachability.cs(154,4): error CA1422: This call site is reachable on: 'iOS' 13.0 and later, 'maccatalyst' 13.0 and later. 'NetworkReachability.SetNotification(NetworkReachability.Notification)' is obsoleted on: 'ios' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-ios]
/Users/builder/azdo/_work/1/s/src/Essentials/src/Connectivity/Connectivity.ios.tvos.macos.reachability.cs(145,4): error CA1422: This call site is reachable on: 'iOS' 13.0 and later, 'maccatalyst' 13.0 and later. 'NetworkReachability.SetNotification(NetworkReachability.Notification)' is obsoleted on: 'ios' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-ios]
/Users/builder/azdo/_work/1/s/src/Essentials/src/Connectivity/Connectivity.ios.tvos.macos.reachability.cs(146,4): error CA1422: This call site is reachable on: 'iOS' 13.0 and later, 'maccatalyst' 13.0 and later. 'NetworkReachability.Schedule(CFRunLoop, string)' is obsoleted on: 'ios' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.), 'maccatalyst' 17.4 and later (Use 'NSUrlSession' or 'NWConnection' instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-ios]
/Users/builder/azdo/_work/1/s/src/Essentials/src/HapticFeedback/HapticFeedback.ios.cs(24,17): error CA1422: This call site is reachable on: 'iOS' 13.0 and later, 'maccatalyst' 13.0 and later. 'UIImpactFeedbackGenerator' is obsoleted on: 'ios' 17.5 and later (Use 'GetFeedbackGenerator' method instead.), 'maccatalyst' 17.5 and later (Use 'GetFeedbackGenerator' method instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-ios]
/Users/builder/azdo/_work/1/s/src/Essentials/src/HapticFeedback/HapticFeedback.ios.cs(32,17): error CA1422: This call site is reachable on: 'iOS' 13.0 and later, 'maccatalyst' 13.0 and later. 'UIImpactFeedbackGenerator' is obsoleted on: 'ios' 17.5 and later (Use 'GetFeedbackGenerator' method instead.), 'maccatalyst' 17.5 and later (Use 'GetFeedbackGenerator' method instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-ios]
/Users/builder/azdo/_work/1/s/src/Essentials/src/WebAuthenticator/WebAuthenticator.ios.tvos.cs(75,11): error CA1422: This call site is reachable on: 'iOS' 12.0 and later, 'maccatalyst' 13.0 and later. 'ASWebAuthenticationSession' is obsoleted on: 'ios' 17.4 and later (Use the 'ASWebAuthenticationSessionCallback' overload instead.), 'maccatalyst' 17.4 and later (Use the 'ASWebAuthenticationSessionCallback' overload instead.). (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1422) [/Users/builder/azdo/_work/1/s/src/Essentials/src/Essentials.csproj::TargetFramework=net9.0-ios]
    0 Warning(s)
    14 Error(s)
```

**Comment by rmarinho** [comment]
@jonathanpeppers  how did you figure you had the change the macios names?

**Comment by dalexsoto** [comment]
> @jonathanpeppers how did you figure you had the change the macios names?

Probably from our CI artifact names inside the net9.0 branch, I have updated to our latest  https://github.com/xamarin/xamarin-macios/commits/release/9.0.1xx-preview7

**Comment by rmarinho** [comment]
@dalexsoto  I reverted your last commit as it wasn't able to find the versions.

**Comment by rmarinho** [comment]
@javiercn https://github.com/dotnet/maui/pull/23809/commits/3386e79bd570a04fa0ad5aa41de814ba5b5d3ef5

**Pull request merged**
