### PR TITLE
set the parents to installer

### PR DESCRIPTION
**Pull request by lewing**
This is updated dependencies against build ~~199238~~199405 of installer, It has runtime and emscripten switching to stable versions ~~but apparently not aspnetcore~~. You could definitely drop the separate variables for everything and do the substitution where they are used but hopefully this is enough to work with.

I updated the dependencies using
`darc update-dependencies --id 199405`
feel free to pick a different installer build/bar id to use

### CODE REVIEW

**Comment by trivalik** [comment]
Looks like duplicate https://github.com/dotnet/maui/pull/18085, maybe some parts are different.

**Comment by lewing** [comment]
yeah, this was part of a discussion with rui, needs several changes I'll try to make later today

**Comment by lewing** [comment]
This is updated dependencies against build 199238 of installer,  It has runtime and emscripten switching to stable versions but apparently not aspnetcore.  You could definitely drop the separate variables for everything and do the substitution where they are used but hopefully this is enough to work with.

I updated the dependencies using
`darc update-dependencies --id 199238`
feel free to pick a different installer build/bar id to use

**Comment by lewing** [comment]
It would be nice if CI would run on my prs

**Comment by lewing** [comment]
Deps have been updated to 199405 now

**Comment by jsuarezruiz** [comment]
@lewing Could you rebase to fix the conflicts?. Thanks in advance!

**Comment by lewing** [comment]
bad resolution, will fix tomorrow

**Comment by lewing** [comment]
@rmarinho @Redth do we still want this or are alternate means working now?

**Review by jonathanpeppers — DISMISSED** [review]

**Comment by rmarinho** [comment]
@lewing can you rebase this on net9 for us to try there as net8  is old news?

**Comment by lewing** [comment]
> @lewing can you rebase this on net9 for us to try there as net8 is old news?

will update soonish

**Comment by rmarinho** [comment]
Let's try this against the net9 branch , can you rebase and reopen when you have time @lewing ? 

Thanks

**Pull request closed without merging**
