### PR TITLE
Add MaxLength limit to cursor position updates

### LINKED ISSUE #15937: [iOS] Issue when using BindableLayout and Entry/Editor
### Description

I'm using a StackLayout with `BindableLayout.ItemsSource` to show Entry or Editor.
However, the app throws an exception:

`System.ArgumentNullException: Value cannot be null. (Parameter 'fromPosition')`
Screenshot 2023-06-29 at 18 44 52

### Steps to Reproduce

1. Create a .NET Maui project.
2. Add the following XAML code.

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiSample.MainPage">

    <ScrollView>
        <VerticalStackLayout
            Spacing="25"
            Padding="30,0"
            VerticalOptions="Center">


            <StackLayout Margin="10"
                         VerticalOptions="Center"
                         BindableLayout.ItemsSource="{Binding CustomList}">
                <BindableLayout.ItemTemplate>
                    <DataTemplate>
                        <Grid Margin="0,0,0,20"
                              Padding="0"
                              RowSpacing="0"
                              ColumnSpacing="0">
                            <Entry Text="{Binding Name}"
                                   MaxLength="{Binding MaxLength}"
                                   Keyboard="{Binding KeyboardType}"/>

                            <!--Same issue using Editor-->
                            <!--<Editor Text="{Binding Name}"
                                   MaxLength="{Binding MaxLength}"
                                   Keyboard="{Binding KeyboardType}"/>-->
                        </Grid>
                    </DataTemplate>
                </BindableLayout.ItemTemplate>
            </StackLayout>

            <Image
                Source="dotnet_bot.png"
                SemanticProperties.Description="Cute dot net bot waving hi to you!"
                HeightRequest="200"
                HorizontalOptions="Center" />

            <Label
                Text="Hello, World!"
                SemanticProperties.HeadingLevel="Level1"
                FontSize="32"
                HorizontalOptions="Center" />

            <Label
                Text="Welcome to .NET Multi-platform App UI"
                SemanticProperties.HeadingLevel="Level2"
                SemanticProperties.Description="Welcome to dot net Multi platform App U I"
                FontSize="18"
                HorizontalOptions="Center" />

            <Button
                x:Name="CounterBtn"
                Text="Click me"
                SemanticProperties.Hint="Counts the number of times you click"
                Clicked="OnCounterClicked"
                HorizontalOptions="Center" />

        </VerticalStackLayout>
    </ScrollView>

</ContentPage>
```

3. Add the following code behind

```c#
using System.Collections.ObjectModel;

namespace MauiSample;

public class CustomItem
{
    public string Name { get; set; }
    public double MaxLength { get; set; }
    public Keyboard KeyboardType { get; set; }
}

public partial class MainPage : ContentPage
{
	int count = 0;
	public ObservableCollection<CustomItem> CustomList { get; set; }

	public MainPage()
	{
		InitializeComponent();
		CustomList = new ObservableCollection<CustomItem>();
		AddCustomItems();
        BindingContext = this;
    }

	void AddCustomItems()
	{
		CustomList.Clear();

        for (int i = 0; i < 10; i++)
        {
            CustomList.Add(new CustomItem
            {
                MaxLength = 10,
                KeyboardType = Keyboard.Email,
                Name = "my value: " + i
            });
        }


  //      CustomList.Add(new CustomItem { Name = "Test1", MaxLength = 20, KeyboardType = Keyboard.Email });
		//CustomList.Add(new CustomItem { Name = "Test2", MaxLength = 30, KeyboardType = Keyboard.Plain });
		//CustomList.Add(new CustomItem { Name = "Test3", MaxLength = 10, KeyboardType = Keyboard.Numeric });
		//CustomList.Add(new CustomItem { Name = "Test4", MaxLength = 23, KeyboardType = Keyboard.Default });
    }

	private void OnCounterClicked(object sender, EventArgs e)
	{
		count++;

		if (count == 1)
			CounterBtn.Text = $"Clicked {count} time";
		else
			CounterBtn.Text = $"Clicked {count} times";

		SemanticScreenReader.Announce(CounterBtn.Text);
	}
}
```

4. Run the project and the app will crash.

### Link to public reproduction project repository

https://github.com/juniorsaraviao/MauiSample

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.2 and up

### Did you find any workaround?

No

### Relevant log output

```shell
Unhandled Exception:
System.ArgumentNullException: Value cannot be null. (Parameter 'fromPosition')
   at ObjCRuntime.ThrowHelper.ThrowArgumentNullException(String argumentName)
   at ObjCRuntime.NativeObjectExtensions.GetNonNullHandle(INativeObject self, String argumentName)
   at UIKit.UITextField.GetTextRange(UITextPosition fromPosition, UITextPosition toPosition)
   at Microsoft.Maui.Platform.TextInputExtensions.SetTextRange(IUITextInput platformView, Int32 start, Int32 selectedTextLength)
   at Microsoft.Maui.Controls.Platform.TextExtensions.UpdateText(UITextField textField, InputView inputView)
   at Microsoft.Maui.Controls.Entry.MapText(IEntryHandler handler, Entry entry)
   at Microsoft.Maui.Controls.Entry.MapText(EntryHandler handler, Entry entry)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.Controls.Entry, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.EntryHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IEntry, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.MauiTextField, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.EntryHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IEntry, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.MauiTextField, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.ScrollViewHandler.UpdateContentView(IScrollView scrollView, IScrollViewHandler handler)
   at Microsoft.Maui.Handlers.ScrollViewHandler.MapContent(IScrollViewHandler handler, IScrollView scrollView)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IScrollView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IScrollViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IScrollView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[UIKit.UIScrollView, Microsoft.iOS, Version=16.4.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IScrollView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[UIKit.UIScrollView, Microsoft.iOS, Version=16.4.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent(IContentViewHandler handler)
   at Microsoft.Maui.Handlers.ContentViewHandler.MapContent(IContentViewHandler handler, IContentView page)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IContentViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ViewExtensions.ToHandler(IView view, IMauiContext context)
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRootRenderer.SetPageRenderer(Page page, ShellContent shellContent)
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRootRenderer.LoadRenderers()
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRootRenderer.ViewDidLoad()
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at MauiSample.Program.Main(String[] args) in /Users/juniorsaraviao/Projects/MauiSample/Platforms/iOS/Program.cs:line 13
```

### PR DESCRIPTION
**Pull request by cat0363**
### Description of Change

An exception will occur on Android and iOS if you bind a string that exceeds the value specified in the MaxLength property to the Text property of Entry and Editor. In this PR, we will add consideration of the MaxLength property to cursor position updates.

On iOS, calling the GetTextRange method inside the SetTextRange method of the TextInputExtensions class caused an ArgumentNullException. 

[src\Core\src\Platform\iOS\TextInputExtensions.cs]

    internal static void SetTextRange(this IUITextInput platformView, int start, int selectedTextLength)
    {
        int end = start + selectedTextLength;

        // Let's be sure we have positive positions
        start = Math.Max(start, 0);
        end = Math.Max(end, 0);

        // Switch start and end positions if necessary
        start = Math.Min(start, end);
        end = Math.Max(start, end);

        var startPosition = platformView.GetPosition(platformView.BeginningOfDocument, start);
        var endPosition = platformView.GetPosition(platformView.BeginningOfDocument, end);
        platformView.SelectedTextRange = platformView.GetTextRange(startPosition, endPosition);
    }

This is because the startPosition and endPosition passed to the GetTextRange method are null. This is because null is returned if you specify an index that exceeds MaxLength in the offset of the GetPosition method. This offset should be set considering MaxLength.

I fixed it as follows.

[src\Core\src\Platform\iOS\TextInputExtensions.cs]

    internal static void SetTextRange(this IUITextInput platformView, int start, int selectedTextLength, int maxLength)
    {
        int end = start + selectedTextLength;

        // Let's be sure we have positive positions
        start = Math.Max(start, 0);
        end = Math.Max(end, 0);

        // Switch start and end positions if necessary
        start = Math.Min(start, end);
        end = Math.Max(start, end);

        if (maxLength >= 0)
        {
            start = Math.Min(start, maxLength);
            end = Math.Min(end, maxLength);
        }

        var startPosition = platformView.GetPosition(platformView.BeginningOfDocument, start);
        var endPosition = platformView.GetPosition(platformView.BeginningOfDocument, end);
        platformView.SelectedTextRange = platformView.GetTextRange(startPosition, endPosition);
    }

[src\Controls\src\Core\Platform\iOS\Extensions\TextExtensions.cs]

    public static void UpdateText(this UITextView textView, InputView inputView)
    {
        // Setting the text causes the cursor to be reset to the end of the UITextView.
        // So, let's set back the cursor to the last known position and calculate a new
        // position if needed when the text was modified by a Converter.
        var oldText = textView.Text ?? string.Empty;
        var newText = TextTransformUtilites.GetTransformedText(
            inputView?.Text,
            textView.SecureTextEntry ? TextTransform.Default : inputView.TextTransform
        );

        // Re-calculate the cursor offset position if the text was modified by a Converter.
        // but if the text is being set by code, let's just move the cursor to the end.
        var cursorOffset = newText.Length - oldText.Length;
        var cursorPosition = textView.IsFirstResponder ? textView.GetCursorPosition(cursorOffset) : newText.Length;

        if (oldText != newText)
            textView.Text = newText;

        textView.SetTextRange(cursorPosition, 0, inputView.MaxLength);
    }

    public static void UpdateText(this UITextField textField, InputView inputView)
    {
        // Setting the text causes the cursor to be reset to the end of the UITextView.
        // So, let's set back the cursor to the last known position and calculate a new
        // position if needed when the text was modified by a Converter.
        var oldText = textField.Text ?? string.Empty;
        var newText = TextTransformUtilites.GetTransformedText(
            inputView?.Text,
            textField.SecureTextEntry ? TextTransform.Default : inputView.TextTransform
        );

        // Re-calculate the cursor offset position if the text was modified by a Converter.
        // but if the text is being set by code, let's just move the cursor to the end.
        var cursorOffset = newText.Length - oldText.Length;
        var cursorPosition = textField.IsEditing ? textField.GetCursorPosition(cursorOffset) : newText.Length;

        if (oldText != newText)
            textField.Text = newText;

        textField.SetTextRange(cursorPosition, 0, inputView.MaxLength);
    }

On Android, calling the SetSelection method inside the UpdateText method of the EditTextExtensions class caused an IndexOutOfBoundsException. 

[src\Controls\src\Core\Platform\Android\Extensions\EditTextExtensions.cs]

    public static void UpdateText(this EditText editText, InputView inputView)
    {
        (var oldText, var newText) = GetTexts(editText, inputView);

        if (oldText != newText)
        {
            editText.Text = newText;

            // When updating from xplat->plat, we set the selection (cursor) to the end of the text
            editText.SetSelection(newText.Length);
        }
    }

This is because an index exceeding the MaxLength property was specified as an argument when the SetSelection method was called.

I fixed it as follows.

[src\Controls\src\Core\Platform\Android\Extensions\EditTextExtensions.cs]

    public static void UpdateText(this EditText editText, InputView inputView)
    {
        (var oldText, var newText) = GetTexts(editText, inputView);

        if (oldText != newText)
        {
            editText.Text = newText;

            // When updating from xplat->plat, we set the selection (cursor) to the end of the text
            int selectionLength = newText.Length;
            if (inputView.MaxLength >= 0)
            {
                selectionLength = Math.Min(selectionLength, inputView.MaxLength);
            }
            editText.SetSelection(selectionLength);
        }
    }

On Windows, the exception is not thrown, but updating the cursor position requires a similar fix.

[src\Controls\src\Core\Platform\Windows\Extensions\TextBoxExtensions.cs]

    public static void UpdateText(this TextBox platformControl, InputView inputView)
    {
        var hasFocus = platformControl.FocusState != UI.Xaml.FocusState.Unfocused;
        var passwordBox = platformControl as MauiPasswordTextBox;
        var isPassword = passwordBox?.IsPassword ?? false;
        var textTransform = inputView?.TextTransform ?? TextTransform.None;

        // Setting the text causes the cursor to be reset to position zero.
        // So, let's retain the current cursor position and calculate a new cursor
        // position if the text was modified by a Converter.
        var oldText = platformControl.Text ?? string.Empty;
        var newText = TextTransformUtilites.GetTransformedText(
            inputView?.Text,
            isPassword ? TextTransform.None : textTransform
        );

        // Re-calculate the cursor offset position if the text was modified by a Converter.
        // but if the text is being set by code, let's just move the cursor to the end.
        var cursorOffset = newText.Length - oldText.Length;
        int cursorPosition = hasFocus ? platformControl.GetCursorPosition(cursorOffset) : newText.Length;

        if (inputView?.MaxLength >= 0)
        {
            cursorPosition = Math.Min(cursorPosition, inputView.MaxLength);
        }

        if (oldText != newText && passwordBox is not null)
            passwordBox.Password = newText;
        else if (oldText != newText)
            platformControl.Text = newText;

        platformControl.Select(cursorPosition, 0);
    }

However, there is no problem with the Windows TextBox Select method even if you specify an Index that exceeds MaxLength, so there is no problem even if you do not include a guard condition.

In addition to the solution in PR #7371, the MaxLength property should be considered.
This PR targets iOS, Android, and Windows, which were targeted for fixes in PR #7371.

### Issues Fixed

Fixes #15937

### CODE REVIEW

**Comment by juniorsaraviao** [comment]
who should review this PR?

**Comment by waguilar** [comment]
I have the same issue :/
Any chance someone can review this PR, pretty please?

**Comment by rodrigojuarez** [comment]
+1

**Comment by jfversluis** [comment]
Hey @cat0363 I was just looking into this one, it seems like some work was done in this area. Could you confirm that this fix is still needed? And if you think it is, could you rebase it? Thanks!

**Comment by cat0363** [comment]
@jfversluis , Thank you for the good news.
I tested the latest version of main and confirmed that the issue was resolved on Android, iOS, and Windows platforms.
I was busy with my day job, so my reply was delayed.

**Comment by jfversluis** [comment]
Hehehe no worries my friend, I think we should be apologising to you for the delay on this PR 😉 

Thanks for your efforts here and confirming this is fixed! Looking forward to your future work on this project!

**Pull request closed without merging**
