### PR TITLE
Fixing image shadows on Windows

### LINKED ISSUE #3082: [Bug] Ain't no shadow like a Windows shadow
### Description

I've been experimenting with shadows, and they render beautifully on Android:

```
<Image Source="dotnet_bot.png"
       WidthRequest="250"
       HeightRequest="310">
    <Image.Shadow>
        <Shadow Brush="Black"
                Offset="20,20"
                Radius="40"
                Opacity="0.8" />
    </Image.Shadow>
</Image>
```

image

Then I switched to Windows:

win1

'Nuff said.

### Steps to Reproduce

1. Run the attached sample on Windows.

### Expected Behavior

Shadows as per on Android.

### Actual Behavior

The horror. The horror.

### Basic Information

- Version with issue: preview.9.1843
- IDE: VS 17.0 P6
- Platform Target Frameworks:
  - Android: API 31
  - Win: 10.0.18362.0

### Reproduction Link

[ShadowsDemo.zip](https://github.com/dotnet/maui/files/7397479/ShadowsDemo.zip)

### PR DESCRIPTION
**Pull request by VSadov**
### Description of Change

GetAlphaMaskAsync tries to render an image into a render target bitmap and then fetch pixel data to create alpha mask.
According to the comments in the code we use this approach instead of getting the alpha mask directly from the visual because it could potentially result in a clipped mask.

It was observed that `RenderAsync` sometimes does not work properly in this case and returns 0x0 image. Possibly because the rendering happens on the first measure pass and maybe that is too early.

In this fix we detect the bad render result and fallback to `image.GetAlphaMask()` as returning `null` mask results in something that looks a lot worse.

### Issues Fixed

Fixes #3082

### CODE REVIEW

**Comment by VSadov** [comment]
== Before:
Before

**Comment by VSadov** [comment]
After the fix:
After

**Comment by VSadov** [comment]
@jsuarezruiz  I am wondering 
- Should we just use `Image.GetAlphaMask();` for images? 
- And perhaps for shapes as well?

**Review by jsuarezruiz — APPROVED** [review]

**Comment by jsuarezruiz** [comment]
> @jsuarezruiz I am wondering
> 
> * Should we just use `Image.GetAlphaMask();` for images?
> * And perhaps for shapes as well?

Yes, I think we can check the types and if we are using TextBlock, Image or Shapes use the GetAlphaMask method.

**Comment by VSadov** [comment]
@jsuarezruiz - is this ok to merge? Thanks!

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
