### PR TITLE
[build] Add support for Visual Studio on win-arm64

### PR DESCRIPTION
**Pull request by jonathanpeppers**
### Description of Change

Context: https://github.com/dotnet/maui/issues/11090
Context: https://github.com/xamarin/yaml-templates/pull/204
Context: https://github.com/xamarin/xamarin-android/pull/7471
Context: https://github.com/xamarin/xamarin-macios/pull/16935

Updates the VSMAN files generated for our .NET workload to support Visual Studio on windows-arm64.

### CODE REVIEW

**Review by mattleibow — APPROVED** [review]

**Comment by mattleibow** [comment]
Is there some flag or light that I can see on CI artifacts to make sure this all kicked in?

**Comment by jonathanpeppers** [comment]
If you look at a signed build, like xamarin-android/main:

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7029241&view=artifacts&pathAsName=false&type=publishedArtifacts

`Microsoft.NET.Sdk.Android.Workload.net8.0.multitarget.vsman` has:

```json
  "packages": [
    {
      "id": "Microsoft.Android.Sdk.net8.34.0.0-preview.1.74",
      "version": "34.0.0.0",
      "type": "Msi",
      "machineArch": "arm64
```

I don't know if you can see that until this is merged? Do PRs build `.vsman` files?

**Comment by mattleibow** [comment]
> Do PRs build .vsman files?

I don't think so, but I will check it once merged to confirm.

**Comment by jonathanpeppers** [comment]
@mattleibow the build is done from where this merged, what artifact contains the `.vsman` file?

@pjcollins you might know.

**Comment by pjcollins** [comment]
@jonathanpeppers I think https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7036408&view=results is the pipeline you'll want.

**Comment by jonathanpeppers** [comment]
@Redth @mattleibow this looks right to me:

```json
  "packages": [
    {
      "id": "Maui.Sdk.net7.7.0.0-ci.net7.7216",
      "version": "7.0.0.0",
      "type": "Msi",
      "machineArch": "arm64",
```

How do we backport to .NET 6 and 7?

**Pull request merged**
