### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by rookiejava**
This PR updates the Tizen backend module owner correctly for ensuring code quality and faster issue handling.

ℹ️ It would be more appreciated if you could create a group like `@dotnet/dotnet-maui-tizen-eng` and put us in it instead of specifying individuals.

### CODE REVIEW

**Comment by rookiejava** [comment]
> It would be more appreciated if you could create a group like @dotnet/dotnet-maui-tizen-eng and put us in it instead of specifying individuals

@Redth @rmarinho @davidortinau  Could you take care of this?

**Review by jsuarezruiz — APPROVED** [review]

**Comment by Eilon** [comment]
Currently this file is invalid because the people listed are not contributors, so it sounds like GitHub will ignore those lines anyway?

image

And:

image

**Comment by Eilon** [comment]
As such, I believe that merging this PR will not do anything.

It seems that the people have to have Write access in order for a `CODEOWNERS` file to do anything.

**Review by Eilon — DISMISSED** [review]
See earlier comment.

**Comment by rookiejava** [comment]
> As such, I believe that merging this PR will not do anything.
> 
> It seems that the people have to have Write access in order for a `CODEOWNERS` file to do anything.

Yes, that's why I've been been requesting that permission for a long tome for proper Tizen backend support.

Anyway, as you said, it's true that we need write permission to github's CODEOWNERS work properly. (If anyone can help, I would appreciate it.) But even before the permission issue is resolved, this file needs to be updated correctly. It's limited, but I think this will help users know who is reponsible for Tizen backend.

**Comment by jfversluis** [comment]
I'll merge it for now so that it's at least a little bit more up to date?

We still have #1747 to track the actual updating.

**Review by jfversluis — APPROVED** [review]

**Pull request merged**
