### PR TITLE
Move TabbedPageHandler to TabbedViewHandler

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change ###

Currently TabbedPage code lives inside Controls under `TabbedPageHandler`. Ideally all of that code will one day move into `Maui.Core.TabbedViewHandler` and then we use the standard `Remap` patterns where we need to.

This PR sets up an empty `TabbedViewHandler` and then remaps everything inside `Controls.TabbedPage`. This allows us to only surface the API we want instead of just having some temporary APIs (`TabbedPageHandler`) that we will eventually just deprecate.

This PR should have no functional changes. It's mainly just moving code around

### Additions made ###

- Adds `ITabbedView`
- Sets `TabbedPageManager` to internal and then I setup calls from the mappers into `TabbedPageManager` so that users can replace the mappers in an expected way

### CODE REVIEW

**Review by jsuarezruiz — DISMISSED** [review]
Testing the branch with the Gallery get some exceptions trying to open the TabbedPage Gallery.
image

**Comment by PureWeen** [comment]
Should be fixed now @jsuarezruiz

**Review by Redth — APPROVED** [review]

**Comment by maonaoda** [comment]
@PureWeen 
In the original Android TabbedPageHandler, I could get the BottomNavigationView like this, but since tabbedPageManager is non-exposed, how do I get the BottomNavigationView using TabbedViewHandler?

https://github.com/dotnet/maui/blob/d287e2f1e7e614c25689efed243d6d1efb4e68aa/src/Controls/src/Core/Handlers/TabbedPage/TabbedPageHandler.Android.cs#L14
```
		public TabLayout TabLayout =>
			_tabbedPageManager.IsBottomTabPlacement ? null :
				_tabbedPageManager.TabLayout;

		public BottomNavigationView BottomNavigationView =>
			_tabbedPageManager.IsBottomTabPlacement ? _tabbedPageManager.BottomNavigationView :
				null;
```

**Pull request merged**
