### PR TITLE
ICanvas.DrawText - System.NotImplementedException

### PR DESCRIPTION
**Pull request by luckybc2021**
```
public void Draw(ICanvas canvas, RectF dirtyRect)
{
      string markdownText = @"This is *italic text*, **bold text**, __underline text__, and ***bold italic text***.";
      var attributedText = MarkdownAttributedTextReader.Read(markdownText); // Requires the Microsoft.Maui.Graphics.Text.Markdig package
	canvas.DrawText(attributedText, 0, 0, 400, 100); **//System.NotImplementedException: 'The method or operation is not implemented.'**
}
```

I added the new package of Microsoft.Maui.Graphics.Text.Markdig, version 7.0.81+11-sha.4f59bc012-azdo.7507992.

### CODE REVIEW

**Comment by luckybc2021** [comment]
@dotnet-policy-service agree

**Comment by luckybc2021** [comment]
> 

So what should I do right now? I really need the ICanvas.DrawText for many stuffs.

**Comment by luckybc2021** [comment]
> I'm just saying that your PR description _I added the new package of Microsoft.Maui.Graphics.Text.Markdig, version 7.0.81+11-sha.4f59bc012-azdo.7507992._ does not seem to correspond with the actual code diff.
> 
> So I guess that locally you have a different diff than on Github. Is that true or am I wrong?

How to fix that?

**Comment by luckybc2021** [comment]
> public void Draw(ICanvas canvas, RectF dirtyRect)
> {
>       string markdownText = @"This is *italic text*, **bold text**, __underline text__, and ***bold italic text***.";
>       var attributedText = MarkdownAttributedTextReader.Read(markdownText); // Requires the Microsoft.Maui.Graphics.Text.Markdig package
> 	canvas.DrawText(attributedText, 0, 0, 400, 100); **//System.NotImplementedException: 'The method or operation is not implemented.'**
> }

I did it,

https://discord.com/channels/732297728826277939/732297916680765551/1100364254814683137

**Comment by Eilon** [comment]
Hi, this PR appears to merge the entire net7.0 branch into main, which is probably not what you intended. I recommend creating a _new_ fork of this repo, adding your changes, and then submit a new PR.

**Pull request closed without merging**
