### PR TITLE
Remove FontImageExtension

### PR DESCRIPTION
**Pull request by jfversluis**
### Description of Change

Ports [this fix/obsoletion](https://github.com/xamarin/Xamarin.Forms/pull/12903) from Xamarin.Forms

> this markup extension is a pass-through and does nothing, but add some
> restricition (can't bind, or set dynamic resource to Color, e.g.). Using
> the FontImageSource as a markup, like in {FontImageSource}, doesn't
> have those restricitions, and reduce the amount of processing and
> allocation. It should be used instead

### Issues Fixed

NA original Forms issue: https://github.com/xamarin/Xamarin.Forms/issues/12851

### Other

When using this in XAML we now get this warning, is that expected? I guess this is something to be done on the tooling side?

image

### CODE REVIEW

**Comment by mattleibow** [comment]
Does this work? The `{FontImageSource}` is not a markup extension, so how does it work? Are we writing custom code in the parser for this? Should we be making these exceptions in code instead of using the markup extensions as they are designed for this.

**Comment by jfversluis** [comment]
The unit test passes at least 🤷  not sure what the intent was for this change, just figured if we wanted to still do this the time is now. I pinged Stephane already and we'll be talking about it!

**Comment by StephaneDelcroix** [comment]
@mattleibow we've always supported in our parsers and inflaters the use of markup-like syntax for non-marker types. It makes XAML so much more readable. But we should align with @mgoertz-msft so it doesn't issue a warning

**Comment by StephaneDelcroix** [comment]
> So what's the rule here? How does the user know what can be treated like a markup extension?

no rule. everything could technically be written as a markup. `{Label Text='foo'}` would be valid... I understand it doesn't make the Intelisense easy at all... I would provide completion based on the property type

**Comment by mgoertz-msft** [comment]
FYI @maddymontaquila 

Wow, so that's not just a bug then. This is a whole new feature request for the tooling. Is this true for Xamarin Forms as well? And if so, why have we never seen any reports about that?

Perhaps users don't even know this exists, and if so, should it actually exist?

**Comment by jfversluis** [comment]
Won't build, needs changes in tooling, I think we're OK here for now to let this slide

**Pull request closed without merging**
