### PR TITLE
Implement rate for TextToSpeech on supported platforms

### LINKED ISSUE #14851: TTS: Speech rate in SpeechOptions and more
### Description

The current support for TTS in MAUI seems very basic. I have following requests -

1. Control speech rate/speed
`SpeechOptions` does not contain any property to control speech rate, and this should be a **P0** scenario to be supported. Any app which has TTS functionality, cannot offer it without speech rate control.
Is there any workaround for Android for this?

2. Callback/Event to track which utterance has been completed
Currently `SpeakAsync()` is fire and forget, there should be some mechanism to pass Id and get callback once the utterance is complete, so that program can track the progress. There are some ways to do it outside from the program but it could be error prone, but out of the box would me preferred and better.

3. Support for SSML?

### Public API Changes

`SpeechOptions` 

`ITextToSpeech.SpeakAsync`

### Intended Use-Case

I have an epub book reader app on UWP, and I am trying to port it to Android. The app offers TTS support, and most users prefer to set the speech rate as per the preference. The current lack of speech control in MAUI appears to be a blocker.

Any short-term workaround available for Android would help me unblock.

### PR DESCRIPTION
**Pull request by tiaanv**
### Description of Change

Attempting to dosome good and implement a Rate option on TextToSpeech.  Rate is not supported for all platforms, but on most.

### Issues Fixed

#14851 

Fixes #

- Implemented Additional Rate option
- Implementation for Android
- Implemenetation for UWP
- Implementation for macos
- Implementation for watchos

It might be possible to implement for Tizen as well, but Pitch is being used already to specify rate, so don't want to change that at this stage. Unable to test all platforms.

### CODE REVIEW

**Comment by tiaanv** [comment]
@dotnet-policy-service agree
@dotnet-policy-service agree
@dotnet-policy-service agree company="Microsoft"

**Review by rmarinho — CHANGES_REQUESTED** [review]
You need to add more api changes to other platforms.

```
D:\a\_work\1\s\src\Essentials\src\TextToSpeech\TextToSpeech.shared.cs(263,24): error RS0016: Symbol 'Rate.get' is not part of the declared public API [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj::TargetFramework=net7.0-maccatalyst]
D:\a\_work\1\s\src\Essentials\src\TextToSpeech\TextToSpeech.shared.cs(263,29): error RS0016: Symbol 'Rate.set' is not part of the declared public API [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj::TargetFramework=net7.0-maccatalyst]
D:\a\_work\1\s\src\Essentials\src\TextToSpeech\TextToSpeech.shared.cs(263,24): error RS0016: Symbol 'Rate.get' is not part of the declared public API [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj::TargetFramework=net7.0-windows10.0.19041]
D:\a\_work\1\s\src\Essentials\src\TextToSpeech\TextToSpeech.shared.cs(263,29): error RS0016: Symbol 'Rate.set' is not part of the declared public API [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj::TargetFramework=net7.0-windows10.0.19041]
D:\a\_work\1\s\src\Essentials\src\TextToSpeech\TextToSpeech.shared.cs(263,24): error RS0016: Symbol 'Rate.get' is not part of the declared public API [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj::TargetFramework=net7.0-windows10.0.20348]
D:\a\_work\1\s\src\Essentials\src\TextToSpeech\TextToSpeech.shared.cs(263,29): error RS0016: Symbol 'Rate.set' is not part of the declared public API [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj::TargetFramework=net7.0-windows10.0.20348]
D:\a\_work\1\s\src\Essentials\src\TextToSpeech\TextToSpeech.shared.cs(263,24): error RS0016: Symbol 'Rate.get' is not part of the declared public API [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj::TargetFramework=net7.0-tizen]
D:\a\_work\1\s\src\Essentials\src\TextToSpeech\TextToSpeech.shared.cs(263,29): error RS0016: Symbol 'Rate.set' is not part of the declared public API [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj::TargetFramework=net7.0-tizen]
D:\a\_work\1\s\src\Essentials\src\TextToSpeech\TextToSpeech.shared.cs(263,24): error RS0016: Symbol 'Rate.get' is not part of the declared public API [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj::TargetFramework=net7.0-ios]
D:\a\_work\1\s\src\Essentials\src\TextToSpeech\TextToSpeech.shared.cs(263,29): error RS0016: Symbol 'Rate.set' is not part of the declared public API [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj::TargetFramework=net7.0-ios]
D:\a\_work\1\s\src\Essentials\src\TextToSpeech\TextToSpeech.shared.cs(263,24): error RS0016: Symbol 'Rate.get' is not part of the declared public API [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj::TargetFramework=net7.0-android]
D:\a\_work\1\s\src\Essentials\src\TextToSpeech\TextToSpeech.shared.cs(263,29): error RS0016: Symbol 'Rate.set' is not part of the declared public API [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj::TargetFramework=net7.0-android]
    16 Warning(s)
    12 Error(s)
```

**Comment by jfversluis** [comment]
@tiaanv are you happy to take this any further? Thanks!

**Pull request closed without merging**
