### PR TITLE
[android] improve FormattedString performance

### LINKED ISSUE #14222: CollectionView+FormattedString Poor Performance
### Description

When using a Collection View with a formatted string inside a grid, the scroll performance or framerate is severely reduced. 

Similar issue was found Open in the Xamarin Forms repo: https://github.com/xamarin/Xamarin.Forms/issues/5087

Here is a video of it scrolling smoothly (using a model property)

https://user-images.githubusercontent.com/12143535/228093105-21e2cc76-2d28-4252-afa2-814ccfaef1dd.mp4

And a video of it very choppy (using FormattedString)

https://user-images.githubusercontent.com/12143535/228093142-8d3c00fa-0ef0-4d7b-a322-83c9da1de010.mp4

Its subtle, but noticeable enough to be a problem for users.

### Steps to Reproduce

1. Add a CollectionView with an Item Template. 
2. Inside the item template add a grid and display some Labels. 
3. Include a label with a few Spans in formatted string. 
4. Observe performance impact versus a code-centric model binding.

### Link to public reproduction project repository

https://github.com/shadowfoxish/Temp-CollectionViewFormattedStringSlowness

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Tested on Android 9.0, API 28

### Did you find any workaround?

Using a get-only model property eliminates the need for FormattedString, but breaks the Model-View-ViewModel paradigm as it pushes UI logic into the Model or ViewModel.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jonathanpeppers**
Context: https://github.com/Redth/MauiCollectionViewGallery
Fixes #14222

This depends on changes in:

* https://github.com/dotnet/maui/pull/20352

(as both of these would conflict with each other)

Profiling the above sample while scrolling on a Pixel 5, a lot of time is spent in `FormattedStringExtensions.RecalculateSpanPositions()`:

    (20%) Microsoft.Maui.Controls!Microsoft.Maui.Controls.Platform.FormattedStringExtensions.RecalculateSpanPositions(Android.Widget.TextView,Microsoft.Maui.Controls.Label,Android.Text.SpannableString,Microsoft.Maui.SizeRequest)
    (11%) Microsoft.Maui.Controls!Microsoft.Maui.Controls.Platform.FormattedStringExtensions.FontSpan.UpdateDrawState(Android.Text.TextPaint)
    (11%) Microsoft.Maui.Controls!Microsoft.Maui.Controls.Platform.FormattedStringExtensions.FontSpan.Apply(Android.Text.TextPaint)
    (6.3%) MauiCollectionViewGallery!PoolMathApp.Helpers.FormattedTextExtensions.ToFormattedString(PoolMathApp.Models.FormattedTex

The key contributors are `FontSpan` and `LineHeightSpan` which:

* Implement `MetricAffectingSpan`, an abstract class that allows to change the metrics of the text.

* Implement `UpdateDrawState()` and `Apply()` methods that are called during draw. Causing frequent Java -> C# interop.

To fix this, let's move the following types from C# to Java:

* `FontSpan` -> `PlatformFontSpan`
* `LetterSpacingSpan` -> `PlatformFontSpan` (use different ctor)
* `LineHeightSpan` -> `PlatformLineHeightSpan`

`PlatformLineHeightSpan` is similar, as it is an implementation of the `LineHeightSpan` interface.

With these changes, I see a nice improvement while scrolling:

    (5.5%) Microsoft.Maui.Controls!Microsoft.Maui.Controls.Platform.FormattedStringExtensions.RecalculateSpanPositions(Android.Widget.TextView,Microsoft.Maui.Controls.Label,Android.Text.SpannableString,Microsoft.Maui.SizeRequest)
    (4.0%) MauiCollectionViewGallery!PoolMathApp.Helpers.FormattedTextExtensions.ToFormattedString(PoolMathApp.Models.FormattedText

`RecalculateSpanPositions` overall, went from 20% to 5.5%!

Comparing the new types, the times spent calling the constructors are also improved:

    Before:
    (1.1%) Microsoft.Maui.Controls!Microsoft.Maui.Controls.Platform.FormattedStringExtensions.FontSpan..ctor(Microsoft.Maui.Font,M
    (1.5%) Microsoft.Maui.Controls!Microsoft.Maui.Controls.Platform.FormattedStringExtensions.LetterSpacingSpan..ctor(double)
    After:
    (1.0%) Microsoft.Maui!Microsoft.Maui.PlatformFontSpan..ctor(Android.Content.Context,Android.Graphics.Typeface,bool,single)
    (0.82%) Microsoft.Maui!Microsoft.Maui.PlatformFontSpan..ctor(single)

This should be reasonable for .NET 8servicing, as there should be no behavior changes and no API changes.

In a future PR, it looks like `FormattedStringExtensions` could be improved further, but this is a decent starting point that makes it a lot better.

### CODE REVIEW

**Review by jsuarezruiz — APPROVED** [review]

**Review by mattleibow — APPROVED** [review]

**Review by mattleibow — COMMENTED** [review]
At some point, this whole method can go into Java code. We can pass in all the values as some sort of parameter list and then no interop at all.

**Comment by mfeingol** [comment]
@jonathanpeppers:

Seeing an odd exception with MAUI 8.0.21 on Android 13. Not seeing this on Android 14. Seems maybe related to your changes here?

```
**Java.Lang.ClassNotFoundException:** 'Didn't find class "com.microsoft.maui.PlatformFontSpan" on path: DexPathList[[zip file "/data/app/~~tkOQN3Wonatt6TCbe0utjA==/com.Backroads.Android-Fo7Ncpx4zIZErEBcne04UQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~tkOQN3Wonatt6TCbe0utjA==/com.Backroads.Android-Fo7Ncpx4zIZErEBcne04UQ==/lib/x86_64, /data/app/~~tkOQN3Wonatt6TCbe0utjA==/com.Backroads.Android-Fo7Ncpx4zIZErEBcne04UQ==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]'
```

```
 	0xFFFFFFFFFFFFFFFF in Android.Runtime.RuntimeNativeMethods.monodroid_debugger_unhandled_exception	C#
 	0x1A in Android.Runtime.JNINativeWrapper._unhandled_exception at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:13,5	C#
 	0x23 in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_L at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:368,26	C#
 	0x168 in Java.Interop.JniEnvironment.Types.TryFindClass at /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.Types.cs:89,5	C#
 	0x2 in Java.Interop.JniEnvironment.Types.FindClass at /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.Types.cs:37,5	C#
 	0x7 in Java.Interop.JniType..ctor at /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniType.cs:51,4	C#
 	0x19 in Java.Interop.JniType.GetCachedJniType at /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniType.cs:106,4	C#
 	0xC in Java.Interop.JniPeerMembers.get_JniPeerType at /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.cs:83,5	C#
 	0x17 in Java.Interop.JniPeerMembers.JniInstanceMethods.get_JniPeerType at /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs:37,9	C#
 	0x3F in Java.Interop.JniPeerMembers.JniInstanceMethods.StartCreateInstance at /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs:139,4	C#
 	0x48 in Microsoft.Maui.PlatformFontSpan..ctor at D:\a\_work\1\s\src\Core\src\obj\Release\net8.0-android\generated\src\Microsoft.Maui.PlatformFontSpan.cs:85,5	C#
 	0x18C in Microsoft.Maui.Controls.Platform.FormattedStringExtensions.ToSpannableStringNewWay at D:\a\_work\1\s\src\Controls\src\Core\Platform\Android\Extensions\FormattedStringExtensions.cs:112,6	C#
 	0x5D in Microsoft.Maui.Controls.Platform.FormattedStringExtensions.ToSpannableString at D:\a\_work\1\s\src\Controls\src\Core\Platform\Android\Extensions\FormattedStringExtensions.cs:17,7	C#
 	0x19 in Microsoft.Maui.Controls.Platform.TextViewExtensions.UpdateText at D:\a\_work\1\s\src\Controls\src\Core\Platform\Android\Extensions\TextViewExtensions.cs:18,7	C#
 	0x7 in Microsoft.Maui.Controls.Label.MapText at D:\a\_work\1\s\src\Controls\src\Core\Label\Label.Android.cs:41,4	C#
 	0x8 in Microsoft.Maui.PropertyMapperExtensions.<>c__DisplayClass2_0<Microsoft.Maui.Controls.Label,Microsoft.Maui.Handlers. at D:\a\_work\1\s\src\Core\src\PropertyMapperExtensions.cs:66,79	C#
 	0x2D in Microsoft.Maui.PropertyMapperExtensions.<>c__DisplayClass1_0<Microsoft.Maui.Controls.Label,Microsoft.Maui.Handlers. at D:\a\_work\1\s\src\Core\src\PropertyMapperExtensions.cs:46,6	C#
 	0x21 in Microsoft.Maui.PropertyMapper<Microsoft.Maui.ILabel,Microsoft.Maui.Handlers.ILabelHandler>. at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:172,6	C#
 	0x17 in Microsoft.Maui.PropertyMapper.UpdatePropertyCore at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:47,4	C#
 	0x8 in Microsoft.Maui.PropertyMapper.UpdateProperty at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:72,4	C#
 	0x1C in Microsoft.Maui.Handlers.ElementHandler.UpdateValue at D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:87,4	C#
 	0xE in Microsoft.Maui.Controls.Label.MapFont at D:\a\_work\1\s\src\Controls\src\Core\Label\Label.Mapper.cs:137,5	C#
 	0x2D in Microsoft.Maui.PropertyMapperExtensions.<>c__DisplayClass1_0<Microsoft.Maui.Controls.Label,Microsoft.Maui.Handlers. at D:\a\_work\1\s\src\Core\src\PropertyMapperExtensions.cs:46,6	C#
 	0x21 in Microsoft.Maui.PropertyMapper<Microsoft.Maui.ILabel,Microsoft.Maui.Handlers.ILabelHandler>. at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:172,6	C#
 	0x17 in Microsoft.Maui.PropertyMapper.UpdatePropertyCore at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:47,4	C#
 	0x1D in Microsoft.Maui.PropertyMapper.UpdateProperties at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:82,5	C#
 	0xCB in Microsoft.Maui.Handlers.ElementHandler.SetVirtualView at D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:79,4	C#
 	0x2 in Microsoft.Maui.Handlers.ViewHandler<Microsoft.Maui.ILabel,AndroidX.AppCompat.Widget.AppCompatTextView>.SetVirtualView at D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:53,4	C#
 	0x7 in Microsoft.Maui.Handlers.ViewHandler<Microsoft.Maui.ILabel,AndroidX.AppCompat.Widget.AppCompatTextView>.SetVirtualView at D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:56,4	C#
 	0x8B in Microsoft.Maui.Controls.Element.SetHandler at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:922,6	C#
 	0x2 in Microsoft.Maui.Controls.Element.set_Handler at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:864,11	C#
 	0x18 in Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler at D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:2061,5	C#
 	0xB0 in Microsoft.Maui.Platform.ElementExtensions.ToHandler at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:96,4	C#
 	0x2 in Microsoft.Maui.Platform.ElementExtensions.ToPlatform at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:127,4	C#
 	0x83 in Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView at D:\a\_work\1\s\src\Core\src\Handlers\Layout\LayoutHandler.Android.cs:41,5	C#
 	0x7 in Microsoft.Maui.Handlers.ViewHandler<Microsoft.Maui.ILayout,Microsoft.Maui.Platform.LayoutViewGroup>.SetVirtualView at D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:56,4	C#
 	0x8B in Microsoft.Maui.Controls.Element.SetHandler at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:922,6	C#
 	0x2 in Microsoft.Maui.Controls.Element.set_Handler at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:864,11	C#
 	0x18 in Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler at D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:2061,5	C#
 	0xB0 in Microsoft.Maui.Platform.ElementExtensions.ToHandler at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:96,4	C#
 	0x2 in Microsoft.Maui.Platform.ElementExtensions.ToPlatform at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:127,4	C#
 	0x83 in Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView at D:\a\_work\1\s\src\Core\src\Handlers\Layout\LayoutHandler.Android.cs:41,5	C#
 	0x7 in Microsoft.Maui.Handlers.ViewHandler<Microsoft.Maui.ILayout,Microsoft.Maui.Platform.LayoutViewGroup>.SetVirtualView at D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:56,4	C#
 	0x8B in Microsoft.Maui.Controls.Element.SetHandler at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:922,6	C#
 	0x2 in Microsoft.Maui.Controls.Element.set_Handler at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:864,11	C#
 	0x18 in Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler at D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:2061,5	C#
 	0xB0 in Microsoft.Maui.Platform.ElementExtensions.ToHandler at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:96,4	C#
 	0x2 in Microsoft.Maui.Platform.ElementExtensions.ToPlatform at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:127,4	C#
 	0x1D in Microsoft.Maui.Handlers.ScrollViewHandler.UpdateInsetView at D:\a\_work\1\s\src\Core\src\Handlers\ScrollView\ScrollViewHandler.Android.cs:180,4	C#
 	0x1F in Microsoft.Maui.Handlers.ScrollViewHandler.MapContent at D:\a\_work\1\s\src\Core\src\Handlers\ScrollView\ScrollViewHandler.Android.cs:114,4	C#
 	0x21 in Microsoft.Maui.PropertyMapper<Microsoft.Maui.IScrollView,Microsoft.Maui.Handlers.IScrollViewHandler>. at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:172,6	C#
 	0x17 in Microsoft.Maui.PropertyMapper.UpdatePropertyCore at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:47,4	C#
 	0x1D in Microsoft.Maui.PropertyMapper.UpdateProperties at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:82,5	C#
 	0xCB in Microsoft.Maui.Handlers.ElementHandler.SetVirtualView at D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:79,4	C#
 	0x2 in Microsoft.Maui.Handlers.ViewHandler<Microsoft.Maui.IScrollView,Microsoft.Maui.Platform.MauiScrollView>.SetVirtualView at D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:53,4	C#
 	0x7 in Microsoft.Maui.Handlers.ViewHandler<Microsoft.Maui.IScrollView,Microsoft.Maui.Platform.MauiScrollView>.SetVirtualView at D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:56,4	C#
 	0x8B in Microsoft.Maui.Controls.Element.SetHandler at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:922,6	C#
 	0x2 in Microsoft.Maui.Controls.Element.set_Handler at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:864,11	C#
 	0x18 in Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler at D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:2061,5	C#
 	0xB0 in Microsoft.Maui.Platform.ElementExtensions.ToHandler at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:96,4	C#
 	0x2 in Microsoft.Maui.Platform.ElementExtensions.ToPlatform at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:127,4	C#
 	0x83 in Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView at D:\a\_work\1\s\src\Core\src\Handlers\Layout\LayoutHandler.Android.cs:41,5	C#
 	0x7 in Microsoft.Maui.Handlers.ViewHandler<Microsoft.Maui.ILayout,Microsoft.Maui.Platform.LayoutViewGroup>.SetVirtualView at D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:56,4	C#
 	0x8B in Microsoft.Maui.Controls.Element.SetHandler at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:922,6	C#
 	0x2 in Microsoft.Maui.Controls.Element.set_Handler at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:864,11	C#
 	0x18 in Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler at D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:2061,5	C#
 	0xB0 in Microsoft.Maui.Platform.ElementExtensions.ToHandler at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:96,4	C#
 	0x2 in Microsoft.Maui.Platform.ElementExtensions.ToPlatform at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:127,4	C#
 	0x60 in Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent at D:\a\_work\1\s\src\Core\src\Handlers\ContentView\ContentViewHandler.Android.cs:42,5	C#
 	0x1 in Microsoft.Maui.Handlers.ContentViewHandler.MapContent at D:\a\_work\1\s\src\Core\src\Handlers\ContentView\ContentViewHandler.Android.cs:47,4	C#
 	0x21 in Microsoft.Maui.PropertyMapper<Microsoft.Maui.IContentView,Microsoft.Maui.Handlers.IContentViewHandler>. at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:172,6	C#
 	0x17 in Microsoft.Maui.PropertyMapper.UpdatePropertyCore at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:47,4	C#
 	0x1D in Microsoft.Maui.PropertyMapper.UpdateProperties at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:82,5	C#
 	0xCB in Microsoft.Maui.Handlers.ElementHandler.SetVirtualView at D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:79,4	C#
 	0x2 in Microsoft.Maui.Handlers.ViewHandler<Microsoft.Maui.IContentView,Microsoft.Maui.Platform.ContentViewGroup>.SetVirtualView at D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:53,4	C#
 	0x2 in Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView at D:\a\_work\1\s\src\Core\src\Handlers\ContentView\ContentViewHandler.Android.cs:26,4	C#
 	0x7 in Microsoft.Maui.Handlers.ViewHandler<Microsoft.Maui.IContentView,Microsoft.Maui.Platform.ContentViewGroup>.SetVirtualView at D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:56,4	C#
 	0x8B in Microsoft.Maui.Controls.Element.SetHandler at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:922,6	C#
 	0x2 in Microsoft.Maui.Controls.Element.set_Handler at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:864,11	C#
 	0x18 in Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler at D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:2061,5	C#
 	0xB0 in Microsoft.Maui.Platform.ElementExtensions.ToHandler at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:96,4	C#
 	0x2 in Microsoft.Maui.Platform.ElementExtensions.ToPlatform at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:127,4	C#
 	0x5A in Microsoft.Maui.Platform.MauiContextExtensions.ToPlatform at D:\a\_work\1\s\src\Core\src\Platform\Android\MauiContextExtensions.cs:96,4	C#
 	0x2B in Microsoft.Maui.Controls.Platform.FragmentContainer.OnCreateView at D:\a\_work\1\s\src\Controls\src\Core\Platform\Android\FragmentContainer.cs:41,4	C#
 	0x24 in AndroidX.Fragment.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_ at C:\a\_work\2\s\generated\androidx.fragment.fragment\obj\Release\net7.0-android\generated\src\AndroidX.Fragment.App.Fragment.cs:2045,4	C#
 	0xD in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_L at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:367,5	C#
```

**Comment by jonathanpeppers** [comment]
@mfeingol did you already try a rebuild?

If I download:
* https://www.nuget.org/api/v2/package/Microsoft.Maui.Core/8.0.21

I see the file inside:

image

So you might also check your NuGet cache, to see if something inside is malformed.

**Comment by mfeingol** [comment]
@jonathanpeppers: okay, yeah, I had to do some cleanup but now it's working without issues so it was probably a bad build artifact. Sorry for the noise!

**Pull request merged**
