### PR TITLE
[net9.0] Merge main to net9.0

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change

Bring latest changes from main to net9.0 branch

### CODE REVIEW

**Comment by rmarinho** [comment]
@StephaneDelcroix  I m hitting this one trying to get stuff merged on net9


```
D:\a\_work\1\s\src\Controls\tests\Xaml.UnitTests\Issues\Maui20616.xaml.cs(54,83): error CS1061: 'SetterSpecificityList<BindingBase>' does not contain a definition for 'Values' and no accessible extension method 'Values' accepting a first argument of type 'SetterSpecificityList<BindingBase>' could be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\Controls\tests\Xaml.UnitTests\Controls.Xaml.UnitTests.csproj]
```

**Comment by rmarinho** [comment]
Ok new error 

```
Issues\Maui20616.xaml(7,10): XamlC XC0103 error : Consider attributing the markup extension "Microsoft.Maui.Controls.Xaml.TypeExtension" with [RequireService] or [AcceptEmptyServiceProvider] if it doesn't require any. [D:\a\_work\1\s\src\Controls\tests\Xaml.UnitTests\Controls.Xaml.UnitTests.csproj]
Issues\Maui20616.xaml(8,10): XamlC XC0103 error : Consider attributing the markup extension "Microsoft.Maui.Controls.Xaml.TypeExtension" with [RequireService] or [AcceptEmptyServiceProvider] if it doesn't require any. [D:\a\_work\1\s\src\Controls\tests\Xaml.UnitTests\Controls.Xaml.UnitTests.csproj]
    5879 Warning(s)
    2 Error(s)
```

**Comment by rmarinho** [comment]
@simonrozsival  we are hitting , should we ignore the warning or fix it ? 

``` 
Issues\Maui20616.xaml(7,10): XamlC XC0103 error : Consider attributing the markup extension "Microsoft.Maui.Controls.Xaml.TypeExtension" with [RequireService] or [AcceptEmptyServiceProvider] if it doesn't require any. [D:\a\_work\1\s\src\Controls\tests\Xaml.UnitTests\Controls.Xaml.UnitTests.csproj]
```

**Comment by simonrozsival** [comment]
@rmarinho I suggest ignoring it for now. I think we can fix it properly tomorrow or on Monday.

**Pull request closed without merging**
