### PR TITLE
Update FlyoutPage.cs

### PR DESCRIPTION
**Pull request by guyvaio**
Switch from landscape to portrait, and from portrait to landscape repeatedly produces this error: androidx.appcompat.widget.LinearLayoutCompat$LayoutParams cannot be cast to androidx.drawerlayout.widget.DrawerLayout$LayoutParams

The root cause is in the OnOrientationChanged implementation in Android that awaits 0.5 second and creates race conditions if the orientation changes again during this interval.

https://github.com/dotnet/maui/issues/18161

### Issues Fixed

Fixes #

### CODE REVIEW

**Comment by guyvaio** [comment]
> @guyvaio please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
>  > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@dotnet-policy-service agree company=INEO srl

**Comment by guyvaio** [comment]
> @guyvaio please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
>  > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@dotnet-policy-service agree company=INEO srl

**Review by PureWeen — CHANGES_REQUESTED** [review]
Can we move all this code to FlyoutViewHandler.Android.cs?

**Comment by guyvaio** [comment]
> Can we move all this code to FlyoutViewHandler.Android.cs?

All the code? I think no. The subclass OrientationListener could be moved as a subclass of FlyoutViewHandler (or elsewhere). This will require some changes from private to internal.

For the rest, considering event QueuedMainDisplayInfoChanged and method OnQueuedMainDisplayInfoChanged must de facto remain, I do not see what else could be moved to platform specific code.

Any other approach is welcome.

**Comment by guyvaio** [comment]
This solution seemed adequate to counter the ClassCastException. Unfortunately, it produces a side effect: the FlyOut appears only briefly when IsPresented is to true.
Sorry for the inconvenience.

**Pull request closed without merging**
