### PR TITLE
Set Parent for child elements added to Border

### LINKED ISSUE #4614: IVisualTreeElement.GetVisualParent returns null for elements in Border
### Description

IVisualTreeElement.GetVisualParent returns null for elements in Border

### Steps to Reproduce

1. Open, build and run attached project.
2. Click on each button and observe changed message.
**Expected**: message should always mention non-null parent
**Actual**: message for Button in Border says "parent is null"
**Note**: there might be other MAUI types which don't have parent and/or don't implement IVisualTreeElement
 
[MauiApp11.zip](https://github.com/dotnet/maui/files/8042991/MauiApp11.zip)

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Windows

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by VSadov**
### Description of Change

Call `OnChild[Added|Removed]` events in `Border.ContentChanged`

### Issues Fixed

Fixes #4614

### CODE REVIEW

**Comment by VSadov** [comment]
CC: @PureWeen

**Review by mattleibow — APPROVED** [review]

**Review by jsuarezruiz — APPROVED** [review]

**Comment by VSadov** [comment]
Thanks!

**Comment by mattleibow** [comment]
@VSadov is it possible to open a new PR with some tests for this? I forgot about tests for a second and I am in shame.
Also, might be worth adding tests for some other similar controls - like a Grid, ContentView, Frame, ScrollView and Page

The can probably go into this project into the test files: `src\Controls\tests\Core.UnitTests\BorderUnitTests.cs`. There are normal unit tests, so it is easy to right click and run in the Test Explorer

**Comment by VSadov** [comment]
Right. Tests would be nice.
For other controls - I will check if there is existing coverage. It might be that unset parent is breaking except in the specific case if container is Border. Possibly a direct result of the bug where Border does not update when child updates.

**Pull request merged**
