### PR TITLE
Add single file analyzer to maui project

### PR DESCRIPTION
**Pull request by tlakollo**
### Description of Change ###

Disclaimer: This PR is not part of the Handler Property Backlog

This analyzer flags code patterns that would make an application have an undesired/unknown behavior when deployed as a single file, since the end result of MAUI apps it's a single file (.apk or .ipa) the relevance of having an analyzer that flags these patterns is important. Enabling the analyzer in the current repo didn't flag any dangerous code pattern usage, but having this analyzer enabled would allow it to not regress from the current state. 

### Additions made ###
- Enables the Single File analyzer, the analyzer is already included as part of the ILLink.RoslynAnalyzer package and it was just turned on.

### CODE REVIEW

**Comment by mattleibow** [comment]
> dangerous code pattern usage 

Can you elaborate?

Also, I am not sure if mobile apps are a single file exactly, there is one app package file (.apk for example) but that contains all the other dlls.

Does this feature have docs or something that indicates what this feature actually does?

**Comment by tlakollo** [comment]
Yes, this [document ](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file) describes what is single file, and then describes a procedure to enable it in console applications. The important piece is "DLLs are bundled with the app into a single executable. When the app starts, the managed DLLs are extracted and loaded in memory" which is the behavior you described with the .apk. Problems arise when a user uses one of the [API incompatibility patterns](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file#api-incompatibility) but since everything is loaded in memory the answer is kind of unexpected.

**Comment by Eilon** [comment]
Right, .NET MAUI projects are not actually single file projects. It's just a ZIP that contains the actual app. When you install the IPK/APX/MSIX/MSI/whatever on the target machine, it gets un-zipped and then run.

**Comment by Eilon** [comment]
Or more to the point, all the assemblies that you think exist in your project all continue to exist on the target device where the app is being run. This is in contrast to a "single-file app" where the original assemblies don't exist at all anymore.

**Comment by Redth** [comment]
It might be helpful to have a few others look at this too: @dalexsoto @rolfbjarne @jonpryor

**Comment by tlakollo** [comment]
> Or more to the point, all the assemblies that you think exist in your project all continue to exist on the target device where the app is being run. This is in contrast to a "single-file app" where the original assemblies don't exist at all anymore.

Yes, all the assemblies still exist and what this analyzer does is flag code patterns that try to get information about those assemblies. You can respond to things like where the executable is located and get the path to your .apk, but patterns like getting a specific assembly location, that in a nonsingle-file app will return the path to the assembly, in single-file mode will return empty.
Also, the single-file feature described in the document preserves the original assemblies, there is even an unbundler that allows you to go from a single-file to the original dlls. You can still do a lot of stuff with the assemblies just not get certain information like their location because there is no good answer in single-file. Even if not loaded into memory and just unzipped on disk it has been proven to cause trouble.

**Comment by Eilon** [comment]
But on these platforms, the assemblies are really on disk, and each have individual file paths, no? The APK is just a way to deliver the app to a device, as if I emailed you a ZIP of my multi-file app that you then un-zipped and ran.

I feel like I'm missing something about how this would be useful in .NET MAUI scenarios?

**Comment by agocke** [comment]
My understanding was that iOS bundling did not produce assemblies with individual file paths. Is that right? If so, maybe this should be limited to things that run on iOS.

**Comment by Redth** [comment]
I think the answer here is more complicated.  On iOS/Catalyst the assemblies are still inside the app bundle and exist on disk.  Android is much the same, however there's flags to embed assemblies differently that I'm not sure would make them still exist on disk in the context of this issue.

We really need iOS (@dalexsoto) and Android (@jonpryor) team members to weigh in here and help understand the scenarios for each platform a bit better.

**Comment by rolfbjarne** [comment]
Apps for the Apple platforms (iOS, tvOS, macOS, Mac Catalyst) are not deployed as single files (as defined here: https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file). They're a zip file of an app bundle (which is a directory of all the files required at runtime), which is unzipped upon install. This means that all the assemblies exist as separate files on disk at execution time.

This also means that none of the API incompatibilities here: https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file#api-incompatibility apply to Apple platforms.

So this change does not make sense for Apple platforms.

**Comment by agocke** [comment]
In that case we can probably close this out -- sounds like there's nothing to do here. Thanks!

**Pull request closed without merging**
