### PR TITLE
Fix android image loading into views

### LINKED ISSUE #6067: Externally hosted images cannot load on native apps
### Description

Loading an hosted image into an image control doesn't work after upgrading to RC1.
I thought it would be the same as #5986, but I'm using native maui controls, no webview and getting an other error message.

### Steps to Reproduce

1. Create a new MAUI app.
2. Add ```<uses-permission android:name="android.permission.INTERNET" />``` to the android manifest.
3. Change the source of the existing image control to: ```https://devblogs.microsoft.com/dotnet/wp-content/uploads/sites/10/2020/10/dotnet-bot_handybot.png```
4. Image does not show up on android, neither in the emulator, nor directly in an deployed app. Couldn't find an error message either.
5. If I load the image from code-behind ```		img.Source = ImageSource.FromUri(new Uri("https://devblogs.microsoft.com/dotnet/wp-content/uploads/sites/10/2020/10/dotnet-bot_handybot.png"));
```, it breaks with an error message: ```**System.InvalidOperationException:** 'An attempt was made to transition a task to a final state when it had already completed.'```

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Preview 14

### Affected platforms

Android

### Affected platform versions

Android 11+

### Did you find any workaround?

_No response_

### Relevant log output

```shell
at System.Threading.Tasks.TaskCompletionSource`1[[Microsoft.Maui.IImageSourceServiceResult, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetResult(IImageSourceServiceResult result)
   at Microsoft.Maui.ImageLoaderCallback.OnComplete(Boolean success, Drawable drawable, IRunnable dispose) in D:\a\_work\1\s\src\Core\src\ImageSources\Android\ImageLoaderCallback.cs:line 88
   at Microsoft.Maui.IImageLoaderCallbackInvoker.n_OnComplete_Ljava_lang_Boolean_Landroid_graphics_drawable_Drawable_Ljava_lang_Runnable_(IntPtr jnienv, IntPtr native__this, IntPtr native_p0, IntPtr native_p1, IntPtr native_p2) in D:\a\_work\1\s\src\Core\src\obj\Release\net6.0-android\generated\src\Microsoft.Maui.IImageLoaderCallback.cs:line 87
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_V(_JniMarshal_PPLLL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 297
```

### LINKED ISSUE #6228: Embedded images not render in Android Maui
### Description

The Embedded image is shown properly in WinUI and not working in Android. Below are the screen shots,

WinUI: 
EmbeddedWinUI

Android:
EmbeddedAndroidscreenshots

### Steps to Reproduce

1. Run the attached sample in WinUI the image will be shown properly
2. Run the same sample in Android the image has not shown in the UI

[EmbeddedImageAndroid.zip](https://github.com/dotnet/maui/files/8512290/EmbeddedImageAndroid.zip)

### Version with bug

Preview 14

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

No

### Relevant log output

_No response_

### LINKED ISSUE #6231: StreamImageSource doesn't work on Image Control
### Description

I am using StreamImage Source to save rendered objects into ImageSource by converting from byte[] to Stream. But after updating to preview 14, I have faced a breaking issue with Image control. When I tried setting StreamImageSource to the source of my Image control, the image is not visible.

Note :-  Setting URI or File image source types, works as expected.

**XAML**
```
 <ContentPage.Content>
        <Image  x:Name="imageControl"
                    WidthRequest="400"
                    HeightRequest="400"
                    HorizontalOptions="Center" />
 </ContentPage.Content>

```

**C#**
```
public partial class Sample : ContentPage
{
    public void Sample()
    {
            InitializeComponent();

           //Converting the default dotnet image to stream
            var assembly = this.GetType().GetTypeInfo().Assembly;
            Stream stream = assembly.GetManifestResourceStream("_YOURSAMPLENAME_.Resources.Images.dotnet_bot.svg");

            if (stream != null)
            {
                imageControl.Source = ImageSource.FromStream(() => stream);
            }
    }
}
```

### Steps to Reproduce

1. Create a new Maui Application
2. Add Image control to the content page.
3. Create the default `dotnet_bot.svg ` image loaded in the assembly into Stream source
4. Set the Stream to the source of the Image control added.
5. See that no image is rendered.

_Note: Make sure you set the **Build Action** of the image to **EmbeddedResource** to reproduce this._

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Preview 14

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 11 and up, Windows SDK 10.0.19041

### Did you find any workaround?

No

### Relevant log output

_No response_

### LINKED ISSUE #6363: RC1 - EllipseGeometry does not work
### Description

I have noticed that EllipseGeometry is not working in .NET Maui, I have tried the same case in Xamarin.Forms and it does work. I have tried to circle an image using EllipseGeometry but it doesn't work. As additional data if you have the application running and you replace the Image control with an ImageButton and reload with Hot Reload if it shows circular, however if you run the application directly with an ImageButton it does not work.

### Steps to Reproduce

Run the following code and you will notice that EllipseGeometry is not working, however the same code in Xamarin.Forms does:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             BackgroundColor="White"
             x:Class="MauiCollectionView.MainPage">
    <StackLayout>
        <Image 
               Source="dotnet_bot.svg"
               BackgroundColor="Red"
               HorizontalOptions="Center"
               VerticalOptions="Start"
               Aspect="AspectFit"
               HeightRequest="60"
               WidthRequest="60">
            <Image.Clip>
                <EllipseGeometry
                        Center="30,30"
                        RadiusX="30"
                        RadiusY="30" />
            </Image.Clip>
        </Image>
    </StackLayout>
</ContentPage>
```

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 10

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Redth**
- Clean up code using lambdas in java
- Use the MauiCustomViewTarget's view directly

I think the main fix here is using the builder with caching was not retaining the correct builder instance in those cases, this fixes the logic.

fixes #6231 
fixes #6228 
fixes #6363 
fixes #6067

Screenshot_1650588688

### CODE REVIEW

**Review by jonathanpeppers — COMMENTED** [review]
Is this a real test failure?
```
InvalidSourceFailsToLoad
Assert.Equal() Failure\nExpected: List<String> ["LoadingStarted", "LoadingFailed"]\nActual:   List<String> ["LoadingStarted"]
```
I clicked retry, just in case.

**Comment by Redth** [comment]
I think it is a real failure, but I haven't quite figured out why yet.

**Comment by jonathanpeppers** [comment]
Maybe it only passed because things weren’t fully working before.

**Comment by Redth** [comment]
Not sure, I can't seem to make it fail locally... Could be an API level thing I guess, or perhaps the tests are taking too long in CI?

Screen Shot 2022-04-21 at 11 09 12 PM

**Comment by Redth** [comment]
Though I suppose that test is now timing out so that's probably not correct.

**Comment by Redth** [comment]
Ok I'm not sure what's happening inside Glide, but the load does actually take this long to fail.  I was setting breakpoints in the java code, and from calling `.into(target)` to `onLoadFailed` in the target, is like 5 seconds with an invalid filename...

**Review by mattleibow — APPROVED** [review]

**Review by jsuarezruiz — APPROVED** [review]

**Pull request merged**
