### PR TITLE
[Android] Page.IsBusy activity indicators gets stuck/causes multiple to be displayed

### LINKED ISSUE #23674: Page.IsBusy activity idicators gets stuck/causes multiple to be displayed
### Description

When a page with `IsBusy = true` is navigated back from, the activity indicator stays displayed and if another page with `IsBusy = true` is navigated to, another activity indicator is layered on top. I expect the activity indicator to disappear when navigating away, thereby also preventing multiple activity indicators stacked on top of each other.

### Steps to Reproduce

1. Start the public reproduction project and navigate to the second page using the button.
2. Toggle `IsBusy` using the button and navigate back using either the device's back button or the back button in the toolbar
3. The activity indicator will stay active and now display on the first 
4. Going to the second page and toggling `IsBusy` again will layer another activity indicator on top of the existing one

I kinda expect the activity indicator to disappear when the page is navigated away from

### Link to public reproduction project repository

https://github.com/MarcelStommel/IsBusyExample

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

Setting `IsBusy = false` in the `OnBackButtonPressed` method makes the activity indicator disappear like expected

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/23674

|After|Before|
|--|--|
|<video src="https://github.com/user-attachments/assets/9901cf0e-80b2-4a65-b002-9f721b38a66b" width="300px"/>|<video src="https://github.com/user-attachments/assets/e8f1d6ba-adfb-4c7e-b22a-eb162846b955" width="300px"/>|

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
Triggered build to generate test snapshots.

**Comment by jsuarezruiz** [comment]
Potentially could fix https://github.com/dotnet/maui/issues/25585

**Review by jsuarezruiz — APPROVED** [review]

**Review by rmarinho — CHANGES_REQUESTED** [review]
Screenshot 2024-11-15 at 16 44 01

Seems it s always failing this 2 UITests

**Comment by kubaflo** [comment]
@albyrock87 and I noticed that @rmarinho these 2 test fails for other PRs too. For example in this @albyrock87's PR https://dev.azure.com/xamarin/public/_build/results?buildId=128205&view=ms.vss-test-web.build-test-results-tab&runId=3368660&resultId=100075&paneView=debug

The issue is that the screenshotS generated by the pipeline are different that what we can see locally:

Locally:



CI:

**Comment by jsuarezruiz** [comment]
> @albyrock87 and I noticed that @rmarinho these 2 test fails for other PRs too. For example in this @albyrock87's PR https://dev.azure.com/xamarin/public/_build/results?buildId=128205&view=ms.vss-test-web.build-test-results-tab&runId=3368660&resultId=100075&paneView=debug
> 
> The issue is that the screenshotS generated by the pipeline are different that what we can see locally:
> 
> Locally:  
> 
> CI:  

That tests will change and will be fixed in another PR.

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
