### PR TITLE
Revert "[iOS] Clear BindingContext when cell is queued for reuse (#14…

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

Revert https://github.com/dotnet/maui/pull/14619

It looks like this change caused the following "regression" https://github.com/dotnet/maui/issues/21374.

From testing I don't think this change directly caused the regression, but I think it exposed a flaw in the prototype code that now only surfaces because of that PR.

The prototype code inside ItemsViewLayout creates a prototype cell to measure with if no cells have been measured yet. This creates a phantom `TemplatedCell` that gets added to the logical children and causes there to be two `TemplatedCells` for the same `View`

I did a quick test just returning the results of the prototype cell without creating it and it no longer crashes. So, I think we need to rework the prototype cells a bit for SR4

image

### CODE REVIEW

**Review by rmarinho — APPROVED** [review]

**Review by jsuarezruiz — APPROVED** [review]

**Comment by mooola** [comment]
@PureWeen Is there a reason this was closed and not merged?

**Comment by SonicScholar** [comment]
> @PureWeen Is there a reason this was closed and not merged?

Agree with this question. We've been hosed on iOS trying to get a release out from this regression and waiting for a fix. The vibe here seemed promising until it was closed unexpectedly.

**Comment by PureWeen** [comment]
It's the same timeline for us to fix forward or revert. 
If we're unable to fix forward, we'll revisit. 

@SonicScholar if you have an additional repro you could add here https://github.com/dotnet/maui/issues/21374 that'd be helpful.

At this point it feels riskier to revert vs fix forward given the data I have. This change has been part of the code now for a good amount of time with no other issues logged and @mooola found workaround.

**Pull request closed without merging**
