### PR TITLE
Bump AspNet.Security.OAuth.Apple to 6.0.10

### PR DESCRIPTION
**Pull request by martincostello**
### Description of Change

Bump AspNet.Security.OAuth.Apple to 6.0.10 in the WebAuthenticator sample to resolve https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/security/advisories/GHSA-3893-h8qg-6h5f.

### CODE REVIEW

**Comment by martincostello** [comment]
I think someone from your infra team will need to add this package to your internal mirror of NuGet.org.

**Comment by rmarinho** [comment]
yap i asked @martincostello  is already there going to rerun these

**Comment by rmarinho** [comment]
@martincostello this fix will probabily only go to net7.rc2, do you want to make this against net6.0 we just shipped sr5, but if we have a sr6 it will be there

**Comment by martincostello** [comment]
I guess that depends what the use case for this is. If people regularly fork the repo/copy the code to produce applications from, then it's sort of propagating the problem further if not fixed at the source.

It would be good to also patch the 6.0 branch if this package "ships" in some way via the sample.

I sort of ended up here via looking at the package dependencies in GitHub and finding all these repos that have been forked from other people's templates that use this library:

image

The source of many of the forks is this enkodellc/blazorboilerplate repo, which already has a PR open with the fix: https://github.com/enkodellc/blazorboilerplate/pull/922

**Comment by rmarinho** [comment]
Oh right, we don't ship this sorry, it's just on the sample app.

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
