### PR TITLE
[Windows] Fixes DatePicker format

### LINKED ISSUE #9255: Date format DatePicker wrong in Windows
### Description

I set the date format to yyyy-MM-dd.
In Android the date shows as 2022-08-09.
In Windows the date shows as 2022-8-9.

Using Visual Studio Community 2022 - 17.3.0 Preview 6.0

### Steps to Reproduce

1. Open the attached project in Android.
2. Open the attached project in Windows.
3.
[MauiAppTestDateFormat.zip](https://github.com/dotnet/maui/files/9280413/MauiAppTestDateFormat.zip)

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by andres-fg**
### Description of Change
Fixes DatePicker format on Windows to show days and months using 1 or 2 digits.

Also fixes a related bug to format correctly the abbreviated day 

### Issues Fixed
Fixes #9255

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=9924) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=9924) before we can accept your contribution.<br/><br/>:x: andres-fg [sign now](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=9924)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/maui?pullRequest=9924) it.</sub>

**Review by jfversluis — APPROVED** [review]

**Review by mattleibow — APPROVED** [review]

**Comment by jfversluis** [comment]
Thank you so much for this great contribution @andres-fg! I'm sorry we left this laying around for too long, I promise we'll do better. Looking forward to more of your work!

**Comment by andres-fg** [comment]
thank you @jfversluis !

**Pull request merged**
