### PR TITLE
NavigationBar properties not updating - fix

### LINKED ISSUE #11790: MAUI - Android Navigationbar BarBackgroundColor is not updating as per the Theme color specified.
### Description

Android Navigationbar BarBackgroundColor is not reflecting when the theme is changed.
Rest of the UI is updating to the theme color that is specified though AppThemeBinding.
When Naviagte to another page , suddenly navigation bar shows the theme color

### Steps to Reproduce

1. Create a new MAUI project
2. Add following code to the App.xaml for the NavigationPage style.
   ```xaml
   <Style TargetType="NavigationPage">
        <Setter Property="BarBackgroundColor" Value="{AppThemeBinding Light={StaticResource Red}, Dark={StaticResource Green}}" />
        <Setter Property="BarTextColor" Value="{AppThemeBinding Light={StaticResource Gray200}, Dark={StaticResource White}}" />
        <Setter Property="IconColor" Value="{AppThemeBinding Light={StaticResource Gray200}, Dark={StaticResource White}}" />
    </Style>
    ```
3. Set MainPage = new NavigationPage( new MainPage() );
4. Run the App and try to change the theme by pressing the Dark / Light button . You can see that Navigatiobar background color not changing its color and rest of the UI components are updating as per the theme color specified.
5. Navigate to second page, Suddenly Navigationbar changes the color

### Link to public reproduction project repository

https://github.com/febinDonz/Maui-Theme-Bug

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up

### Did you find any workaround?

no

### Relevant log output

_No response_

### LINKED ISSUE #22899: Title not updated after OnAppearing for TabbedPage in NavigationPage
### Description

The title of the navigation page is not updated if we set the title after the "OnAppearing" event. We only have the problem with the "TabbedPage", so we don't have it with a classic "ContentPage".
If we set the title inside the "OnAppearing" method, the title is well updated.

The problem exists at least with Android API 33 and 29.
Microsoft.Maui.Controls v8.0.40.

image

### Steps to Reproduce

1. Create a tabbed page in a navigation page
2. For example, override the "OnAppearing" method inside the TabbedPage with 
```
protected override void OnAppearing()
{
	base.OnAppearing();

    this.Title = "On Appearing Title";

    var timer = Dispatcher.CreateTimer();
    timer.Interval = TimeSpan.FromMilliseconds(2000);
    timer.Tick += (s, e) =>
    {
        MainThread.BeginInvokeOnMainThread(() =>
        {
            this.Title = DateTime.Now.ToString();
        });
    };
    timer.Start();
}
```

Expected : Firstly, the title is "On Appearing Title", then the title is updated every two seconds with the date
Actual : The title is "On Appearing Title", and it doesn't change

### Link to public reproduction project repository

https://github.com/TWEESTY/MAUI_Issue_TabbedPage_Title

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Android 10, Android 13

### Did you find any workaround?

No.

### Relevant log output

_No response_

### LINKED ISSUE #23195: NavigationBarColors from NavigationPage not changing on AppTheme changing
### Description

if app starts, the colors (text and background) will display fine

image

but if the apptheme is changed, the navigationbar colors will not be refreshed

image

### Steps to Reproduce

1.) create a default MAUI-App

2.) change from AppShell to NavigationPage
image

3.) add new button to MainPage
image

4.) implement the apptheme changing
image

5.) start the app on android platform and change the apptheme by tap the button "Change theme"
image

or use my prepared project, see the link below.

### Link to public reproduction project repository

https://1drv.ms/u/s!AvfMdSsMYykdlc9mU0VghHueddr2VA?e=G8c03n

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/22899 
Fixes https://github.com/dotnet/maui/issues/23195
Fixes https://github.com/dotnet/maui/issues/11790

### CODE REVIEW

**Comment by jfversluis** [comment]
Looks like tests might be failing? Do we need to update the snapshots here?

**Comment by kubaflo** [comment]
Should work now

**Comment by kubaflo** [comment]
@jfversluis snapshots are ready

**Review by jfversluis — APPROVED** [review]

**Review by PureWeen — APPROVED** [review]

**Comment by marcojak** [comment]
I think this is causing a crash, precisely at NavigationPageToolbar.cs:line 210.

This happens when inside the OnAppearing method I try to set
 (page.Detail as NavigationPage).BarBackgroundColor = ...

where page is a FlyoutPage.

This doesn't crash in the previous version of MAUI

**Comment by MitchBomcanhao** [comment]
> I think this is causing a crash, precisely at NavigationPageToolbar.cs:line 210.
> 
> This happens when inside the OnAppearing method I try to set (page.Detail as NavigationPage).BarBackgroundColor = ...
> 
> where page is a FlyoutPage.
> 
> This doesn't crash in the previous version of MAUI

I have the exact same issue, as referenced in https://github.com/dotnet/maui/issues/25114

**Pull request merged**
