### PR TITLE
Essentials.Barometer refactored to interface and singleton

### PR DESCRIPTION
**Pull request by moljac**
### Description of Change ###

Implements #

```csharp
	public interface IBarometer
	{
		bool IsSupported { get; set; }

		bool IsMonitoring { get; set; }

		void Start(SensorSpeed sensorSpeed);

		void Stop();
	}
```

### Additions made ###

* Adds 

### PR Checklist ###

- [ ] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [ ] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [ ] Adds the mapping method to the WinUI, Android, iOS, and Standard aspects of the handler
- [ ] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- [ ] Does this PR introduce a new control? (If yes, add an example using SemanticProperties to the SemanticsPage)
- [ ] APIs that modify focusability?
- [ ] APIs that modify any text property on a control?
- [ ] Does this PR modify view nesting or view arrangement in anyway?
- [ ] Is there the smallest possibility that your PR will change accessibility? 
- [ ] I'm not sure, please help me

If any of the above checkboxes apply to your PR, then the PR will need to provide testing to demonstrate that accessibility still works.

### CODE REVIEW

**Comment by rmarinho** [comment]
Weird is still failing 

```
  D:\a\_work\1\s\src\Essentials\src\Barometer\Barometer.uwp.cs(7,41): error CS0535: 'BarometerImplementation' does not implement interface member 'IBarometer.IsSupported.set' [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj]
```

**Comment by moljac** [comment]
> Weird is still failing
> 
> ```
>   D:\a\_work\1\s\src\Essentials\src\Barometer\Barometer.uwp.cs(7,41): error CS0535: 'BarometerImplementation' does not implement interface member 'IBarometer.IsSupported.set' [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj]
> ```

both get/set are here in shared:

https://github.com/dotnet/maui/pull/4604/files#diff-d66c6e3b89f7f04044dfcaa1e59893887da79687e9f7178037abda5cc4035cfaR10

not weird - UWP is missin `set`

https://github.com/dotnet/maui/pull/4604/files#diff-4402b7a418a599f95a2601a3d6fcdcd7838a620a9782a8725dced59b9cb387fdR15

**Comment by moljac** [comment]
fixed - IsSupported setter removed!

https://github.com/dotnet/maui/pull/4604/commits/9976576d41e01ee2eae13322aea4b323fc91b4e1

**Comment by Redth** [comment]
Closing, superceded by #4761

**Pull request closed without merging**
