### PR TITLE
Remove allocation from Color.TryParse

### PR DESCRIPTION
**Pull request by eerhardt**
C# now allows for switching over a ReadOnlySpan<char>. Updating the code to no longer allocate a new string when trying to find the named color.

### CODE REVIEW

**Review by Redth — APPROVED** [review]

**Review by jonathanpeppers — COMMENTED** [review]
Is this available in .NET 8 / .NET framework / C# 12? Or new in .NET 9?

**Comment by eerhardt** [comment]
> Is this available in .NET 8 / .NET framework / C# 12? Or new in .NET 9?

It came in VS 17.3 - so C# 11 and .NET 7. See https://github.com/dotnet/roslyn/pull/59962. It just wasn't available at the time this was first refactored (we were on .NET 6).

When I try it with an older LangVersion I get:

```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	CS8936	Feature 'pattern matching ReadOnly/Span<char> on constant string' is not available in C# 10.0. Please use language version 11.0 or greater.	ConsoleApp110	C:\Users\eerhardt\source\repos\ConsoleApp110\ConsoleApp110\Program.cs	8	Active	
```

**Review by jonathanpeppers — APPROVED** [review]

**Review by jsuarezruiz — APPROVED** [review]

**Comment by PureWeen** [comment]
We're getting a few things ironed out with CI
I've put this in our Feb iteration, so it doesn't get buried once we get these back on track.

**Pull request merged**
