### PR TITLE
[Android] Removes freeze using SecureStorage

### LINKED ISSUE #17706: SecureStorage GetAsync not working in .NET 8 MAUI
### Description

I am in the process of Migrating our mobile app from Xamarin to MAUI. I have found that SecureStorage.Default.GetAsync(ID_TOKEN); method not executing or returning any value in .NET 8. The same code is working for NET 7 but the issue happens only with the NET8(Preview) version.

I am using Visual Studio 2022 Version 17.8.0 Preview 2.0

This is a similar issue already reported on https://github.com/dotnet/maui/issues/12341. 

### Steps to Reproduce

- Create a sample MAUI application with .NET 8.
- Create two buttons, one for get and another for Set(SecureStorage.GetAsync and SecureStorage.SetAsync)
- Execute the MAUI app and click on the Setasync button(*this is randomly set an string value)
- Close the app
- Re-open the same app and click on GetAsync button.
- await getSecureStorage is kept waiting and the call is not executed 

### Link to public reproduction project repository

https://github.com/DharunAR/SecureTest/

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

7.0.49

### Affected platforms

Android

### Affected platform versions

Android 12 and Android 13

### Did you find any workaround?

No.

### Relevant log output

```shell
No
```

### LINKED ISSUE #18685: Cannot retrieve larger string from SecureStorage on Android
### Description

I'm using the Xamarin/Maui Essentials SecureStorage in my iOS/Android project.
Recently I started migration from Xamarin to Maui and I am running into a issue.

Whenever I store a large string (2500 characters in this example) in secure storage using `SecureStorage.SetAsync()` it seems to work fine (the returned task completes with no errors), but as soon as I try to retrieve the string using `SecureStorage.GetAsync()` the returned task hangs and never completes. If I try to retrieve shorter strings this doesn't occur and the GetAsync returns properly

This issue only occurs for larger strings on Android. On iOS/Mac/Windows the larger strings work fine.
This also isn't an issue in Xamarin.Android/Xamarin.Forms (albeit with a slight performance hit due to SecureStorage not being optimal for larger strings)

It's reproducible in both `net7.0-android` and `net8.0-android`.

### Steps to Reproduce

1. Create a MAUI-based Android app with Maui or Maui Essentials enabled
2. Store a large string (2500 characters in this example) in the securestorage using `await SecureStorage.Default.SetAsync("my_example_string", largeString);`
3. Try to retrieve the string using `var retrievedValue = await SecureStorage.Default.GetAsync("my_example_string");`
4. The task/await never completes

### Link to public reproduction project repository

_No response_

### Version with bug

7.0.101

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 and 13

### Did you find any workaround?

None so far

### Relevant log output

_No response_

### LINKED ISSUE #18817: SecureStorage.GetAsync() hangs in Android devices with .NET 8 GA in VS 2022 17.8.0 - Demo REPO
### Description

When invoking SecureStorage.GetAsync in App.Xaml.cs in the constructor. This method will NEVER return. No exception thrown, it just never returns.
It works fine in Windows and and iOS but hangs in Android.

I deployed to a physical Android tablet and phone both running Android 13. The Samsung S9 Ultra tablet (SM-X910) and the Samsung Galaxy S22.

I changed from SecureStorage.GetAsync() to Preferences.Get() and then it returns immediately. The sample is as simple as just trying to find a key that doesn't exist. I'm not sure if it matters if the key exists or not, but I am not working with thousands of bytes just literally. GetAsync("password").

There was a reference to this issue from RC1 I believe that said it was fixed but it is not!
[https://github.com/dotnet/maui/issues/18685](https://github.com/dotnet/maui/issues/18685)

### Steps to Reproduce

This REPO is just a new Hello World .NET Maui app with a single line added that causes the app to hang in the splash screen upon deployment to an Android device from VS 2022 17.8.0.

[Public REPO - New hello world app with one line added to App.xaml.cs](https://github.com/schlaman/Net8SecureStorageHangsInAndroid)

### Link to public reproduction project repository

https://github.com/schlaman/Net8SecureStorageHangsInAndroid

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

My workaround for now is to use Preferences.Get() instead of SecureStorage.GetAsync().
I'm getting ready to go into beta so for now this is fine but need SecureStorage.GetAsync to work ultimately

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Removes freeze using SecureStorage on Android.

image

### Issues Fixed

Fixes #17706 
Fixes #18685
FIxes #18817

### CODE REVIEW

**Review by mattleibow — COMMENTED** [review]
Can we do the same for the Set?

**Comment by jsuarezruiz** [comment]
> Can we do the same for the Set?

Sure, done. Could you take another look?. Thanks in advance.

**Review by mattleibow — APPROVED** [review]

**Comment by phillippschmedt** [comment]
Can you please give an estimation on when this will be released? This is ESSENTIAL!! for your app.

**Comment by mattleibow** [comment]
This will go out with SR1.

**Pull request merged**
