### PR TITLE
Importing Maui property pages

### PR DESCRIPTION
**Pull request by stmoor**
### Description of Change

Extended the Application page for MAUI single project. This PR is to pull it in. 
 
[Here ](https://github.com/xamarin/XamarinVS/pull/12883) is the related work from the XamarinVs repo. 
[Work Item](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1492679)

### CODE REVIEW

**Comment by Redth** [comment]
@mattleibow @jonathanpeppers any concerns with this change?

**Comment by jonathanpeppers** [comment]
I was reading the linked file:

https://github.com/xamarin/XamarinVS/pull/12883/files#diff-1696e3fa43f89446782d1dd73cdd1c9e5ca9d8b2c4766fd6e8b8103fd6d6c76dR4

Should this even check `$(SingleProject)` is true? We talked about dropping this property completely.

**Review by jonathanpeppers — APPROVED** [review]
No issue with the changes in this PR, though.

**Pull request merged**
