### PR TITLE
Fix a couple life cycle scenarios on shell modals

### LINKED ISSUE #8513: OnAppearing not triggered when going back from Modal page
### Description

OnAppearing is not triggered when going back from Modal page.

### Steps to Reproduce

0. Download solution here 
[BugMauiModal.zip](https://github.com/dotnet/maui/files/9038845/BugMauiModal.zip)

1. Run solution
2. On MainPage, click on button to go the Second page
3. Go back with "Back button" located on navigation bar
4. On MainPage, label should display "Appeared 2" --> OK
5. On MainPage, click on button to go the Second page
6. From SecondPage, click on "Open modal" button
7. On modal page, click on "Close" button
8. On second page, abel should display "Appeared 2" but it displays "Appeared 1 time"--> Not OK

Mean, OnAppearing was not triggered in this case

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

N/A

### Relevant log output

_No response_

### LINKED ISSUE #11498: OnAppearing not called if returning from a modal page to a modal page
### Description

I'm not sure if this is by design, so if not, please let me know. Please see the attached repro.

```cs
protected override async void OnAppearing()
    {
       // Set breakpoint here for both modals
        base.OnAppearing(); 
        try
        {
            await ((WatchlistDetailsModalPageViewModel)BindingContext).OnAppearing();
        }
        catch (Exception) { }
    }
```

### Steps to Reproduce

1. Create a new maui app and add two modals pages to it
2. Override the OnAppearing and set a break point
3. Use Shell to navigate to the first modal and see, that the breakpoint is hit. 
4. Navigate to the next modal page, also this breakpoint is hit
5. Navigate back using Shell, and see that the breakpoint of modal number 1 is not hit on appearing

### Link to public reproduction project repository

https://github.com/AndreasReitberger/ReproScrollingIssueModal

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS 16.1, but also could be not relevant to version

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

With `Shell` you can modify the entire stack with a single URI request so with modals we're smart with `Appearing` and `Disappearing` so it doesn't fire on all the intermediate pages while the navigation is happening. 

This PR covers a couple cases where we weren't firing the `Appearing` and `Disappearing` event when pushing modals through the `INavigation` APIs.

I'm working to centralize all the `Modal` code into `ModalNavigationManager` https://github.com/dotnet/maui/pull/13025

Eventually this logic won't be spread out everywhere and just isolated down to a single class. This PR for now fixes a couple pain points for users and adds some tests for future refactoring. 

### Issues Fixed

Fixes #11498
Fixes #8513

### CODE REVIEW

**Review by rmarinho — APPROVED** [review]

**Review by rachelkang — APPROVED** [review]

**Comment by borrmann** [comment]
are these fixes going to be released in .NET 7 as well?

**Comment by SmartmanApps** [comment]
> /backport to net7.0

I love you Gerald! 😍

**Comment by jfversluis** [comment]
You can see the draft of the next release [here](https://github.com/dotnet/maui/releases/tag/untagged-0d3d534408ebca4e2147) and it's on there! 🎉

**Comment by SmartmanApps** [comment]
> You can see the draft of the next release [here](https://github.com/dotnet/maui/releases/tag/untagged-0d3d534408ebca4e2147) and it's on there! 🎉

Awesome! But I get a 404 on the link.

**Comment by gabsamples6** [comment]
Hi @jfversluis  thanks for the link but unfortunately its not visible to us.

**Comment by jfversluis** [comment]
Oh interesting I didn't know that draft released weren't public!

It's on the list and should be part of the next release.

**Comment by SmartmanApps** [comment]
This issue got mentioned again recently, and I want to clarify something about it...

"pushing modals through the INavigation APIs"

So this should affect (fix) NavigationPage as well, right? I'm having an issue with OnAppearing when pushing/popping Modal pages on Windows, and I THINK this fix will fix it, but I'm not sure cos the title says "shell", and I'm not using shell - will this fix the NavigationPage issue too?

**Comment by PureWeen** [comment]
> This issue got mentioned again recently, and I want to clarify something about it...
> 
> "pushing modals through the INavigation APIs"
> 
> So this should affect (fix) NavigationPage as well, right? I'm having an issue with OnAppearing when pushing/popping Modal pages on Windows, and I THINK this fix will fix it, but I'm not sure cos the title says "shell", and I'm not using shell - will this fix the NavigationPage issue too?

is there an open bug for this?

**Comment by SmartmanApps** [comment]
> > This issue got mentioned again recently, and I want to clarify something about it...
> > "pushing modals through the INavigation APIs"
> > So this should affect (fix) NavigationPage as well, right? I'm having an issue with OnAppearing when pushing/popping Modal pages on Windows, and I THINK this fix will fix it, but I'm not sure cos the title says "shell", and I'm not using shell - will this fix the NavigationPage issue too?
> 
> is there an open bug for this?

There were at least 3, all of which have been closed, at least 2 were closed because "duplicate of:/"fixed by" this issue (but as I said, this one mentions shell and the others don't, so I'm looking to clarify if this is just a fix for shell or for the other ones too - if it's only for shell then the others shouldn't have been closed).

https://github.com/dotnet/maui/issues/8513
https://github.com/dotnet/maui/issues/11498
https://github.com/dotnet/maui/issues/13668

**Comment by PureWeen** [comment]
> > > This issue got mentioned again recently, and I want to clarify something about it...
> > > "pushing modals through the INavigation APIs"
> > > So this should affect (fix) NavigationPage as well, right? I'm having an issue with OnAppearing when pushing/popping Modal pages on Windows, and I THINK this fix will fix it, but I'm not sure cos the title says "shell", and I'm not using shell - will this fix the NavigationPage issue too?
> > 
> > 
> > is there an open bug for this?
> 
> There were at least 3, all of which have been closed, at least 2 were closed because "duplicate of:/"fixed by" this issue (but as I said, this one mentions shell and the others don't, so I'm looking to clarify if this is just a fix for shell or for the other ones too - if it's only for shell then the others shouldn't have been closed).
> 
> #8513 #11498 #13668

The sample App in all three of those issues are using `Shell`.

Is there an issue/sample I can test that doesn't use `Shell` ?

**Comment by SmartmanApps** [comment]
> The sample App in all three of those issues are using `Shell`.
> 
> Is there an issue/sample I can test that doesn't use `Shell` ?

   Oh! I didn't notice that. I was just looking at the titles/labels, none of which mentioned shell.

   In looking around for some other info, I thought I found one (which doesn't mention shell, but does mention Windows) https://github.com/dotnet/maui/issues/10161 - but upon looking at the actual code it's using shell too. I can't share the project I'm experiencing it in, so I'd have to create a new one if needed (can't do that until later). 

   What I'm seeing is that after await PushModalAsync, OnAppearing for the page that just disappeared runs again - i.e. doesn't wait for the modal page to get popped - then it doesn't run when the page actually does reappear. I think it's getting it's sense on OnAppearing and OnDisappearing reversed (which is what I thought this issue was fixing?). i.e. OnAppearing is running when OnDisappearing should be running. I don't think it's a shell/platform-specific issue.

**Pull request merged**
