### PR TITLE
Update the macios dependencies to new package names.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Update the macios dependencies to new package names.

### CODE REVIEW

**Comment by rmarinho** [comment]
```
/Users/builder/azdo/_work/2/s/src/DotNet/Dependencies/Workloads.csproj : error NU1102: Unable to find package Microsoft.NET.Sdk.macOS.Manifest-8.0.100-rc.1 with version (= 13.3.8888-net8-rc2) [/Users/builder/azdo/_work/2/s/src/DotNet/DotNet.csproj]
```

Do we need to moveto rc2 first?

**Comment by rolfbjarne** [comment]
> ```
> /Users/builder/azdo/_work/2/s/src/DotNet/Dependencies/Workloads.csproj : error NU1102: Unable to find package Microsoft.NET.Sdk.macOS.Manifest-8.0.100-rc.1 with version (= 13.3.8888-net8-rc2) [/Users/builder/azdo/_work/2/s/src/DotNet/DotNet.csproj]
> ```
> 
> Do we need to moveto rc2 first?

Yes, seems that way.

**Comment by rmarinho** [comment]
Can you merge https://github.com/dotnet/maui/pull/17278 here ?

**Comment by rmarinho** [comment]
```
/Users/builder/azdo/_work/1/s/src/DotNet/Dependencies/Workloads.csproj : error NU1102: Unable to find package Microsoft.NET.Sdk.iOS.Manifest-8.0.100-rc.2 with version (= 16.4.8888-net8-rc2) [/Users/builder/azdo/_work/1/s/src/DotNet/DotNet.csproj]
```

**Comment by rolfbjarne** [comment]
```
D:\a\_work\1\s\src\Graphics\samples\GraphicsTester.iOS\SceneDelegate.cs(7,44): error CS8706: 'INativeObject._Xamarin_ConstructINativeObject(NativeHandle, bool)' cannot implement interface member 'INativeObject._Xamarin_ConstructINativeObject(NativeHandle, bool)' in type 'SceneDelegate' because feature 'static abstract members in interfaces' is not available in C# 10.0. Please use language version '11.0' or greater. [D:\a\_work\1\s\src\Graphics\samples\GraphicsTester.iOS\GraphicsTester.iOS.csproj]
D:\a\_work\1\s\src\Graphics\samples\GraphicsTester.iOS\AppDelegate.cs(9,42): error CS8706: 'INativeObject._Xamarin_ConstructINativeObject(NativeHandle, bool)' cannot implement interface member 'INativeObject._Xamarin_ConstructINativeObject(NativeHandle, bool)' in type 'AppDelegate' because feature 'static abstract members in interfaces' is not available in C# 10.0. Please use language version '11.0' or greater. [D:\a\_work\1\s\src\Graphics\samples\GraphicsTester.iOS\GraphicsTester.iOS.csproj]
D:\a\_work\1\s\src\Graphics\samples\GraphicsTester.MacCatalyst\AppDelegate.cs(9,42): error CS8706: 'INativeObject._Xamarin_ConstructINativeObject(NativeHandle, bool)' cannot implement interface member 'INativeObject._Xamarin_ConstructINativeObject(NativeHandle, bool)' in type 'AppDelegate' because feature 'static abstract members in interfaces' is not available in C# 10.0. Please use language version '11.0' or greater. [D:\a\_work\1\s\src\Graphics\samples\GraphicsTester.MacCatalyst\GraphicsTester.MacCatalyst.csproj]
D:\a\_work\1\s\src\Graphics\samples\GraphicsTester.MacCatalyst\SceneDelegate.cs(7,44): error CS8706: 'INativeObject._Xamarin_ConstructINativeObject(NativeHandle, bool)' cannot implement interface member 'INativeObject._Xamarin_ConstructINativeObject(NativeHandle, bool)' in type 'SceneDelegate' because feature 'static abstract members in interfaces' is not available in C# 10.0. Please use language version '11.0' or greater. [D:\a\_work\1\s\src\Graphics\samples\GraphicsTester.MacCatalyst\GraphicsTester.MacCatalyst.csproj]
```

Looks like we might need these two?

[`f697840` (#16987)](https://github.com/dotnet/maui/pull/16987/commits/f6978408137780f24501c849b7073925a4f2dd5d)
[`4b34bd5` (#16987)](https://github.com/dotnet/maui/pull/16987/commits/4b34bd5a410f00b586504760a351bfa7893245f7)

**Comment by rolfbjarne** [comment]
@rmarinho looks like the failures are unrelated?

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
