### PR TITLE
.NET 6 maui-mobile template

### PR DESCRIPTION
**Pull request by jonathanpeppers**
This adds a new `.NET Maui Application` template to join the ranks of
other templates in .NET 6:

    Template Name                                 Short Name           Language    Tags
    --------------------------------------------  -------------------  ----------  ----------------------
    Android Application                           android              [C#]        Android
    Console Application                           console              [C#],F#,VB  Common/Console
    Class library                                 classlib             [C#],F#,VB  Common/Library
    .NET MAUI Mobile Application                  maui-mobile          [C#]        MAUI/Android/iOS
    iOS Application                               ios                  [C#]        iOS

To build & install these templates:

    > dotnet pack .\src\Controls\src\Templates\Microsoft.Maui.Templates.csproj
    > dotnet new -i .\artifacts\Microsoft.Maui.Templates.*.nupkg

Note that the version should match what comes from
`eng\Version.targets`, the template will contain a `.csproj` with the
same version inside.

Then you should be able to see the installed templates with:

    > dotnet new --list

To use them you should be able to do:

    > mkdir foo ; cd foo
    > dotnet new maui-mobile
    > dotnet build

### CODE REVIEW

**Comment by BretJohnson** [comment]
Should this be `.NET MAUI Application` since it will (sooner or later) support desktop too?
And then the short name could probably be `maui-app` or `mauiapp`, depending on conventions for using the dash.

**Comment by qcjxberin** [comment]
这是可以开始构建 Maui模板并使用了吗？

**Comment by qcjxberin** [comment]
Is it possible to start building Maui templates and use them?

**Comment by jonathanpeppers** [comment]
@BretJohnson eventually there will be just a `dotnet new maui` and it would be desktop + mobile.  I took this name from an internal doc, but @Redth me know if it should be something else. I don't think we want `app` in the name, or it doesn't match the other platforms: `dotnet new ios` and `dotnet new android`

@qcjxberin you would need to build Maui itself, but you might start with these samples:

https://github.com/dotnet/maui/tree/main/src/Controls/samples

**Comment by qcjxberin** [comment]
@jonathanpeppers Thank you very much, just waiting to study and learn

**Comment by BretJohnson** [comment]
@jonathanpeppers Good to know. Where is the internal doc - can you share a link?

**Comment by jonathanpeppers** [comment]
@BretJohnson, sent you the link on Teams.

**Review by Redth — APPROVED** [review]

**Review by Redth — APPROVED** [review]

**Review by mattleibow — APPROVED** [review]
Woot!

**Pull request merged**
