### PR TITLE
Implement Date property in WinUI DatePickerHandler

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Implement `Date` property in WinUI DatePickerHandler

### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [x] Adds the property to the appropriate interface
- [x] Avoids any changes not essential to the handler property
- [x] Adds the mapping to the PropertyMapper in the handler
- [x] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [x] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [x] Tags ported renderer methods with [PortHandler]
- [x] Adds an example of the property to the sample project (MainPage)
- [x] Adds the property to the stub class
- [x] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might effect accessibility?
No

### CODE REVIEW

**Review by rachelkang — COMMENTED** [review]
I can see the Date when the DatePicker is initialized, but when I pick a different date, the DatePicker looks empty :/

**Comment by rmarinho** [comment]
Seems to work fine  selecting: 
image


image

Setting a date:

```new DatePicker { Date = new DateTime(1984, 11, 25) }```
image

**Review by rmarinho — APPROVED** [review]

**Comment by rachelkang** [comment]
@rmarinho will try again... did you change the background color though? I wonder if that's related

**Review by rachelkang — APPROVED** [review]
hmm nevermind, LGTM now!

**Pull request merged**
