### PR TITLE
Update maui blazor template min android version to API 24

### PR DESCRIPTION
**Pull request by TanayParikh**

### CODE REVIEW

**Comment by TanayParikh** [comment]
@rmarinho if we want to target this for MAUI patch, should we be merging into `release/6.0.3xx` or is main sufficient?

**Review by mattleibow — APPROVED** [review]

**Comment by TanayParikh** [comment]
\backport to release/6.0.3xx

**Comment by mattleibow** [comment]
@Redth do we need to set up a sr1 branch since 3xx is like GA?

**Pull request merged**
