### PR TITLE
Stop Android from pinning native references to system services

### PR DESCRIPTION
**Pull request by aritchie**
Android system services can have their pointers disposed of causing pinned MAUI references to error. 

### Description of Change
Remove all private references in Android Essentials.  Resolve the service from Application.Context.GetSystemService each time

### Issues Fixed

https://github.com/dotnet/maui/issues/22204

Fixes # 22204

### CODE REVIEW

**Comment by Redth** [comment]
@mattleibow do you recall why we ended up pinning these?

It looks like the change to do so happened in https://github.com/dotnet/maui/pull/5407 but I'm not seeing any explanation of the choice of approach.

**Comment by aritchie** [comment]
I don't think there will be much of a perf hit here.  It isn't called enough to really matter, however, I can also keep the private reference and watch the Handle == IntPtr.Zero to resolve the service again

**Review by mattleibow — APPROVED** [review]

**Comment by mattleibow** [comment]
@Redth mentioned to me offline that maybe we have the field to prevent the GC from collecting it. But, I am not sure if that was more just for iOS.

**Comment by PureWeen** [comment]
@aritchie any reason not to mark this ready for review?

**Comment by aritchie** [comment]
@PureWeen There was some debate around performance.  I can check the Handle to keep a reference pinned, but I don't think it was necessary.  Other than that, I haven't been able to get the sensor testing to work.

**Comment by mattleibow** [comment]
@aritchie what do you mean by this:

> I haven't been able to get the sensor testing to work.

Does the essentials sample app not run or something?

**Comment by aritchie** [comment]
@mattleibow Ya I've been having issues with it.  I've basically written a side chunk of code to test with for now.  I just haven't had the time to go back to sensors.

**Comment by mattleibow** [comment]
maybe we broke everything. We basically did 2 major changes to the build system these last few days so all is bad. Hopefully we can fix things soon and all the samples start running again :)

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
