### PR TITLE
Fix typo in ScrollToRequest.cs

### PR DESCRIPTION
**Pull request by lindexi**
### Description of Change

Just fix the typo.

### CODE REVIEW

**Review by rmarinho — APPROVED** [review]

**Comment by rmarinho** [comment]
@lindexi  you need to fix the usage also. and public api file

**Comment by lindexi** [comment]
@rmarinho Thank you

**Review by jsuarezruiz — APPROVED** [review]

**Review by mattleibow — APPROVED** [review]

**Comment by mattleibow** [comment]
@lindexi add this tp all the PublicAPI.txt files in the Core project:

```
*REMOVED*Microsoft.Maui.ScrollToRequest.HoriztonalOffset.get -> double
*REMOVED*Microsoft.Maui.ScrollToRequest.HoriztonalOffset.init -> void
*REMOVED*Microsoft.Maui.ScrollToRequest.ScrollToRequest(double HoriztonalOffset, double VerticalOffset, bool Instant) -> void
Microsoft.Maui.ScrollToRequest.HorizontalOffset.get -> double
Microsoft.Maui.ScrollToRequest.HorizontalOffset.init -> void
Microsoft.Maui.ScrollToRequest.ScrollToRequest(double HorizontalOffset, double VerticalOffset, bool Instant) -> void
```

**Comment by rmarinho** [comment]
Fixed with #9661 9661

**Pull request closed without merging**
