### PR TITLE
Do not use underscores in the ApplicationId

### LINKED ISSUE #19364: DEP0700 ERROR - Registration of the app failed. App manifest validation error...
### Description

Hello, after I created new MAUI blazor hybrid project in .NET 8, I am not able to build and start the app.

### Steps to Reproduce

1. `Create a file > New .NET MAUI APP`
2. `Press start (F5) Button with Windows Machine.`
Visual studio give me this error:

```
DEP0700: Registration of the app failed. [0x80080204] error 0xC00CE169: App manifest validation error: The app manifest must be valid as per schema: Line 10, Column 13, Reason: 'com.companyname.nis_tt' violates pattern constraint of '[-.A-Za-z0-9]+'.
The attribute 'Name' with value 'com.companyname.nis_tt' failed to parse.		
```	

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.49

### Affected platforms

Windows

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change

Underscores are not supported on Windows.

### Issues Fixed

Fixes #19364

### CODE REVIEW

**Review by tj-devel709 — DISMISSED** [review]

**Review by jfversluis — DISMISSED** [review]
Something is not happy here

>  /Users/builder/azdo/_work/3/s/src/TestUtils/src/Microsoft.Maui.IntegrationTests/TemplateTests.cs(70,30): error CS0103: The name 'docPath' does not exist in the current context [/Users/builder/azdo/_work/3/s/src/TestUtils/src/Microsoft.Maui.IntegrationTests/Microsoft.Maui.IntegrationTests.csproj]
/Users/builder/azdo/_work/3/s/src/TestUtils/src/Microsoft.Maui.IntegrationTests/TemplateTests.cs(71,51): error CS1061: 'IEnumerable<XElement>' does not contain a definition for 'Element' and no accessible extension method 'Element' accepting a first argument of type 'IEnumerable<XElement>' could be found (are you missing a using directive or an assembly reference?) [/Users/builder/azdo/_work/3/s/src/TestUtils/src/Microsoft.Maui.IntegrationTests/Microsoft.Maui.IntegrationTests.csproj]
/Users/builder/azdo/_work/3/s/src/TestUtils/src/Microsoft.Maui.IntegrationTests/TemplateTests.cs(71,16): error CS8602: Dereference of a possibly null reference. [/Users/builder/azdo/_work/3/s/src/TestUtils/src/Microsoft.Maui.IntegrationTests/Microsoft.Maui.IntegrationTests.csproj]

**Review by Eilon — DISMISSED** [review]

**Review by rmarinho — DISMISSED** [review]
Tests are failing . Also seems this changes from using the provisioned dotnet to use a global one ?

**Comment by mattleibow** [comment]
Thanks for catching that. My local changes got mixed in there.

**Review by Redth — APPROVED** [review]

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
