### PR TITLE
Update URL for MAUI support

### PR DESCRIPTION
**Pull request by mairaw**
### Description of Change

The way I see it, the tech community space is for discussions, announcements, not for support. Q&A would be the more appropriate platform for support.

### Issues Fixed

This is a small repo workflow suggestion, so I didn't file an issue, but let me know if it's required for this sort of change.

### CODE REVIEW

**Comment by mattleibow** [comment]
Shouldn't we use the new GitHub Discussions so that bugs can be upgraded to such and linked? https://github.com/dotnet/maui/discussions

**Comment by mairaw** [comment]
Happy to change to that as well. Let me know.

**Comment by jfversluis** [comment]
Yeah personally I feel more for keeping it close as well in the Discussions here

**Review by jamesmontemagno — APPROVED** [review]

**Comment by jamesmontemagno** [comment]
Official support should go over to Q&A as the CSS team monitors and answers questions along with the community.

**Pull request merged**
