### PR TITLE
Build maui.aar on CI

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change

Make sure to build the maui.aar binary on CI.

The current behaviour is that the aar needs to be built locally and then checked in. This means there is no way to know what is in the aar and potential for all sorts of issues. Building this part on CI make sure the code in the repo is what is shipped.

### CODE REVIEW

**Comment by rmarinho** [comment]
Why is this ? can we add some more documentation here?

**Comment by mattleibow** [comment]
I see CI is failing because it needs a newer Java:

>  Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.

**Comment by rmarinho** [comment]
what are we missing here @mattleibow  ?

**Comment by mattleibow** [comment]
Figuring out where the android sdk is I think... The build was failing last with not being found... Or maybe it was Java 11. I wonder if we can maybe set an envvar of ANDROID_SDK_ROOT to the Android sdk path

**Review by hartez — APPROVED** [review]

**Pull request merged**
