### PR TITLE
[X] Incremental SourceGenerator

### LINKED ISSUE #2688: [Enhancement] implement IIncrementalGenerator
## Summary

Currently, the new "XamlG" roslyn source generator does its full set of work on every build.

https://github.com/dotnet/maui/blob/c7b06faed7b66944fe6682e2757dc5568302244f/src/Controls/src/SourceGen/CodeBehindGenerator.cs#L16-L17

For example, an incremental build for `dotnet new maui` with a small C# change takes:

image

_NOTE: I only have `TargetFramework=net6.0-android`, I removed the other platforms. So this would be potentially x4 for Windows, iOS, Android, and Catalyst._

Compared to a `dotnet new android` app:

image

To help with incremental builds, Roslyn implemented a new `IIncrementalGenerator` interface:

* https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.md
* Used by ASP.NET here: https://github.com/dotnet/sdk/commit/ffeb2ec55dafd2b882e81ec63dfd65e33eee442d

_NOTE: their doc is slightly out of date, as `RegisterExecutionPipeline()` is now `RegisterSourceOutput()`._

## Intended Use Case

Any incremental build with no `.xaml` changes could be able to do less work.

/cc @StephaneDelcroix (I can also look into this, but thought I'd file for now)

### PR DESCRIPTION
**Pull request by StephaneDelcroix**
### Description of Change ###

Incremental SourceGenerator for XamlG

- fixes #2688

Implements #

### Additions made ###

* Adds 

### PR Checklist ###

- [ ] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [ ] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [ ] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [ ] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- [ ] Does this PR introduce a new control? (If yes, add an example using SemanticProperties to the SemanticsPage)
- [ ] APIs that modify focusability?
- [ ] APIs that modify any text property on a control?
- [ ] Does this PR modify view nesting or view arrangement in anyway?
- [ ] Is there the smallest possibility that your PR will change accessibility? 
- [ ] I'm not sure, please help me

If any of the above checkboxes apply to your PR, then the PR will need to provide testing to demonstrate that accessibility still works.

### CODE REVIEW

**Review by jonathanpeppers — APPROVED** [review]
I tested a `dotnet new maui` app after building with `dotnet cake --configuration=Release`.

Then even inside VS with .NET framework MSBuild, I'm getting:

image

This seems much better than what I saw in:

https://github.com/dotnet/maui/issues/2688

Thanks!

**Comment by StephaneDelcroix** [comment]
I wouldn't merge this PR until we can depend on stable nuget for the analyzers

**Comment by Redth** [comment]
@StephaneDelcroix @jonathanpeppers should the package reference to codeanalysis be moved into: https://github.com/dotnet/maui/blob/main/eng/Microsoft.Extensions.targets ?  Does this need to be added anywhere else to get pulled in as a library-pack or anything in the future?

**Comment by jonathanpeppers** [comment]
Aside I think `Microsoft.Extensions.targets` should be renamed to `PackageReferences.targets` or something. I named it that originally because only `Microsoft.Extensions` packages were in there.

This `PackageReference` determines a minimum version of Roslyn you're building with:
```xml
<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.0.0-4.final" PrivateAssets="All" />
```

And so if this works in VS 2022 17.1 (and whatever current build of VS Mac), I would say we're good to merge this.

I don't know what cadence Roslyn ships `Microsoft.CodeAnalysis.CSharp`, I'm not sure if that's something that should be setup for Maestro.

**Review by Redth — APPROVED** [review]

**Pull request merged**
