### PR TITLE
BlazorWebView: Allow for WPF and WinForms WebView2 Custom Startup Settings and Fixed Distribution Mode

### PR DESCRIPTION
**Pull request by MichaelPeter**
### Description of Change

Currently it is not possible to use WebView2 Fixed Distribution mode since the Blazor WebView creates a custom Environment which cannot be modified. This also prevents:
See [WebViewInitialize](https://github.com/dotnet/maui/issues/3861)

- Using Edge Canary Builds.
- Activating Beta features like --unsafe-web-gpu 
- Using startup flags in general
- Starting an FPS Counter.
- and many more...

This is a implementation which was implemented based on a suggestion in the issue.

Other issues related to that
https://github.com/dotnet/maui/issues/2548

`Uncarlities:` The WPF Version used a EventHandler<> Delegate Depedency Property for ExternalNavigationStarting. It is not clear why no WPF RoutedEvent is used for events. In WinForms it is also an EventHandler<> delegate, even thought for Windows Forms Controls, events are also more common.

The new InitializingWebView is an RoutedEvent in WPF. In Windows Forms it is an EventHandler Delegate Property.

Could change InitializingWebView after an explanation also to EventHandler<> in WPF too. But wanted to leave it like that will I know why an EventHandler is use.

### Issues Fixed

https://github.com/dotnet/maui/issues/3861
https://github.com/dotnet/maui/issues/2548

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=5086) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=5086) before we can accept your contribution.<br/><br/>:x: MichaelPeter [sign now](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=5086)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/maui?pullRequest=5086) it.</sub>

**Comment by MichaelPeter** [comment]
Thank you @SteveSandersonMS for the hint,

I was aware of `WEBVIEW2_RELEASE_CHANNEL_PREFERENCE`, but not the other environment variables - I tested it in my scenario and it worked.

As a hint:
The only thing which is still missing are these properties, but these are not importaint of my scenario:


```
            e.CoreWebView2EnvironmentOptions.AllowSingleSignOnUsingOSPrimaryAccount = true;
            e.CoreWebView2EnvironmentOptions.Language = "DE-DE";
            e.CoreWebView2EnvironmentOptions.TargetCompatibleBrowserVersion 
```

But `AllowSingleSignOnUsingOSPrimaryAccount`  I could imagine is importaint for azure developers. I did not find environment variables for them. (https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.1150.38)

As TargetCompatibleBrowserVersion a webgpu compatible version is installed, but ensureing a compatible version can also be checked differently, even if more diffcult.

**Comment by SteveSandersonMS** [comment]
Thanks @MichaelPeter. I've filed https://github.com/dotnet/maui/issues/5512 to follow up on the `AllowSingleSignOnUsingOSPrimaryAccount` requirement.

**Comment by Eilon** [comment]
Hi @MichaelPeter , with PR https://github.com/dotnet/maui/pull/5802 merged, I think there are now enough events and hooks to customize various WebView2 startup settings (and similar on other platforms in .NET MAUI).

Is it safe to close this PR now because there is enough functionality?

**Comment by jfversluis** [comment]
As per Eilon's comment, closing this one. @MichaelPeter thank you so much for all your efforts. If you believe this is still necessary please let us know and we'll gladly reopen this and see if we can get this merged.

**Pull request closed without merging**
