### PR TITLE
Android: recreate activity on dark mode change

### LINKED ISSUE #15359: Android dynamic theme change not working without styles.xaml file
### Description

The Android dynamic theme change feature in MAUI (Multi-platform App UI) is not functioning as expected when the styles.xaml file is missing. The dynamic theme change allows users to switch between different visual themes on the fly, enhancing the user experience and providing customization options. However, without the styles.xaml file, this feature fails to work properly on the Android platform.

Expected Behavior:

The dynamic theme change feature in MAUI should function correctly on Android, even when the styles.xaml file is absent. The application should allow users to switch between visual themes seamlessly, providing the desired customization options.

Current Behavior:

When the styles.xaml file is missing in the MAUI Android project, the dynamic theme change feature fails to work. Users are unable to switch between different visual themes, and the application retains the default theme without any option for customization.

https://github.com/dotnet/maui/assets/42434498/6d4a9cda-addb-4803-98f4-fdfb18137796

### Steps to Reproduce

1. Create a new MAUI project targeting the Android platform.
2. Exclude or remove the styles.xaml file from the project.
3. Implement dynamic theme change functionality in the application, allowing users to switch between visual themes.
Deploy and run the application on an Android device or emulator.
Attempt to change the theme dynamically using the provided options or controls.

### Link to public reproduction project repository

https://github.com/kubaflo/DynamicAppThemeChange

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #15524: Text entry border disappear when changing to/from dark mode in Android
### Description

If dark theme is enabled or disabled when application is running, border around text entry widgets (Entry, TextEditor, Picker) disappears. More specifically, it doesn't update its color on theme change so it blends with the background.
This is true for both light -> dark and dark -> light changes.

#### Light -> dark:
Capture_entry_border_light
Capture_entry_border_dark

------
#### Dark -> Light:
Capture_entry_border_dark_2
Capture_entry_border_light_2

### Steps to Reproduce

1. Create a Maui app with Entry elements.
2. Launch app on Android
3. While app is running, switch dark theme on (if it was off) or off (if it was on)

#### Expected behavior:
Text entry border remains visible.

#### Actual behavior:
Text entry border is not visible.

### Link to public reproduction project repository

https://github.com/webwarrior-ws/SampleMauiAppWithEntry

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

any?

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by webwarrior-ws**
### Description of Change

Recreate activity every time dark mode is enabled or disabled.
This ensures that theme changes are reflected in UI.

### Issues Fixed

Fixes #15359
Fixes #15524

### CODE REVIEW

**Comment by jfversluis** [comment]
@webwarrior-ws thanks for this! Does this have any implications for the lifecycle events being triggered or the state of the current screen etc?

**Comment by webwarrior-ws** [comment]
> @webwarrior-ws thanks for this! Does this have any implications for the lifecycle events being triggered or the state of the current screen etc?

Can't say for sure. I only managed to test it on a simple app.
On thing though is that recreation of activity breaks Maui test runner. It crashes with the following exception:
```
Java.Lang.IllegalStateException: 'The Fragment NavigationRootManager_ElementBasedFragment{c10521e} (559e9e4d-e909-4bb6-b192-a3f5a7b12427) that owns View androidx.fragment.app.FragmentContainerView{ede4b43 V.E...... ......ID 0,0-1080,1988 #7f080135 app:id/nav_host aid=1073741831} has already been destroyed. Nested fragments should always use the child FragmentManager.'
```

**Comment by mattleibow** [comment]
What happens if you remove the `ConfigChanges.UiMode` from `ConfigurationChange`:

https://github.com/dotnet/maui/blob/02481e6ef8a9267f810f86daae1e8c2228a26de4/src/Templates/src/templates/maui-mobile/Platforms/Android/MainActivity.cs#L7

I think if you want a new activity, you should let the OS know and it will recreate for you...

**Review by mattleibow — CHANGES_REQUESTED** [review]
Marking this red for now as I think the better fix is to remove the "do not recreate activity" flag if you do indeed want to recreate.

**Comment by knocte** [comment]
> So I just want to clarify, this PR is fixing the case where there is **no dynamic styles xaml**

Yes (because it fixes bug 15359), however it also fixes a case where the developer uses the stock MAUI template without removing any styles.xaml, which is bug 15524.

**Comment by webwarrior-ws** [comment]
> What happens if you remove the `ConfigChanges.UiMode` from `ConfigurationChange`:
> 
> https://github.com/dotnet/maui/blob/02481e6ef8a9267f810f86daae1e8c2228a26de4/src/Templates/src/templates/maui-mobile/Platforms/Android/MainActivity.cs#L7
> 
> I think if you want a new activity, you should let the OS know and it will recreate for you...

I tried that, and it doesn't work correctly - some colors get updated, but not others and UI becomes unusable (dark text/other elements on dark background or vice versa).

**Comment by webwarrior-ws** [comment]
> @mattleibow requested a review from @PureWeen 

@PureWeen ping?


> > So I just want to clarify, this PR is fixing the case where there is **no dynamic styles xaml**
> 
> Yes (because it fixes bug 15359), however it also fixes a case where the developer uses the stock MAUI template without removing any styles.xaml, which is bug 15524.

@knocte is correct, does that answer your question @mattleibow ?

BTW do you guys need me to rebase the PR?

**Comment by mattleibow** [comment]
Recreating the activity when the theme changes is not what we want to do. We need a different way to pass configuration changes to components that are not responding.

You mention:

> I tried that, and it doesn't work correctly - some colors get updated, but not others and UI becomes unusable (dark text/other elements on dark background or vice versa).

This either needs to be a new issue or we need to keep tracking the existing ones.

This PR forces the activity to recreate, when MAUI already handles most of the theme changes without destroying anything.

**Pull request closed without merging**
