### PR TITLE
[core] use Lazy<T> for MauiContext properties

### PR DESCRIPTION
**Pull request by jonathanpeppers**
Context: https://github.com/unoplatform/performance/tree/master/src/dopes/DopeTestMaui

Building upon #7996 and #8001, I noticed while profiling the sample
app putting N `Label` on the screen:

    405.02ms (2.3%) microsoft.maui!Microsoft.Maui.MauiContext.get_Context()
    77.90ms (0.44%) microsoft.maui!Microsoft.Maui.MauiContext.get_Handlers()

Meaning that around ~2.74% of the time was spent just calling these two
properties. These properties hit Microsoft.Extensions each time to
locate the service:

    public Android.Content.Context? Context => _services.GetService<Android.Content.Context>();

These are core-services that wouldn't change after
startup, so should we just use `Lazy<T>` instead of doing a call like
this each time?

I also made use of `ANDROID`, as that is the preferred define to use
in .NET 6+ instead of `__ANDROID__`:

https://github.com/dotnet/designs/blob/a447d77bb53d189746ccd80c2d814064c2b6c606/accepted/2020/net5/net5.md#vary-implementation

## Results ##

A `Release` build on a Pixel 5 device, I was getting:

    Before: 81.70 Dopes/s
    After:  91.94 Dopes/s

image

### CODE REVIEW

**Review by jsuarezruiz — APPROVED** [review]

**Comment by PureWeen** [comment]
@jonathanpeppers 

> These properties hit Microsoft.Extensions each time to locate the service:

Is this slower because it's going through our [`WrappedServiceProvider`](https://github.com/jonathanpeppers/maui/blob/5c4a4993d5d62634b570650be58e2c3aaf70a779/src/Core/src/MauiContext.cs#L60-L69) ?

It looks like from your measurements the `get_Context` call is the slower of the two and I'm pretty sure that's the one that'll hit the `WrappedServiceProvider` and won't make it to `Extensions` at all?

**Comment by jonathanpeppers** [comment]
Yeah it is `WrappedServiceProvider`:

image

[maui-app_20220614_112919.speedscope.zip](https://github.com/dotnet/maui/files/8910551/maui-app_20220614_112919.speedscope.zip)

But it should just be hitting that `ConcurrentDictionary`. This might only be a problem because `.Context` is called so many times.

**Comment by PureWeen** [comment]
@jonathanpeppers Yea, these changes are just a little interesting because AFAICR this is [originally how we were doing it](https://github.com/dotnet/maui/pull/2653/files#diff-a917d9253a90aaf0e151e17691b19e4cb23bbac83ae652372879451d3631d2dfL28-L29) but then we generalized it into the `ConcurrentDictionary` 

The amount of things we add into the `WrappedServiceProvider` is contained and it's not something that users can add to, so I kind of wonder if we need to just get rid of the `ConcurrentDictionary` and just go back to having a single property for everything. 

The code now how it runs just feels a bit funny
- We add a specific scoped service like `Android.Context` that goes into the `ConcurrentDict`
- Then the first time it's retrieved we store it locally so it's no longer retrieved from the `ConcurrentDict`

Meanwhile all user requests are now going through the `ConcurrentDict` before hitting the Ms.Ext's

Not saying we need to block this PR on any of this but it feels like we should just get rid of the `ConcurrentDict` and just deal with manually adding these `Scoped` properties that we create.

@mattleibow ^

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/issues/8128

**Pull request merged**
