### PR TITLE
Fix 'Properties' folder visibility in the .NET MAUI Blazor template

### LINKED ISSUE #4641: Properties folder doesn't show up in the .NET MAUI Blazor template
### Description

The .NET MAUI Blazor template removes the Properties folder for some unknown reason. The .NET MAUI template doesn't do this. 

### Steps to Reproduce

Create a default .NET MAUI Blazor template and look for the Properties folder.

### Version with bug

Preview 13

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Win11

### Did you find any workaround?

Include the Properties folder in the solution

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by MackinnonBuck**
### Description of Change

The .NET MAUI Blazor App template was explicitly excluding `Properties\launchSettings.json` from the `.csproj` to prevent it from being copied to output directories, but this also prevented the 'Properties' folder from displaying in the VS Solution Explorer. This led to an inconsistent IDE experience, since the 'Properties' folder was visible when using the .NET MAUI App template, but not when using the .NET MAUI Blazor App template.

This change updates the .NET MAUI Blazor App template to exclude the 'Properties' folder from the build output directory without making it invisible in the IDE.

This is only necessary at all because of a difference in SDK behavior between [`Microsoft.NET.Sdk`](https://github.com/dotnet/sdk/blob/85886857f1037a1596603837ffc28022a09ed928/src/WebSdk/Worker/Targets/Microsoft.NET.Sdk.Worker.props#L32) and [`Microsoft.NET.Sdk.Razor`](https://github.com/dotnet/sdk/blob/85886857f1037a1596603837ffc28022a09ed928/src/RazorSdk/Sdk/Sdk.Razor.StaticAssets.ProjectSystem.props#L40).

### Issues Fixed

Fixes #4641

### CODE REVIEW

**Review by SteveSandersonMS — APPROVED** [review]
I'm not super familiar with these specific MSBuild properties but this looks great to me.

**Comment by SteveSandersonMS** [comment]
> I'll have to do a bit more investigation here - the number of CI failures seems a bit too high to be attributed to general flakiness.

Yeah, the CI errors include `error : The path '../../../../../../../../../_temp/templatesTestmaui_blazor/Properties/launchSettings.json' would result in a file outside of the app bundle and cannot be used.` which seems like it does relate to the change here.

> Also, I've discovered that for whatever reason, the Properties folder still gets copied to the output directory only on Windows

Oh dear, that's inconvenient. Let us know if you don't manage to find the right info!

**Comment by Eilon** [comment]
Yeah the tricky part here is to make it work for Android and iOS, each of which do things with `Content` items that are incompatible with what the Razor SDK wants.

Pranav did some changes recently that might somehow alleviate this: https://github.com/dotnet/maui/pull/4861

So it's worth investigating how Pranav's changes might relate to this and whether we can do something similar here, or somehow build on those changes.

**Comment by MackinnonBuck** [comment]
Thanks for the pointer, @Eilon.

I've made a small addition to Pranav's changes that removes the contents of the Properties folder from the build output (without doing so in the template, which affects the visibility of the folder in the IDE). This does seem to behave properly for all platforms now. Would you mind taking a look to make sure I didn't do anything obviously egregious? 🙃

**Review by mattleibow — APPROVED** [review]

**Pull request merged**
