### PR TITLE
Remove unnecessary MeasureOverride from RefreshView;

### LINKED ISSUE #3248: [Bug] [Android] RefreshView not resizing
### Description
When using a padding on `VerticalStackLayout`, to which elements get added after finishing an HTTP-request, inside a `RefreshView`, the size of the refresh views content is not getting calculated (updated) correctly.

### Steps to Reproduce

1. Create `ContentPage`
2. Add `RefreshView`
3. Add `ScrollView`
4. Add `VerticalStackLayout`
5. Add padding to `VerticalStackLayout`
6. Perform HTTP-request and add components to `VerticalStackLayout`

### Expected Behavior
The `RefreshView` gets resized correctly.

### Actual Behavior
The size of `RefreshView` is not updated.

### Basic Information

- Version with issue: 6.0.101-preview.9.1843
- Last known good version: -
- IDE: Visual Studio 2022 Preview 7

#### Actual:
image
#### Expected:
image
(Removed padding due to the issue)

### Reproduction Link
[Here](https://github.com/LarsBehl/StatusApp/blob/feature/stat-07_refreshView/MainPage.xaml) is a link to the `XAML` where the issue is currently present.

### LINKED ISSUE #5772: ScrollView is not scrollable inside of RefreshView
### Description

Seems like VerticalStackLayout grows infinitely inside of RefreshView, therefore you cannot scroll any content inside of RefreshView.

### Steps to Reproduce

1. Run the page with the following content:
```xaml
    <RefreshView>
        <ScrollView>
            <VerticalStackLayout Spacing="50">
                <Label Text="1" />
                <Label Text="2" />
                <Label Text="3" />
                <Label Text="4" />
                <Label Text="5" />
                <Label Text="6" />
                <Label Text="7" />
                <Label Text="8" />
                <Label Text="9" />
                <Label Text="10" />
                <Label Text="11" />
                <Label Text="12" />
                <Label Text="13" />
                <Label Text="14" />
                <Label Text="15" />
                <Label Text="16" />
                <Label Text="17" />
                <Label Text="18" />
                <Label Text="19" />
                <Label Text="20" />
            </VerticalStackLayout>
        </ScrollView>
    </RefreshView>
```

2. Try to scroll down.

ER:
Content is scrolled successfully,

AR: 
You cannot scroll down.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 12

### Did you find any workaround?

You can wrap it in yet another ScrollView, so it would look something like that:
```xaml
    <ScrollView>
        <RefreshView>
            <ScrollView>
                <VerticalStackLayout>
                      ...
                </VerticalStackLayout>
            </ScrollView>
        </RefreshView>
    </ScrollView>
```

### Relevant log output

_No response_

### LINKED ISSUE #12132: ISO: Scrollview inside Refrehview
### Description

Although the last update should have provided a bugfix - this is not the case.
When there is a scrollview inside a refreshview, you can´t scroll to the bottom.
In my sample there is height-request set for the collectionviews because of the height-bug (infinite height) of the collectionview in IOS.

### Steps to Reproduce

1. Clone repository
2. Start the app
3. Click on "Scrollview inside refreshview IOS"
4. Try to scroll to the bottom

### Link to public reproduction project repository

https://github.com/FM1973/RefreshGridRepo.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS 14 and up

### Did you find any workaround?

Not really.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by hartez**
### Description of Change

RefreshView has an old override of MeasureOverride from back when the layout system was still in flux and the porting from Forms was going fast, furious, and largely un-thought-through. The resulting measured size could exceed the container constraints to become the size of entire content of the ScrollView, which ultimately meant the ScrollView could not be, well, scrolled.

These changes remove the now-unnecessary override. 

Since the difference between working/not working is scrollability, we don't currently have a good way to write an automated test for this.

### Issues Fixed

Fixes #5772
Fixes #3248
Fixes #12132

### CODE REVIEW

**Review by PureWeen — APPROVED** [review]
Looks good!

I tested these changes with https://github.com/dotnet/maui/issues/3248 as well and it looks it fixes that issue as well.

**Comment by sung-insightly** [comment]
Will this be back ported to .net6?

**Pull request merged**
