### PR TITLE
Develop/net9.0 maonaoda custom fix

### PR DESCRIPTION
**Pull request by maonaoda**
Don`t merge.

I just want to build nuget.

### CODE REVIEW

**Comment by maonaoda** [comment]
I just want to generate nuget for custom fix. anyone can help me ?

**Comment by mattleibow** [comment]
What are you hoping to see different with these changes?

**Comment by maonaoda** [comment]
> What are you hoping to see different with these changes?


- https://github.com/dotnet/maui/issues/23128
- https://github.com/dotnet/maui/issues/23131
- https://github.com/maonaoda/maui/commit/2bf2ead1dd2a8cdb584338c236470e24c2d59658
   Reset to Xamarin's code, fixes bad behavior on menu index changes, such as missing text and icon of menu

**Comment by maonaoda** [comment]
The third problem can only be reproduced on 9.0.0-preview.7.24407.4. Other versions will crash when changing（add/remove）tab item

**Comment by PureWeen** [comment]
You can generate a nuget locally with 

dotnet cake --pack

**Comment by maonaoda** [comment]
I used dotnet cake --pack, but the generated package does not contain net8.0android?

**Comment by maonaoda** [comment]
I remember that net8.0 was also generated at that time, but now the latest code seems to have cancelled the generation of net8.0

**Pull request closed without merging**
