### PR TITLE
[net7.0] [Tizen] Add missing Shell features in Tizen

### PR DESCRIPTION
**Pull request by shyunMin**
### Description of Change

This PR backports #11597  to `net7.0`

### CODE REVIEW

**Comment by mattleibow** [comment]
Can we move the API changes to Unshipped? We need that for tooling to generate API diffs.

Basically, Shipped must remain unchanged and Unshipped can:
 - Remove by adding the `*REMOVED*<old-api>`
 - Change by adding `*REMOVED*<old-api>` and `<new-api>`
 - Add by just adding `<new api>`

Items do not need a removed from unshipped, they can just be deleted.

**Comment by shyunMin** [comment]
@mattleibow Thank you for explaining to me.  I've updated Unshipped file😊

**Comment by mattleibow** [comment]
I think I understand what you are saying and yeah, all changes are in UNshipped, a script moves it to shipped.

**Comment by shyunMin** [comment]
> I think I understand what you are saying and yeah, all changes are in UNshipped, a script moves it to shipped.

Thank you :) I have made a new commit.

**Review by mattleibow — APPROVED** [review]

**Comment by shyunMin** [comment]
Hello @mattleibow, I have rebased this PR to resolve the conflict, please re-run azp

**Review by mattleibow — APPROVED** [review]

**Pull request merged**
