### PR TITLE
[android] update AOT profile

### PR DESCRIPTION
**Pull request by jonathanpeppers**
This should be one last update for the Android `*.aotprofile` files. I
recorded these using the latest Android build on the branch for PR #6863.

Looking at the [JIT times report][0] for the .NET Podcast app, I
noticed `{Binding}` was listed:

    Total (ms) |  Self (ms) | Method
          0.99 |       0.99 | Microsoft.Maui.Controls.Xaml.BindingExtension:Microsoft.Maui.Controls.Xaml.IMarkupExtension<Microsoft.Maui.Controls.BindingBase>.ProvideValue (System.IServiceProvider)

I duplicated the `Label` from `CommonMethods.cs` to .xaml, and used
`{Binding}` on the `Text` property, so this will be included in the
profile.

[0]: https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/profiling.md#profiling-the-jit-compiler

## Results ##

.NET Podcast app:

    Average(ms): 802
    Std Err(ms): 4.25049016781202
    Std Dev(ms): 13.4412301024373
    ---
    Average(ms): 797.7
    Std Err(ms): 3.45784133046423
    Std Dev(ms): 10.934654391734

`dotnet new maui`:

    Average(ms): 565.8
    Std Err(ms): 4.4988887516808
    Std Dev(ms): 14.226735395023
    ---
    Average(ms): 550.7
    Std Err(ms): 1.96666666666667
    Std Dev(ms): 6.21914606499781

### CODE REVIEW

**Comment by mattleibow** [comment]
Might be worth adding a collectionview in there tbh... Get some nice perf numbers from that.

**Review by mattleibow — APPROVED** [review]
A fair bit of changes in this one that I am not sure why is happening, but if that is the state then it is the state.

**Comment by jonathanpeppers** [comment]
> Might be worth adding a collectionview in there tbh... Get some nice perf numbers from that.

We have that here: 

https://github.com/dotnet/maui/blob/744966449e4bd6c9935442984069a71aff1586cc/src/ProfiledAot/src/maui/App.xaml#L15

But maybe it could actually get displayed on the screen with items -- I'll look into that in the future.

**Pull request merged**
