### PR TITLE
[Android] Fix Border clipping issues

### LINKED ISSUE #18071: New bug in .NET 8: Windows and Android no longer drawing Borders/clipping correctly (previously was okay)
### Description

I posted a bug report here regarding .NET 7 iOS not rendering Borders and clipping masks correctly: https://github.com/dotnet/maui/issues/17998

I was suggested to try .NET 8 and .NET 8 did fix this in iOS but it has now broken it in Android and Windows.

Here is the correct behavior from .NET 7 Android and also now seen with .NET 8 iOS:
ios border mask bug 2

Here is what Windows .NET 8 is now doing (the same thing iOS used to do):
windows border alignment bug

Here is what Android .NET 8 is now doing (new abnormal behavior):
ios border mask bug android 8

So this problem was fixed in iOS from .NET 7 to .NET 8. But it is now broken in Windows and Android, whereas in .NET 7 Windows and Android worked fine.

A unified fix please would be very appreciated, as this function is very basically essential.

### Steps to Reproduce

Open bug project, play in various platforms and versions, observe the various behaviors.

Working:
- .NET 7 Windows, .NET 7 Android, .NET 8 iOS

Broken:
- .NET 8 Windows, .NET 8 Android, .NET 7 iOS

### Link to public reproduction project repository

https://github.com/jonmdev/Border-iOS-Mask-Bug

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.96

### Affected platforms

Android, Windows

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

_(Work in progress)_

Fix Border clipping issues on Android.
issue-border-droid

The issue mentions problems in Windows, but I can't reproduce them.
fix-18071-win

Added a golden test to validate this scenario.

### Issues Fixed

Fixes #18071

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
Added another test to validate the Border with different shapes and strokes
image

**Comment by jonmdev** [comment]
Does this fix by any chance also fix this issue?

https://github.com/dotnet/maui/issues/17882

It would be really great to get a fix for that too. If both these are fixed we can get consistent predictable layouts with Borders which is really critical for putting out any projects using Borders. It would help a lot.

Currently, between both of these bugs it is very hard to know how anything will look on any given platform or consistently control it.

**Comment by jonmdev** [comment]
Also, I hate to pile on, but I just remembered in iOS we also have this pretty bad bug, which I think might be due to automatic iOS animation tweening of the object preventing it from reaching the target size immediately:

https://github.com/dotnet/maui/issues/18204

If we could get all three of these fixed (the masking, the drawing to the edges, and the iOS lagging) Border would be pretty solid for use and it would be appreciated. Thanks again.

**Comment by activa** [comment]
Your test shows this:

chrome_2023-11-16_21-35-44

That's not how it's supposed to render though. The border is cut off in the rounded corners.

This is more obvious in the following test case:
qemu-system-x86_64_2023-11-16_21-37-06

On Windows and iOS it renders correctly:

MauiApp8-1_2023-11-16_21-38-00

The above is using the following XAML:

```
<Border Stroke="Black" StrokeThickness="8"
        StrokeShape="RoundRectangle 30,0,0,30" 
        WidthRequest="200" HeightRequest="200">
    <Grid RowDefinitions="Auto,*" >
        <BoxView Color="Red" Grid.Row="0" HeightRequest="50"/>
        <BoxView Color="Green" Grid.Row="1" />
    </Grid>
</Border>
```

**Pull request closed without merging**
