### PR TITLE
[MacCatalyst] Fix Button appearance on Catalyst using UIDeviceFamily 6

### LINKED ISSUE #7782: [MacCatalyst] Button's appearance does not look good after building an application with adopted Mac idiom
### Description

When I adopt the Mac idiom for my catalyst application the appearance of the Button changes and doesn't look good. Here is the button with iPad idiom:
Screenshot 2022-06-06 at 10 40 32

And here is how the Button looks after adopting the Mac idiom:
Screenshot 2022-06-06 at 10 41 14

As you can see it looks like the background of the control is not applied fully (only partially) which makes it look like there is some kind of a border around the control.

### Steps to Reproduce

1. Create a new maui project.
2. Go to the Info.plist of Catalyst and set the UIDeviceFamily to 6 - that enables the optimized interface for macOS.
3. Run the application and check the Button's appearance.

Attached you can find a project that demonstrates the issue.
[HelloMaui.zip](https://github.com/dotnet/maui/files/8842766/HelloMaui.zip)

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS Monterey 12.4

### Did you find any workaround?

You can set PreferredBehavioralStyle of the native Button to Pad in order to preserve the iPad look and feel of the control:
`button.PreferredBehavioralStyle = UIBehavioralStyle.Pad;`

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix Button appearance on Catalyst using UIDeviceFamily 6.

### Issues Fixed

Fixes #7782

### CODE REVIEW

**Review by rmarinho — CHANGES_REQUESTED** [review]
I don't think this is the correct fix. What if the user want's to use the mac style ? we are hardcoding it.

**Comment by jsuarezruiz** [comment]
> I don't think this is the correct fix. What if the user want's to use the mac style ? we are hardcoding it.

Let me review it again finding another approach.

**Comment by Redth** [comment]
This one needs more thought.  If the intent is to enable UIDeviceFamily to be macOS, there's probably a reason, and us setting the style to be forced back to iPad style is probably not the desired outcome.

**Comment by rmarinho** [comment]
Ok I did some work today and got somewhere.. but I m missing something. 

We need to find a way to understand if the user wanted the "optimized Mac version" or the iPad Version. I think one way is to check UIDeviceFamily = 6.

then we need to grab the new UIBUttonConfiguration and change some properties there.. something like this:

```

var config = button.Configuration ?? UIButtonConfiguration.FilledButtonConfiguration;
config.BaseBackgroundColor = button.BackgroundColor;
config.BaseForegroundColor = button.TextColor;
config.Background.StrokeColor = button.StrokeColor;
config.Background.StrokeWidth = button.StrokeThickness;
config.Background.CornerRadius = button.CornerRadius
config.ContentInset = button.Padding;

**Comment by rmarinho** [comment]
to test use : UIDeviceFamily 6

```
<key>UIDeviceFamily</key>
	<array>
		<!-- <integer>1</integer>
		<integer>2</integer> -->
		<integer>6</integer>	
	</array>
```

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
