### PR TITLE
Refactored Map to an interface

### PR DESCRIPTION
**Pull request by sps014**
### Description of Change ###

Implements #

```cs
public interface IMap
{
	Task OpenMapsAsync(double latitude, double longitude, MapLaunchOptions options);
	Task OpenMapsAsync(Placemark placemark, MapLaunchOptions options);
}
```
Part of https://github.com/dotnet/maui/issues/4497

### CODE REVIEW

**Comment by sps014** [comment]
@mattleibow can you please review it.
Thanks

**Review by Redth — APPROVED** [review]

**Review by mattleibow — APPROVED** [review]

**Comment by sps014** [comment]
Can you please rerun the pipelines, yesterday every pipeline was failing due to .net sdk issue?

**Pull request merged**
