### PR TITLE
feat: Added nullable annotations for IValueConverter.

### PR DESCRIPTION
**Pull request by HavenDV**
### Description of Change
Added nullable annotations to IValueConverter as it is often used. Since mostly nullable annotations are available, it's strange to see them missing from classes like IValueConverter.

I am not sure about nullability of `targetType` and `culture` parameters.

### Issues Fixed

Fixes #

### CODE REVIEW

**Comment by rmarinho** [comment]
```
D:\a\_work\1\s\src\Controls\src\Core\Platform\Tizen\IconConverter.cs(12,48): error CS8600: Converting null literal or possible null value to non-nullable type. [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net7.0-tizen]
D:\a\_work\1\s\src\Controls\src\Core\Platform\Tizen\IconConverter.cs(12,48): error CS8604: Possible null reference argument for parameter 'text' in 'object? TypeConverter.ConvertFromInvariantString(string text)'. [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net7.0-tizen]
    14 Warning(s)
    2 Error(s)
```

**Comment by HavenDV** [comment]
Since `TypeConverter.ConvertFromInvariantString` allows null, I used this code `converter.ConvertFromInvariantString((value as string)!)`
Refs:
https://referencesource.microsoft.com/#System/compmod/system/componentmodel/TypeConverter.cs,125
https://referencesource.microsoft.com/#System/compmod/system/componentmodel/TypeConverter.cs,246

**Review by mandel-macaque — APPROVED** [review]

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
