### PR TITLE
refactored Geocoding to an interface

### PR DESCRIPTION
**Pull request by sps014**
#### Implements 

```cs
public interface IGeocoding
{
	Task<IEnumerable<Placemark>> GetPlacemarksAsync(double latitude, double longitude);
	Task<IEnumerable<Location>> GetLocationsAsync(string address);
}
```
Part of #4497

### CODE REVIEW

**Comment by sps014** [comment]
@mattleibow @Redth  can you please look into this one.

**Comment by Redth** [comment]
Awesome, will look more closely tomorrow, thanks for the help here!

**Review by mattleibow — APPROVED** [review]

**Comment by mattleibow** [comment]
Thanks for the help!

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
