### PR TITLE
[Essentials] Add DateTimeOffset overload in Preferences

### LINKED ISSUE #22786: Add DateTimeOffset overload to Preferences
### Description

I would love to store DateTimeOffset in MAUI Essentials Preferences, today it only accepts DateTime. Perhaps other overloads for primitives like TimeSpan would also be nice, so you don't have to convert to string and back.

### Public API Changes

```csharp
var date = DateTimeOffset.UtcNow;
Preferences.Set("MyTime", date);

date = Preferences.Get("MyTime", DateTimeOffset.UtcNow);
```

### Intended Use-Case

I have instances where I need to store a last fetched timestamp, which currently I have to convert from DateTimeOffset to DateTime.

### PR DESCRIPTION
**Pull request by Cheesebaron**
### Description of Change

Adds overload in Preferences to store and retrieve DateTimeOffset.

There is no `ToBinary()` method on `DateTimeOffset` so I am storing it as a    ###string.

~~I have an issue with the roslyn analyzer that checks for PublicAPI, it keeps complaining no matter what I add to either file.~~ ~~

### Issues Fixed

Fixes #22786

### CODE REVIEW

**Comment by jfversluis** [comment]
> I have an issue with the roslyn analyzer that checks for PublicAPI, it keeps complaining no matter what I add to either file.

Yeah its kind of annoying, but it probably keeps complaining because you have to add it to every txt file for every platform where this API is introduced.

**Comment by Cheesebaron** [comment]
> > I have an issue with the roslyn analyzer that checks for PublicAPI, it keeps complaining no matter what I add to either file.
> 
> Yeah its kind of annoying, but it probably keeps complaining because you have to add it to every txt file for every platform where this API is introduced.

Do I add it to .Shipped or .Unshipped?

**Comment by mattleibow** [comment]
Unshipped.

**Comment by Cheesebaron** [comment]
Ah let me fix that

**Comment by mattleibow** [comment]
I see you are using `ToString("O")` - how does this work when the culture or timezone changes on the device?  I don't see docs on the `O` format, and is it better to save using invariant culture and then a parse exact?

**Comment by Cheesebaron** [comment]
> I see you are using `ToString("O")` - how does this work when the culture or timezone changes on the device? I don't see docs on the `O` format, and is it better to save using invariant culture and then a parse exact?

Looking at standard format strings here: https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings

`O` format saves in ISO 8601 which doesn't affect the format regardless of culture. It is also the only format that also contains the offset part.

**Review by mattleibow — DISMISSED** [review]

**Comment by mattleibow** [comment]
> Sorry for the many pushes, I can't build UWP on my machine 😢 

No prob, I also do CI driven dev because I am to lazy to boot a windows machine or launch a new devbox.

**Comment by mattleibow** [comment]
Windows is having a few failures:

System.InvalidCastException : Invalid cast from 'System.String' to 'System.DateTimeOffset'.

Stack trace
```
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at Microsoft.Maui.Storage.UnpackagedPreferencesImplementation.Get[T](String key, T defaultValue, String sharedName) in /_/src/Essentials/src/Preferences/Preferences.uwp.cs:line 210
   at Microsoft.Maui.Storage.PreferencesImplementation.Get[T](String key, T defaultValue, String sharedName) in /_/src/Essentials/src/Preferences/Preferences.uwp.cs:line 37
   at Microsoft.Maui.Essentials.DeviceTests.Preferences_Tests.DateTimeOffsetPreservesOffset_NonStatic(String sharedName, TimeSpan offset) in /_/src/Essentials/test/DeviceTests/Tests/Preferences_Tests.cs:line 497
   at InvokeStub_Preferences_Tests.DateTimeOffsetPreservesOffset_NonStatic(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
``

**Comment by mattleibow** [comment]
Since this has a new API, it probably needs to target net9.0 instead.

**Review by mattleibow — CHANGES_REQUESTED** [review]
Since this has a new API, it probably needs to target net9.0 instead.

**Comment by Cheesebaron** [comment]
> Since this has a new API, it probably needs to target net9.0 instead.



> Windows is having a few failures:
> 
> System.InvalidCastException : Invalid cast from 'System.String' to 'System.DateTimeOffset'.
> 
> Stack trace
> 
> ```
>    at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
>    at Microsoft.Maui.Storage.UnpackagedPreferencesImplementation.Get[T](String key, T defaultValue, String sharedName) in /_/src/Essentials/src/Preferences/Preferences.uwp.cs:line 210
>    at Microsoft.Maui.Storage.PreferencesImplementation.Get[T](String key, T defaultValue, String sharedName) in /_/src/Essentials/src/Preferences/Preferences.uwp.cs:line 37
>    at Microsoft.Maui.Essentials.DeviceTests.Preferences_Tests.DateTimeOffsetPreservesOffset_NonStatic(String sharedName, TimeSpan offset) in /_/src/Essentials/test/DeviceTests/Tests/Preferences_Tests.cs:line 497
>    at InvokeStub_Preferences_Tests.DateTimeOffsetPreservesOffset_NonStatic(Object, Span`1)
>    at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
> ```

Gotta fire up my Windows machine to see what is up here. Thanks!

**Comment by Cheesebaron** [comment]
So seems like DateTime was skipped in the device tests for unpackaged UWP. I've gone ahead and fixed that so that test isn't skipped and made sure DateTimeOffset tests also work. If this is not what you want I can also just skip the DateTimeOffset tests on upackaged UWP. Let me know which direction you want to go.

**Comment by Cheesebaron** [comment]
Looks like the failing pipelines are unrelated to the changes in this PR

**Review by mattleibow — APPROVED** [review]

**Comment by mattleibow** [comment]
Looking good, now to see what is going on with ci and UI tests

**Comment by Cheesebaron** [comment]
Not to be pushy, but any chance this gets in before .NET 9 comes out of preview?

**Pull request merged**
