### PR TITLE
Treat */Auto spans as resolvable finite measures rather than infinite 

### LINKED ISSUE #14537: Feedback: Grid layouts are not working as they did in 7.0.59 (Windows)
### Description

Certain layouts that use Grid are not layouting correctly anymore or are not updating content sizes at all. 

I don't have a simple repro example, maybe I can find one, but this happens on several different places in my app after the update to 7.0.81. I reverted back to 7.0.59

### Steps to Reproduce

---

### Link to public reproduction project repository

xxx

### Version with bug

7.0 (current)

### Last version that worked well

7.0 (current)

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows

### Did you find any workaround?

Simplify the layout, remove Grid

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by hartez**
### Description of Change

When revising the Grid to handle more `*` column/row cases as resolvable from the outset (rather than having to measure them multiple times), combination values of `Auto`/`*` were treated as requiring unconstrained measures (because of the `Auto` component). This causes a couple of problems - for one, it means that Labels spanning `Auto`/`*` column combinations are always measured as if they will be allowed infinite width; this means they will never wrap. For another, we see problems like #14537 where the native Windows layout system only sees unconstrained width measures and assumes that the native control's DesiredSize is correct even when the container's width expands. This results in a situation where expanding the container does not expand the content, even though we request that it lay out at a larger width.

These changes make the cross-platform Grid treat constrained `Auto`/`*` combinations as resolvable (the size the `Auto` value + the size of the `*` value, if any) to a finite size and measure accordingly, rather then treating those values as unconstrained. With tests to that effect.

### Issues Fixed

Fixes #14537

### CODE REVIEW

**Review by Redth — APPROVED** [review]

**Comment by nor0x** [comment]
@Redth  when can we expect another "service release" with this fix? 
it's kind of a severe issues and having to wait weeks for an update after a completed PR is not great!

**Comment by nll** [comment]
@nor0x A new service release was created a few hours ago: https://github.com/dotnet/maui/releases/tag/7.0.86

**Comment by hartez** [comment]
That service release does not have this fix in it.

**Comment by hartez** [comment]
As a workaround (if you don't want to wait for the service release), you can grab the updated Grid code from main and drop it into your app using a custom layout manager: https://github.com/hartez/CustomLayoutExamples#custom-layoutmanagers-for-existing-layouts

**Comment by baaaaif** [comment]
> That service release does not have this fix in it.

@hartez 
SR5 was skipped according to the github release page and SR6 was released directly with the fix

**Comment by nor0x** [comment]
@hartez 
> That service release does not have this fix in it.

it is mentioned in the bug fixes 🤔

**Comment by nll** [comment]
> That service release does not have this fix in it.

The release notes clearly include a reference to the a backport of this pull request here. 

Is "the process" not working again ([#14520](https://github.com/dotnet/maui/issues/14520#issuecomment-1511606572)) ?

Screenshot 2023-05-11 at 09 29 55

**Comment by nor0x** [comment]
i downloaded the assets of the release and indeed the changes from this PR are in there:
image

i'm not 100% sure if this is correct though, since the code from the release is already 2 weeks behind the current state - this whole process is such a mess!
image

and even after my VS and workload updates my app still has a broken layout

**Comment by hartez** [comment]
> That service release does not have this fix in it.

I was wrong about this, I apologize. I must have been looking at the wrong branch, the commit is clearly there.

**Pull request merged**
