### PR TITLE
[net9.0] Bump to RC.1

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change

Bump packages to rc.1, seems there s no sdk build yet

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
For the SDK, I think you might need to use a new package name:
* https://github.com/dotnet/android/pull/9119/commits/21c35f6fdf7abbe78be659d99da74a034b7e2566
* https://github.com/dotnet/android/pull/9119

You might wait and see if this version works for us (or not).

**Comment by rmarinho** [comment]
> For the SDK, I think you might need to use a new package name:
> 
> * [dotnet/android@21c35f6](https://github.com/dotnet/android/commit/21c35f6fdf7abbe78be659d99da74a034b7e2566)
> * [[main] Update dependencies from dotnet/sdk android#9119](https://github.com/dotnet/android/pull/9119)
> 
> You might wait and see if this version works for us (or not).

Thanks I wonder why nobody tells us about these changes :/

**Comment by rmarinho** [comment]
Needs this iOS bump to fix and get merged https://github.com/xamarin/xamarin-macios/pull/20949

**Comment by jonathanpeppers** [comment]
@mcumming @haritha-mohan did you see the latest error on this PR:
```
Workload installation failed: chmod: /Users/builder/azdo/_work/1/s/bin/temp/Microsoft.MacCatalyst.Sdk.net9.0_17.5-17.5.9235-net9-rc1-extracted/tools/bin/xcsync: No such file or directory
```
It might mean that file is missing from the package, but it was listed to be automatically `chmod`ed at install time.

**Comment by mcumming** [comment]
> @mcumming @haritha-mohan did you see the latest error on this PR:
> 
> ```
> 
> Workload installation failed: chmod: /Users/builder/azdo/_work/1/s/bin/temp/Microsoft.MacCatalyst.Sdk.net9.0_17.5-17.5.9235-net9-rc1-extracted/tools/bin/xcsync: No such file or directory
> 
> ```
> 
> It might mean that file is missing from the package, but it was listed to be automatically `chmod`ed at install time.

Yes, we have a or to fix this in the net9.0 branch once it's merged should be good

**Pull request merged**
