### PR TITLE
Update to Preview 7

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change

Update the net7.0 branch to preview 7.

### CODE REVIEW

**Review by Redth — APPROVED** [review]

**Review by TanayParikh — COMMENTED** [review]
Should we update the AspNetCore packages here as well?

https://github.com/dotnet/maui/pull/8884/files#diff-1ea18ff65faa2ae6fed570b83747086d0317f5e4bc325064f6c14319a9c4ff67R30-R37

**Comment by mattleibow** [comment]
I'll set up a PR to bring in that since the on we have is RC 1.

**Comment by mattleibow** [comment]
This is the ASP.NET Core packages: https://github.com/dotnet/maui/pull/8784

**Comment by mattleibow** [comment]
If we haven't merged this PR by the time that one is complete and green, we can merge that in here and di a big boy merge.

**Pull request merged**
