### PR TITLE
Add Essentials Maps TryOpen

### PR DESCRIPTION
**Pull request by jfversluis**
### Description of Change

Port from this Xamarin.Essentials PR here: https://github.com/xamarin/Essentials/pull/1665

Note, this feature will not be merged in Essentials, but it was approved at the time, so I thought it might be a nice addition for .NET MAUI

> - Added Map.TryOpenAsync method for every Map.OpenAsync.
> - I also did some refactoring of this module to remove code duplication.
> - I contemplated that I could also add Map.CanOpenAsync. However, I'm not sure how to implement this on iOS.
> - I came across weird behavior on Android 11. I could run geo intent, however `PackageManager.QueryIntentActivities()` always returned me empty list for some reason. I did some research, and I think that it's necessary to add this intent to AndroidManifest, like all other intents.
`<intent>
    <action android:name="android.intent.action.VIEW" />
    <data android:scheme="geo" />
</intent>`
> - I'm not sure whether I should write some tests for this.

### API Changes ###

Added: 
- `Task<bool> TryOpenAsync(Location location)`
- `Task<bool> TryOpenAsync(Location location, MapLaunchOptions options)`
- `Task<bool> TryOpenAsync(double latitude, double longitude)`
- `Task<bool> TryOpenAsync(double latitude, double longitude, MapLaunchOptions options)`
- `Task<bool> TryOpenAsync(Placemark placemark)`
- `Task<bool> TryOpenAsync(Placemark placemark, MapLaunchOptions options)`

### Issues Fixed

Original Xamarin.Essentials issue: https://github.com/xamarin/Essentials/issues/1289

### CODE REVIEW

**Comment by jfversluis** [comment]
@mattleibow is there a specific reason that not all overloads are surfaced in the `IMap`??

**Comment by jfversluis** [comment]
Do we want to have XML API docs for this? Do we generate that? How does it work?

**Comment by mattleibow** [comment]
> @mattleibow is there a specific reason that not all overloads are surfaced in the `IMap`??

Mostly because a lot are the same api, just different parameters. The overload are echoed via extension methods in the shared code.

**Comment by mattleibow** [comment]
> Do we want to have XML API docs for this? Do we generate that? How does it work?

Not yet for the interfaces. We need to. And the extension methods

**Review by mattleibow — APPROVED** [review]

**Comment by g0dpain** [comment]
does this only check if some map is installed to be opened or should it open maps too?

**Pull request merged**
