### PR TITLE
[Blazor] Fix Win UI deployed app

### LINKED ISSUE #5024: Running installed .NET MAUI Blazor app fails on Windows
### Description

Running an installed .NET MAUI Blazor app on Windows fails with the following error:

Unhandled exception at 0x00000251D0338198 (Microsoft.ui.xaml.dll) in MauiApp7.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x00000251E04ECF80, 0x0000000000000002).

With some help from some folks on the WDX team I confirmed that the error is coming from a E_PATHNOTFOUND in Application.OnLaunched, presumably related to the HostPage of the BlazorWebView.

The installed app under *\Program Files\WindowsApps* does appear to have the correct wwwroot folder and static files.

The app also runs fine in development from VS. It's only after publishing and installing the app that it fails.

### Steps to Reproduce

1. Create a .NET MAUI Blazor project
2. Publish the project for Windows: `msbuild /restore /t:Publish /p:TargetFramework=net6.0-windows10.0.19041 /p:configuration=release /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="<Cert Thumbprint>" /p:PackageCertificatePassword="<Cert Password>"`. See [steps for creating a signing cert](https://docs.microsoft.com/windows/msix/package/create-certificate-package-signing)
3. Run the generated .msix installer to install the app and run it (to install the msix you may need to install the App Installer app from the Microsoft Store).

Expected result: App runs fine
Actual result: App fails to start. Error in the Application event log.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

### Did you find any workaround?

Workarounds: Removing the `HostPage` property from the `BlazorWebView`. The app will then run, but of course the Blazor content won't show up.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by javiercn**
### Description of Change

The APIs we were using were not correct, this change updates the code to use alternative APIs that are better suited for this task.

The image below shows the deployed app after this fix:
image

### Issues Fixed

Fixes #5024

### CODE REVIEW

**Review by SteveSandersonMS — APPROVED** [review]
Great work on tracking this down!

**Comment by mattleibow** [comment]
Is this also working in unpackaged apps?

**Comment by javiercn** [comment]
@mattleibow nope, that's something I discussed yesterday with @Eilon and is something we need to implement.

@mattleibow what are the steps for publishing an unpackaged app? I'm using `msbuild /restore /t:Publish /p:TargetFramework=net6.0-windows10.0.19041 /p:configuration=release /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="<Cert Thumbprint>" /p:PackageCertificatePassword="<Cert Password>"` for the packaged version.

**Comment by mattleibow** [comment]
Check out: https://github.com/dotnet/maui/issues/3166

It is a msbuild prop and change to launchSettings.json

Then normal F5 things.

**Review by TanayParikh — APPROVED** [review]

**Review by mattleibow — APPROVED** [review]

**Review by Eilon — APPROVED** [review]

**Pull request merged**
