### PR TITLE
[iOS] Fix for the CollectionView to prevent duplicate groups or crashes when adding a new item to a group or when adding a new group.

### LINKED ISSUE #17969: CollectionView with grouping show duplicates groups or crash when adding/removing data on iOS and MacCatalyst
### Description

A CollectionView with IsGrouped set to True results in a wrong view rendering with duplicate groups when data is added, usually if not at the top scroll position. It crashes sometimes when data is removed. This happen on iOS and MacCatalyst. It works correctly on Android.

This may be related to issue https://github.com/dotnet/maui/issues/14978

https://github.com/dotnet/maui/assets/3500501/9cf74ebe-0674-47da-8f39-d8ca7921cb12

### Steps to Reproduce

1. Deploy the sample project on iOS Simulator or on Mac.
2. Scroll a bit down the displayed list 
3. Click 'Add' to add items to the list and observe the rendering of duplicate groups.
4. Click 'Clear' to reset the list: the app crash or display empty groups.

### Link to public reproduction project repository

https://github.com/daniel-c/MauiGroupedCollectionTest.git

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 17, macOS 14.0

### Did you find any workaround?

No

### Relevant log output

```shell
ObjCRuntime.ObjCException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Invalid batch updates detected: the number of sections and/or items returned by the data source before and after performing the batch updates are inconsistent with the updates.
Data source before updates = { 1 section with item counts: [1] }
Data source after updates = { 1 section with item counts: [1] }
Updates = [
	Insert item (0 - 0)
]
Collection view: <UICollectionView: 0x138bba800; frame = (0 0; 393 754.333); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x600000c689f0>; backgroundColor = UIExtendedGrayColorSpace 0 0; layer = <CALayer: 0x6000006edf20>; contentOffset: {0, 0}; contentSize: {393, 134}; adjustedContentInset: {0, 0, 0, 0}; layout: <Microsoft_Maui_Controls_Handlers_Items_ListViewLayout: 0x132374fc0>; dataSource: <Microsoft_Maui_Controls_Handlers_Items_ReorderableItemsViewController_1: 0x13235cac0>>
Native stack trace:
	0   CoreFoundation                      0x00007ff80048d28d __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff800057894 objc_exception_throw + 48
	2   Foundation                          0x00007ff800da2c80 _userInfoForFileAndLine + 0
	3   UIKitCore                           0x000000012068c0a7 -[UICollectionView _Bug_Detected_In_Client_Of_UICollectionView_Invalid_Batch_Updates:] + 115
	4   UIKitCore                           0x000000012068b2bc -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:collectionViewAnimator:] + 13332
	5   UIKitCore                           0x0000000120686fec -[UICollectionView _updateRowsAtIndexPaths:updateAction:updates:] + 492
	6   UIKitCore                           0x00000001206870d2 -[UICollectionView insertItemsAtIndexPaths:] + 64
	7   libxamarin-dotnet-debug.dylib       0x000000010e73e0a9 xamarin_dyn_objc_msgSend + 217
	8   libmonosgen-2.0.dylib               0x000000010ee96db1 do_icall + 193
	9   libmonosgen-2.0.dylib               0x000000010ee955d7 do_icall_wrapper + 295
	10  libmonosgen-2.0.dylib               0x000000010ee862f6 mono_interp_exec_method + 3990
	11  libmonosgen-2.0.dylib               0x000000010ee83a63 interp_runtime_invoke + 259
	12  libmonosgen-2.0.dylib               0x000000010ef6aaed mono_runtime_try_invoke + 157
	13  libmonosgen-2.0.dylib               0x000000010ef6deae mono_runtime_invoke + 478
	14  TestCollectionView                  0x000000010ce571a5 _ZL31native_to_managed_trampoline_10P11objc_objectP13objc_selectorPP11_MonoMethodS0_j + 469
	15  TestCollectionView                  0x000000010cec19f2 -[UIKit_UIBarButtonItem_Callback InvokeAction:] + 50
	16  UIKitCore                           0x00000001212514c6 -[UIApplication sendAction:to:from:forEvent:] + 95
	17  UIKitCore                           0x00000001204682d9 -[UIBarButtonItem _triggerActionForEvent:fallbackSender:] + 267
	18  UIKitCore                           0x00000001204381bb __45-[_UIButtonBarTargetAction _invoke:forEvent:]_block_invoke + 39
	19  UIKitCore                           0x0000000120438068 -[_UIButtonBarTargetAction _invoke:forEvent:] + 152
	20  UIKitCore                           0x00000001212514c6 -[UIApplication sendAction:to:from:forEvent:] + 95
	21  UIKitCore                           0x00000001208e92f3 -[UIControl sendAction:to:forEvent:] + 112
	22  UIKitCore                           0x00000001208e96e8 -[UIControl _sendActionsForEvents:withEvent:] + 334
	23  UIKitCore                           0x00000001208e9744 -[UIControl _sendActionsForEvents:withEvent:] + 426
	24  UIKitCore                           0x00000001208e7f79 -[UIControl touchesEnded:withEvent:] + 485
	25  UIKitCore                           0x0000000121294ae8 -[UIWindow _sendTouchesForEvent:] + 1261
	26  UIKitCore                           0x0000000121296c54 -[UIWindow sendEvent:] + 5284
	27  UIKitCore                           0x000000012126be6c -[UIApplication sendEvent:] + 772
	28  UIKitCore                           0x0000000121318b99 __dispatchPreprocessedEventFromEventQueue + 8406
	29  UIKitCore                           0x000000012131b455 __processEventQueue + 8414
	30  UIKitCore                           0x00000001213118d6 __eventFetcherSourceCallback + 163
	31  CoreFoundation                      0x00007ff8003e9d0f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	32  CoreFoundation                      0x00007ff8003e9c51 __CFRunLoopDoSource0 + 157
	33  CoreFoundation                      0x00007ff8003e944e __CFRunLoopDoSources0 + 215
	34  CoreFoundation                      0x00007ff8003e3b83 __CFRunLoopRun + 919
	35  CoreFoundation                      0x00007ff8003e3409 CFRunLoopRunSpecific + 557
	36  GraphicsServices                    0x00007ff80a650187 GSEventRunModal + 137
	37  UIKitCore                           0x000000012124b3a2 -[UIApplication _run] + 972
	38  UIKitCore                           0x000000012124fe10 UIApplicationMain + 123
	39  libxamarin-dotnet-debug.dylib       0x000000010e6f847a xamarin_UIApplicationMain + 58
	40  libmonosgen-2.0.dylib               0x000000010ee96e45 do_icall + 341
	41  libmonosgen-2.0.dylib               0x000000010ee955d7 do_icall_wrapper + 295
	42  libmonosgen-2.0.dylib               0x000000010ee862f6 mono_interp_exec_method + 3990
	43  libmonosgen-2.0.dylib               0x000000010ee83a63 interp_runtime_invoke + 259
	44  libmonosgen-2.0.dylib               0x000000010ef69b68 mono_runtime_invoke_checked + 136
	45  libmonosgen-2.0.dylib               0x000000010ef7133b mono_runtime_exec_main_checked + 107
	46  libmonosgen-2.0.dylib               0x000000010edd61d2 mono_jit_exec + 354
	47  libxamarin-dotnet-debug.dylib       0x000000010e73cbca xamarin_main + 1898
	48  TestCollectionView                  0x000000010ceea694 main + 68
	49  dyld                                0x000000010d7023ee start_sim + 10
	50  ???                                 0x00000001189493a6 0x0 + 4707357606

Native stack trace:
	0   CoreFoundation                      0x00007ff80048d28d __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff800057894 objc_exception_throw + 48
	2   Foundation                          0x00007ff800da2c80 _userInfoForFileAndLine + 0
	3   UIKitCore                           0x000000012068c0a7 -[UICollectionView _Bug_Detected_In_Client_Of_UICollectionView_Invalid_Batch_Updates:] + 115
	4   UIKitCore                           0x000000012068b2bc -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:collectionViewAnimator:] + 13332
	5   UIKitCore                           0x0000000120686fec -[UICollectionView _updateRowsAtIndexPaths:updateAction:updates:] + 492
	6   UIKitCore                           0x00000001206870d2 -[UICollectionView insertItemsAtIndexPaths:] + 64
	7   libxamarin-dotnet-debug.dylib       0x000000010e73e0a9 xamarin_dyn_objc_msgSend + 217
	8   libmonosgen-2.0.dylib               0x000000010ee96db1 do_icall + 193
	9   libmonosgen-2.0.dylib               0x000000010ee955d7 do_icall_wrapper + 295
	10  libmonosgen-2.0.dylib               0x000000010ee862f6 mono_interp_exec_method + 3990
	11  libmonosgen-2.0.dylib               0x000000010ee83a63 interp_runtime_invoke + 259
	12  libmonosgen-2.0.dylib               0x000000010ef6aaed mono_runtime_try_invoke + 157
	13  libmonosgen-2.0.dylib               0x000000010ef6deae mono_runtime_invoke + 478
	14  TestCollectionView                  0x000000010ce571a5 _ZL31native_to_managed_trampoline_10P11objc_objectP13objc_selectorPP11_MonoMethodS0_j + 469
	15  TestCollectionView                  0x000000010cec19f2 -[UIKit_UIBarButtonItem_Callback InvokeAction:] + 50
	16  UIKitCore                           0x00000001212514c6 -[UIApplication sendAction:to:from:forEvent:] + 95
	17  UIKitCore                           0x00000001204682d9 -[UIBarButtonItem _triggerActionForEvent:fallbackSender:] + 267
	18  UIKitCore                           0x00000001204381bb __45-[_UIButtonBarTargetAction _invoke:forEvent:]_block_invoke + 39
	19  UIKitCore                           0x0000000120438068 -[_UIButtonBarTargetAction _invoke:forEvent:] + 152
	20  UIKitCore                           0x00000001212514c6 -[UIApplication sendAction:to:from:forEvent:] + 95
	21  UIKitCore                           0x00000001208e92f3 -[UIControl sendAction:to:forEvent:] + 112
	22  UIKitCore                           0x00000001208e96e8 -[UIControl _sendActionsForEvents:withEvent:] + 334
	23  UIKitCore                           0x00000001208e9744 -[UIControl _sendActionsForEvents:withEvent:] + 426
	24  UIKitCore                           0x00000001208e7f79 -[UIControl touchesEnded:withEvent:] + 485
	25  UIKitCore                           0x0000000121294ae8 -[UIWindow _sendTouchesForEvent:] + 1261
	26  UIKitCore                           0x0000000121296c54 -[UIWindow sendEvent:] + 5284
	27  UIKitCore                           0x000000012126be6c -[UIApplication sendEvent:] + 772
	28  UIKitCore                           0x0000000121318b99 __dispatchPreprocessedEventFromEventQueue + 8406
	29  UIKitCore                           0x000000012131b455 __processEventQueue + 8414
	30  UIKitCore                           0x00000001213118d6 __eventFetcherSourceCallback + 163
	31  CoreFoundation                      0x00007ff8003e9d0f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	32  CoreFoundation                      0x00007ff8003e9c51 __CFRunLoopDoSource0 + 157
	33  CoreFoundation                      0x00007ff8003e944e __CFRunLoopDoSources0 + 215
	34  CoreFoundation                      0x00007ff8003e3b83 __CFRunLoopRun + 919
	35  CoreFoundation                      0x00007ff8003e3409 CFRunLoopRunSpecific + 557
	36  GraphicsServices                    0x00007ff80a650187 GSEventRunModal + 137
	37  UIKitCore                           0x000000012124b3a2 -[UIApplication _run] + 972
	38  UIKitCore                           0x000000012124fe10 UIApplicationMain + 123
	39  libxamarin-dotnet-debug.dylib       0x000000010e6f847a xamarin_UIApplicationMain + 58
	40  libmonosgen-2.0.dylib               0x000000010ee96e45 do_icall + 341
	41  libmonosgen-2.0.dylib               0x000000010ee955d7 do_icall_wrapper + 295
	42  libmonosgen-2.0.dylib               0x000000010ee862f6 mono_interp_exec_method + 3990
	43  libmonosgen-2.0.dylib               0x000000010ee83a63 interp_runtime_invoke + 259
	44  libmonosgen-2.0.dylib               0x000000010ef69b68 mono_runtime_invoke_checked + 136
	45  libmonosgen-2.0.dylib               0x000000010ef7133b mono_runtime_exec_main_checked + 107
	46  libmonosgen-2.0.dylib               0x000000010edd61d2 mono_jit_exec + 354
	47  libxamarin-dotnet-debug.dylib       0x000000010e73cbca xamarin_main + 1898
	48  TestCollectionView                  0x000000010ceea694 main + 68
	49  dyld                                0x000000010d7023ee start_sim + 10
	50  ???                                 0x00000001189493a6 0x0 + 4707357606
```

### LINKED ISSUE #20336: Grouped CollectionView content/items overlaps on iOS when data changes or when pull to refresh data
### Description

On iOS when CollectionView is used to display grouped data, the content items displayed in the CollectionView overlaps. For the first time it calculates the size correctly and shows everything as expected, but if sometimes, the list data changes or I pull to refresh new data (using RefreshView), the collection content is overlapping and looks so ugly.

### Steps to Reproduce

1. Create a new MAUI app project using usual VS for Mac

2. Create ObservableCollection for grouped data:

3. [ObservableProperty]
 ObservableCollection<IGrouping<DateTime?, Items>> groupedItems;
 
4. Populate the data from API or your data model
 
5. Design your layout to include CollectionView with DataTemplateSelector:
 
  ```
<ResourceDictionary>
  <templateSelector:ItemDataTemplateSelector x:Key="itemDataTemplateSelector"
                                          TemplateOne ="{StaticResource DataTemplateOne}"
                                          TemplateTwo ="{StaticResource DataTemplateTwo}"
                                         TemplateThree ="{StaticResource DataTemplateThree}"
                                          TemplateFour ="{StaticResource DataTemplateFour}"
                                          TemplateFive ="{StaticResource DataTemplateFive}"/>

        </ResourceDictionary>
        
        
        <RefreshView Grid.Row="0"  VerticalOptions="FillAndExpand" IsRefreshing="{Binding IsRefreshing}"
                     RefreshColor="{StaticResource Primary}"
                     Command="{Binding RefreshCommand}">
        <CollectionView TranslationY="-23"
            VerticalScrollBarVisibility="Always" ItemTemplate="{StaticResource itemDataTemplateSelector}"
            ItemsSource="{Binding GroupedItems}"  VerticalOptions="FillAndExpand"
            IsGrouped="True" ItemsUpdatingScrollMode="KeepLastItemInView">
            <CollectionView.ItemsLayout>
                <GridItemsLayout VerticalItemSpacing="5"
                    Orientation="Vertical" />
            </CollectionView.ItemsLayout>
            <CollectionView.GroupHeaderTemplate>
                <DataTemplate>
                    <Label Style="{StaticResource HeadingTextStyle}"
                        Padding="30,10,30,0" 
                        Text="{Binding Key, StringFormat='{0: dddd, MMMM dd}'}"
                        VerticalTextAlignment="Center" 
                         />
                </DataTemplate>
            </CollectionView.GroupHeaderTemplate>
            </CollectionView>
            </RefreshView>
```

6. Run in iOS simulator, it will look good the very first time and then if you pull to refresh the data, observe the bad overlapping.

7. Data is dynamic, it will sometimes overlap if the data is changed during runtime and some of the data templates are now not available as per the data

8. I cannot use ItemSizingStrategy="MeasureFirstItem" because, my design list design requires different data templates, which are of complete different sizes, so there is no chance I can use MeasureFirstItem ItemSizingStrategy.

Due to this, the UI for the very first screen of my app looks so bad that it's not possible to release or at least demo it to client.

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17+

### Did you find any workaround?

Couldn't find any workaround yet.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Tamilarasan-Paranthaman**
#### 1. Add item in the group:
- Dequeuing a supplementary view for measurement caused multiple instances of the header and footer to appear in the view. 
#### 2. Adding new group:
- We checked if `_collectionView.NumberOfSections() == 0` to determine whether a reload was required, in conjunction with the `NotLoadedYet()` condition. 
- However, using `_collectionView.NumberOfSections()` caused a crash when the collection view was empty and a new group was added, as `NumberOfSections() == 0` is always true for an empty collection. This check prevented the adding a new group.

#### 1. Add item in the group:
- We removed the version check and dequeuing logic to prevent the issue of duplicate header/footer templates.
- Now, we always use MeasureSupplementaryView, which calculates the size without dequeuing the view, ensuring that the supplementary is only rendered when necessary.
 
#### 2. Adding new group:
- Modified the condition to check only if the collection view has not yet been loaded using the NotLoadedYet() method.
- By removing the section check and focusing solely on whether the collection view has been loaded, we ensure that the data reloads properly in both empty and populated states.  

**Validated the behaviour in the following platforms,**
 
- [ ] Android
- [ ] Windows
- [x] iOS
- [x] Mac

### Issues Fixed

Fixes #17969
Fixes #20336

#### After Issue Fix 

https://github.com/user-attachments/assets/7c07f47b-9d76-40f4-a2a3-53e84604f336

### CODE REVIEW

**Review by rmarinho — COMMENTED** [review]
I think this shifts the problem a little bit, if the REloadRequired is still called it will crash. Should we instead of checking the NumberofSections of the CollectionView can we try look at the ItemsSource Count ?

**Review by PureWeen — CHANGES_REQUESTED** [review]
https://github.com/dotnet/maui/pull/24873#pullrequestreview-2325818906

**Comment by Tamilarasan-Paranthaman** [comment]
> I think this shifts the problem a little bit, if the REloadRequired is still called it will crash. Should we instead of checking the NumberofSections of the CollectionView can we try look at the ItemsSource Count ?

@rmarinho / @PureWeen, currently, `ReloadRequired` is only called when removing a group in the [Remove ](https://github.com/dotnet/maui/pull/24873/files#diff-356239a714d4dc463c1cb61eb7b29159f2a3585df197943212a9ac551316ceffL236)method. In the case of group removal, it make sense to check if there are any groups available to remove. However, this check is unnecessary when adding a group. Additionally, this check alone was not the cause of the crash. The actual issue occurred when a data reload was triggered inside the `if` condition, leading to the crash.

To explain in more detail: when the `ReloadRequired` condition is true, the code enters the `if` block and calls `ReloadData` and `ResetGroupTracking` on the CollectionView. This is what caused the crash.

This issue specifically arises when clearing the ItemsSource and immediately adding a group, as reported by the customer. However, the crash does not occur if these actions are performed individually.

It seems that during a reset, we call Reload(true), which internally invokes _collectionView.LayoutIfNeeded() based on the boolean parameter. Similarly, an additional layout call may be required when adding a group immediately after clearing. The issue is resolved if we call _collectionView.LayoutIfNeeded, which can be achieved by using Reload(true) in the group-adding case as well.

However, it seems that the [InsertSections](https://github.com/dotnet/maui/pull/24873/files#diff-356239a714d4dc463c1cb61eb7b29159f2a3585df197943212a9ac551316ceffL221) method of the CollectionView handles this. Therefore, I believe checking the NumberOfSections (which will be 0) is unnecessary in this scenario. I have resolved the issue by removing the `ReloadRequired` check.

Could you please share your thoughts on this approach?

**Review by rmarinho — APPROVED** [review]
Thanks for the clarification, this solution looks good and addresses the root cause of the crash effectively. The explanation clearly outlines how the issue occurs, and removing the unnecessary ReloadRequired check when adding a group seems like a smart optimization.
This PR is good to go, and I approve it. Excellent work in identifying the underlying cause and providing a clear solution!

**Comment by FlavioGoncalves-Cayas** [comment]
@Tamilarasan-Paranthaman 
Thanks for this PR. This looks very promising. I tested this with my reproduction for #17969 and the issue seems to be fixed.

**Pull request merged**
