### PR TITLE
Invert SourceRect width/height on orientation change for ActionSheet

### LINKED ISSUE #26560: iPad - ActionSheet does not stay in the centre of the screen on orientation change
### Description

If an iPad is rotated while an action sheet is being displayed, the action sheet will move off centre:

Image

### Steps to Reproduce

1. Open the repro app
2. Tap the button to open the action sheet
3. Rotate the device
4. Observe the action sheet now being off centre

### Link to public reproduction project repository

https://github.com/eth-ellis/Issue-Repro/tree/main/ActionSheetOrientationChange

### Version with bug

9.0.14 SR1.4

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by eth-ellis**
### Description of Change

Invert SourceRect width/height on orientation change for ActionSheet to ensure it says centred.

### Issues Fixed

Fixes #26560

| Before | After |
| -------- | ------- |
|Simulator Screen Recording - iPad Pro 11-inch (M4) - 2024-12-12 at 18 14 02|Simulator Screen Recording - iPad Pro 11-inch (M4) - 2024-12-12 at 18 05 41|

### CODE REVIEW

**Review by jfversluis — APPROVED** [review]

**Comment by jfversluis** [comment]
Thinking of how we could add a test for this, I guess a snapshot test would be easiest

**Comment by eth-ellis** [comment]
@jfversluis Is there documentation on where/how to add a snapshot test for this?

**Comment by jfversluis** [comment]
Please don't merge main into this unless you really have to. That will reset the build status and I will need to trigger it again and a whole new run will begin. Thanks!

As for the testing docs, this should be helpful: https://github.com/dotnet/maui/blob/main/docs/design/UITesting.md#screenshots

**Comment by eth-ellis** [comment]
@jfversluis Yep, realised that as soon as I did it. Need to resist the urge to always be 100% up to date with main 😆

Cheers, that doco outlines the process very clearly!

Is there a way to run this test on an iPad though as this is an iPad specific issue?
From what I can tell, all of the snapshots appear to be from an iPhone.

**Comment by jfversluis** [comment]
Ah yeah that's a good call. They all run on iPhones only right now. OK I'll have a closer look, don't worry about the test for now.

**Comment by jfversluis** [comment]
Thanks for reporting and fixing the bug yourself! Much appreciated!

**Pull request merged**
