### PR TITLE
Fixed low quality images in Resizetizer

### LINKED ISSUE #23212: [Windows] [.NET 9.0 Preview 5] App icon in the taskbar is pixelated
### Description

This is a .NET MAUI App using .NET MAUI 9.0 Preview 5 and .NET SDK 9.0 Preview 5. This bug pertains to the Windows platform (WinUI 3).

#### The Problem
Our app logo is pixelated in the task bar, when I start it in the Debug mode.

I have two screens. One at 100% scaling and the other at 200% scaling. The 100% screen shows it like this:

pixelated1

The 200% screen shows it like this:

pixelated2

The original image is this:

appicon

Resizetizer seems to work OK, and all image sizes are created in `obj\Debug\net9.0-windows10.0.19041.0\win10-x64\resizetizer\r`.

### Steps to Reproduce

1. Build GnollHack for MAUI Windows using these instructions:
https://github.com/hyvanmielenpelit/GnollHack/wiki/Development-Information

2. Start the Game in Debug mode.

### Link to public reproduction project repository

https://github.com/hyvanmielenpelit/GnollHack

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

_No response_

### Did you find any workaround?

Not yet.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by TommiGustafsson-HMP**
### Description of Change

Added `FilterQuality = SKFilterQuality.High` to Paint in SkiaSharpTools. This fixes low quality images produced by Resizetizer.

### Issues Fixed

[Windows] [.NET 9.0 Preview 5] App icon in the taskbar is pixelated (#23212).

Fixes #23212.

### CODE REVIEW

**Review by mattleibow — DISMISSED** [review]

**Comment by mattleibow** [comment]
Thanks for this PR! This is probably going to make a whole lot of images better that folks didn't even notice was poor quality.

**Review by rmarinho — CHANGES_REQUESTED** [review]
Tests are failing https://dev.azure.com/xamarin/public/_build/results?buildId=120966&view=ms.vss-test-web.build-test-results-tab&runId=3008137&resultId=100048&paneView=debug

**Comment by TommiGustafsson-HMP** [comment]
Are the failing tests comparing some pre-rendered images? Because I added the High Quality filter, the resulting images can be different than before.

**Comment by mattleibow** [comment]
I regenerated all the images, so let's see. Also, we can see the results of this.

**Comment by TommiGustafsson-HMP** [comment]
@dotnet-policy-service agree [company="Hyvän mielen pelit ry"]

**Comment by TommiGustafsson-HMP** [comment]
@dotnet-policy-service agree company="Hyvän mielen pelit ry"

**Comment by mattleibow** [comment]
The `CollectionScrollToGroupWorks` test is new and failing on main. Unrelated to this PR.

**Review by mattleibow — APPROVED** [review]

**Comment by KeithBoynton** [comment]
How do I work out which release this will be included in?

**Comment by KeithBoynton** [comment]
Thanks very much @MartyIX is there somewhere I can track that please?

**Pull request merged**
