### PR TITLE
Template Tweaks for P4

### PR DESCRIPTION
**Pull request by Redth**
Adding a few more tweaks to the templates...

### CODE REVIEW

**Comment by Eilon** [comment]
Since you're already in here, can you take a look at https://github.com/dotnet/maui/issues/1060 and include a fix in here?

**Comment by Redth** [comment]
@Eilon yep, fixed the typo... I'm more surprised it didn't cause problems with the typo.

**Comment by Eilon** [comment]
Yeah it's kind of odd, which made me wonder if it's even needed? Obviously with the typo it's just ignored anyway...

**Comment by Redth** [comment]
I think it has more impact in some of the xamlc/xamlg steps, there's impact here I believe in it not being there (and correct), so I'd like to keep it.

**Review by Eilon — APPROVED** [review]

**Pull request merged**
