### PR TITLE
Build Debug and Release device tests

### LINKED ISSUE #14390: Create Release test runs for Device Tests
### Description

_Originally posted by @rmarinho in https://github.com/dotnet/maui/issues/14301#issuecomment-1493156990_
            

Right now we have no way to verify anything in Release builds. This would have caught a few issues that we only discovered later on.

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change

Current state:

 * Android: Debug
 * iOS: Release

This PR:

 Everything is _both_ Debug and Release

### Issues Fixed

Fixes #14390

### CODE REVIEW

**Comment by rmarinho** [comment]
Seems @mandel-macaque wants to make this consume the nupkg created here, and we already build them in debug/release

**Comment by rmarinho** [comment]
seems some failures on release mode for Android, soem related with leak tests, any ideas @jonathanpeppers  @PureWeen  ?

**Comment by jonathanpeppers** [comment]
The memory leak tests are passing for me locally on device & emulator, but I found this issue: https://github.com/dotnet/maui/pull/14492

Let me try it a few more times.

**Comment by jonathanpeppers** [comment]
Ok, if I restart the app and Run All, it took two tries to get:

image

**Comment by jonathanpeppers** [comment]
I pushed a change that seems like it made these tests pass 3 times in a row in Release mode. Let's see how it does on CI?

**Comment by rmarinho** [comment]
Ok these look real failures on Android in release, IsInAccessibleTree

https://dev.azure.com/xamarin/public/_build/results?buildId=84050&view=ms.vss-test-web.build-test-results-tab

**Comment by rmarinho** [comment]
Seems we still have 2 failing tests on android/ release

IsInAccessibleTree and ExcludedWithChildren

**Pull request closed without merging**
