### PR TITLE
Update templates for non-VS IDE hosts

### LINKED ISSUE #22381: Blazor Hybrid + Web solution template missing project refs in .sln when created via VS Code
### Description

Trying out the new .NET Blazor Hybrid and Web App template in VS Code (with C# Dev Kit and MAUI extension installed), the .SLN file isn't generated properly so the solution never opens in the Solution Explorer. This happens on Windows and Mac. 

### Steps to Reproduce

C# Dev Kit v1.5.20
.NET MAUI extension v0.11.87 
Microsoft.Maui.Templates.net8.8.0.100-dev.nupkg installed
Windows or Mac

- Create a new .NET project in VS Code (Windows or Mac) via the command pallet and select the new .NET MAUI Blazor and Web App template. 

VSCodeCreate

- Notice that it doesn't open the project in VS Code
- Open the folder and the projects are created but the .SLN is missing the project references. 

```code
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.0.31903.59
MinimumVisualStudioVersion = 10.0.40219.1
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
EndGlobal
```

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, macOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by smitpatel**
### Description of Change

List csproj files in primaryOutputs for maui blazor solution template

### Issues Fixed

Fixes #22381

net9.0. I didn't find this template in main branch.

### CODE REVIEW

**Review by jfversluis — DISMISSED** [review]

**Comment by jfversluis** [comment]
Looking at the rest of the templates I do see that not opening a file on VS was intentional (see #12756), do we show a Getting Started page for this template?

@Eilon @jknaudt21

**Comment by smitpatel** [comment]
@jfversluis - Updated PR to remove those changes. File opening post action has no impact on the original issue. So it can be updated (or not) separately.

**Review by Eilon — APPROVED** [review]
Wow nice! So it was a template authoring error all along. My bad!

And hi, Smit 😁

**Review by jfversluis — APPROVED** [review]

**Comment by jknaudt21** [comment]
> Do we show a Getting Started page for this template?

@jfversluis  for VS we show the Overview Page on all projects that have the `MauiSingleProject` capability and **_not_** `MauiBlazor`.

Since this is in the maui-blazor folder, my assumption is that we don't show it here.

**Review by jknaudt21 — APPROVED** [review]

**Comment by jfversluis** [comment]
Thanks @jknaudt21 lets merge this first and I'll double check and make that other change if needed

**Comment by jfversluis** [comment]
Actually it shows the Getting Started for ASP.NET it seems, probably because it picks up on the web project so thats fine

image

**Pull request merged**
