### PR TITLE
Mark all the Device [Obsolete]

### LINKED ISSUE #4549: Obsolete `Device` in Controls
All the APIs in `Device` are either found on `Application`, `Window` or in Essentials.

This API is now basically just for compatibility.

Actually part of #1965, but that diff got huge with all the usages and code changes/warnings. This needs to be a separate PR.

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change

Fixes #4549

Mark `Device` and related obsolete in preparation of a better system:

 - `Device`  
   This is the containing class, and everything it had is now obsolete. Ready for removal in .NET 7!
 - `GetNamedSize`, `NamedSize` and `IFontNamedSizeService`  
   This used to be the only way to get scaled font sizes, but now it is built into Font. If we want to actually expose those values to the user, we can maybe use a "stringly-typed enum" to allow for supporting the other values on the system. We only had `Title1`, but there is also a `Title2` and `Title3`.
 - `Device.Styles` and `ISystemResourcesProvider` ("Device Styles" eg: `{DynamicResource TitleStyle}`)  
   This is the way to get the OS font styles. This may be more popular than I think, but I am just pre-emptively removing it for now.

In both cases (named sizes and device styles), I may be missing the real uses here, so this PR is to show what is going and can start a conversation.

If anything, some things need to be tweaked and not exist only in the `Device` class. 

### Named Sizes

> NOTE: these values appear to be magical and do things, but at XAML parse time, they are translated into a double with no idea that they were special values. Thus, they never did respond to OS changes. Once set, they are just a number and nothing special

For named sizes, we could have `Font` be smarter and actually have the stringly-typed value as a field. For example:

```cs
class Font {
    double Size;
    string NamedSize;
    string Family;
}
```

Then the font manager can do a check like this:

```cs
double realSize;
if (font.NamedSize != null) {
    realSize = GetSizeFromName(font.NamedSize);
} else {
    realSize = font.Size * scalingFactor;
}
```

### Device Styles

And then for the device styles, this can maybe just move to an application level service... Or maybe a Window-service as each window may have different rules? These values may actually change in dark/light modes, so we need to confirm they work. And also verify that accessibility is in place. Some platforms don't seem to have that last part hooked up...

### CODE REVIEW

**Comment by StephaneDelcroix** [comment]
what's the implication for the FontTypeExtension ?

**Comment by mattleibow** [comment]
> what's the implication for the FontTypeExtension ?

You mean `FontTypeConverter`? Right now it is just obsolete, but basically this PR is saying "Medium", "Small" and "Micro" (and the others) are obsolete and you should use real numbers.

And this is where I need to call upon the people people to say they actually use this feature and I need to find a way to keep this. The issue is: what is "Micro"? The size is per-platform and yet also fixed in most cases. Theoretically it should change when the OS changes things, but I think that broke people, so it went to a hard coded value. Now on iOS it is 12, Android 10 and Windows 15.667. Yay! A wide range of sizes and totally useless because on Android Medium is 14... so visually smaller than Windows' Micro.

Are these values used? Maybe because some of the sizes are loaded from resources on some of the platforms, people are actually doing:

```xaml
<Label FontSIze="{OnPlatform Android=Medium, iOS=Body, WinUI=14}" />
```

Or whatever. That is just plain scary and everything is so much easier to use a `14` and it is the same for each platform.

**Review by Redth — APPROVED** [review]

**Review by jfversluis — APPROVED** [review]

**Comment by MagicAndre1981** [comment]
How do I replace this XF code in MAUI?

`FontSize = Device.GetNamedSize (NamedSize.Large, typeof(Label)),`

I get the obsolete warning but with no API suggestion what I should use now in MAUI

**Comment by Kapusch** [comment]
Hi @MagicAndre1981 , as per this [comment from Gerald](https://github.com/dotnet/maui/issues/8798#issuecomment-1213001071):

> NamedSize should not be used nor needed anymore. All the fontsizes now automatically scale as per the OS settings. This improves accessibility overall.

**Pull request merged**
