### PR TITLE
Build projects in parallel

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change ###

This will probably help for the slow windows builds.

### Additions made ###

- adds `-m` to msbuild args

### CODE REVIEW

**Comment by Eilon** [comment]
I vaguely recall that there could sometimes be issues with adding parallelism to the build due to various concurrency bugs in the multitude of various components involved in building a million lines of code. Having said that, I still think this is the right thing to do, assuming it actually works in the .NET MAUI build. I recommend trying to build, rebuild, clean, and repeat again like a hundred times overnight on a machine and checking if any builds failed (save all the binlogs somewhere), to know if it's reasonably reliable.

**Review by Eilon — APPROVED** [review]

**Comment by mattleibow** [comment]
> trying to build, rebuild, clean, and repeat again like a hundred times overnight

I call that "CI" 🤣  We are bound to pick up something here.

**Comment by mattleibow** [comment]
Maybe a fluke, but this seems to take off about 2-5 mins. So a mini win here I suppose.

**Comment by Eilon** [comment]
> I call that "CI" 🤣 We are bound to pick up something here.

Fair enough 😄 So I guess what I said boils down to: Keep an eye out for suspicious CI failures because if this does introduce flakiness, that's bad. Folks need to be on the lookout so we're not dealing with even more flakiness. If that does end up being the case on CI, then we could conditionally disable parallel on CI, and keep it for local dev.

**Comment by mattleibow** [comment]
Well, I would argue that any flakey CI means that either we need to fix our targets or ASP.NET needs to fix blazor targets. Parallel builds are the default in the IDE and I also don't want slow down builds because of bugs.

I get what you mean with regards to MAUI velocity, but then we better file a bug and mark it as P0.

**Pull request merged**
