### PR TITLE
[Android] Fix incorrect CornerRadius in RoundRectangle

### LINKED ISSUE #5820: Border rendered incorrectly and shadow not working on Android
### Description

Borders aren't rendered correctly on Android. The Border is too thin in straight lines, but too thick in rounded corners. Shadows aren't rendered at all. They look perfectly fine on Windows.

Windows:
image

Android:
signal-2022-04-05-085412_001

### Steps to Reproduce

Here the XAML for the page in the screenshots. It's basically the Border example from the Documentation with an added Shadow without properties.

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp6.MainPage"
             BackgroundColor="White">
    <Border 
        VerticalOptions="Center"
        HorizontalOptions="Center"
        Stroke="#C49B33"
        StrokeThickness="4"
        Background="#2B0B98"
        Padding="16,8">
      <Border.StrokeShape>
        <RoundRectangle CornerRadius="40,0,0,40" />
      </Border.StrokeShape>
      <Border.Shadow>
        <Shadow />
      </Border.Shadow>
      <Label Text=".NET MAUI"
           TextColor="White"
           FontSize="18"
           FontAttributes="Bold" />
    </Border>
</ContentPage>
```

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 7, Android 12

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #6981: Inconsistent RoundRectangle CornerRadius Border.ClipShape between Android and iOS
### Description

Using a `RoundRectangle` in a `ClipShape` of a `Border` yields different radiuses between Android and iOS.

Ignoring the border rendering on Android, which is a known issue (#5820), the inner radius on Android is much smaller than the on on iOS.

Link to reproduction repo: [https://github.com/paulvarache/MauiIssueBorderRadius](https://github.com/paulvarache/MauiIssueBorderRadius)

Result on Android:
 

Result on iOS:

### Steps to Reproduce

1. Create a new Maui App
2. Add a Border with a ClipShape containing a RoundRectangle with a CornerRadius e.g. 

```xaml
<Border HeightRequest="64" WidthRequest="320" Stroke="Red" StrokeThickness="4" Background="Blue">
    <Border.StrokeShape>
        <RoundRectangle CornerRadius="16" />
    </Border.StrokeShape>
</Border>
```

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15, Android 11.0

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

 Fix incorrect CornerRadius in Android `RoundRectangle`.

fix-6981

### Issues Fixed

Fixes #6981 
Fixes #5820

### CODE REVIEW

**Review by mattleibow — DISMISSED** [review]
~I think there is a Context extension method for this `ToPixels`~

I see this is in the xplat world.

**Comment by mattleibow** [comment]
Actually... On Android everything needs to be multiplied by the density - like stroke and size... Why is it that only the radius needs this? What happens if we set a stroke of 2 and the density is 3? Is the stroke thickness scaled elsewhere? And the size? Is this view using raw pixels on Android and scaled pixels on other platforms?

**Review by mattleibow — CHANGES_REQUESTED** [review]
@jsuarezruiz was going to see if this was fixable in maui graphics.

**Comment by mattleibow** [comment]
I want to verify that this did not break other things that use path... Seems sus with my testing with just graphics that everything scales. So it may just be clip/border things...

**Comment by mattleibow** [comment]
Yeah, radius is used differently in different places...

image

**Comment by mattleibow** [comment]
So as you may notice, it is fixed! Yay! I could not understand why it did not affect anything else and then discovered that we are doing this all backwards. On all the platforms, we pass scaled pixels to the shapes, yet on Android we pass raw pixels. This means that all the shapes are wrong and we only notice with rounded rectangle.

I will fix this in a new PR and we can decide which is better/safer for now.

**Comment by mattleibow** [comment]
I think the more correct fix is to not have any special code in the cross-platform layer: #7016

Not sure why we went the dodgy way at the start... Shame! shame! shame!

**Comment by jsuarezruiz** [comment]
I close this PR in favor of https://github.com/dotnet/maui/pull/7016

**Pull request closed without merging**
