### PR TITLE
[ci] Add xharness dependency via maestro

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change

Helps get updated versions of xharness

### Issues Fixed

maybe some xcode 13.3 issues

### CODE REVIEW

**Comment by premun** [comment]
There's also this one: https://github.com/dotnet/maui/blob/553b69bc5c5dea29f95a72ae331a6fd526df6ffb/src/TestUtils/src/DeviceTests.Runners/TestUtils.DeviceTests.Runners.csproj#L22

**Comment by premun** [comment]
Also technically, this is still some November version of XHarness so not sure the description is accurate

**Review by premun — APPROVED** [review]

**Comment by rmarinho** [comment]
yeah i didnt update the version right now, just to make sure this works, then a maestro pr with the bump of version

**Comment by premun** [comment]
Or you can also now run the `update-dependencies` command locally and push it here too

**Pull request merged**
