### PR TITLE
Fix design time image converter

### PR DESCRIPTION
**Pull request by etvorun**
Fix design time image converter

Based on the work in https://github.com/dotnet/maui/pull/19301

### CODE REVIEW

**Review by jsuarezruiz — COMMENTED** [review]
The test ImageSourceDesignTypeConverter_Invalid is failing with empty value:
image

**Review by StephaneDelcroix — APPROVED** [review]
works for me if it works for you @etvorun

**Comment by etvorun** [comment]
@jsuarezruiz, @PureWeen  any clue about remaining test failures in this PR? What else I need to do to complete it?

**Review by mattleibow — APPROVED** [review]

**Pull request merged**
