### PR TITLE
Add missing android font weight

### PR DESCRIPTION
**Pull request by AlleSchonWeg**
### Description of Change

Add missing Android Systemfont

### CODE REVIEW

**Review by mattleibow — APPROVED** [review]

**Comment by rmarinho** [comment]
@AlleSchonWeg  can you rebase on main seems we can t ?

**Comment by rmarinho** [comment]
> /rebase

I think you have to do it locally

**Review by PureWeen — CHANGES_REQUESTED** [review]
rebase

**Comment by AlleSchonWeg** [comment]
I created a new fork and PR: https://github.com/dotnet/maui/pull/26450. 
I had this branch only on github (not locally) and github UI only has a sync button. Which do a merge not a rebase.

**Pull request closed without merging**
