### PR TITLE
Fix for odd Cursor behavior

### LINKED ISSUE #6906: [Entry] Avoid transforming the text when `IsPassword` is set to true
### Description

If you set `IsPassword="True"` and `TextTransform="Uppercase "`, the input text will be transformed. Is this the desired effect?

On Windows this is avoided; if `IsPassword` is enabled, the `TextTransform` property is ignored.

https://user-images.githubusercontent.com/5924210/167217594-25fb649e-2164-45dd-a98d-319085ab091e.mp4

https://user-images.githubusercontent.com/5924210/167218004-e04cd26e-f840-479e-9551-7fa3eecc34c2.mov

### Steps to Reproduce

* Add the following Control:

``` xml
<Entry 
    IsPassword="True"
    TextTransform="Uppercase" />
```

* Test the control.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15.4, Android 12

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #6916: [Entry] Cursor makes undesired jumps
### Description

Testcase: https://github.com/SotoiGhost/MauiEntryConverterIssue

On iOS, if you set the `TextTransform` to `Uppercase` the cursor jumps to the end of the TextBox if you try to put text in between:

https://user-images.githubusercontent.com/5924210/167231676-55abd9e3-d000-4cf8-91df-568ee74b188d.mov

With `Lowercase`, the same happens when you try to capitalize a letter:

https://user-images.githubusercontent.com/5924210/167231956-c98629bd-7d99-4fde-91c7-3dadb6d009b4.mov

The same behavior happens if you set `IsPassword` to `True`.

---

On iOS and Android if you use a Converter with the Text property, the cursor jumps to infinity and beyond.

On iOS, the cursor jumps to the end of the text

https://user-images.githubusercontent.com/5924210/167232155-7f33a557-fe0d-439b-9796-13bb95d1f54d.mov

On Android, it jumps to the beginning of the text

https://user-images.githubusercontent.com/5924210/167232175-fb83c274-885d-4a5d-9975-88420b60c9f2.mp4

### Steps to Reproduce

* Use the following control to repro the issue with the `TextTransform`

``` xml
<Entry 
    TextTransform="Uppercase" />
```

---

* Use the following control to repro the issue with the Converter

```xml
<Entry 
    Text="{Binding SubtotalBill, Mode=TwoWay, Converter={x:StaticResource NumberToCurrency}}" />
```

The Converter and ViewModel are within the testcase linked.

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 15, Android 12

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #7937: [Win] Editor's CursorPosition and SelectionLength properties are not limited to Text.Length
### Description

If you set the Editor's `CursorPosition` or `SelectionLength` properties by code, you can set a value beyond the Text.Length value. On Android or iOS, the value is capped to the text's length.

Here's the testcase: https://github.com/SotoiGhost/maui-EditorPropertiesIssue

https://user-images.githubusercontent.com/5924210/173146088-22e247e1-e908-450e-a563-a4f362397653.mp4

### Steps to Reproduce

1. Open the testcase
2. Run the testcase
3. Click on the "Click me" button

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.17763.0 and up

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by SotoiGhost**
### Description of Change

This PR brings the following fixes on iOS, Mac, and Android:

* Text is no longer transformed when `IsPassword` is enabled
* Cursor does not longer make orbital jumps to the beginning or the end of an Entry/Editor control when:
   * The text is transformed
   * A Converter is used
   * Or a combination of the above
* Entry/Editor CursorPosition and SelectedLength properties are now in harmony with its Platform properties and viceversa
* Entry/Editor CursorPosition and SelectedLength are no longer overridden at Init stage

For Windows:

* Entry/Editor CursorPosition and SelectedLength properties are now limited to Text.Length
* Enabled the Editor and Entry Core.DeviceTests.
* Fixed a scenario where the cursor jumps to the beginning of the Entry/Editor when `IsPassword` is set
* Fixed a NRE when Keyboard property is not set

### Issues Fixed

* Fixes #6906
* Fixes #6916
* Fixes #7937

### CODE REVIEW

**Comment by hartez** [comment]
@SotoiGhost This needs to be retargeted to the net6.0 branch if we're going to put it in sr2.

**Comment by devonuto** [comment]
@SotoiGhost how is this going? This issue is a bit of a blocker for me. Is there anything we can do to help get it through?

**Comment by SotoiGhost** [comment]
@devonuto Sorry for the late reply, I missed your post. This PR was ready yesterday and hope to be reviewed by the following week.

**Comment by SotoiGhost** [comment]
The following tests are failing on CI but are unrelated to these PR changes:

* UpdatingSourceUpdatesImageCorrectly

**Comment by devonuto** [comment]
> @devonuto Sorry for the late reply, I missed your post. This PR was ready yesterday and hope to be reviewed by the following week.

No worries. Looks like it's still failing a couple of checks. Will that stop it?

**Review by hartez — CHANGES_REQUESTED** [review]
Looks great, just a concern about the casting in the connect/disconnect methods.

**Review by hartez — APPROVED** [review]

**Pull request merged**
