### PR TITLE
Minimal changes required to support RemoteWebView

### PR DESCRIPTION
**Pull request by budcribar**
### Description of Change ###

Created a new virtual method CreateWebViewManager so that subclasses of BlazorWebView (Both the WinForms and WPF versison_ can override the WebViewManager and the FileProvider

Implements # 1603

### Additions made ###

* CreateWebViewManager method in both WinForms and WPF versions of BlazorWebView.cs
* Changed access on RequiredStartupPropertiesSet protected virtual so subclasses can override
* Changed tabs to spaces 
* 

### PR Checklist ###

- [ ] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [ ] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [ ] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [ ] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- [ ] Does this PR introduce a new control? (If yes, add an example using SemanticProperties to the SemanticsPage)
- [ ] APIs that modify focusability?
- [ ] APIs that modify any text property on a control?
- [ ] Does this PR modify view nesting or view arrangement in anyway?
- [ ] Is there the smallest possibility that your PR will change accessibility? 
- [ ] I'm not sure, please help me

If any of the above checkboxes apply to your PR, then the PR will need to provide testing to demonstrate that accessibility still works.

### CODE REVIEW

**Comment by budcribar** [comment]
@rmarinho  Can you re-run the tests? Looks like a build issue

**Comment by rmarinho** [comment]
@Eilon can you review this one ?

**Comment by Eilon** [comment]
Yup, this one is on me.

**Comment by budcribar** [comment]
There may be another small simplification if my assumption is correct.  RequiredStartupPropertiesSet will not return true unless Created  is true and it appears that Created will not be true until after HostPage and Services have changed. If either  HostPage or Services change after Created then _webviewManager will not be null and StartWebViewCoreIfPossible() will just return.

Relevent code snippets follows:

private bool RequiredStartupPropertiesSet =>
            Created &&
            _webview != null &&
            HostPage != null &&
            Services != null;






  // We never start the Blazor code in design time because it doesn't make sense to run
  // a Blazor component in the designer.
            if (!IsAncestorSiteInDesignMode2 && (!RequiredStartupPropertiesSet || _webviewManager != null))

p.s. I am also confused on   "if (!IsAncestorSiteInDesignMode2 &&"
if it is design mode then won't it try and create the BlazorWeb View before the properties are set up?

thanks,
bud

**Comment by budcribar** [comment]
Created a new pull request #3496 which accounts for the changes since the original PR

**Pull request closed without merging**
