### PR TITLE
[iOS] Custom font icon is not rendered in a shell tabbar tab 

### LINKED ISSUE #8244: IOS: Custom font icon is not rendered in a shell tabbar tab
### Description

Did attach some screenshots and a code sample. 
 
android_emul_sample
Screenshot 2022-06-22 at 16 52 40

[MauiApp3.zip](https://github.com/dotnet/maui/files/8959517/MauiApp3.zip)

### Steps to Reproduce

1. It's all in the sample code.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #12250: (Un)SelectedTabColor do not work for TabbedPage icons (FontImageSource) on iOS
### Description

When using a font (FontImageSource) for tab icon, TabbedPage does not apply (Un)SelectedTabColor properties, on iOS.
However, the colors are properly applied to tab titles. 
Also, no issue when using an image (png) for the icon.
No issue on Android.

On this example, Tab1 uses an image, Tab2 uses a font:
Screenshot_1671633286

Similar issues:
https://github.com/dotnet/maui/issues/6043
https://github.com/dotnet/maui/issues/6718
https://github.com/xamarin/Xamarin.Forms/issues/8556

### Steps to Reproduce

1. Create a maui app, both for android and ios
2. Add a TabbedPage, and use either image or font for tab icons.
3. Set (Un)SelectedTabColor properties on TabbedPage
4. Observe colors, both on android and ios, both for image and font icons.

### Link to public reproduction project repository

https://github.com/tranb3r/Issues/tree/main/MauiAppTabbedPageIconColor

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.1

### Did you find any workaround?

Use an image instead of a font.

### Relevant log output

_No response_

### LINKED ISSUE #20866: Font Icons in Shell Tabs not showing in iOS
### Description

Font Icons are not showing in iOS builds in Shell Tabs but they are working in Android - this is the same issue as reported in #4774

### Steps to Reproduce

Create MAUI app
Add relevant icon ttf file to app
Create shell, add icons to tabs via tabbar
Run on iOS local device

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

6.0

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

Setting the FontImageSource Colour works but then it would need updating on selection to have selected and unselected different colours

### Relevant log output

_No response_

### LINKED ISSUE #22032: iOS : Shell FlyoutItem Tab Selected Icon Color not changing if using Font icons
### Description

Shell FlyoutItem Tab Selected Icon Color not changing if using Font image source in iOS.
Only the Title color is changing 

### Steps to Reproduce

Shell FlyoutItem Tab Selected Icon Color not changing if using Font image source in iOS.
Only the Title color is changing 

### Link to public reproduction project repository

na

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS All versions

### Did you find any workaround?

No

### Relevant log output

```shell
na
```

### LINKED ISSUE #23174: TabbedPage doesn't change icon colour
### Description

The TabbedPage doesn't change the icon colour as the tabs are selected/unselected. The title text changes ok.

Using a PNG, instead of an Icon works too, and the colour changes in sync with the title text.

This was working on Xamarin.Forms and works on Android .NET Maui with some tweaks.

### Steps to Reproduce

Create a new maui app.
Add fontawesome
Add a tabbed page with content and set the title and icon for each.
See reproduction project for details.

### Link to public reproduction project repository

https://github.com/richaplinvs/reproduction-projects/tree/main/maui/TabbedSelectionIssue

### Version with bug

9.0.0-preview.4.10690

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

iOS 17.4, Android Api 33

### Did you find any workaround?

On Android changing the position of the toolbar: 

    On<Microsoft.Maui.Controls.PlatformConfiguration.Android>().SetToolbarPlacement(ToolbarPlacement.Bottom);

or  tab colours:

    UnselectedTabColor = Colors.Red;
    SelectedTabColor = Colors.Orange;
    BarBackgroundColor = Colors.HotPink;

On iOS use the OnAppearing/OnDisappearing in each of the tabs content page to set the colour. This requires creating a new instance of FontImageSource each time because the Color property cannot be set on it's own.

    var IconImage = new FontImageSource() { FontFamily = "FontAwesomeProSolid", Glyph = FontAwesome.FontAwesomeIcons.Pencil, Size = 25, Color = Colors.Gray };         
    if(selectedTab)
    {
        IconImage.Color = Colors.Red;
    }
    IconImageSource = IconImage;

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by SuthiYuvaraj**
### RootCause 

The custom font images used for icons in the ShellTabBar are being generated with a default color(white) in ImageSourceExtensions. However, since the TabBar background color is also white, the icons are not properly visible.

### Description of Change

Modified the rendering mode as Automatic which allows the icon color and selection color of the icon in the TabBar to adjust dynamically based on the current theme or selected state.

### Validated the behaviour in the following platforms
 
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Issues Fixed
Fixes #8244 
Fixes https://github.com/dotnet/maui/issues/22032
Fixes https://github.com/dotnet/maui/issues/12250
Fixes https://github.com/dotnet/maui/issues/20866
Fixes https://github.com/dotnet/maui/issues/23174
Fixes https://github.com/dotnet/maui/issues/8244

Before Issue Fix | After Issue Fix |
|----------|----------|
|Screenshot 2024-09-12 at 10 28 36 AM|Screenshot 2024-09-12 at 10 10 39 AM|

### CODE REVIEW

**Comment by mattleibow** [comment]
What happens if the theme changes at runtime?

**Comment by SuthiYuvaraj** [comment]
@mattleibow https://github.com/dotnet/maui/pull/24721#issuecomment-2344299271 = > We have ensured that runtime theme changes and specific style settings work as expected. In the dark theme, the icon color will be updated based on the title text color.

| Light Theme | Dark Theme |
|----------|----------|
|<image src = "https://github.com/user-attachments/assets/262781dd-86ae-47d3-b7f2-5d652ffc1040" width = "200" height= "400">|<image src = "https://github.com/user-attachments/assets/5cc5165f-ff75-4760-9c7b-445591464e6f" width = "200" height= "400">|

**Comment by jfversluis** [comment]
Whoops lets see which of those PRs we should take in for this and coordinate! Thanks @kubaflo !

**Comment by kubaflo** [comment]
Sure thing! However, please have in mind who was first this time 😅

**Pull request closed without merging**
