### PR TITLE
[net7.0] Make CollectionView on iOS measure to content size

### PR DESCRIPTION
**Pull request by hartez**
Backport of #14951 to net7.0

/cc @hartez

### CODE REVIEW

**Comment by Syed-RI** [comment]
@hartez Hurray! Backport to .NET7 FTW!

**Comment by jsuarezruiz** [comment]
Tested with #9135 sample:
Captura de pantalla 2023-07-21 a las 10 28 08

And #14966:
Captura de pantalla 2023-07-21 a las 10 38 58

Everything is working as expected. In the second sample detected that images are not loading. We have a couple of related issues like https://github.com/dotnet/maui/issues/13904

**Review by jsuarezruiz — APPROVED** [review]

**Comment by UkeHa** [comment]
This is (currently the last) blocker for us. When will it be merged and when will be the next service release?

**Comment by jfversluis** [comment]
@hartez this still good to merge in net7?

**Comment by Syed-RI** [comment]
> @hartez this still good to merge in net7?

Who knows 🤷🏽‍♂️

**Comment by Hooterr** [comment]
For what it's worth, I managed to back port this fix manually by inheriting from the existing handlers and adding changes from this pull request (some reflection usage was needed as well) but it works fine in 7.0.92.

**Comment by UkeHa** [comment]
@Hooterr it's certainly possible to roll your own MAUI-version, but i for one would prefer to get a stable .net7 release. Especially after testing the latest .net preview and running into a whole bunch of regressions.

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
