### PR TITLE
Make IsTrimmable=False in all assemblies that have no value

### LINKED ISSUE #9816: Add IsTrimmable=False attribute to non-trimmable assemblies
## iOS:
Depending on the value of MTouchLink (and LinkMode for macOS projects), we set the corresponding TrimMode value(s) to get the same behavior. If a TrimMode value is set, that takes precedence over MTouchLink/LinkMode. 

    
We should add `[assembly: AssemblyMetadata ("IsTrimmable", "False")]`  for MAUI assemblies that don't support trimming.

Note that in .NET 7 the default (for non-Apple workloads, because we override the default) is to trim assemblies unless they have that attribute (the default in .NET 6 was to only trim assemblies that had the attribute set to "True"). This means that in .NET 7 your assemblies will get trimmed unless they set the attribute (again, this does not apply to Apple workloads, because we override the default, and our default has not changed).

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change

Make sure the assemblies have an absolute value that we control.

### Issues Fixed

Fixes #9816

### CODE REVIEW

**Review by Redth — APPROVED** [review]

**Review by jonathanpeppers — COMMENTED** [review]
Can you share a before/after iOS `.app`/`.ipa`? At least the size difference?

I tried `[assembly: AssemblyMetadata ("IsTrimmable", "False")]` recently on a different issue, and it didn't actually do anything...

**Review by tj-devel709 — APPROVED** [review]

**Comment by mattleibow** [comment]
Wouldn't a no-difference be expected as according to docs mono does not set this to true in net7, just console apps

**Comment by jonathanpeppers** [comment]
> Wouldn't a no-difference be expected as according to docs mono does not set this to true in net7, just console apps

Right, so then how does this fix https://github.com/dotnet/maui/issues/9816?

**Comment by mattleibow** [comment]
I don't think it fixes anything, just gives us back control. Maybe they change the default in servicing. Maybe net8 is True. This way we control the value always.

**Comment by Redth** [comment]
The intent of the bug this links to was also to just validate if this was or was not even needed given the change in defaults. I hadn't originally seen the asterisk that the change in defaults did not apply to all workloads or platforms. 

Windows may still be interesting here? Does the default apply to windows apps?

If we can absolutely rule out this is not needed we could just close and not merge, but I lean towards liking the clarity that having the  explicit values sets provides, all other things being equal.

**Review by jonathanpeppers — APPROVED** [review]
It won't hurt anything to merge this, but I'm not sure if it fixes anything either.

**Pull request merged**
