### PR TITLE
Update the Windows App SDK and Win2D

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change ###

Update the Windows App SDK to 1.0.0-preview2 and Win2D to 1.0.0.27-preview1

> To use/test with CI builds of the Windows App SDK, we can set the `$(UseInternalWinUIPackages)` to true and then make sure the `wasdk-internal` feed is enabled in the NuGet.config.

### CODE REVIEW

**Review by rmarinho — APPROVED** [review]

**Review by rmarinho — CHANGES_REQUESTED** [review]
```
 D:\agent\1\s\src\Essentials\src\Battery\Battery.uwp.cs(25,18): error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Microsoft.Windows' (are you missing an assembly reference?) [D:\agent\1\s\src\Essentials\src\Essentials-net6.csproj]
  D:\agent\1\s\src\Essentials\src\Contacts\Contacts.uwp.cs(42,67): error CS0234: The type or namespace name 'Contacts' does not exist in the namespace 'Microsoft.Windows.ApplicationModel' (are you missing an assembly reference?) [D:\agent\1\s\src\Essentials\src\Essentials-net6.csproj]

```

**Comment by mattleibow** [comment]
This is needed first: https://github.com/dotnet/Microsoft.Maui.Graphics/pull/176

**Comment by mattleibow** [comment]
I tested a few things, and it all seems to work.

**Review by mattleibow — COMMENTED** [review]
After we updated to preview1 of the WASDK, I notice we get an exception about missing dlls:

Exception thrown: 'System.DllNotFoundException' in System.Private.CoreLib.dll
Unable to load DLL 'Microsoft.Graphics.Canvas.Geometry.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)

Exception thrown: 'System.DllNotFoundException' in System.Private.CoreLib.dll
Unable to load DLL 'Microsoft.Graphics.Canvas.UI.Xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)

If I just skip through those, I get a new exception:

Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
Specified cast is not valid.

Do we need a bump for Win2D as well?

**Comment by mattleibow** [comment]
Seems all things that use Win2D is not working. This is shapes, graphics and shadows.

**Comment by mattleibow** [comment]
Taking to the Winui team, we are waiting on a Win2D release to get the version that matches the WinUI version

**Comment by mattleibow** [comment]
does not support multi-window

**Pull request merged**
