### PR TITLE
Correctly notify changes in the Page BackgroundColor property

### LINKED ISSUE #4335: AppThemeBinding not working (p11/p12)
### Description

See -> https://github.com/microsoft/dotnet-podcasts/issues/36

Basically the app theme doesn't seem to apply the theme across the board.

### Steps to Reproduce

1.) Download .net podcast app and run on any platform and see

### Version with bug

Preview 11

### Last version that worked well

Preview 10

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All

### Did you find any workaround?

Nope

### Relevant log output

_No response_

### LINKED ISSUE #5681: [Bug] BackgroundColor of ContentPage not being updated on AppThemeBinding update
### Description

BackgroundColor of ContentPage does not update on app theme change, while most other colors do.

### Steps to Reproduce

1. Checkout this repo: https://github.com/MyLastWish/-MauiBackgroundColorBug
2. Run project.
3. When clicking the button it will update text color, but not page's backgroundColor.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android API 30, Windows 10 Educational

### Did you find any workaround?

No.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Correctly notify changes in the Page **BackgroundColor** property.

fix-5681

### Issues Fixed

Fixes #5681 
Fixes #4335

### CODE REVIEW

**Comment by antonfirsov** [comment]
I wonder if there is a way to add regression tests for these kind of use cases, or at least add pages to the samples application based on the repro code?

**Comment by mattleibow** [comment]
Wasn't this done in the controls? Usually there would be an override for the OnPropertyChanged method and then a "if BackgroundColor then also fire Background". This way we don't need a whole new thing.

**Comment by rmarinho** [comment]
Can we add a device test to Controls?

**Review by rachelkang — APPROVED** [review]
LGTM

**Review by PureWeen — CHANGES_REQUESTED** [review]
Wasn't this done in the controls? Usually there would be an override for the OnPropertyChanged method and then a "if BackgroundColor then also fire Background". This way we don't need a whole new thing. Or even have the bindable property propertyChanged delegate fire the Background.

Also, isn't this part of VisualElement, so how is that working and shouldn't this flow automatically since it is the base?

**Comment by PureWeen** [comment]
Closing in favor of https://github.com/dotnet/maui/pull/6372

**Pull request closed without merging**
