### PR TITLE
[Windows] Clamp images inside buttons to button width/height

### LINKED ISSUE #21683: [Windows] Image on button not scaling down for all scenarios when dimensions are less than button
### Description

```XAML
<VerticalStackLayout>
    <Button ImageSource="dotnet_bot.png" WidthRequest="60" HeightRequest="100" Text="Hi there">
    </Button>
</VerticalStackLayout>
```

### Result

Windows: 
image

Android:
image

### PR DESCRIPTION
**Pull request by Foda**
### Description of Change

This PR forces images inside buttons to always fit inside the available space, rather than expand be clipped

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/21683 https://github.com/dotnet/maui/issues/21970

### CODE REVIEW

**Review by jsuarezruiz — COMMENTED** [review]
Have done tests with some samples like Issue18242.
image
The behavior looks good so far, but, in the snapshot from Issue21513Test, the first image seems to be clipped:
image

Is this expected?

**Comment by mattleibow** [comment]
As @jsuarezruiz noticed, the image is clipped. But if you look at all the other images, they are all clipping now. Or rather, still clipping. Should they?

**Comment by jsuarezruiz** [comment]
After the later changes related with spacing, the snapshot for the test Issue21513Test needs changes.

`Snapshot different than baseline: Issue21513Test.png (0.62% difference)`

image

**Review by jsuarezruiz — APPROVED** [review]

**Review by mattleibow — APPROVED** [review]
Looks good!

Not sure if there is value in a device test for Windows that picks a few sizes/options and then renders it on screen. The test would be to make sure the position of things are where they are expected to be.

**Pull request merged**
