### PR TITLE
[UITesting] Moved ButtonHandler.ImageSourceInitializesCorrectly to Appium

### LINKED ISSUE #24916: [UITesting] Move ButtonHandler.ImageSourceInitializesCorrectly to appium
### Description

Currently the following test occasionally crashes our WinUI Device Tests

https://github.com/dotnet/maui/blob/a7b43dd9e152672b1e7d2ec6d86ddec0c5e35c2c/src/Core/tests/DeviceTests/Handlers/Button/ButtonHandlerTests.cs#L72

Let's just move this one to Appium. 
It should be easy to replicate this inside Appium with the screen shot testing if those colors get set.

### PR DESCRIPTION
**Pull request by kubaflo**
### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/24916

### CODE REVIEW

**Comment by jfversluis** [comment]
I guess we're missing baseline screenshots for this one?

**Comment by kubaflo** [comment]
> I guess we're missing baseline screenshots for this one?

Yes, I'm waiting for them :)

**Comment by kubaflo** [comment]
@jfversluis may you please azp it :)

**Review by PureWeen — APPROVED** [review]

**Comment by PureWeen** [comment]
Failing test unrelated

**Pull request merged**
