### PR TITLE
GraphicsView Touches - Alternate API

### PR DESCRIPTION
**Pull request by Redth**
Uses Comet as an inspiration to take a slightly different approach to the API proposed in #3261 

This would allow us to add mouse hover support on desktops (and maybe iPad?)

### CODE REVIEW

**Review by jsuarezruiz — COMMENTED** [review]
Some details and the implementation in Windows would be missing, but it looks good so far. I think sharing API with Comet (when there were very few differences) is a good thing.

**Comment by mattleibow** [comment]
I also had this API for skia views: https://github.com/mono/SkiaSharp/blob/main/source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.Android/SKTouchHandler.cs

I have one event, but maybe there is something here?

**Comment by Redth** [comment]
No longer necessary

**Pull request closed without merging**
