### PR TITLE
[net9.0][Enhancement] FontImageSource defaults and style

### PR DESCRIPTION
**Pull request by kubaflo**
### Description of Change

```
    <ContentPage.Resources>
        <Style TargetType="FontImageSource">
            <Setter Property="FontFamily" Value="FA"/>
            <Setter Property="Color" Value="Red"/>
        </Style>
    </ContentPage.Resources>

    <VerticalStackLayout>
        <ImageButton HeightRequest="100" WidthRequest="100" BackgroundColor="Green" Source="{FontImageSource Glyph=''}"/>
        <ImageButton HeightRequest="100" WidthRequest="100" Source="{FontImageSource Color='Black', Glyph=''}"/>
    </VerticalStackLayout>
```

Screenshot 2024-07-14 at 02 30 32

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/13474

### CODE REVIEW

**Review by rmarinho — COMMENTED** [review]
@kubaflo can we add a test for this? We can add a xaml unit test and maybe a a screenshot uitest test to make it looks ok at runtime.

**Comment by kubaflo** [comment]
@rmarinho Sure, I can add tests on the weekend. The reason I haven't added them is that was that I wasn't sure if you wanted this feature in MAUI :)

**Comment by kubaflo** [comment]
@rmarinho I've added a XAML and a UITest

**Review by rmarinho — DISMISSED** [review]

**Comment by StephaneDelcroix** [comment]
MergedStyle is set at VisualElement currently. it should probably be set for everything that can get a Style. This is a workaround, and if we go that route, we probably will have to apply it at multiple places

**Review by PureWeen — CHANGES_REQUESTED** [review]
@StephaneDelcroix does this PR make sense to merge? 

I can't quite extract from your last comment if you're thinking this is a good way to go. 
Sounds like you're thinking we need a little bit more discussion here?

**Review by PureWeen — APPROVED** [review]
Chatted with @StephaneDelcroix and he gave this one the thumbs up

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
