### PR TITLE
Reverting default item and globbing updates

### LINKED ISSUE #16501: [regression/8.0.0] `.xaml.cs` file nesting doesn't work on first build
### Description

If you create a MAUI project on a fresh (or recently upgraded MAUI) on a machine, you see:

image

In my case, I had just installed an internal build of Visual Studio with a new version of .NET MAUI. I setup the proper `dotnet8` feeds, but the problem wasn't solved until I unloaded and reloaded the project:

image

I suspect customers creating their first .NET MAUI project will also see this behavior. You could also reproduce this by clearing your NuGet cache and creating a new project.

I think the underlying issue is when MAUI moved to NuGet packages in .NET 8, I believe this line should be moved to be *inside* the workload:

https://github.com/dotnet/maui/blob/ab09cf98bc17f57725e8d088cbf02c3f0723cea3/src/Controls/src/Build.Tasks/nuget/buildTransitive/netstandard2.0/Microsoft.Maui.Controls.DefaultItems.targets#L11

### Steps to Reproduce

1. On a clean machine
2. Create a new .NET MAUI project
3. Look at the solution explorer

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.0-preview.6.8686

### Last version that worked well

7.0.92

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Any .NET 8+ project

### Did you find any workaround?

You could `dotnet restore` the project before opening Visual Studio

New projects after the first restore will work as expected.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change

2 changes were made to fix https://github.com/dotnet/maui/issues/16501

- https://github.com/dotnet/maui/pull/16990
- https://github.com/dotnet/maui/pull/17091

However, it appears that this did not fix the issue and rather the IDE changed the way things worked. When testing with older IDEs, these changes cause the solution explorer to not render correctly where preview 7 works.

Reverting locally seems to make it work again. However, after the packages restore it breaks again. I am not sure what is going on, but it was working since Preview 1 so getting back to that state isa better start.

This PR is just reverting all the things so we can start again with looking at the IDE/SDK.

net8.0 PR https://github.com/dotnet/maui/pull/17852

### CODE REVIEW

**Review by jsuarezruiz — APPROVED** [review]

**Comment by mattleibow** [comment]
Looking closer, there is certainly something going wrong. I checked out Preview 7 (before any of these changes) and the issue happens differently. The initial create is correct, but after the projects restore then it breaks and the .xaml.cs files are no longer under the .xaml files.

I am still trying to see why this happens - and if we need to do anything at all because I removed the code from the targets files to do the nesting and the IDE seems to be fine. Does the IDE do this automatically now? Seems _our_ code to nest files is breaking the nesting.

However, the original fix was moving _just_ the `<None Remove="**\*.xaml" />` to the workload _before_ the `<MauiXaml>` was set up, causing the _new_ issue of missing xaml files to appear. So for this reason, we should revert and re-apply the fix to make sure we correctly handle the `MauiXaml` item groups.

**Review by PureWeen — CHANGES_REQUESTED** [review]
Currently this PR is targeting main (SR1) with a GA milestone. 
Can you please update the Milestone to SR1 or update the targeted branch to net8.0.

**Review by pjcollins — APPROVED** [review]

**Comment by mattleibow** [comment]
Merged to net8.0 in https://github.com/dotnet/maui/pull/17852 and then merged to main in https://github.com/dotnet/maui/pull/17906

**Pull request closed without merging**
