### PR TITLE
[Tizen] Update resizetizer for Tizen for Net6

### PR DESCRIPTION
**Pull request by JoonghyunCho**
### Description of Change

This PR adds shared manifest features, fixing a bug and enhancing logic to allow incremental builds for Tizen.

1. Adding Shared Manifest
Maui [shared app manifest](https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/single-project#app-manifest) properties now applies to Tizen. 
- `ApplicationTitle`, `ApplicationId` and `ApplicationDisplayVersion` values will be applied to tizen-manifest.xml
- `ApplicationVersion` will be ignored as it does not fit to Tizen.

2. Fixing a bug
Removing unnecessary original splash images from packaging.

3. Enhancing behavior
- Use timestamp to prevent unnecessary regeneration of `tizen-manifest.xml`.
- Copy `tizen-manifest.xml` file to `obj` directory and update/package file instead of overwrite it in working directory.
- Only update shared app manifest information back to original `tizen-manifest.xml` .

### CODE REVIEW

**Review by mattleibow — APPROVED** [review]

**Comment by mattleibow** [comment]
This appears to be the same changes as this PR: https://github.com/dotnet/maui/pull/8298

We can close that one as these changes will get merged up.

**Review by rookiejava — APPROVED** [review]
Thank you for your efforts!

**Pull request merged**
