### PR TITLE
Implement ThumbColor property in WinUI Slider

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Implement `ThumbColor` property in WinUI Slider

winui-slider-thumbcolor

### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [x] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [x] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [x] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [x] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- No

### CODE REVIEW

**Review by rmarinho — CHANGES_REQUESTED** [review]
Works,but when i hover it changes the color of the maximum color and thumb color to white

before 
image

when hover: 
image

**Comment by rachelkang** [comment]
still seeing similar issues where hovering changes the color

**Review by rmarinho — APPROVED** [review]
Fixed the issue with hover changing color

**Review by rachelkang — CHANGES_REQUESTED** [review]
Hitting this NRE and then it crashes :/

image

**Comment by rmarinho** [comment]
@rachelkang  you can try again, i fixed that on main, and merged now on this branch

**Review by rachelkang — COMMENTED** [review]
no longer an issue for sliders with a designated thumb color, but the default color still changes on hover (blue to black)
thumb color hover

**Comment by rmarinho** [comment]
Yes @rachelkang  that's the default behavior

**Pull request merged**
