### PR TITLE
[Windows] Fixed VisualState Update for CollectionView SelectedItem

### LINKED ISSUE #22104: VisualState Setters not working properly on Windows for a CollectionView
### Description

The visual states are not functioning correctly when inside at a CollectionView's DataTemplate on Windows.

If VisualState setters are defined then firstly the elements are not displayed correctly on initial render and then the visual state isn't changed when an item is selected.

This happens only on Windows, it is working correctly on iOS, MacCatalyst and Android.

### Android
image

### Windows
image

### Steps to Reproduce

1. Clone the attached project
2. Run the solution on MacCatalyst
3. Observe the Items are initially rendered correctly
4. Click the Select Next button and observe the items being selected correctly with a Red background
5. Do the same on iOS and observe it working correctly
6. Do the same on Android and observe it working correctly
7. Run the solution on Windows
8. Observe the items not getting rendered correctly initially and also not when items are selected

### Link to public reproduction project repository

https://bitbucket.org/KeithBoynton/collection-view-selection-highlight/src/master/

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

_No response_

### Did you find any workaround?

No

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Vignesh-SF3580**
### RootCause  

When the SelectedItem is programmatically changed in the collection, the VisualState of the corresponding item does not update as expected. This occurs because the SelectionChanged function restricts visual state changes based on a boolean flag, which prevents the necessary state transitions when the selection is updated programmatically.

### Description of Change

This fix ensures that the visual state of items in CollectionView is properly updated when the selection changes. A new method, UpdateItemContentControlSelection, is introduced to handle the selection state of item controls, ensuring consistent updates regardless of whether the selection is made programmatically or by the user. This resolves the issue where item visual states were not being correctly updated after selection changes.

### Issues Fixed
Fixes https://github.com/dotnet/maui/issues/22104

### Tested the behaviour in the following platforms
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Screenshots

| Before  | After  |
|---------|--------|
|  <video src="https://github.com/user-attachments/assets/5f004f1d-fe7a-4eff-8a95-9e165ad33c29" width="320" height="240" controls></video>   |   <video src="https://github.com/user-attachments/assets/3204b2d7-e471-489b-9513-a20cc9395b88" width="320" height="240" controls></video>   |

### CODE REVIEW

**Review by PureWeen — CHANGES_REQUESTED** [review]
```
D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\SelectableItemsViewHandler.Windows.cs(129,4): error CS0103: The name 'UpdateItemContentControlSelection' does not exist in the current context [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-windows10.0.19041.0]
D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\SelectableItemsViewHandler.Windows.cs(164,4): error CS0103: The name 'UpdateItemContentControlSelection' does not exist in the current context [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-windows10.0.19041.0]
D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\SelectableItemsViewHandler.Windows.cs(246,36): error CS0120: An object reference is required for the non-static field, method, or property 'ItemsViewHandler<TItemsView>.ListViewBase' [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-windows10.0.19041.0]
D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\SelectableItemsViewHandler.Windows.cs(250,24): error CS0120: An object reference is required for the non-static field, method, or property 'ItemsViewHandler<TItemsView>.ItemsView' [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-windows10.0.19041.0]
D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\SelectableItemsViewHandler.Windows.cs(250,94): error CS0120: An object reference is required for the non-static field, method, or property 'ItemsViewHandler<TItemsView>.ItemsView' [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-windows10.0.19041.0]
C:\Users\cloudtest\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(841,9): error MSB3073: The command ""C:\Users\cloudtest\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\buildTransitive\..\tools\net6.0\..\net472\XamlCompiler.exe" "D:\a\_work\1\s\artifacts\obj\Controls.Core\Release\net8.0-windows10.0.19041.0\\input.json" "D:\a\_work\1\s\artifacts\obj\Controls.Core\Release\net8.0-windows10.0.19041.0\\output.json"" exited with code 1. [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-windows10.0.19041.0]
D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\SelectableItemsViewHandler.Windows.cs(129,4): error CS0103: The name 'UpdateItemContentControlSelection' does not exist in the current context [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-windows10.0.20348.0]
D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\SelectableItemsViewHandler.Windows.cs(164,4): error CS0103: The name 'UpdateItemContentControlSelection' does not exist in the current context [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-windows10.0.20348.0]
D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\SelectableItemsViewHandler.Windows.cs(246,36): error CS0120: An object reference is required for the non-static field, method, or property 'ItemsViewHandler<TItemsView>.ListViewBase' [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-windows10.0.20348.0]
D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\SelectableItemsViewHandler.Windows.cs(250,24): error CS0120: An object reference is required for the non-static field, method, or property 'ItemsViewHandler<TItemsView>.ItemsView' [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-windows10.0.20348.0]
D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\SelectableItemsViewHandler.Windows.cs(250,94): error CS0120: An object reference is required for the non-static field, method, or property 'ItemsViewHandler<TItemsView>.ItemsView' [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-windows10.0.20348.0]

```

**Comment by Vignesh-SF3580** [comment]
> ```
> D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\SelectableItemsViewHandler.Windows.cs(129,4): error CS0103: The name 'UpdateItemContentControlSelection' does not exist in the current context [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-windows10.0.19041.0]
> D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\SelectableItemsViewHandler.Windows.cs(164,4): error CS0103: The name 'UpdateItemContentControlSelection' does not exist in the current context [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-windows10.0.19041.0]
> D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\SelectableItemsViewHandler.Windows.cs(246,36): error CS0120: An object reference is required for the non-static field, method, or property 'ItemsViewHandler<TItemsView>.ListViewBase' [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-windows10.0.19041.0]
> D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\SelectableItemsViewHandler.Windows.cs(250,24): error CS0120: An object reference is required for the non-static field, method, or property 'ItemsViewHandler<TItemsView>.ItemsView' [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-windows10.0.19041.0]
> D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\SelectableItemsViewHandler.Windows.cs(250,94): error CS0120: An object reference is required for the non-static field, method, or property 'ItemsViewHandler<TItemsView>.ItemsView' [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-windows10.0.19041.0]
> C:\Users\cloudtest\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(841,9): error MSB3073: The command ""C:\Users\cloudtest\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\buildTransitive\..\tools\net6.0\..\net472\XamlCompiler.exe" "D:\a\_work\1\s\artifacts\obj\Controls.Core\Release\net8.0-windows10.0.19041.0\\input.json" "D:\a\_work\1\s\artifacts\obj\Controls.Core\Release\net8.0-windows10.0.19041.0\\output.json"" exited with code 1. [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-windows10.0.19041.0]
> D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\SelectableItemsViewHandler.Windows.cs(129,4): error CS0103: The name 'UpdateItemContentControlSelection' does not exist in the current context [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-windows10.0.20348.0]
> D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\SelectableItemsViewHandler.Windows.cs(164,4): error CS0103: The name 'UpdateItemContentControlSelection' does not exist in the current context [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-windows10.0.20348.0]
> D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\SelectableItemsViewHandler.Windows.cs(246,36): error CS0120: An object reference is required for the non-static field, method, or property 'ItemsViewHandler<TItemsView>.ListViewBase' [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-windows10.0.20348.0]
> D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\SelectableItemsViewHandler.Windows.cs(250,24): error CS0120: An object reference is required for the non-static field, method, or property 'ItemsViewHandler<TItemsView>.ItemsView' [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-windows10.0.20348.0]
> D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\SelectableItemsViewHandler.Windows.cs(250,94): error CS0120: An object reference is required for the non-static field, method, or property 'ItemsViewHandler<TItemsView>.ItemsView' [D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj::TargetFramework=net8.0-windows10.0.20348.0]
> ```

We have validated the issue and resolved it. Could you please check?

**Review by Foda — APPROVED** [review]

**Review by PureWeen — APPROVED** [review]

**Pull request merged**
