### PR TITLE
[net9.0] Move to rtm

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change

Move net9 to rtm versions

### CODE REVIEW

**Review by jonathanpeppers — COMMENTED** [review]
We are seeing similar weird workload errors here:
* https://github.com/dotnet/android/pull/9339

Using the rtm .NET SDK:
```
         Writing workload pack installation record for Microsoft.NETCore.App.Runtime.AOT.osx-x64.Cross.android-arm64 version 9.0.0-rtm.24476.4...
##[error]Warning(0,0): Error : System.IO.FileNotFoundException: Workload version 9.0.100-rtm.24479.2 was not found.
     1>Warning : Workload garbage collection failed with error : System.IO.FileNotFoundException: Workload version 9.0.100-rtm.24479.2 was not found. [/Users/runner/work/1/s/build-tools/create-packs/Microsoft.Android.Sdk.proj]
            at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.RefreshWorkloadManifests()
            at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider..ctor(String sdkRootPath, String sdkVersion, Func`2 getEnvironmentVariable, String userProfileDir, String globalJsonPath, String workloadSetVersion)
            at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.ForWorkloadSet(String sdkRootPath, String sdkVersion, String userProfileDir, String workloadSetVersion)
            at Microsoft.DotNet.Workloads.Workload.Install.WorkloadResolverFactory.CreateForWorkloadSet(String dotnetPath, String sdkVersion, String userProfileDir, String workloadSetVersion)
            at Microsoft.DotNet.Workloads.Workload.Install.WorkloadGarbageCollector.GarbageCollectWorkloadManifestsAndPacks()
            at Microsoft.DotNet.Workloads.Workload.Install.WorkloadGarbageCollector.Collect()
            at Microsoft.DotNet.Workloads.Workload.Install.FileBasedInstaller.GarbageCollect(Func`2 getResolverForWorkloadSet, Nullable`1 offlineCache, Boolean cleanAllPacks)
            at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallCommand.TryRunGarbageCollection(IInstaller workloadInstaller, IReporter reporter, VerbosityOptions verbosity, Func`2 getResolverForWorkloadSet, Nullable`1 offlineCache).
         
         Successfully installed workload(s) android.
```
I think the workload installed successfully, but then a GC warning made it a non-zero exit code?

I think @marcpopMSFT or @dsplaisted mentioned they are fixing something related to rtm branding & workloads?

**Comment by dsplaisted** [comment]
Yes, this should be fixed with this PR: https://github.com/dotnet/sdk/pull/43797

Garbage collection is failing, which for most workload commands is reported as a warning but the command completes successfully.  For `workload uninstall`, it is reported as an error and the command fails.

**Comment by jonathanpeppers** [comment]
Ok, I see why it failed, we run some `dotnet workload` commands with the `<Exec/>` task. MSBuild saw that stacktrace (which is a warning) and decided it was an error. `<Exec/>` will consider some output an error, even if the exit code is successful.

**Comment by dsplaisted** [comment]
The fix has been merged.  If you need a workaround before it flows, you could delete the `sdk-manifests\9.0.100-rtm.<build>\workloadsets` folder from the SDK install.

**Comment by jonathanpeppers** [comment]
I think there is a build, trying it [here](https://github.com/dotnet/android/pull/9339):
```
> darc get-build --repo dotnet/sdk --commit eab3ae2483035e83669769158a17fbd36d96df9e
Repository:    https://github.com/dotnet/sdk
Branch:        release/9.0.1xx
Commit:        eab3ae2483035e83669769158a17fbd36d96df9e
Build Number:  20241003.1
Date Produced: 10/3/2024 9:22 AM
Build Link:    https://dev.azure.com/dnceng/internal/_build/results?buildId=2551880
AzDO Build Id: 2551880
BAR Build Id:  240864
Released:      False
Channels:
- .NET 9.0.1xx SDK
```

**Comment by rmarinho** [comment]
Yeah @Redth  the issue is back here with RTM 

```
D:\a\1\s\bin\dotnet\sdk\9.0.100-rtm.24503.1\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(322,5): warning NETSDK1206: Found version-specific or distribution-specific runtime identifier(s): win10-arm64, win10-x64, win10-x86. Affected libraries: Microsoft.WindowsAppSDK. In .NET 8.0 and higher, assets for version-specific and distribution-specific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details. [D:\a\1\s\src\Graphics\src\Graphics.Win2D\Graphics.Win2D.csproj::TargetFramework=net9.0-windows10.0.19041.0]
D:\a\1\s\src\Core\src\Platform\Windows\TextBlockExtensions.cs(47,41): error CS0433: The type 'TextDecorations' exists in both 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b' and 'Microsoft.Windows.SDK.NET, Version=10.0.20348.38, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [D:\a\1\s\src\Core\src\Core.csproj::TargetFramework=net9.0-windows10.0.20348.0]
D:\a\1\s\src\Core\src\Platform\Windows\TextBlockExtensions.cs(49,40): error CS0433: The type 'TextDecorations' exists in both 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b' and 'Microsoft.Windows.SDK.NET, Version=10.0.20348.38, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [D:\a\1\s\src\Core\src\Core.csproj::TargetFramework=net9.0-windows10.0.20348.0]
D:\a\1\s\src\Core\src\Platform\Windows\TextBlockExtensions.cs(52,41): error CS0433: The type 'TextDecorations' exists in both 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b' and 'Microsoft.Windows.SDK.NET, Version=10.0.20348.38, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [D:\a\1\s\src\Core\src\Core.csproj::TargetFramework=net9.0-windows10.0.20348.0]
D:\a\1\s\src\Core\src\Platform\Windows\TextBlockExtensions.cs(54,40): error CS0433: The type 'TextDecorations' exists in both 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b' and 'Microsoft.Windows.SDK.NET, Version=10.0.20348.38, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [D:\a\1\s\src\Core\src\Core.csproj::TargetFramework=net9.0-windows10.0.20348.0]
C:\Users\VssAdministrator\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(841,9): error MSB3073: The command ""C:\Users\VssAdministrator\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\buildTransitive\..\tools\net6.0\..\net472\XamlCompiler.exe" "D:\a\1\s\artifacts\obj\Core\Release\net9.0-windows10.0.20348.0\\input.json" "D:\a\1\s\artifacts\obj\Core\Release\net9.0-windows10.0.20348.0\\output.json"" exited with code 1. [D:\a\1\s\src\Core\src\Core.csproj::TargetFramework=net9.0-windows10.0.20348.0]
D:\a\1\s\src\Core\src\Platform\Windows\TextBlockExtensions.cs(47,41): error CS0433: The type 'TextDecorations' exists in both 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b' and 'Microsoft.Windows.SDK.NET, Version=10.0.19041.38, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [D:\a\1\s\src\Core\src\Core.csproj::TargetFramework=net9.0-windows10.0.19041.0]
D:\a\1\s\src\Core\src\Platform\Windows\TextBlockExtensions.cs(49,40): error CS0433: The type 'TextDecorations' exists in both 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b' and 'Microsoft.Windows.SDK.NET, Version=10.0.19041.38, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [D:\a\1\s\src\Core\src\Core.csproj::TargetFramework=net9.0-windows10.0.19041.0]
D:\a\1\s\src\Core\src\Platform\Windows\TextBlockExtensions.cs(52,41): error CS0433: The type 'TextDecorations' exists in both 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b' and 'Microsoft.Windows.SDK.NET, Version=10.0.19041.38, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [D:\a\1\s\src\Core\src\Core.csproj::TargetFramework=net9.0-windows10.0.19041.0]
D:\a\1\s\src\Core\src\Platform\Windows\TextBlockExtensions.cs(54,40): error CS0433: The type 'TextDecorations' exists in both 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b' and 'Microsoft.Windows.SDK.NET, Version=10.0.19041.38, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [D:\a\1\s\src\Core\src\Core.csproj::TargetFramework=net9.0-windows10.0.19041.0]
C:\Users\VssAdministrator\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(841,9): error MSB3073: The command ""C:\Users\VssAdministrator\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\buildTransitive\..\tools\net6.0\..\net472\XamlCompiler.exe" "D:\a\1\s\artifacts\obj\Core\Release\net9.0-windows10.0.19041.0\\input.json" "D:\a\1\s\artifacts\obj\Core\Release\net9.0-windows10.0.19041.0\\output.json"" exited with code 1. [D:\a\1\s\src\Core\src\Core.csproj::TargetFramework=net9.0-windows10.0.19041.0]
    22 Warning(s)
    10 Error(s)
    ```

**Pull request merged**
