### PR TITLE
`LayoutHandler.Windows`: Store children to a local variable

### PR DESCRIPTION
**Pull request by MartyIX**
### Description of Change

The PR trivially attempts to decrease the number of interops.

### Issues Fixed

Contributes to #21787

### CODE REVIEW

**Comment by symbiogenesis** [comment]
Maybe we could write an analyzer to detect usages of iterating on members or properties that call platform-specific code.

**Review by jonathanpeppers — COMMENTED** [review]
Can you share a screenshot or `.speedscope` that shows approximately how much the `get_Children` calls improved things?

**Review by jonathanpeppers — APPROVED** [review]
Overall, the right approach was taken here:
* Measure, see a `get_Children` call, that does some interop on the platform. (Note this would be similar for Windows, iOS/Catalyst, and Android)
* Call `get_Children` less
* Measure again, see it improves

An analyzer that could find these is an idea I've had as well. But in a lot of cases it doesn't matter -- and measuring first, we know we found a spot that matters! Thanks!

**Review by jsuarezruiz — APPROVED** [review]

**Pull request merged**
