### PR TITLE
[Windows] Fix Entry clear button is not taking the color of the text.

### LINKED ISSUE #19152: Windows | Entry ClearButton not taking color of text
### Description

Bug was already fixed for Android and IOS, but it is still not working on Windows.
TestMauiApp 01 12 2023 10_19_07
TestMauiApp 01 12 2023 10_18_52

Former Bug: #13432 

### Steps to Reproduce

Make an Entry with Text Color Red on a white background. Clear Button is not visible because it is not using the Text Color.

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

No not yet. I cannot set it manually with an custom renderer

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by BagavathiPerumal**
### Root cause

The Clear button in the Entry control does not match the TextColor settings because the TextBoxExtension is missing the necessary keys for the ClearButton in the TextColorResourceKeys list. The keys only cover the text colors for the Entry control and do not include the Clear button.

### Description of Issue Fix

The fix involves adding additional resource keys for the Clear button’s foreground colors. This ensures that the Clear button correctly adopts the specified text colors for different states, such as pointer over and pressed.

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/19152

### Output 

Before Fix:

image

After Fix:

image

### CODE REVIEW

**Review by jfversluis — DISMISSED** [review]

**Review by Foda — APPROVED** [review]

**Review by PureWeen — APPROVED** [review]

**Comment by jfversluis** [comment]
@BagavathiPerumal can you agree with the CLA even if you did it already somewhere else just to see if that gets is unstuck?

**Comment by BagavathiPerumal** [comment]
@dotnet-policy-service agree

**Pull request merged**
