### PR TITLE
Implement basic SliderHandler properties in WinUI

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Implement basic Slider properties in WinUI.

- Minimum
- Maximum
- Value
- MinimumTrackColor
- MaximumTrackColor

### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [x] Adds the property to the appropriate interface
- [x] Avoids any changes not essential to the handler property
- [x] Adds the mapping to the PropertyMapper in the handler
- [x] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [x] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [x] Tags ported renderer methods with [PortHandler]
- [x] Adds an example of the property to the sample project (MainPage)
- [x] Adds the property to the stub class
- [x] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might effect accessibility?
No

### CODE REVIEW

**Review by rachelkang — COMMENTED** [review]
I can't slide the slider on WinUI :/
Also, the background bar thing on which the thumb part slides across is fleeting - it's only visible when the thumb is clicked on.

**Comment by rmarinho** [comment]
image

seems to work fine

**Comment by rmarinho** [comment]
@rachelkang  i think you can't slide by default because is just 0 and 1 

try something like :

```
new Slider { Minimum = 0, Maximum = 10, MinimumTrackColor = Colors.Pink, MaximumTrackColor = Colors.Red }
```

**Review by rmarinho — APPROVED** [review]

**Comment by rachelkang** [comment]
@rmarinho I tried that but it didn't work for me :/ will try again though

**Review by rachelkang — APPROVED** [review]
Just checked again - LGTM now!

Regarding the color thing - probably for a separate PR, if anything, but I realized the trackColor and backgroundColor changes during interaction (hover/click), to blue and gray, respectively. Is this default WinUI behavior? Can we change it? It's especially confusing when a backgroundColor isn't specified, and it becomes visible during interaction

**Pull request merged**
