### PR TITLE
[Android] Ecosystem updates WAS:Google Maps bump/update

### LINKED ISSUE #20740: Support for latest renderer in Google Map
### Description

Google announced that by March 3, 2025 the legacy renderer of Google Map will be decommissioned. We need a way to use the `latest` renderer in MAUI 

See more:
[https://developers.google.com/maps/documentation/android-sdk/renderer](https://developers.google.com/maps/documentation/android-sdk/renderer)

### Public API Changes

I'm not experienced enough to suggest where this setting to toggle between `latest` and `legacy` should be implemented, but we need the option somewhere.

### Intended Use-Case

.

### PR DESCRIPTION
**Pull request by moljac**
### Description of Change

1. Bumped versions of AX and GPS-FB-MLKit nugets
2. fixed errors for obsolete native types

### Issues Fixed

Fixes #20740

https://github.com/dotnet/maui/issues/20740

| Package | From | To |
| --- | --- | --- |
| [Xamarin.AndroidX.AppCompat.AppCompatResources](https://github.com/xamarin/AndroidX) | `1.6.1.4` | `1.6.1.8` |
| [Xamarin.AndroidX.SwipeRefreshLayout](https://github.com/xamarin/AndroidX) | `1.1.0.14` | `1.1.0.18` |
| [Xamarin.AndroidX.Lifecycle.LiveData](https://github.com/xamarin/AndroidX) | `2.6.1.3` | `2.7.0.1` |
| [Xamarin.AndroidX.Navigation.UI](https://github.com/xamarin/AndroidX) | `2.6.0.1` | `2.7.7.1` |
| [Xamarin.AndroidX.Navigation.Fragment](https://github.com/xamarin/AndroidX) | `2.6.0.1` | `2.7.7.1` |
| [Xamarin.AndroidX.Navigation.Runtime](https://github.com/xamarin/AndroidX) | `2.6.0.1` | `2.7.7.1` |
| [Xamarin.AndroidX.Navigation.Common](https://github.com/xamarin/AndroidX) | `2.6.0.1` | `2.7.7.1` |
| [Xamarin.AndroidX.Browser](https://github.com/xamarin/AndroidX) | `1.5.0.3` | `1.6.0.2` |
| [Xamarin.AndroidX.MediaRouter](https://github.com/xamarin/AndroidX) | `1.4.0.2` | `1.6.0.3` |
| [Xamarin.AndroidX.Palette](https://github.com/xamarin/AndroidX) | `1.0.0.19` | `1.0.0.23` |
| [Xamarin.AndroidX.RecyclerView](https://github.com/xamarin/AndroidX) | `1.3.1` | `1.3.2.2` |
| [Xamarin.Google.Android.Material](https://github.com/xamarin/AndroidX) | `1.9.0.2` | `1.10.0.3` |
| [Xamarin.AndroidX.Window.WindowJava](https://github.com/xamarin/AndroidX) | `1.1.0.1` | `1.2.0.2` |

### CODE REVIEW

**Comment by moljac** [comment]
### Error 1

```
./src/Core/src/Platform/Android/Navigation/StackNavigationManager.cs(197,8): 
error CS0618: 
    'NavGraph.StartDestination.get' is obsolete: 'deprecated' 
[./src/Core/src/Core.csproj::TargetFramework=net8.0-android]
```

https://github.com/dotnet/maui/blob/main/src/Core/src/Platform/Android/Navigation/StackNavigationManager.cs#L197

Code:

```csharp
			if (NavGraph.StartDestination != startId)
				NavGraph.StartDestination = startId;
```

replaced with:

```csharp
                        if (NavGraph.FindStartDestination(NavGraph).Id != startId)
				NavGraph.StartDestination = startId;
```


### Error 2

```
./src/Core/src/Platform/Android/MauiSwipeRefreshLayout.cs(108,12): 
error XAOBS001: 
    'NestedScrollView.ComputeVerticalScrollOffset()' is obsolete: 'While this member is 'public', Google considers it internal API and reserves the right to modify or delete it in the future. Use at your own risk.' 
[./src/Core/src/Core.csproj::TargetFramework=net8.0-android]
    0 Warning(s)
    1 Error(s)
```

https://github.com/dotnet/maui/blob/main/src/Core/src/Platform/Android/MauiSwipeRefreshLayout.cs#L108

Code:

```csharp
			if (view is NestedScrollView nestedScrollView)
				return nestedScrollView.ComputeVerticalScrollOffset() > 0;
```

replaced with:

```csharp
			if (view is NestedScrollView nestedScrollView)
				return nestedScrollView.ScrollY > 0;
```

**Comment by moljac** [comment]
New errors:
```
./src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs(247,58): 
error XAOBS001: 
    'BottomNavigationMenuView' is obsolete: 'While this type is 'public', Google considers it internal API and reserves the right to modify or delete it in the future. Use at your own risk.' 
[./src/Controls/src/Core/Controls.Core.csproj::TargetFramework=net8.0-android]
```

https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomnavigation/BottomNavigationMenuView.java#L40

```java
public class BottomNavigationMenuView extends NavigationBarMenuView {
```


```
./src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs(269,26): 
error XAOBS001: 
    'BottomNavigationItemView' is obsolete: 'While this type is 'public', Google considers it internal API and reserves the right to modify or delete it in the future. Use at your own risk.' 
[./src/Controls/src/Core/Controls.Core.csproj::TargetFramework=net8.0-android]
```


```
./src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellBottomNavViewAppearanceTracker.cs(75,47): 
error XAOBS001: 
    'BottomNavigationMenuView' is obsolete: 'While this type is 'public', Google considers it internal API and reserves the right to modify or delete it in the future. Use at your own risk.' 
[./src/Controls/src/Core/Controls.Core.csproj::TargetFramework=net8.0-android]
```

**Comment by moljac** [comment]
DeviceTests are failing because of timeout.

**Comment by moljac** [comment]
Errors in DeviceTests - obsoleted classes

```
024-03-16T18:31:33.4064390Z /Users/builder/azdo/_work/3/s/src/TestUtils/src/DeviceTests/AssertionExtensions.Android.cs(686,10): error XAOBS001: 'BottomNavigationItemView' is obsolete: 'While this type is 'public', Google considers it internal API and reserves the right to modify or delete it in the future. Use at your own risk.' [/Users/builder/azdo/_work/3/s/src/TestUtils/src/DeviceTests/TestUtils.DeviceTests.csproj::TargetFramework=net8.0-android]
2024-03-16T18:31:33.4065740Z /Users/builder/azdo/_work/3/s/src/TestUtils/src/DeviceTests/AssertionExtensions.Android.cs(691,51): error XAOBS001: 'NavigationBarView.MenuView.get' is obsolete: 'While this member is 'public', Google considers it internal API and reserves the right to modify or delete it in the future. Use at your own risk.' [/Users/builder/azdo/_work/3/s/src/TestUtils/src/DeviceTests/TestUtils.DeviceTests.csproj::TargetFramework=net8.0-android]
2024-03-16T18:31:33.4067060Z /Users/builder/azdo/_work/3/s/src/TestUtils/src/DeviceTests/AssertionExtensions.Android.cs(691,26): error XAOBS001: 'BottomNavigationMenuView' is obsolete: 'While this type is 'public', Google considers it internal API and reserves the right to modify or delete it in the future. Use at your own risk.' [/Users/builder/azdo/_work/3/s/src/TestUtils/src/DeviceTests/TestUtils.DeviceTests.csproj::TargetFramework=net8.0-android]
2024-03-16T18:31:33.4068370Z /Users/builder/azdo/_work/3/s/src/TestUtils/src/DeviceTests/AssertionExtensions.Android.cs(692,52): error XAOBS001: 'BottomNavigationItemView' is obsolete: 'While this type is 'public', Google considers it internal API and reserves the right to modify or delete it in the future. Use at your own risk.' 
```

**Comment by moljac** [comment]
mac test - green
windows - weird stacktrace

/azp run

**Comment by moljac** [comment]
errors

seems like AVD errors and XHarness crashes...

```
2024-03-20T15:39:01.7853970Z Error: There is no Android Virtual Device named 'DEVICE_TESTS_EMULATOR'.
2024-03-20T15:39:01.7854700Z null
```

```
emulator-5554 uninstall com.microsoft.maui.controls.devicetests'
2024-03-20T15:52:56.9655880Z [40m[32minfo[39m[22m[49m: Successfully uninstalled com.microsoft.maui.controls.devicetests
2024-03-20T15:52:56.9689830Z XHarness exit code: 80 (APP_CRASH)
2024-03-20T15:52:57.0041740Z [41m[37;1mAn error occurred when executing task '[0m[41;1m[37;1mTest[0m[41m[37;1m'.[0m
2024-03-20T15:52:57.0051910Z 
2024-03-20T15:52:57.0052880Z ----------------------------------------
2024-03-20T15:52:57.0053230Z TearDown
2024-03-20T15:52:57.0053570Z ----------------------------------------
2024-03-20T15:52:57.0054940Z AdbEmuKill
2024-03-20T15:52:57.8408150Z glTexImage2D: got err pre :( 0x502 internal 0x1907 format 0x1907 type 0x1401
2024-03-20T15:53:02.3591340Z emulatorProcess.Kill()
2024-03-20T15:53:02.3760800Z AndroidAvdDelete
2024-03-20T15:53:05.2296420Z [41m[37;1mError: [0m[41;1m[37;1mThe file '/Users/builder/azdo/_work/2/a/test-results/TestResultsFailures/9d0dea4d-bf07-4bdf-9b9b-b5fbf928acfc/TestResults.xml' does not exist.[0m
2024-03-20T15:53:05.4073910Z 
2024-03-20T15:53:15.4097280Z The STDIO streams did not close within 10 seconds of the exit event from process '/bin/bash'. This may indicate a child process inherited the STDIO streams and has not yet exited.
2024-03-20T15:53:15.4145710Z ##[error]Bash exited with code '1'.
2024-03-20T15:53:17.4893360Z ##[warning]RetryHelper encountered task failure, will retry (attempt #: 1 out of 1) after 1000 ms
2024-03-20T15:53:18.8063920Z Generating script.
```

```
2024-03-20T15:53:27.3236610Z [37;1mDeleting AVD if exists: [0m[44m[37;1mDEVICE_TESTS_EMULATOR[0m[37;1m...[0m
2024-03-20T15:53:29.3611560Z Error: There is no Android Virtual Device named 'DEVICE_TESTS_EMULATOR'.
2024-03-20T15:53:29.3612650Z null
2024-03-20T15:53:29.4354090Z [37;1mCreating AVD: [0m[44m[37;1mDEVICE_TESTS_EMULATOR[0m[37;1m...[0m
2024-03-20T15:53:31.5723100Z [37;1mStarting Emulator: [0m[44m[37;1mDEVICE_TESTS_EMULATOR[0m[37;1m...[0m
2024-03-20T15:53:31.9442870Z - waiting for device -
```

```
2024-03-20T16:02:17.6858670Z XHarness exit code: 80 (APP_CRASH)
2024-03-20T16:02:17.7168320Z [41m[37;1mAn error occurred when executing task '[0m[41;1m[37;1mTest[0m[41m[37;1m'.[0m
2024-03-20T16:02:17.7179260Z 
2024-03-20T16:02:17.7180370Z ----------------------------------------
2024-03-20T16:02:17.7181270Z TearDown
2024-03-20T16:02:17.7181780Z ----------------------------------------
2024-03-20T16:02:17.7182070Z AdbEmuKill
2024-03-20T16:02:18.5654870Z glTexImage2D: got err pre :( 0x502 internal 0x1907 format 0x1907 type 0x1401
2024-03-20T16:02:22.9944920Z emulatorProcess.Kill()
2024-03-20T16:02:23.0564440Z AndroidAvdDelete
2024-03-20T16:02:26.2975960Z [41m[37;1mError: [0m[41;1m[37;1mThe file '/Users/builder/azdo/_work/2/a/test-results/TestResultsFailures/3d0b5112-9283-49db-b0b2-7b62bd181a50/TestResults.xml' does not exist.[0m
2024-03-20T16:02:26.4790000Z 
2024-03-20T16:02:36.4814120Z The STDIO streams did not close within 10 seconds of the exit event from process '/bin/bash'. This may indicate a child process inherited the STDIO streams and has not yet exited.
```

**Review by PureWeen — CHANGES_REQUESTED** [review]
```
03-20 12:00:45.921  5270  5270 E AndroidRuntime: FATAL EXCEPTION: main
03-20 12:00:45.921  5270  5270 E AndroidRuntime: Process: com.microsoft.maui.controls.devicetests, PID: 5270
03-20 12:00:45.921  5270  5270 E AndroidRuntime: java.lang.IllegalStateException: Design assumption violated.
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at androidx.viewpager2.adapter.FragmentStateAdapter.onBindViewHolder(FragmentStateAdapter.java:182)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at androidx.viewpager2.adapter.FragmentStateAdapter.onBindViewHolder(FragmentStateAdapter.java:67)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7747)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7847)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6646)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6917)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.view.View.layout(View.java:23693)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6413)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:527)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.view.View.layout(View.java:23693)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6413)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.view.View.layout(View.java:23693)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6413)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2348)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:953)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.view.View.layout(View.java:23693)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6413)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.view.View.layout(View.java:23693)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6413)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at androidx.appcompat.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1669)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at androidx.appcompat.widget.LinearLayoutCompat.layoutHorizontal(LinearLayoutCompat.java:1658)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at androidx.appcompat.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1433)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.view.View.layout(View.java:23693)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6413)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:799)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.view.View.layout(View.java:23693)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6413)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3999)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3372)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2328)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9087)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
03-20 12:00:45.921  5270  5270 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
03-20 12:00:45.922  5270  5270 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
03-20 12:00:45.922  5270  5270 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:832)
03-20 12:00:45.922  5270  5270 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
03-20 12:00:45.922  5270  5270 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
03-20 12:00:45.922  5270  5270 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-20 12:00:45.922  5270  5270 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
03-20 12:00:45.922  5270  5270 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
03-20 12:00:45.922  5270  5270 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
03-20 12:00:45.922  5270  5270 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-20 12:00:45.922  5270  5270 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
03-20 12:00:45.922  5270  5270 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by moljac** [comment]
Related

MAUI:

https://github.com/dotnet/maui/pull/17793

Android:

https://issuetracker.google.com/issues/134246546

https://github.com/android/views-widgets-samples/issues/103

https://stackoverflow.com/questions/62880883/notifydatasetchanged-not-working-in-fragmentstateadapter-with-viewpager2

**Comment by maonaoda** [comment]
What is the latest news on this? I encountered this problem during the migration process.

**Comment by maonaoda** [comment]
@moljac 
I want to confirm whether this modification can solve my problem, but I can't compile successfully.

@PureWeen 
Is there no plan for this PR for the time being? I think this will definitely affect the migration of projects that need to modify tab elements during operation

I hope to get a clear answer, thank you.

**Comment by hot33331** [comment]
Is there an ETA on this? Looks like we need to disable AOT to prevent the app from crashing.

**Comment by rmarinho** [comment]
Can we close this one @moljac ?

**Comment by moljac** [comment]
> Can we close this one @moljac ?

@rmarinho 

yes. closing.

**Pull request closed without merging**
