### PR TITLE
Update SGen to add "NET6_0_OR_GREATER" instead of NET5

### LINKED ISSUE #8540: Source Generator adds "NET5_0_OR_GREATER" and not "NET6_0_OR_GREATER"
I noticed that the [source generator adds "NET5_0_OR_GREATER"](https://github.com/dotnet/maui/blob/c1439acf4dfeb0e5a6f56583d6a1860a12ff4a6f/src/Controls/src/SourceGen/CodeBehindGenerator.cs#L196) and not "NET6_0_OR_GREATER" which I would expect as MAUI only runs on .net 6.

### PR DESCRIPTION
**Pull request by jfversluis**
### Description of Change

Updates a piece of source generated code to check for .NET 6 as opposed to .NET 5 which it is now. 

### Issues Fixed

Fixes #8540

### CODE REVIEW

**Review by Eilon — CHANGES_REQUESTED** [review]
Presumably everything in .NET MAUI 7 will be restricted to .NET 7 and we will no longer support .NET 6, so we should have this change be future-proof.

**Comment by Eilon** [comment]
Or, you know what, do we even need such checks at all? What was this even meant to protect against, and has it become irrelevant ages ago? .NET MAUI 6 runs on only .NET 6, so that check was already irrelevant. I'm guessing that check is ancient and from before .NET 6 shipped and there might have been early cases where you could mix things with .NET 5.

But really, any project in which this generator will apply will already be in the correct version of .NET, so it could never generate code for anything except the correct version of .NET to begin with.

The only possible exception to this that I can think of is if this generator is part of an _SDK_ that has to cross-target to different versions of .NET. For example, if you have .NET 7 SDK installed, but you're building an app that runs on .NET MAUI 6, does this tool run? If so, then we might need some checks, but this isn't the right check anyway. If this tool only ever runs on the .NET version that it's targetting, then no checks are needed at all.

**Comment by AmrAlSayed0** [comment]
@Eilon I added that guard around `MemberNotNull` use because the min API for this [attribute](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.membernotnullattribute?view=net-5.0) is .NET 5. At the time, MAUI was already being built with the .NET 6 SDK #3497 but I consulted this [spec](https://github.com/dotnet/docs/blob/main/includes/preprocessor-symbols.md) and decided to use `NET5_0_OR_GREATER`.

According to that spec `NET5_0_OR_GREATER` should be defined if you build with .NET 5 or .NET 6 or .NET 7 SDKs so it's fine if you leave this preprocessor tag as is.

**Comment by Eilon** [comment]
@AmrAlSayed0 understood, but this code can never run on .NET 5 or lower. MAUI 6 runs only on .NET 6, and MAUI 7 only on .NET 7, etc. So that `#if` will never apply.

**Pull request closed without merging**
