### PR TITLE
Ensure the iOS ScrollView content container is at least the ScrollView size

### LINKED ISSUE #8446: Buttons (or clicking) don't seem to work properly in scrollviews
### Description

Using the default template, I notice that I was not able to click the button. Seems that this happens when in a scrollview AND when the vertical stack is centered. I was able to get half the button clickable by adding ` HeightRequest="100"` so this looks to be that the view is centered but some container or something is not actually centering. 

| Default | Centered |
| :-------: | :---------: |
| image | image |

### Steps to Reproduce

1. File | New | Maui
2. Deploy to iOS simulator
3. Click the button
4. Observe no clicky
5. Make the button taller
6. Oberserve clicky
7. Remove the height and either remvoe the scroll view or make the stack not centered
8. Observ clicky

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

All

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by hartez**
### Description of Change

For various reasons, the ScrollView is using a container ContentView to hold all the stuff in the ScrollView on iOS. If the container isn't large enough for the content, the content will still layout and display just fine, but the hit testing won't work for any part of the content outside the bounds of the container. 

These changes ensure that the container is large enough to contain the content so that the hit testing works. They also fix an issue where ScrollView content did not properly account for SafeArea (drawing some content outside the safe area even when the content requested otherwise), and fix an issue where vertical alignments other than Fill were slightly off-alignment inside of ScrollView (when the content itself was smaller than the viewport size).

### Issues Fixed

Fixes #8446

### CODE REVIEW

**Comment by mattleibow** [comment]
The device test failure is unrelated and @PureWeen has a fix coming.

**Comment by gbelmont22** [comment]
Has this fix also been merged into net7.0 ?  I am seeing this behavior on iOS using a VericalStackLayout as a BindableLayout inside a ScrollView.  The ScrollView also contains a button, used to add a new element to the collection that the BindableLayout is bound to.  So the process is 1. the button works, 2. the user clicks the button, 3. a new element is added to the bound collection and so it is displayed in the BindableLayout, 4. rinse and repeat until the button is pushed off the bottom of the screen, 5. click events stop firing.  If the button is half-on and half-off the display, you can scroll it to be fully visible, but only the top half responds to click events.

**Comment by hartez** [comment]
> Has this fix also been merged into net7.0 ? 

Yes, it was merged before net7.0 was first released.

> I am seeing this behavior on iOS using a VericalStackLayout as a BindableLayout inside a ScrollView. The ScrollView also contains a button, used to add a new element to the collection that the BindableLayout is bound to. So the process is 1. the button works, 2. the user clicks the button, 3. a new element is added to the bound collection and so it is displayed in the BindableLayout, 4. rinse and repeat until the button is pushed off the bottom of the screen, 5. click events stop firing. If the button is half-on and half-off the display, you can scroll it to be fully visible, but only the top half responds to click events.

I think you're seeing a newer bug that's popped up: https://github.com/dotnet/maui/issues/14624

**Pull request merged**
