### PR TITLE
Memory Leak in Style with Trigger - fix

### LINKED ISSUE #22036: Memory Leak in Style with Trigger
### Description

A memory leak occurs when an implicit style with an associated trigger is used.

Please see the linked repository for a reproduction, where I have created a rudimentary test harness to illustrate the issue.

### Steps to Reproduce

1. Run the sample at the linked repository
2. Use the navigate button to navigate to a new page, and press the back arrow to go back to the original page. Repeat this a number of times.
3. Back on the main page, use the GC button to trigger garbage collections by clicking a few times.
4. Observe the memory usage does not return to baseline.
5. Remove the style from the App constructor and repeat the steps above
6. Observe the memory returns to baseline

Simulator Screenshot - iPX15 4 - 2024-04-24 at 16 43 33
_Above: Image with style present_

Simulator Screenshot - iPX15 4 - 2024-04-24 at 16 42 31
_Above: Image with style removed_

### Link to public reproduction project repository

https://github.com/markmccaigue/mauitriggerleaktest

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/22036

### CODE REVIEW

**Review by jsuarezruiz — COMMENTED** [review]
Could you include a related test?
Here you can find an example: https://github.com/dotnet/maui/blob/60a46c58df8cca8dc6f7e90f0ef65edfc8453a19/src/Controls/tests/Xaml.UnitTests/Issues/Maui21839.xaml.cs#L64 Let me know if can help in something :)

**Comment by kubaflo** [comment]
> Could you include a related test? Here you can find an example:
> 
> https://github.com/dotnet/maui/blob/60a46c58df8cca8dc6f7e90f0ef65edfc8453a19/src/Controls/tests/Xaml.UnitTests/Issues/Maui21839.xaml.cs#L64
> 
> Let me know if can help in something :)

@jsuarezruiz  I've added a test :)

**Review by StephaneDelcroix — APPROVED** [review]

**Pull request merged**
