### PR TITLE
[Essentials] Fixes IPreferences DateTime handling

### LINKED ISSUE #8853: Preference not work with DateTime
### Description

When use Preferences.Default.Set() method with a DateTime value on Android Local Device, no preference is saved.

### Steps to Reproduce

1. Create Maui project
2. Replace OnCounterClicked function with:

```
private void OnCounterClicked(object sender, EventArgs e)
	{
		Preferences.Default.Set("myPreference1",DateTime.Now);

		if (!Preferences.Default.ContainsKey("myPreference1"))
		{
			Shell.Current.DisplayAlert("Error", "Preference not saved", "Ok");
		}
	}
```

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by andres-fg**
### Description of Change
Fixes Preferences native implementations for `DateTime` handling. It was working using the static Set/Get methods but it did not work when using the `IPreferences` interface

Adds type check for unsupported types.

### Issues Fixed
Fixes #8853

Tested on Windows, iOS and Android. No tested on a Tizen device, but it should work fine.

### CODE REVIEW

**Comment by andres-fg** [comment]
@rmarinho I'm sorry, I had a couple of bugs on the Tizen side, so it didn't build. Yesterday I pushed 2 commits to fix them. You can run the pipelines again.

Thanks

**Review by mattleibow — APPROVED** [review]

**Comment by mattleibow** [comment]
Actually, I know this is a pain, but could we copy the entire test for preferences and make another set that tests the non-static version?

Then we may catch things like this in the future. Thanks!

**Comment by andres-fg** [comment]
> 
> Actually, I know this is a pain, but could we copy the entire test for preferences and make another set that tests the non-static version?
> 
> Then we may catch things like this in the future. Thanks!

Yeah, I think it's a good idea. I'll do that

**Review by mattleibow — APPROVED** [review]

**Comment by andres-fg** [comment]
There are a couple of build pipelines failing (MAUI-DeviceTests-public (Android Device Tests Core (API 23))), but I do not understand the errors, from the logs I see:

09-15 08:15:02.381  4036  4036 W System.err: android.runtime.JavaProxyThrowable: System.NotSupportedException: Unable to activate instance of type Microsoft.Maui.Platform.MauiWebViewClient from native handle 0xbfeb14fc (key_handle 0x274dbcd).
09-15 08:15:02.381  4036  4036 W System.err:  ---> System.MissingMethodException: No constructor found for Microsoft.Maui.Platform.MauiWebViewClient::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)
09-15 08:15:02.381  4036  4036 W System.err:  ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
09-15 08:15:02.381  4036  4036 W System.err: Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
09-15 08:15:02.381  4036  4036 W System.err:   --- End of managed Java.Lang.Error stack trace ---
09-15 08:15:02.381  4036  4036 W System.err: java.lang.Error: Java callstack:
09-15 08:15:02.381  4036  4036 W System.err: 	at crc6452ffdc5b34af3a0f.MauiWebViewClient.n_onPageFinished(Native Method)
09-15 08:15:02.381  4036  4036 W System.err: 	at crc6452ffdc5b34af3a0f.MauiWebViewClient.onPageFinished(MauiWebViewClient.java:48)
09-15 08:15:02.381  4036  4036 W System.err: 	at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:560)
09-15 08:15:02.381  4036  4036 W System.err: 	at org.chromium.android_webview.AwWebContentsObserver.didFinishLoad(AwWebContentsObserver.java:44)
09-15 08:15:02.381  4036  4036 W System.err: 	at org.chromium.content.browser.webcontents.WebContentsObserverProxy.didFinishLoad(WebContentsObserverProxy.java:162)

Seems something else not related to this PR, isn't it?

**Review by rmarinho — APPROVED** [review]

**Comment by rmarinho** [comment]
@andres-fg can you retarget this to net7 branch  please? 

Thanks

**Comment by andres-fg** [comment]
> @andres-fg can you retarget this to net7 branch please?
> 
> Thanks

Sure, I'll do that

**Comment by rmarinho** [comment]
I m sorry @andres-fg this was merged so we are all good.

**Pull request merged**
