### PR TITLE
Minimal changes to support RemoteWebView

### PR DESCRIPTION
**Pull request by budcribar**
### Description of Change ###

Created a new virtual method CreateWebViewManager so that subclasses of BlazorWebView (Both the WinForms and WPF versison_ can override the WebViewManager and the FileProvider

Implements # 1603 

### Additions made ###

CreateWebViewManager  method in both WinForms and WPF versions of BlazorWebView.cs

* Adds 

### PR Checklist ###

- [ ] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [ ] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [ ] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [ ] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- [ ] Does this PR introduce a new control? (If yes, add an example using SemanticProperties to the SemanticsPage)
- [ ] APIs that modify focusability?
- [ ] APIs that modify any text property on a control?
- [ ] Does this PR modify view nesting or view arrangement in anyway?
- [ ] Is there the smallest possibility that your PR will change accessibility? 
- [ ] I'm not sure, please help me

If any of the above checkboxes apply to your PR, then the PR will need to provide testing to demonstrate that accessibility still works.

### CODE REVIEW

**Comment by budcribar** [comment]
@Eilon ,

Is the holdup about adding the CreateWebViewManager method? 
There are 2 alternatives that I can think of 

First is to change the following 
BlazorWebView.cs 

private bool RequiredStartupPropertiesSet => protected bool RequiredStartupPropertiesSet
private void StartWebViewCoreIfPossible() => protected void StartWebViewCoreIfPossible()
private bool IsAncestorSiteInDesignMode => => protected bool IsAncestorSiteInDesignMode
private WebView2WebViewManager _webviewManager;=> protected WebView2WebViewManager _webviewManager;
private readonly WebView2Control _webview; => change to protected 
private WindowsFormsDispatcher Dispatcher => change to protected 

RooTComponent.cs 
internal Task AddToWebViewManagerAsync(WebViewManager webViewManager) => protectedTask AddToWebViewManagerAsync(WebViewManager webViewManager)

and then override the StartWebViewCoreIfPossible method 

The downside to that Every release would require subclasses of BlazorWebView.cs to review the source code for StartWebViewCoreIfPossible to make sure they take any changes.

The second alternative is to create to create a factory class and add it to the Services collection in AddBlazorWebView();

then instead of 
webviewManager = CreateWebViewManager(new WindowsFormsWebView2Wrapper(_webview), Services, Dispatcher);

Services.GetService<WebView2WebViewManagerFactory >().Create(this,new WindowsFormsWebView2Wrapper(_webview), Services, Dispatcher)

then clients would only need to substitute their implementation of  the WebView2WebViewManagerFactory .

Let me know if either of these approaches works for you.

thanks,
bud

**Comment by Eilon** [comment]
Hi @budcribar this PR looks much simpler than the previous iteration but I have been busy with a few other items so I haven't had a chance to put my full thought into it. I'm confident we can get something like this in, though!

**Comment by budcribar** [comment]
@Eilon ,
No worries. I know you have things coming at you from every direction. 
thanks,
bud

**Comment by rmarinho** [comment]
@budcribar you mind rebase? thanks

**Comment by budcribar** [comment]
Sure. I will re-base tomorrow

**Comment by budcribar** [comment]
I am closing this request and reopening another which is based on the current build as of 9/13

**Comment by budcribar** [comment]
New pull request is Minimal changes required to support RemoteWebView #2469

**Pull request closed without merging**
