### PR TITLE
[UnitTests] MSBuildTests run dotnet build against .NET 6 projects

### PR DESCRIPTION
**Pull request by jonathanpeppers**
### Description of Change ###

6be8a1c1 ignored some failing tests, but it seems like we should have
fixed and modernized the tests instead.

Some parts of these tests seem out of date:

* We don't need to build long-form .NET framework projects.
* We should generate/build `net6.0` projects instead of `netstandard2`.
* We should run `dotnet build` instead of MSBuild. We don't need
  `Microsoft.Build.Locator` anymore.
* `RestoreIfNeeded()` is no longer needed because `dotnet build`
  implicitly restores.
* I fixed the `DesignTimeBuild()` test that can just use the `Compile`
  target now.
* The `sdkStyle` parameter is no longer needed anymore for any of
  these tests, so we have 1/2 as many tests now.

I mostly deleted code here.

#### Other changes ####

Some other stuff was needed for this test to work:

* Move usage of dotnet-install.ps1|sh to yaml
* We now install .NET 6 for the `Build Windows` stage.
* Disable code coverage in child processes
* Add the `msbuild.binlog` file as a test attachment.

### Additions made ###

None

### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [ ] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [ ] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [ ] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
@rmarinho does the `Build Windows` build phase not install .NET 6?

```
       "d:\agent\1\s\src\Controls\tests\Xaml.UnitTests\bin\Debug\net47\temp\AddNewFile\test.csproj" (Restore target) (1) ->
       "d:\agent\1\s\src\Controls\tests\Xaml.UnitTests\bin\Debug\net47\temp\AddNewFile\test.csproj" (_GenerateRestoreGraphProjectEntry target) (1:5) ->
       (_CheckForUnsupportedNETCoreVersion target) -> 
         C:\Program Files\dotnet\sdk\5.0.103\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(141,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 6.0.  Either target .NET Core 5.0 or lower, or use a version of the .NET SDK that supports .NET Core 6.0. [d:\agent\1\s\src\Controls\tests\Xaml.UnitTests\bin\Debug\net47\temp\AddNewFile\test.csproj]

    0 Warning(s)
    1 Error(s)
```

Also why does the PR have a green status with failing tests?

**Comment by rmarinho** [comment]
Hey, @jonathanpeppers  we were marking continue on error on the xaml unit tests , we have 2 sln one for net6 other for classic. Build Windows is the classic one, we then have Pack/Build net6 in Windows/macOS

**Comment by jonathanpeppers** [comment]
Thanks @rmarinho I'll update the `.yaml`, I'm running into something new now:
```
error MSB4018: The "XamlGTask" task failed unexpectedly. [d:\agent\1\s\src\Controls\tests\Xaml.UnitTests\bin\Release\net47\temp\AddNewFile\test.csproj]
error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.CodeCoverage.Shim, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. [d:\agent\1\s\src\Controls\tests\Xaml.UnitTests\bin\Release\net47\temp\AddNewFile\test.csproj]
error MSB4018: File name: 'Microsoft.VisualStudio.CodeCoverage.Shim, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [d:\agent\1\s\src\Controls\tests\Xaml.UnitTests\bin\Release\net47\temp\AddNewFile\test.csproj]
error MSB4018:    at Microsoft.Maui.Controls.Build.Tasks.XamlGTask.Execute() [d:\agent\1\s\src\Controls\tests\Xaml.UnitTests\bin\Release\net47\temp\AddNewFile\test.csproj]
error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [d:\agent\1\s\src\Controls\tests\Xaml.UnitTests\bin\Release\net47\temp\AddNewFile\test.csproj]
error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [d:\agent\1\s\src\Controls\tests\Xaml.UnitTests\bin\Release\net47\temp\AddNewFile\test.csproj]
```

I guess I need to figure out what `codeCoverageEnabled: true` does, it seems to be breaking this.

**Comment by jonathanpeppers** [comment]
I think everything works now, I can find green MSBuild tests:

image

They should fail the build now if they fail as well, and attach `msbuild.binlog` files as attachments.

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
