### PR TITLE
Implement TextType property in LabelHandlers

### LINKED ISSUE #1998: [Bug] HTML TextType on Label does not render HTML as elements
### Description

When using `<Label TextType="Html"/>` the label does not render the HTML elements as Native elements. This previously worked on Xamarin.Forms.

### Steps to Reproduce

1. Create a Label
2. Set the text to a valid HTML string.

### Expected Behavior

The content for the label would render the HTML contents as native elements.

### Actual Behavior

The label renders the raw text.

Xamarin.Forms Implementation

MAUI Implementation

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Implement `TextType` property in LabelHandlers

### Platforms Affected ### 

- Core
- iOS
- macOS
- Android
- Windows

### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [x] Targets a single property for a single control (or intertwined few properties)
- [x] Adds the property to the appropriate interface
- [x] Avoids any changes not essential to the handler property
- [x] Adds the mapping to the PropertyMapper in the handler
- [x] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [x] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [x] Tags ported renderer methods with [PortHandler]
- [x] Adds an example of the property to the sample project (MainPage)
- [x] Adds the property to the stub class
- [x] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- No

### CODE REVIEW

**Comment by hartez** [comment]
I think we should hold off on merging this until we've evaluated #1082. Most of what's in this PR would still be valid, but the interfaces would change a bit.

**Comment by jsuarezruiz** [comment]
@hartez Could we include the `TextType` property in the `ILabel` interface?

**Comment by hartez** [comment]
> @hartez Could we include the `TextType` property in the `ILabel` interface? Right now it doesn't work because Core MapText method overwrites native properties from MapTextType Controls method. We must avoid updating plain text if TextType is Html.

Fixed that. No need to add the property to the interface.

**Review by PureWeen — APPROVED** [review]

**Comment by GuildOfCalamity** [comment]
This appears to be broken again.
If I do a simple test with a full http link I get an `Unhandled Exception: '=' is an unexpected token.`

**Comment by hartez** [comment]
> This appears to be broken again (`TextType="Html"`). If I do a simple test with a full http link I get an `Unhandled Exception: '=' is an unexpected token.`

@GuildOfCalamity  Please open a new issue and post an example of what you're trying to do.

**Comment by GuildOfCalamity** [comment]
@hartez done

**Pull request merged**
