### PR TITLE
Feat: Added "Keyboard.None"

### LINKED ISSUE #10331: Add "Keyboard.None"
### Description

Currently I can only choose _what_ type of keyboard I want for a specific `Entry`, but in order to fully disable the keyboard I have to do some weird workarounds with `#if`s and custom renderers involved: https://stackoverflow.com/questions/73199602/need-a-way-to-hide-soft-keyboard-in-mauis-editor-entry-fields (the first link in google search for me). I think such capability should be implemented on platform layer and be available to all MAUI users without that much effort to use it.

The end result of this proposal should look like this (taken from the article about how to implement such feature in Xamarin, which also didn't have a build-in solution for it):

### Public API Changes

In https://github.com/dotnet/maui/blob/main/src/Core/src/Primitives/Keyboard.cs:
```diff
public class Keyboard
{
    ...
+    public static Keybord None
+    {
+        ...
+    }
}
```

https://github.com/dotnet/maui/blob/main/src/Core/src/Converters/KeyboardTypeConverter.cs should also be modified.

### Intended Use-Case

Well, see almost any calculator app for reference. It provides an input field but doesn't trigger the system keyboard when tapped/clicked. In general the feature would be _very_ useful when the app needs a specific control over what user is typing. Such apps usually have their own keyboard or a limited set of buttons for data input

### PR DESCRIPTION
**Pull request by ChaplinMarchais**
### Description of Change

Add support for a new `NoneKeyboard` type. 

### Issues Fixed

Fixes #10331

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=11024) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=11024) before we can accept your contribution.<br/><br/>:x: ChaplinMarchais [sign now](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=11024)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/maui?pullRequest=11024) it.</sub>

**Comment by mattleibow** [comment]
How does this prevent they keyboard rrom appearing? Is there any code to do that or does it just work?

**Comment by mattleibow** [comment]
Is there a reason you rebased on net7? Can you go back to main? We usually merge into main and then backport the PR once it is merged.

**Comment by ChaplinMarchais** [comment]
> Is there a reason you rebased on net7?

No not in particular, so I will close out this PR then and create a new one with a feature branch that is based of master.

**Comment by rachelkang** [comment]
Hi, @ChaplinMarchais - just checking in! Are you still working on opening a new PR based on main?

**Comment by PureWeen** [comment]
I added a comment here on the original issue
https://github.com/dotnet/maui/issues/10331#issuecomment-1432152667

I'm going to close this PR for now and wait for additional comments/PR

**Pull request closed without merging**
