### PR TITLE
Allow LayoutView to pass touches to child controls when CascadeInputTransparent is false

### LINKED ISSUE #6574: [IOS] InputTransparency always cascaded to Children even when CascadeInputTransparent= false
### Description

The TapGestureRecognizer attached on Children of Layout will NOT function when Layout is set `InputTransparent = true`, and `CascadeInputTransparent= false`. 

### Steps to Reproduce

```
Content = new AbsoluteLayout
{
    InputTransparent = true,
    CascadeInputTransparent = false,
    Children =
    {
	    new BoxView
	    {
		    Color =Colors.Green,
	    }.LayoutFlags(Microsoft.Maui.Layouts.AbsoluteLayoutFlags.PositionProportional)
	    .LayoutBounds(0.5,0.7,100,100)
	    .TapGesture(t => t.Tapped += (s,e) =>
	    {
		    Debug.WriteLine("This should be clicked but doesn't");
	    }),
    }
},
```

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by hartez**
### Description of Change

The default InputTransparent handling for LayoutView is disabling all user interaction, including with child controls. For situations where the Layout is InputTransparent but the child controls are not, this prevents interaction with the child controls.

These changes allow the LayoutView on iOS to pass touches through to child controls when it's corresponding Layout is InputTransparent, making it consistent with the other platforms.

This also removes some old code for enabling gestures on layouts that pre-dates the InputTransparent implementation for MAUI.Core (see #1190).

### Issues Fixed

Fixes #6574

### CODE REVIEW

**Comment by mattleibow** [comment]
Is this correct behaviour? When we set a parent to input transparent, we still want the children to be hit?

Is there a way to say "make this layout and everything in it transparent"?

**Comment by hartez** [comment]
> Is this correct behaviour? When we set a parent to input transparent, we still want the children to be hit?

Yes, this is correct. We want the option of setting a parent to be input transparent, while still allowing the children to be hit. Consider a UI with a map control, and an overlay with, say, a zoom slider and a couple of buttons. The layout which contains the overlay controls needs to be input transparent (so the user can interact with the map), but the controls it contains should _not_ be input transparent. 

> Is there a way to say "make this layout and everything in it transparent"?

Yes, that's what the `CascadeInputTransparent` property mentioned in the title does.

**Review by mattleibow — APPROVED** [review]

**Comment by emceelovin** [comment]
> > Is this correct behaviour? When we set a parent to input transparent, we still want the children to be hit?
> 
> Yes, this is correct. We want the option of setting a parent to be input transparent, while still allowing the children to be hit. Consider a UI with a map control, and an overlay with, say, a zoom slider and a couple of buttons. The layout which contains the overlay controls needs to be input transparent (so the user can interact with the map), but the controls it contains should _not_ be input transparent.
> 
> > Is there a way to say "make this layout and everything in it transparent"?
> 
> Yes, that's what the `CascadeInputTransparent` property mentioned in the title does.

This is not the correct behavior/what should happen. MSDN specifically says CascadeInputTransparent is True by default. Which causes all children in a layout to inherit the InputTransparent value of the parent layout. E.g. InputTransparent="True" on a parent layout implicity sets InputTransparent="True" on all of it's children. This is logically what should happen. Since children will block antecedents, and you could have MANY MANY children, it's a LOT easier to set a cascading property that's inherited,  which will be respected until another CascadeInputTransparency is found down in the tree, versus setting InputTransparent="True" on, depending on the complexity of the tree, a lot of UI elements.

[MAUI Layout documentation](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/layouts/)
> The Layout class, from which all layouts derive, has a CascadeInputTransparent bindable property that controls whether child elements inherit the input transparency of the layout. Its default value is _**true,**_ ensuring that setting the InputTransparent property to true on a layout class will result in all elements within the layout not receiving any input.

**Comment by hartez** [comment]
This was a change for MAUI.Core to allow for the situation where `CascadeInputTransparent` is `false`. Without it, the `CascadeInputTransparent` property would be useless on iOS - it would effectively always be `true`.

**Pull request merged**
