### PR TITLE
Generate unplated icons on Windows

### LINKED ISSUE #5162: AppIcon shows a border on windows taskbar
### Description

Adding a custom image as appicon not shown correctly in Windows taskbar. A Blue border or padding gets applied.

[MauiApp4.zip](https://github.com/dotnet/maui/files/8213941/MauiApp4.zip)

Issue screenshot:

icon

### Steps to Reproduce

1. Create a MAUI project.
2. Add a image named as appicon.png and set as MauiIcon.

Run the app in windows.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 19041

### Did you find any workaround?

No

### Relevant log output

_No response_

### LINKED ISSUE #6164: Generate unplated icons on Windows
### Description

By default, MAUI icon on Windows look like this:

image

The blue square around the icon is the "plate". It was added in Windows 8 but is rarely used anymore. It's ugly and makes the actual icon smaller, so I think it should be removed :-) 

image

Read more here:
https://docs.microsoft.com/en-us/windows/apps/design/style/app-icons-and-logos#more-about-app-icon-assets

I think the only necessary change to do is to add `altform-unplated` in the icon filename, like `LogoSquare44x44.targetsize-48_altform-unplated.png`.

### Public API Changes

No API changes necessary :-)

### Intended Use-Case

Make apps prettier in Windows.

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change

Generate unplated icons on Windows.

Before & After

image

### Issues Fixed

Fixes #6164
Fixes #5162

### CODE REVIEW

**Review by jfversluis — APPROVED** [review]

**Comment by BarFoo** [comment]
This still does not work for me on the latest version, Windows 11. From a brand new project. 

You may want to re-open this ticket.

**Comment by mattleibow** [comment]
What version of maui are you using? I do not think there was a new release?

**Comment by BarFoo** [comment]
My apologies, I thought it had been released, misread this issue.

**Comment by HakanL** [comment]
@mattleibow Will there be a way to get this as a fix to MAUI on .NET6, or do we have to wait for .NET 7 release? Is there a workaround?

**Comment by mattleibow** [comment]
I merged this into .net 6, so should be going out really soon in the next service release. Maybe Tuesday or next week Tuesday. Typically on a Tuesday.

**Comment by FedericoSMEC** [comment]
Hey @mattleibow , thanks for your work. I just updated my Visual Studio to 17.4.0 and this issue seems to be there still. Do you have any news about this?

**Comment by Mashedpoturtles** [comment]
@mattleibow has this been released yet?

**Pull request merged**
