### PR TITLE
[android] improve FormattedString performance

### LINKED ISSUE #14222: CollectionView+FormattedString Poor Performance
### Description

When using a Collection View with a formatted string inside a grid, the scroll performance or framerate is severely reduced. 

Similar issue was found Open in the Xamarin Forms repo: https://github.com/xamarin/Xamarin.Forms/issues/5087

Here is a video of it scrolling smoothly (using a model property)

https://user-images.githubusercontent.com/12143535/228093105-21e2cc76-2d28-4252-afa2-814ccfaef1dd.mp4

And a video of it very choppy (using FormattedString)

https://user-images.githubusercontent.com/12143535/228093142-8d3c00fa-0ef0-4d7b-a322-83c9da1de010.mp4

Its subtle, but noticeable enough to be a problem for users.

### Steps to Reproduce

1. Add a CollectionView with an Item Template. 
2. Inside the item template add a grid and display some Labels. 
3. Include a label with a few Spans in formatted string. 
4. Observe performance impact versus a code-centric model binding.

### Link to public reproduction project repository

https://github.com/shadowfoxish/Temp-CollectionViewFormattedStringSlowness

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Affected platform versions

Tested on Android 9.0, API 28

### Did you find any workaround?

Using a get-only model property eliminates the need for FormattedString, but breaks the Model-View-ViewModel paradigm as it pushes UI logic into the Model or ViewModel.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jonathanpeppers**
Context: https://github.com/Redth/MauiCollectionViewGallery
Fixes: https://github.com/dotnet/maui/issues/14222

This will conflict with:

* https://github.com/dotnet/maui/pull/20352

But I will rework this after it is merged.

Profiling the above sample while scrolling on a Pixel 5, a lot of time is spent in `FormattedStringExtensions.RecalculateSpanPositions()`:

    (20%) Microsoft.Maui.Controls!Microsoft.Maui.Controls.Platform.FormattedStringExtensions.RecalculateSpanPositions(Android.Widget.TextView,Microsoft.Maui.Controls.Label,Android.Text.SpannableString,Microsoft.Maui.SizeRequest)
    (11%) Microsoft.Maui.Controls!Microsoft.Maui.Controls.Platform.FormattedStringExtensions.FontSpan.UpdateDrawState(Android.Text.TextPaint)
    (11%) Microsoft.Maui.Controls!Microsoft.Maui.Controls.Platform.FormattedStringExtensions.FontSpan.Apply(Android.Text.TextPaint)
    (6.3%) MauiCollectionViewGallery!PoolMathApp.Helpers.FormattedTextExtensions.ToFormattedString(PoolMathApp.Models.FormattedTex

The key contributors are `FontSpan` and `LineHeightSpan` which:

* Implement `MetricAffectingSpan`, an abstract class that allows to change the metrics of the text.

* Implement `UpdateDrawState()` and `Apply()` methods that are called during draw. Causing frequent Java -> C# interop.

To fix this, let's move the following types from C# to Java:

* `FontSpan` -> `PlatformFontSpan`
* `LetterSpacingSpan` -> `PlatformFontSpan` (use different ctor)
* `LineHeightSpan` -> `PlatformLineHeightSpan`

`PlatformLineHeightSpan` is similar, as it is an implementation of the `LineHeightSpan` interface.

With these changes, I see a nice improvement while scrolling:

    (5.5%) Microsoft.Maui.Controls!Microsoft.Maui.Controls.Platform.FormattedStringExtensions.RecalculateSpanPositions(Android.Widget.TextView,Microsoft.Maui.Controls.Label,Android.Text.SpannableString,Microsoft.Maui.SizeRequest)
    (4.0%) MauiCollectionViewGallery!PoolMathApp.Helpers.FormattedTextExtensions.ToFormattedString(PoolMathApp.Models.FormattedText

`RecalculateSpanPositions` overall, went from 20% to 5.5%!

Comparing the new types, the times spent calling the constructors are also improved:

    Before:
    (1.1%) Microsoft.Maui.Controls!Microsoft.Maui.Controls.Platform.FormattedStringExtensions.FontSpan..ctor(Microsoft.Maui.Font,M
    (1.5%) Microsoft.Maui.Controls!Microsoft.Maui.Controls.Platform.FormattedStringExtensions.LetterSpacingSpan..ctor(double)
    After:
    (1.0%) Microsoft.Maui!Microsoft.Maui.PlatformFontSpan..ctor(Android.Content.Context,Android.Graphics.Typeface,bool,single)
    (0.82%) Microsoft.Maui!Microsoft.Maui.PlatformFontSpan..ctor(single)

This should be reasonable for .NET 8 servicing, as there should be no behavior changes and no API changes.

In a future PR, it looks like `FormattedStringExtensions` could be improved further, but this is a decent starting point that makes it a lot better.

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
Is something pending?, could you rebase?. Thanks in advance.

**Comment by jonathanpeppers** [comment]
New one is here: https://github.com/dotnet/maui/pull/21712

**Pull request closed without merging**
