### PR TITLE
Improve design type converters

### PR DESCRIPTION
**Pull request by etvorun**
Improve design type converters

### CODE REVIEW

**Comment by mattleibow** [comment]
Does this property need to be set for all converters? Also, why is this needed now? And, does this have to go back to net6/7/8?

**Review by mattleibow — APPROVED** [review]

**Comment by jonathanpeppers** [comment]
@mattleibow yes, can we please backport this to .NET 6 and 7? It helps our OKR for Hot Reload.

**Comment by jonathanpeppers** [comment]
What this fixes, is it prevents the IDE from trying to apply a typo for LayoutOptions, it's one of the top errors:

image

**Pull request merged**
