### PR TITLE
Essentials.Compass refactored to interface and singleton

### PR DESCRIPTION
**Pull request by moljac**
### Description of Change ###

Implements #

```csharp
	public interface ICompass
	{
		bool IsSupported { get; }

		bool IsMonitoring { get; set; }

		void Start(SensorSpeed sensorSpeed);

		void Start(SensorSpeed sensorSpeed, bool applyLowPassFilter);
		
		void Stop();
	}
```

### Additions made ###

* Adds 

### PR Checklist ###

- [ ] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [ ] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [ ] Adds the mapping method to the WinUI, Android, iOS, and Standard aspects of the handler
- [ ] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- [ ] Does this PR introduce a new control? (If yes, add an example using SemanticProperties to the SemanticsPage)
- [ ] APIs that modify focusability?
- [ ] APIs that modify any text property on a control?
- [ ] Does this PR modify view nesting or view arrangement in anyway?
- [ ] Is there the smallest possibility that your PR will change accessibility? 
- [ ] I'm not sure, please help me

If any of the above checkboxes apply to your PR, then the PR will need to provide testing to demonstrate that accessibility still works.

### CODE REVIEW

**Review by rmarinho — CHANGES_REQUESTED** [review]
uwp missing

```
    "D:\a\_work\1\s\Microsoft.Maui.BuildTasks.slnf" (Build target) (1:2) ->
       "D:\a\_work\1\s\src\Core\src\Core.csproj" (default target) (2:35) ->
       "D:\a\_work\1\s\src\Core\src\Core.csproj" (Build target) (2:42) ->
       "D:\a\_work\1\s\src\Essentials\src\Essentials.csproj" (default target) (9:60) ->
       (CoreCompile target) -> 
         D:\a\_work\1\s\src\Essentials\src\Compass\Compass.uwp.cs(7,47): error CS0736: 'CompassImplementation' does not implement instance interface member 'ICompass.IsSupported'. 'CompassImplementation.IsSupported' cannot implement the interface member because it is static. [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj]
         D:\a\_work\1\s\src\Essentials\src\Compass\Compass.uwp.cs(7,47): error CS0535: 'CompassImplementation' does not implement interface member 'ICompass.IsMonitoring' [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj]
         D:\a\_work\1\s\src\Essentials\src\Compass\Compass.uwp.cs(7,47): error CS0535: 'CompassImplementation' does not implement interface member 'ICompass.Start(SensorSpeed)' [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj]

    744 Warning(s)
    3 Error(s)
```

**Comment by rmarinho** [comment]
```
"D:\a\_work\1\s\Microsoft.Maui.BuildTasks.slnf" (Build target) (1:2) ->
       "D:\a\_work\1\s\src\Controls\src\Xaml\Controls.Xaml.csproj" (default target) (4:39) ->
       "D:\a\_work\1\s\src\Controls\src\Xaml\Controls.Xaml.csproj" (Build target) (4:56) ->
       "D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj" (default target) (3:63) ->
       "D:\a\_work\1\s\src\Essentials\src\Essentials.csproj" (default target) (9:75) ->
         D:\a\_work\1\s\src\Essentials\src\Compass\Compass.uwp.cs(51,4): error CS0103: The name 'OnChanged' does not exist in the current context [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj]
```

**Comment by moljac** [comment]
> ```
> "D:\a\_work\1\s\Microsoft.Maui.BuildTasks.slnf" (Build target) (1:2) ->
>        "D:\a\_work\1\s\src\Controls\src\Xaml\Controls.Xaml.csproj" (default target) (4:39) ->
>        "D:\a\_work\1\s\src\Controls\src\Xaml\Controls.Xaml.csproj" (Build target) (4:56) ->
>        "D:\a\_work\1\s\src\Controls\src\Core\Controls.Core.csproj" (default target) (3:63) ->
>        "D:\a\_work\1\s\src\Essentials\src\Essentials.csproj" (default target) (9:75) ->
>          D:\a\_work\1\s\src\Essentials\src\Compass\Compass.uwp.cs(51,4): error CS0103: The name 'OnChanged' does not exist in the current context [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj]
> ```

Thanks!

Fixed

https://github.com/dotnet/maui/pull/4615/commits/bb18d52957caa36e372aa7fc20dc2fe56167dd06

**Review by rmarinho — DISMISSED** [review]
Unit test failing 

```
Tests.Compass_Tests.Compass_IsSupported
```

**Comment by moljac** [comment]
local run (on Mac, so....):

```
X/maui/essentials-interfaces-compass %  ./bin/dotnet/dotnet build ./src/Essentials/test/UnitTests/Essentials.UnitTests.csproj 
Microsoft (R) Build Engine version 17.1.0+ae57d105c for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Essentials -> /Users/Shared/Projects/d/X/maui/essentials-interfaces-compass/src/Essentials/src/bin/Debug/net6.0/Microsoft.Maui.Essentials.dll
  Essentials.UnitTests -> /Users/Shared/Projects/d/X/maui/essentials-interfaces-compass/src/Essentials/test/UnitTests/bin/Debug/net6.0/Microsoft.Maui.Essentials.UnitTests.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:05.01
```

**Review by Redth — APPROVED** [review]

**Pull request merged**
