### PR TITLE
[Windows] Fix crash with second window and WebView

### LINKED ISSUE #7317: Windows app gets a unknown win32 error on exit
### Description

[WebViewDemos.zip](https://github.com/dotnet/maui/files/8722841/WebViewDemos.zip)

Start the ap WebVideoDemos app on Windows. Select the last 2 entries, entering and exits. Then exit the app. Upon exiting this windows app there is an unidentified win32 error.

### Steps to Reproduce

Start the ap WebVideoDemos app on Windows. Select the last 2 entries, entering and exits. Then exit the app. Upon exiting this windows app there is an unidentified win32 error.

Included video of sequence of steps to create the error.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows 10.0.19041

### Did you find any workaround?

https://user-images.githubusercontent.com/2566250/169185987-63494b05-315a-48ac-a6aa-914837f4d35d.mp4

### Relevant log output

_No response_

### LINKED ISSUE #8323: App crashes with second window and WebView
### Description

I have a seccond window with a webView. When I try to close the seccond window my app crashes. I did a workaround by removing the webView from the grid. But after I close the seccond window I can't use `DisplayAlert`. 

### Steps to Reproduce

1. Create two windows in Maui
2. In the first window put a button that will open the seccond window.
3. In the seccond window put a webView
4. Run the program and open the seccond window
5. Try to close the program and obsere the bug.

Expected: The seccond window closes and you can still use the first window
What happend: The application crashed.

### Version with bug
 
6.0.400-preview.22301.10

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 11

### Did you find any workaround?

Removed the webView before closing the window. 

```shell
MainGrid.Clear();
while (MainGrid.Children.Count > 0)
{
    await Task.Delay(500);
}
await Task.Delay(1250);

Application.Current.CloseWindow(GetParentWindow());
```

Edit: The app will crash if you use DisplayAlert after closing the window.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix crash with second window and WebView on Windows.

### Issues Fixed

Fixes #8323 
Fixes #7317

### CODE REVIEW

**Comment by namazso** [comment]
Note that this is not quite the universal fix, the issue will resurface every time there's two threadpooltimers that are left to the GC to clean up. WebView just happens to be one of the offenders. Allocations of now unloaded modules should be considered leaked already, instead of turning the language into C.

**Comment by rmarinho** [comment]
Can we add a device test ?

**Comment by jsuarezruiz** [comment]
To help focus and move faster, we're going to have fewer open PRs and focus on the ones we'll be working on in each release. This PR is not included in the next release so I close it for now. I will reopen it and adapt to changes later.

**Comment by namazso** [comment]
I hope the crashing will be listed as a feature for WebViews at least for next release, was kind of hard to track down this easter egg of a feature.

**Comment by BlueHippoGithub** [comment]
Any updates on when the fix is being released?

**Pull request closed without merging**
