### PR TITLE
Use .NET 6 built-in dotnet format tool

### PR DESCRIPTION
**Pull request by jfversluis**
### Description of Change

Fixes the daily code formatting tool by switching to the dotnet format that now lives inside of .NET 6!

### Issues Fixed

NA

### CODE REVIEW

**Comment by jfversluis** [comment]
@rmarinho this sort of fixes it. Apparently, dotnet format is now [part of .NET 6](https://github.com/dotnet/format/issues/1268).

Did we only fix whitespaces before as well, or did it do some other things? 

I have to specify it as a folder, because if we want to use it on the sln file, we need to install the .NET MAUI workload first which might be a bit too much? Maybe that will be different when .NET MAUI is available in .NET 6 stable.

There is something strange going on though. I don't understand this change here for instance: https://github.com/jfversluis/maui/pull/1/files#diff-04c5349477de806e86b983289641cfe4b2e5b1a2e899987ca73a74caeaab572e

**Comment by rmarinho** [comment]
it wasn't just white space I think , it organized usings and a couple of other things, isn't it possible to just use the editorconfig file ?

**Comment by jfversluis** [comment]
I think it still does, maybe we just don't have usings that need to be fixed? 😅

I will have a closer look at that part

**Comment by rmarinho** [comment]
Yeah I committed a big pr with fixes the other day https://github.com/dotnet/maui/pull/6242

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
