### PR TITLE
[iOS] Fix for Single item alignment issue in CollectionView HorizontalGrid Layout

### LINKED ISSUE #25181: [IOS] CollectionView with HorizontalGrid Layout did not align single item properly.
### Description

The CollectionView with a horizontal grid layout does not arrange the first child at the start position. Instead, it places the child in the center.

### Steps to Reproduce

1. Run the attached sample.
2. if only one item is present , it is placed in center.
3. Added another item, then the child is arranged properly.

### Link to public reproduction project repository

https://github.com/NirmalKumarYuvaraj/MauiIssues/tree/CVSingleItemVerticalAlignmentIssue

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

IOS

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Tamilarasan-Paranthaman**
### Root Cause of the issue 

The CollectionView seems to centre the item if only one exists. We had already adjusted the `HorizontalAlignment` for the `VerticalGrid` layout when a single element was in view. However, we missed making the same adjustment for the `HorizontalGrid` layout.

### Description of Change
 
I have applied the same adjustment to the horizontal grid layout as was done for the vertical grid layout.

### Issues Fixed

Fixes #25181

### Tested the behaviour in the following platforms

- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Screenshot

| Before Issue Fix | After Issue Fix |
|----------|----------|
|  |  |

### CODE REVIEW

**Review by PureWeen — CHANGES_REQUESTED** [review]
SingleItemAlignmentInCollectionViewHorizontalGridLayout is failing

**Comment by Tamilarasan-Paranthaman** [comment]
> SingleItemAlignmentInCollectionViewHorizontalGridLayout is failing

@PureWeen, I added this test for this issue. There seems to be a slight difference between the previously committed image and the current one generated by the CI. However, the current image is correct, so I have committed it.

**Review by rmarinho — DISMISSED** [review]

**Review by rmarinho — CHANGES_REQUESTED** [review]
The test is failing for CV1 seems the layout is expanding below the status bar and we cut that off for the test ? or do we need to regenerate images? 

image

Original screenshot full screen 

image

**Comment by Tamilarasan-Paranthaman** [comment]
> The test is failing for CV1 seems the layout is expanding below the status bar and we cut that off for the test ? or do we need to regenerate images?
> 
> image
> 
> Original screenshot full screen
> 
> image

@rmarinho, Yes, it is expanding below the status bar, and it seems the CI did not account for that space. I have modified the test sample to address this by wrapping the CollectionView in a StackLayout, and it now passes both CV1 and CV2 on my end. Could you please review it and let me know if you have any concerns?

**Comment by rmarinho** [comment]
Nop wrapping a CollectionView on a StackLayout is not a good practice. Try use a Grid instead.

**Comment by Tamilarasan-Paranthaman** [comment]
> Nop wrapping a CollectionView on a StackLayout is not a good practice. Try use a Grid instead.

@rmarinho, thank you for pointing this out! I have replaced the StackLayout with a Grid as suggested, and it worked as expected during my testing. Could you please check and let me know if you have any further concerns?

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
