### PR TITLE
WinUI3 Interop for share and file picker

### LINKED ISSUE #2102: [Bug] FilePicker throws System.InvalidOperationException: 'Window Not Found'
### Description
In maui preview7 on android, whenever call `FilePicker.PickAsync();` method the maui application will throw `System.InvalidOperationException: 'Window Not Found'` and crash. 

### Steps to Reproduce

1. create a new maui app using default maui templat
2. setup permissions and call platform init on android
3. add `await FilePicker.PickAsync();`  in button onclick event handler and start debug
4. click the button

### Expected Behavior
the filepicker shows up

### Actual Behavior
the filepicker shows up, then the app throws `System.InvalidOperationException: 'Window Not Found'` and crash.

### Basic Information

- Version with issue: maui preview7
- Last known good version: maui preview6
- IDE: VIsual Studio 2022 preview 3
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:android

### Screenshots
image

### Reproduction Link
https://github.com/Chronostasys/ButtonTest

### PR DESCRIPTION
**Pull request by jamesmontemagno**
### Description of Change ###

Implements new interop pattern to access window and specific services. 

Fixes #2102, #1113, #2194, #1672

### PR Checklist ###

- [ ] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [ ] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [ ] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [ ] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- [ ] Does this PR introduce a new control? (If yes, add an example using SemanticProperties to the SemanticsPage)
- [ ] APIs that modify focusability?
- [ ] APIs that modify any text property on a control?
- [ ] Does this PR modify view nesting or view arrangement in anyway?
- [ ] Is there the smallest possibility that your PR will change accessibility? 
- [ ] I'm not sure, please help me

If any of the above checkboxes apply to your PR, then the PR will need to provide testing to demonstrate that accessibility still works.

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
I am somewhere aroudn 99% sure this all sshoudl work, but i wasn't able to run the test app locally to verify.

My biggest concern is var hwnd = WinRT.Interop.WindowNative.GetWindowHandle(Platform.CurrentWindow); but I think it is right.

**Comment by jamesmontemagno** [comment]
@dotMorten  how do you feel about this code....?

**Comment by dotMorten** [comment]
@jamesmontemagno Not great at all, but none of that is your fault :-) Perhaps @adambraden and @marb2000 might have something better to say about this.

**Comment by marb2000** [comment]
Using WinRT.Interop.WindowNative.GetWindowHandle is correct to get the Hwnd in WinAppSDK Preview 3, although I don't know what type will return in Desktop Platform.CurrentWindow. 
```
 var hwnd = WinRT.Interop.WindowNative.GetWindowHandle(Platform.CurrentWindow); 
```
It works if it's a Microsoft.UI.Xaml.Window object.

**Comment by jamesmontemagno** [comment]
it should be the current window object -> https://github.com/dotnet/maui/blob/main/src/Essentials/src/Platform/Platform.uwp.cs

**Comment by dotMorten** [comment]
That seems dangerous then. What if it's a different window that initiates this code?

**Comment by jamesmontemagno** [comment]
It would always be from the Activated Window currently -> https://github.com/dotnet/maui/blob/main/src/Essentials/src/Platform/Platform.uwp.cs#L33

However I could see a platform specific here for sure. I'll add that in.

**Comment by AdamBraden** [comment]
adding @angelazhangmsft as FYI to track interop improvements.

**Comment by joshfourbadideas** [comment]
Now that VS2022 has dropped and we're almost out of preview for MAUI v1 can we get this fix checked in?  Just started converting an app and this is beyond frustrating that these simple fixes haven't landed for such core functionality.

**Review by Redth — APPROVED** [review]

**Comment by Magic73** [comment]
I tried FilePicker and Share on Windows 10, local deploy (Maui+ Blazor) and none of them works.

Visual Studio 2022 17.1.0 Preview 2

When using Share:

`return Share.RequestAsync(new ShareFileRequest
            {
                Title = "test",
                File = new ShareFile(filePath, "application/pdf")
            });`

`Exception: System.Runtime.InteropServices.COMException (0x80070490): Element not found. (0x80070490) at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr) at ABI.Windows.ApplicationModel.DataTransfer.IDataTransferManagerStaticsMethods.GetForCurrentView(IObjectReference _obj) at Microsoft.Maui.Essentials.Share.PlatformRequestAsync(ShareMultipleFilesRequest request) at...`

When using FilePicker:

` var pickResult = await FilePicker.PickAsync(new PickOptions
            {
                FileTypes = FilePickerFileType.Images, 
                PickerTitle = "test"
            }).ConfigureAwait(false);`

`Exception: System.Runtime.InteropServices.COMException (0x80070578): Invalid window handle. (0x80070578) Consider WindowNative, InitializeWithWindow See https://aka.ms/cswinrt/interop#windows-sdk at Microsoft.Maui.Essentials.FilePicker.PlatformPickAsync(PickOptions options, Boolean allowMultiple) at Microsoft.Maui.Essentials.FilePicker.PickAsync(PickOptions options) at`

**Comment by jamesmontemagno** [comment]
@Magic73  can you open a new issue for this. Seems like something else is broken as it was working for Share.

**Pull request merged**
