### PR TITLE
Remove the confusing `.` in the template tests

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change

Just making life a bit easier without weird dots making the build look like something went wrong.

### CODE REVIEW

**Comment by rmarinho** [comment]
I think this was added to actually test something. are we fine removing it @Eilon  ?

**Comment by Eilon** [comment]
Hmm I'm not sure what exactly this part of the test is doing (it looks quite different from last time I changed it). But, @rmarinho might be onto something: a long, loooooong time ago I updated the test to use "weird" characters to make sure that when the template was created, that the "weird" characters were correctly substituted in the template. For example, if you do `dotnet new maui -o Funny.Dot-Dash_Name` the template has to be authored correctly to ensure it gets created as something like `Funny_Dot_Dash_Name` or something like that. I don't remember the rules, but the key thing is that even with "weird" characters you should get a valid compilable template output.

**Comment by Eilon** [comment]
Oops clicked wrong button somehow. Re-opened.

**Comment by Eilon** [comment]
????????? Apparently Ctrl+Enter closes PRs?? That must be new...

**Comment by rmarinho** [comment]
@mattleibow  what does this fix btw?

**Comment by Eilon** [comment]
@mattleibow can you confirm that the template test still tries to create templates that have dots in the name? I think that's what the test was doing, but I'm not familiar with what this change affects.

**Comment by Eilon** [comment]
Looks like we never had dots, but at one point I added dashes and spaces: https://github.com/dotnet/maui/pull/2368/files#diff-f987df2e4d48c04c42bb417e36d0d8b1fa9ddd29f10459c98f16d7b9b10f47c5R112

I think as long as a few oddities are used, that covers just about everything, because there are only a few substitution variables allowed depending on whether it's a type name, filename, etc.

**Pull request merged**
