### PR TITLE
[iOS] CarouselView: Changing Position after navigation away then comi…

### LINKED ISSUE #23291: CarouselView - iOS - Changing Position no longer works after navigation away then coming back
### Description

On iOS, programmatically changing the `Position` of the CarouselView no longer works if you navigate away and come back when using Shell navigation.

Android works fine.

EDITED: Tested using NavigationPage instead of Shell navigation, and the issue still exists.

### Steps to Reproduce

1. Run the project
2. Tap the bottom buttons to see the CarouselView switch between fragments.
3. Tap the Open Second Page button
4. Tap the Back button at the top left.
5. Tap the bottom buttons again.

### Link to public reproduction project repository

https://github.com/ryanalford-suzy/CarouselViewTest

### Version with bug

8.0.60 SR6

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.40 SR5

### Affected platforms

iOS

### Affected platform versions

iPhone - iOS 16.7.7, iOS Simulator 17.4 

### Did you find any workaround?

No workaround

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/23291

https://github.com/dotnet/maui/assets/42434498/5b4dde5c-df18-4646-a60b-0bfd67bed0da

### CODE REVIEW

**Review by rmarinho — CHANGES_REQUESTED** [review]
Seems the test is failing on Windows. 

```
https://dev.azure.com/xamarin/public/_build/results?buildId=118983&view=ms.vss-test-web.build-test-results-tab
```

**Review by rmarinho — APPROVED** [review]
Fixed a NRE on windows keeping the test from loading

**Comment by kubaflo** [comment]
Thanks! @rmarinho

**Pull request merged**
