### PR TITLE
Fix filename case sensitivity

### PR DESCRIPTION
**Pull request by moljac**
### Description of Change

Fixing filesystem casing issues in the repo:

Error 1:

```
dotnet build src/Compatibility/ControlGallery/test/Android.UITests/
```

```
CSC : error CS2001: Source file './src/Compatibility/ControlGallery/src/Issues.Shared/Issue3262.cs' could not be found. [./src/Compatibility/ControlGallery/test/Android.UITests/Compatibility.ControlGallery.Android.UITests.csproj]
```

### Issues Fixed

None. Working on some other PRs and unit tests are failing.

### CODE REVIEW

**Comment by moljac** [comment]
Errors:


```
2023-11-07T10:07:22.1279525Z   Core.DeviceTests.Shared -> D:\a\_work\1\s\src\Core\tests\DeviceTests.Shared\bin\Release\net8.0-windows10.0.19041\Microsoft.Maui.DeviceTests.Shared.dll
2023-11-07T10:07:22.9070391Z D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rc.2.23502.2\Microsoft.Common.CurrentVersion.targets(4725,5): error MSB3027: Could not copy "obj\Release\netstandard2.0\Microsoft.Maui.Graphics.Text.Markdig.dll" to "bin\Release\netstandard2.0\Microsoft.Maui.Graphics.Text.Markdig.dll". Exceeded retry count of 10. Failed.  [D:\a\_work\1\s\src\Graphics\src\Text.Markdig\Graphics.Text.Markdig.csproj]

... snip ...

2023-11-07T10:31:38.9228286Z D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rc.2.23502.2\Microsoft.Common.CurrentVersion.targets(4725,5): error MSB3027: Could not copy "obj\Release\netstandard2.0\Microsoft.Maui.Graphics.Text.Markdig.dll" to "bin\Release\netstandard2.0\Microsoft.Maui.Graphics.Text.Markdig.dll". Exceeded retry count of 10. Failed.  [D:\a\_work\1\s\src\Graphics\src\Text.Markdig\Graphics.Text.Markdig.csproj]
2023-11-07T10:31:38.9234909Z D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rc.2.23502.2\Microsoft.Common.CurrentVersion.targets(4725,5): error MSB3021: Unable to copy file "obj\Release\netstandard2.0\Microsoft.Maui.Graphics.Text.Markdig.dll" to "bin\Release\netstandard2.0\Microsoft.Maui.Graphics.Text.Markdig.dll". The requested operation cannot be performed on a file with a user-mapped section open. : 'D:\a\_work\1\s\src\Graphics\src\Text.Markdig\bin\Release\netstandard2.0\Microsoft.Maui.Graphics.Text.Markdig.dll' 
```

**Comment by rmarinho** [comment]
Should we rename the file instead?

**Comment by rmarinho** [comment]
> Errors:
> 
> ```
> 2023-11-07T10:07:22.1279525Z   Core.DeviceTests.Shared -> D:\a\_work\1\s\src\Core\tests\DeviceTests.Shared\bin\Release\net8.0-windows10.0.19041\Microsoft.Maui.DeviceTests.Shared.dll
> 2023-11-07T10:07:22.9070391Z D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rc.2.23502.2\Microsoft.Common.CurrentVersion.targets(4725,5): error MSB3027: Could not copy "obj\Release\netstandard2.0\Microsoft.Maui.Graphics.Text.Markdig.dll" to "bin\Release\netstandard2.0\Microsoft.Maui.Graphics.Text.Markdig.dll". Exceeded retry count of 10. Failed.  [D:\a\_work\1\s\src\Graphics\src\Text.Markdig\Graphics.Text.Markdig.csproj]
> 
> ... snip ...
> 
> 2023-11-07T10:31:38.9228286Z D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rc.2.23502.2\Microsoft.Common.CurrentVersion.targets(4725,5): error MSB3027: Could not copy "obj\Release\netstandard2.0\Microsoft.Maui.Graphics.Text.Markdig.dll" to "bin\Release\netstandard2.0\Microsoft.Maui.Graphics.Text.Markdig.dll". Exceeded retry count of 10. Failed.  [D:\a\_work\1\s\src\Graphics\src\Text.Markdig\Graphics.Text.Markdig.csproj]
> 2023-11-07T10:31:38.9234909Z D:\a\_work\1\s\bin\dotnet\sdk\8.0.100-rc.2.23502.2\Microsoft.Common.CurrentVersion.targets(4725,5): error MSB3021: Unable to copy file "obj\Release\netstandard2.0\Microsoft.Maui.Graphics.Text.Markdig.dll" to "bin\Release\netstandard2.0\Microsoft.Maui.Graphics.Text.Markdig.dll". The requested operation cannot be performed on a file with a user-mapped section open. : 'D:\a\_work\1\s\src\Graphics\src\Text.Markdig\bin\Release\netstandard2.0\Microsoft.Maui.Graphics.Text.Markdig.dll' 
> ```

This is an issue that we see happening a lot on CI. Retry the build normally fixes it .. But if you find out what causes it , that would be awesome.

**Comment by moljac** [comment]
> Should we rename the file instead?

Well, it is up to ypu guys. I went easy way.

**Comment by moljac** [comment]
> This is an issue that we see happening a lot on CI. Retry the build normally fixes it .. But if you find out what causes it , that would be awesome.

@rmarinho 
I think it is caused by parallel builds. It would be good to make project dependency graph and to deparallelize/serialize-sequentialize it.

Smells like

https://github.com/xamarin/xamarin-android/blob/8928f1168a74f9edad705f4851f3e9252a64f90e/src/r8/r8.csproj#L11-L15

But I am not expert on MsBuild

**Review by mattleibow — APPROVED** [review]

**Pull request merged**
