### PR TITLE
Workaround VS Bug with using dotnet 7 workloads

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

Apply this fix via the cake command
https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/InstallBuildsFromMain.md#using-visual-studio

### CODE REVIEW

**Comment by mattleibow** [comment]
This should be done in dotnet.csproj maybe?

**Comment by mattleibow** [comment]
Why does VS need something special? is there a difference between the ide and our stuff?

**Comment by jonathanpeppers** [comment]
This was something I discovered and wrote down here:

https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/InstallBuildsFromMain.md#using-visual-studio

@dsplaisted @marcpopMSFT I'm not sure how the workload resolver is updated in Visual Studio. Does the one that is in there now need to be updated?

**Comment by PureWeen** [comment]
@mattleibow the fix also has to be applied after the pack powershell script runs so I think it's just easier to leave this in cake for now.

**Comment by marcpopMSFT** [comment]
@joeloff I believe you did the work for preview workload versions. Is fallback not working with preview workloads? Seems like they are having to copy the files into the 7.0.100 folder from the preview folder which shouldn't be necessary.

@jonathanpeppers  the workload resolver gets updated as part of the SDK insertion into VS.

**Comment by joeloff** [comment]
I updated the Arcade tooling for that so that the manifest installers would generate stable upgrade codes that allowed SxS installs for previews in feature bands.

**Comment by dsplaisted** [comment]
@marcpopMSFT We did the resolver work in the .NET 7 branch, so I imagine it hasn't been inserted into VS 17.3.  If possible, we probably should try to insert the .NET 7 workload resolver into VS 17.3.

**Comment by mattleibow** [comment]
You will need to test after this PR gets merged: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/407789

I am using that build and it seems to be OK.

**Pull request closed without merging**
