### PR TITLE
[Core,Controls] Remove legacy Log and use ILogger

### LINKED ISSUE #883: [Enhancement] Rework LogListener to use new loggers
## Summary
Rework LogListener to use new loggers

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change ###

Remove the old Logger since it was internal, use the new ILogger everywhere

Implements #883

### Additions made ###

None

### PR Checklist ###

- [ ] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [ ] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [ ] Adds the mapping method to the WinUI, Android, iOS, and Standard aspects of the handler
- [ ] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- [ ] Does this PR introduce a new control? (If yes, add an example using SemanticProperties to the SemanticsPage)
- [ ] APIs that modify focusability?
- [ ] APIs that modify any text property on a control?
- [ ] Does this PR modify view nesting or view arrangement in anyway?
- [ ] Is there the smallest possibility that your PR will change accessibility? 
- [ ] I'm not sure, please help me

If any of the above checkboxes apply to your PR, then the PR will need to provide testing to demonstrate that accessibility still works.

### CODE REVIEW

**Comment by Eilon** [comment]
The code change looks good in terms of moving from legacy to new logging.

One feature that some folks might not be aware of is that there is a feature of MS.Extensions.Logging for parameterized log messages that works with loggers that support "dictionary data" (and not just string messages, like Console logger).

You can do a call like this:

```c#
SomeLogger.Log($"The value {value} was bad, and it should be good like {someGoodValue}.");
```

And that will successfully log a string such as `The value BOO was bad, and it should be good like YAY😁.`.

That's certainly fine, but if you avoid the interpolated string (`$"blah {interpolated_value}"`) you can use MS.Ext.Logging's data formatting:

```c#
SomeLogger.Log("The value {Value} was bad, and it should be good like {GoodValue}.", value, someGoodValue);
```

And depending on the logger, it would log two separate things:

1. The formatted string value, just like before: `The value BOO was bad, and it should be good like YAY😁.`
2. And _also_ a dictionary of data values for the string/value pairs:
   ```
   Value = "BOO"
   GoodValue = "YAY😁"
   ```

So for a fancier logger such as SeriLog (depending on its sink), you could store those log values in a database of some sort and query on them (e.g. `find all logs in category X with GoodValue Contains 'YAY'`.

You can learn more about it here: https://docs.microsoft.com/dotnet/core/extensions/logging?tabs=command-line#log-message-template

I'm not at all saying this PR should include any such change, but it's something to consider in cases where it could prove more valuable to have actual data in the logs and not just strings.

**Review by Eilon — APPROVED** [review]

**Comment by rmarinho** [comment]
Thats a great suggestion @Eilon  i didn't know about that. 
Thanks

**Comment by Eilon** [comment]
> Use parameterized log messages

Very nice 😄

**Pull request merged**
