### PR TITLE
[Core] Fix issue not finding IAnimationManager

### LINKED ISSUE #3353: Unable to find IAnimationManager for 'Microsoft.Maui.Controls
### Steps to Reproduce

1. Add animation in view 
2. Call the animation method in  main view (animation view added in main view)touch event 
2. Add main view in xaml
3. Crash Occur like below
Unable to find IAnimationManager for 'Microsoft.Maui.Controls 

### Expected Behavior

Animation will work

### Actual Behavior

Crash Occur

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix issue not finding IAnimationManager.

`System.ArgumentException: Unable to find IAnimationManager for 'Microsoft.Maui.Controls.Label'. (Parameter 'animatable')`

fix-3353

Thanks @enisn for your sample. It helped me understand what was going on.

### Issues Fixed

Fixes #3353

### CODE REVIEW

**Review by Redth — APPROVED** [review]

**Review by mattleibow — CHANGES_REQUESTED** [review]
The Animation manager comes from the services and should not just be created. The Application context should always have an animation manager, does it not sometimes?

**Comment by jsuarezruiz** [comment]
> > Actually, the error so far is that the Context in the control is not set yet. In this case, using the Application context is always enough.
> 
> Yeah, the only time that you don't have an Application instance is during the building phase, and then that is an invalid case as lots of other things will crash.

@mattleibow Updated the PR. Could you review it again?. Thanks.

**Review by mattleibow — APPROVED** [review]

**Comment by PaulAnderson02** [comment]
When this fix will be available. No milestone added for this

**Comment by Sebosek** [comment]
When this fix has been released? I can see the same bug as is reported in https://github.com/dotnet/maui/issues/3353, with a small difference; if an animation is called from within the PropertyChanged event handler, which is called BEFORE the Loaded event handler. Workaround is pretty much the same. The code is taken from the user control (inherited from Grid).

```
    private async void OnPropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (!_loaded) return; // Workaround ...
        
        var animation = new Animation(...);
        animation.Commit(this, ...);
    }

    private void OnLoaded(object? sender, EventArgs e)
    {
        _loaded = true;
    }
```

**Comment by mattleibow** [comment]
The behaviour is actually correct because there may not be an animation manager. You are trying to animate a view that may not be on screen yet. It may just be in memory as those property changed events fire during the constructor.

Can you open a feature request and we can maybe investigate some sort of proxy that queues up animations, but this is also interesting as it may cause issues if you initiate conflicting animations because it will be hard to support await like that.

**Pull request merged**
