### PR TITLE
Add LinkMode command to support XAML Hot Reload for iOS Devices

### LINKED ISSUE #8429: Add MtouchLink command to support XAML Hot Reload for iOS Devices
The default net6.0-ios SDK commands for debug mode on iOS devices sets it up to link to the SDK. That removes some required commands that let XAML Hot Reload work. While there is an error bar telling you what to do, we can change the template to allow it to work right the first time. If a user does change it, the error will still be there, and they can either change it back or ignore it.

### PR DESCRIPTION
**Pull request by drasticactions**
The default net6.0-ios SDK commands for debug mode on iOS devices sets it up to link to the SDK. That removes some required commands that let XAML Hot Reload work. While there is an error bar telling you what to do, we can change the template to allow it to work right the first time. If a user does change it, the error will still be there, and they can either change it back or ignore it.

Adding @dalexsoto and @rolfbjarne to make sure I got the commands right.

### CODE REVIEW

**Review by rolfbjarne — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Comment by mattleibow** [comment]
This fells like something that should be in the ios targets. Not  sure what is more expensive - linking or copying more files to the device.

**Comment by Redth** [comment]
Few thoughts:

- What's the dev loop difference between the current default, and setting linking to none?  My hypothesis is that None is faster, is this true?
- If None is faster, I would tend to agree this should be the Debug default in the iOS targets, not an opinionated default exclusive to MAUI projects
- If there's anything to be gained by keeping the current default, can we look at custom linker steps or some way to explicitly _keep_ the hot reload bits for Debug builds?

**Review by mattleibow — CHANGES_REQUESTED** [review]
Not supported on iOS
https://github.com/xamarin/xamarin-macios/issues/15382

Will have to set the other one

**Comment by mattleibow** [comment]
Superseded by https://github.com/dotnet/maui/pull/8450

**Pull request closed without merging**
