### PR TITLE
Background gradients fixes

### LINKED ISSUE #25193: Background gradients don't work for some views
### Description

The following code:
```
    <VerticalStackLayout>

        <Label Text="Label: "/>
        <Label
            Text="Hello, Maui!"
            AutomationId="label">
            <Label.Background>
                <LinearGradientBrush EndPoint="1,0">
                    <GradientStop Color="Red"
                                  Offset="0.7"/>
                    <GradientStop Color="Green"
                                  Offset="1.0"/>
                </LinearGradientBrush>
            </Label.Background>
        </Label>

        <Label Text="Button: "/>
        <Button Text="Hello, Maui!">
            <Button.Background>
                <LinearGradientBrush EndPoint="1,0">
                    <GradientStop Color="Blue"
                                  Offset="0.7"/>
                    <GradientStop Color="Yellow"
                                  Offset="1.0"/>
                </LinearGradientBrush>
            </Button.Background>
        </Button>

        <Label Text="Entry: "/>
        <Entry Text="Hello, Maui!">
            <Entry.Background>
                <LinearGradientBrush EndPoint="1,0">
                    <GradientStop Color="Pink"
                                  Offset="0.7"/>
                    <GradientStop Color="Lime"
                                  Offset="1.0"/>
                </LinearGradientBrush>
            </Entry.Background>
        </Entry>

        <Label Text="Picker: "/>
        <Picker
            Title="Hello, Maui!">
            <Picker.Background>
                <LinearGradientBrush EndPoint="1,0">
                    <GradientStop Color="Brown"
                                  Offset="0.7"/>
                    <GradientStop Color="Gold"
                                  Offset="1.0"/>
                </LinearGradientBrush>
            </Picker.Background>
        </Picker>


        <Label Text="Scroll view: "/>
        <ScrollView Orientation="Horizontal"
                    HeightRequest="100">
            <ScrollView.Background>
                <LinearGradientBrush StartPoint="0,0.5"
                                     EndPoint="1,0.5">
                    <LinearGradientBrush.GradientStops>
                        <GradientStop Color="Orange"
                                      Offset="0.75"/>
                        <GradientStop Color="Purple"
                                      Offset="1"/>
                    </LinearGradientBrush.GradientStops>
                </LinearGradientBrush>
            </ScrollView.Background>

            <Border WidthRequest="1200"/>
        </ScrollView>

    </VerticalStackLayout>
```
gives the following results on iOS

### Steps to Reproduce

_No response_

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.91 SR9.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

_No response_

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/25193

|Before|After|
|--|--|
|||

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
Added test snapshots. Triggering a new build.

**Review by jsuarezruiz — APPROVED** [review]

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
