### PR TITLE
[Android] Update Entry behavior closing the Keyboard

### LINKED ISSUE #6933: Android Entry control is covered by keyboard or the wrong Entry control is moved up to be visible.
### Description

In XF, the Entry control lost focus when the Android soft keyboard was closed with the back button.  In MAUI this is no longer the case, which is a bug.

### Steps to Reproduce

1. Compile and run the repro sample under Android 11.
2. click on the text "click me" so that the soft keyboard opens and "click me" has a flashing cursor.
3. click the "back" button to close the keyboard.
4. Note that "click me" still has a flashing cursor.  Also, noteFilter_Unfocused is not called.  If I press back again in order to place the entire app in the background, then noteFilter_Unfocused is called.

When closing the soft keyboard, noteFilter_Unfocused should be called AND the Entry control should no longer display the flashing cursor.  This worked properly in XF so this is a regression in MAUI.

[layoutbug9.zip](https://github.com/dotnet/maui/files/8646664/layoutbug9.zip)

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

No

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Update Android Entry behavior closing the Keyboard. Like in Xamarin.Forms, the Entry lost focus when the Android soft keyboard is closed with the back button.

### Issues Fixed

Fixes #6933

### CODE REVIEW

**Comment by jfversluis** [comment]
@jsuarezruiz note that this also impacts pickers. I think since they use Entries it should be fine, but maybe double-check? See #6933

**Comment by philipag** [comment]
@jfversluis, @PureWeen, @rachelkang Can one of you please review and approve this PR?  It's a show stopper for releasing a production app using Maui...

**Review by PureWeen — CHANGES_REQUESTED** [review]
https://github.com/dotnet/maui/issues/6933#issuecomment-1236381789

**Comment by PureWeen** [comment]
> [#6933 (comment)](https://github.com/dotnet/maui/issues/6933#issuecomment-1236381789)

Based on my comment and no additional information with regards to what this is fixing. I'm going to close this PR for now. We can revisit once we add additional Keyboard APIs

**Pull request closed without merging**
