### PR TITLE
Hide maui templates in VS 17.0 and lower

### PR DESCRIPTION
**Pull request by japarson**
### Description of Change ###
Maui project and item templates are appearing in VS 2019 when the Maui workload is installed in VS 2022. This is a SxS issue that can be resolved by modifying the templates to not support hosts < 17.1.

Implements [Bug 1442551: [XVS][SXS]There is Maui project on VS 2019](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1442551)

### Additions made ###
- Adds `unsupportedHosts` to maui-blazor ide.host.json.
- Adds `unsupportedHosts` to maui-contentpage-csharp ide.host.json.
- Adds `unsupportedHosts` to maui-contentpage-xaml ide.host.json.
- Adds `unsupportedHosts` to maui-contentview-csharp ide.host.json.
- Adds `unsupportedHosts` to maui-contentview-xaml ide.host.json.
- Adds `unsupportedHosts` to maui-lib ide.host.json.
- Adds `unsupportedHosts` to maui-mobile ide.host.json.

### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [ ] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [ ] Adds the mapping method to the WinUI, Android, iOS, and Standard aspects of the handler
- [ ] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- [ ] Does this PR introduce a new control? (If yes, add an example using SemanticProperties to the SemanticsPage)
- [ ] APIs that modify focusability?
- [ ] APIs that modify any text property on a control?
- [ ] Does this PR modify view nesting or view arrangement in anyway?
- [ ] Is there the smallest possibility that your PR will change accessibility? 
- [ ] I'm not sure, please help me

If any of the above checkboxes apply to your PR, then the PR will need to provide testing to demonstrate that accessibility still works.

### CODE REVIEW

**Review by Eilon — APPROVED** [review]
This _looks_ good to me, but I'll defer to @phenning who knows more about templates than I do!

**Comment by japarson** [comment]
> This _looks_ good to me, but I'll defer to @phenning who knows more about templates than I do!

I actually haven't been able to verify that this fix works locally yet. I'm having some issues building the repo unfortunately.

**Comment by Eilon** [comment]
BTW building just the templates involves going to `src\Templates` and running `pwsh .\build.ps1` (pwsh == PowerShell). That should build and install the templates with `dotnet new`.

**Review by phenning — CHANGES_REQUESTED** [review]
Unsupported hosts should be in ide.host.json not in the template.json

**Review by jsuarezruiz — APPROVED** [review]

**Review by phenning — APPROVED** [review]
:shipit:

**Review by Eilon — APPROVED** [review]

**Comment by Eilon** [comment]
Thank you @japarson and @phenning !

**Pull request merged**
