### PR TITLE
Add unit test for button images in layouts

### PR DESCRIPTION
**Pull request by molesmoke**
### Description of Change

Adds a skipped test for #21548 due to a regression caused by #20949

### Issues Fixed

None, somebody else will need to fix the actual issue, but it can at least prevent future regressions

### CODE REVIEW

**Comment by jeremy-visionaid** [comment]
@Foda Hope a device test is helpful, even if I don't know how to fix the actual issue without just reverting previous changes

**Comment by mattleibow** [comment]
I removed the skip so we can see if our latest changes have fixed it. 
Namely: https://github.com/dotnet/maui/pull/21737

**Comment by mattleibow** [comment]
Forgot to run the tests

**Review by jsuarezruiz — APPROVED** [review]

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
