### PR TITLE
Essentials.Browser refactored to interface and singleton

### PR DESCRIPTION
**Pull request by moljac**
### Description of Change ###

Implements #

```csharp
	public interface IBrowser
	{
		Task OpenAsync(string uri);

		Task OpenAsync(string uri, BrowserLaunchMode launchMode);
			
		Task OpenAsync(string uri, BrowserLaunchOptions options);

		Task OpenAsync(Uri uri);

		Task OpenAsync(Uri uri, BrowserLaunchMode launchMode);

		Task<bool> OpenAsync(Uri uri, BrowserLaunchOptions options);
	}
```

### Additions made ###

* Adds 

### PR Checklist ###

- [ ] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [ ] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [ ] Adds the mapping method to the WinUI, Android, iOS, and Standard aspects of the handler
- [ ] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- [ ] Does this PR introduce a new control? (If yes, add an example using SemanticProperties to the SemanticsPage)
- [ ] APIs that modify focusability?
- [ ] APIs that modify any text property on a control?
- [ ] Does this PR modify view nesting or view arrangement in anyway?
- [ ] Is there the smallest possibility that your PR will change accessibility? 
- [ ] I'm not sure, please help me

If any of the above checkboxes apply to your PR, then the PR will need to provide testing to demonstrate that accessibility still works.

### CODE REVIEW

**Review by rmarinho — CHANGES_REQUESTED** [review]
Build is failing.

```
  D:\a\_work\1\s\src\Essentials\src\Browser\Browser.uwp.cs(6,47): error CS0736: 'BrowserImplementation' does not implement instance interface member 'IBrowser.OpenAsync(Uri, BrowserLaunchOptions)'. 'BrowserImplementation.OpenAsync(Uri, BrowserLaunchOptions)' cannot implement the interface member because it is static. [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj]
```

**Comment by moljac** [comment]
> Build is failing.
> 
> ```
>   D:\a\_work\1\s\src\Essentials\src\Browser\Browser.uwp.cs(6,47): error CS0736: 'BrowserImplementation' does not implement instance interface member 'IBrowser.OpenAsync(Uri, BrowserLaunchOptions)'. 'BrowserImplementation.OpenAsync(Uri, BrowserLaunchOptions)' cannot implement the interface member because it is static. [D:\a\_work\1\s\src\Essentials\src\Essentials.csproj]
> ```

Hi!

Working on Mac. So sorry. There will be some windows errors.

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
