### PR TITLE
[Controls.Core] Handle Null Values for AdaptiveTrigger

### LINKED ISSUE #7242: [Windows] [Scenario Day] Adaptive Trigger on StackLayout crashes  Windows.
### Description

Following https://docs.microsoft.com/en-us/dotnet/maui/fundamentals/triggers, setting up an adaptive triggers on StackLayout crashes the app. 

 <Style TargetType="StackLayout">
        <Setter Property="VisualStateManager.VisualStateGroups">
            <VisualStateGroupList>
                <VisualStateGroup>
                    <VisualState x:Name="Vertical">
                        <VisualState.StateTriggers>
                            <AdaptiveTrigger MinWindowWidth="0" />
                        </VisualState.StateTriggers>
                        <VisualState.Setters>
                            <Setter Property="Orientation"
                                Value="Vertical" />
                        </VisualState.Setters>
                    </VisualState>
                    <VisualState x:Name="Horizontal">
                        <VisualState.StateTriggers>
                            <AdaptiveTrigger MinWindowWidth="800" />
                        </VisualState.StateTriggers>
                        <VisualState.Setters>
                            <Setter Property="Orientation"
                                Value="Horizontal" />
                        </VisualState.Setters>
                    </VisualState>
                </VisualStateGroup>
            </VisualStateGroupList>
        </Setter>
    </Style>

### Steps to Reproduce

[MauiApp1.zip](https://github.com/drasticactions/Archiverse/files/8710339/MauiApp1.zip)

Download \\ddfiles\Team\XAML\User\chabiss\Maui\MauiApp1.zip
open the app
Run on Windows
Result:
{Microsoft.UI.Xaml.UnhandledExceptionEventArgs} | Microsoft.UI.Xaml.UnhandledExceptionEventArgs
  | ▶ Exception | {"Catastrophic failure (0x8000FFFF (E_UNEXPECTED))"} | System.Exception {System.Runtime.InteropServices.COMException}
  | Handled | false | bool
  | Message | "Microsoft.UI.Xaml.Controls.Frame.NavigationFailed was unhandled." | string

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

10.0.22000.194

### Did you find any workaround?

No so far

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by drasticactions**
### Description of Change

If `_visualElement` is null for a given VisualStateManager, it would blow up a users application because it would try to access `Window` on that null.

If we set AdaptiveTrigger to be nullable, and handle the nulls, it will avoid the blow up. Note that AdaptiveTriggers _may_ still be broken, but this will at least fix the NRE and crash.

### Issues Fixed

might help with #7242

### CODE REVIEW

**Review by mattleibow — APPROVED** [review]
Is it possible to add a test for this? You can use the Controls.UnitTests project and this should be testable from code - not needing device tests.

**Comment by drasticactions** [comment]
@mattleibow I'm not sure what to write for it. The issue is that `visualElement` inside of that method is null to start with when it shouldn't be. So right now, I think, the triggers are not firing for what _should_ be the element specified by the trigger in XAML. The CI tests work, but it doesn't work in real life, at least on WinUI.

IMO I think we need another task to try and look and the underlying issue for it and then create tests based on that. Doing it just for the null check doesn't get us much. Does that sound okay?

**Review by mattleibow — CHANGES_REQUESTED** [review]
This is not the solution as later on the trigger still crashes because at the point of activating the trigger, the visual element is still null.

Something changed with the triggers and/or VSM to no longer pass the visual element along to the triggers - thus the trigger is now invalid.

Just testing with reverting #6889 as that touches the VSM in a big-ish way.

**Comment by drasticactions** [comment]
I agree, but I still think this PR is needed as a starting point.

https://github.com/dotnet/maui/pull/7267/files#diff-93ba88349c2643c6ac2e0b53439b788bee23b22170bd4f9e4037d1952bfff99cR68-R73

Right there, we're checking if _visualElement is null, and then trying to get a property on it. That's not correct, it shouldn't try to. We already have an assumption that it could be null.

**Comment by mattleibow** [comment]
Closing this as the code somehow no longer crashes at runtime, but the issue still exists and the trigger is not functional.

**Comment by StephaneDelcroix** [comment]
> This is not the solution as later on the trigger still crashes because at the point of activating the trigger, the visual element is still null.

might not be the solution to the problem, but this fix is still valid and required. we have code that check for null VE, and then dereference it ignoring the potential nullity.

**Pull request merged**
