### PR TITLE
Set title on maui-blazor template window

### PR DESCRIPTION
**Pull request by Eilon**
### Description of Change

Fix the .NET MAUI Blazor templates to have text in the title bar.

### Issues Fixed

Fixes #25338

### CODE REVIEW

**Comment by Eilon** [comment]
Confirmed this has the right behavior in both Blazor Hybrid templates.

**Comment by rmarinho** [comment]
Do we want in GA if so please target release/9.0.1xx, or else target main for net9 sr1

**Review by PureWeen — CHANGES_REQUESTED** [review]
https://github.com/dotnet/maui/pull/25387#issuecomment-2424297026

**Comment by Eilon** [comment]
Replaced by #25426

**Pull request closed without merging**
