### PR TITLE
[.NET 6] [Blazor] Account for Maui multi-rid builds (#9348)

### LINKED ISSUE #10102: VS 17.3.4 Breaks Android build with - Manifest file at 'obj\Debug\net6.0-android\android-arm\staticwebassets.build.json' not found
### Description

Since updating to VS 17.3.4 I can't build any MAUI Android projects on my machine.

I have verified this on two devices running VS - before updating to VS 17.3.4 it was building ok - post update to 17.3.4 the build errors show for android.

I am unable to verify if this affects iOS but the build errors seem to point only at android.

This is happening on `dotnet --version` 6.0.401

### Steps to Reproduce

1. Update to VS 17.3.4
2. Create a brand new MAUI project (I used MAUI blazor for testing)
3. Attempt a build
4. Fails

### Link to public reproduction project repository

https://github.com/jordanwilcox/maui-build-error-android-17.3.4

### Version with bug

SDK 6.0.401

### Last version that worked well

SDK 6.0.400

### Affected platforms

Android

### Affected platform versions

All android platforms

### Did you find any workaround?

[Workaround found by @cupsos by changing global.json in solution to sdk version 6.0.400](https://github.com/dotnet/maui/issues/10102#issuecomment-1246388109)

### Relevant log output

```shell
1>C:\Program Files\dotnet\sdk\6.0.401\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(680,7): error : Manifest file at 'obj\Debug\net6.0-android\android-arm\staticwebassets.build.json' not found.
1>C:\Program Files\dotnet\sdk\6.0.401\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(680,7): error : Manifest file at 'obj\Debug\net6.0-android\android-x86\staticwebassets.build.json' not found.
1>Done building project "MauiApp1.csproj" -- FAILED.
1>C:\Program Files\dotnet\sdk\6.0.401\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(680,7): error : Manifest file at 'obj\Debug\net6.0-android\android-x64\staticwebassets.build.json' not found.
1>Done building project "MauiApp1.csproj" -- FAILED.
1>C:\Program Files\dotnet\sdk\6.0.401\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(680,7): error : Manifest file at 'obj\Debug\net6.0-android\android-arm64\staticwebassets.build.json' not found.
1>Done building project "MauiApp1.csproj" -- FAILED.
```

### PR DESCRIPTION
**Pull request by TanayParikh**
(cherry picked from commit ef5e813e8940d7cb82f66d9e4395a8a5bf040665)

Backport https://github.com/dotnet/maui/pull/9348

fixes #10102

### CODE REVIEW

**Comment by TanayParikh** [comment]
Companion PR: https://github.com/dotnet/sdk/pull/27108

**Review by jonathanpeppers — APPROVED** [review]

**Comment by TanayParikh** [comment]
@jonathanpeppers can this be directly merged, or must it go through tactics / additional review?

**Comment by jonathanpeppers** [comment]
@mattleibow should probably review/merge.

**Comment by TanayParikh** [comment]
Note, we want to ensure https://github.com/dotnet/sdk/pull/27108 is also merged in conjunction.

**Comment by TanayParikh** [comment]
> @mattleibow should probably review/merge.

/ping @mattleibow

**Review by mattleibow — APPROVED** [review]

**Pull request merged**
