### PR TITLE
[Housekeeping] Add provisionating xcode to net6

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change ###

Provision xcode on net6 builds

Implements #

### Additions made ###

* Adds 

### PR Checklist ###

- [ ] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [ ] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [ ] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [ ] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- [ ] Does this PR introduce a new control? (If yes, add an example using SemanticProperties to the SemanticsPage)
- [ ] APIs that modify focusability?
- [ ] APIs that modify any text property on a control?
- [ ] Does this PR modify view nesting or view arrangement in anyway?
- [ ] Is there the smallest possibility that your PR will change accessibility? 
- [ ] I'm not sure, please help me

If any of the above checkboxes apply to your PR, then the PR will need to provide testing to demonstrate that accessibility still works.

### CODE REVIEW

**Comment by rmarinho** [comment]
@vs-mobiletools-engineering-service2 backport release/6.0.1xxx.preview4

**Review by jonathanpeppers — CHANGES_REQUESTED** [review]
Can you also remove this?

https://github.com/dotnet/maui/blob/4bf6e1109344e70eb927be017b7c18e221bbe2e0/Directory.Build.targets#L7-L10

This was the workaround to be able to use the older Xcode, so we should try to remove it, thanks.

**Comment by rmarinho** [comment]
@jonathanpeppers but for that we would need to build on bigsur on deviddiv and 12.5 right?

**Comment by jonathanpeppers** [comment]
Oh, I thought that was the reason for this PR, was to provisioning Xcode? So you could get Xcode 12.5?

**Review by jonathanpeppers — APPROVED** [review]
The changes here look OK 👍 , but I thought we were trying to get Xcode 12.5.

**Comment by rmarinho** [comment]
this allows us to set it up on those builds once we have the bots..

**Pull request merged**
