### PR TITLE
Update templates to have separate default for framework selection

### PR DESCRIPTION
**Pull request by jfversluis**
### Description of Change

This change allows .NET MAUI projects to have a different default framework version selection (e.g. .NET 6 or .NET 7) from other .NET projects in Visual Studio.

Needed because the .NET MAUI only installs a certain Android SDK together with a .NET version. With .NET 7 that will be Android SDK 33, where the default selection will be .NET 6 (because LTS) and that targets SDK 31, which causes potential issues.

### Issues Fixed

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1654352 (internal link)

### CODE REVIEW

**Comment by Redth** [comment]
We probably want this in the blazor template too... now should the scope name be the same between those two? or separate?

**Comment by phenning** [comment]
If you want the stickiness to be shared between the two, the same. This would be my suggestion so customers don’t get too confused as to why the choice isn’t being remembered between templates like happens with other net core templates.
________________________________

**Comment by Redth** [comment]
@jfversluis can you please update the PR (rebase too) for the blazor template as well?

**Comment by jfversluis** [comment]
@Redth Done!

**Review by Redth — APPROVED** [review]

**Comment by rmarinho** [comment]
@phenning does this look good now?

**Comment by mattleibow** [comment]
Just added the Maui class lib for consistency.

**Review by mattleibow — APPROVED** [review]

**Review by phenning — APPROVED** [review]

**Comment by mattleibow** [comment]
Just tested now and I get net7.0 by default - even when I select net6 and then remove the reg key.

**Review by mattleibow — APPROVED** [review]

**Review by Redth — APPROVED** [review]

**Pull request merged**
