### PR TITLE
Implement LineBreakMode property in ButtonHandler

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Implement **LineBreakMode** property in Button.
- Android
- iOS/macOS
- Windows

button-linebreakmode

### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [x] Targets a single property for a single control (or intertwined few properties)
- [x] Adds the property to the appropriate interface
- [x] Avoids any changes not essential to the handler property
- [x] Adds the mapping to the PropertyMapper in the handler
- [x] Adds the mapping method to the WinUI, Android, iOS, and Standard aspects of the handler
- [x] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [x] Tags ported renderer methods with [PortHandler]
- [x] Adds an example of the property to the sample project (MainPage)
- [x] Adds the property to the stub class
- [x] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- No

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
Updated Wiki:
image

**Review by PureWeen — CHANGES_REQUESTED** [review]
@jsuarezruiz I rolled back some of the changes to interfaces. We have an `ITextButton` that `LineBreakMode` can be applied to so we don't have to change `IButton`. 

I tested the samples in our gallery and what I noticed is
Android: works great
iOS: works but the button doesn't remeasure
WinUI: doesn't appear to do anything

I think this PR makes the world a better place though so let me know if we should just open bugs for iOS/WinUI or if you'd like to try and fix before RC1

image

**Review by Redth — APPROVED** [review]

**Review by PureWeen — APPROVED** [review]
https://github.com/dotnet/maui/issues/5580

**Pull request merged**
