### PR TITLE
Add xplat OpenMauiAsset extension method

### LINKED ISSUE #3270: `<MauiAsset>` is hard to use
### Description

I added a `<MauiAsset Include="Resources\Assets\*">` in my project and I was unable to easily find how to retrieve it. I used Essentials' `FileSystem.OpenAppPackageFileAsync` and I found that it went to different folders:

- Windows => Assets\Resources\Assets\*
- Android => Resources\Assets\*
- iOS/MacCat => error : The name 'Resources' is reserved and cannot be used.

### PR DESCRIPTION
**Pull request by Eilon**
This makes reading MauiAssets a lot easier across platforms.

Example:

```c#
using var stream = await Application.Current.Handler.MauiContext.OpenMauiAsset("Resources/Path/To/File.txt");
```

Fixes #3270

@mattleibow - any thoughts on this? Still a work-in-progress, but at least an initial read.

### CODE REVIEW

**Comment by mattleibow** [comment]
How is this similar/different to Essentials' `FileSystem.OpenAppPackageFileAsync`? I think this does the same work?

**Comment by Eilon** [comment]
@mattleibow - I guess it depends on what Essentials' `FileSystem.OpenAppPackageFileAsync` is meant to do, because it could be just a bug in that API. In WinUI apps the `MauiAssets` get placed in an `Assets` sub-folder in the package folder, which isn't accounted for in the Essentials implementation. That means users have to call the API with different paths, e.g. Android `Foo\Bar.txt` and Windows `Assets\Foo\Bar.txt` to behave the same.

If that's just a bug in Essentials' implementation then I can close this and send a PR to fix that.

**Comment by Eilon** [comment]
BTW some of this is discussed in the issue you originally logged here: https://github.com/dotnet/maui/issues/3270

**Comment by Redth** [comment]
Should we just fix the existing api to check the right known subfolder we _put_ the assets? or is it not that simple?

**Comment by mattleibow** [comment]
My realization is that we were trying to be smart with the assets subfolder because we observed ios was using resources and android an assets folder. But this week I saw that ios sticks everything in the resources folder into the root. Maybe we should be doing that too? Why does Windows have this special sub folder?

**Comment by Eilon** [comment]
I would think that we have to support sub-folders, or else Static Web Assets (used in Blazor) wouldn't work. Also, I would think it's fairly expected that "files" can go in "folders"... An alternative would be to add a manifest that says what each file's logical location is and then we store everything flatly, but use the manifest to look things up...

**Comment by mattleibow** [comment]
We can support sub folders, but the Maui asset should not force all content into a sub folder on windows. Effectively I have a file in the csproj root and mauiasset build action. Suddenly on windows I have to read from assets/myfile? Ios and android do not do this.

Is maui asset only used for Blazor, or can I use it for any content?

Does Blazor require the assets folder in the Windows app?

**Comment by Eilon** [comment]
BTW I just tried using MauiAssets with iOS and sub-folders seem to work just fine (ran from VS Windows, deployed to Mac).

I pushed an update to this PR that does the following:

1. Adds support for iOS/MacCatalyst
2. Updates the Controls.Sample project to switch from the `Resources/**` folder to `MauiResources/**` folder because as you noted in the original issue, the name `Resources` is not allowed on iOS

And with those changes, this code with the new API that I added works on every platform:

```c#
using var stream = await Application.Current.Handler.MauiContext.OpenMauiAsset("MauiResources/Special/index.html");
```

And this code with the MAUI Essentials API works everywhere except Windows:

```c#
using var stream = await Microsoft.Maui.Essentials.FileSystem.OpenAppPackageFileAsync("MauiResources/Special/index.html");
```

**Comment by Eilon** [comment]
I had a great chat with @mattleibow and we concluded that we should make some changes and improvements to MauiAssets and related features so that we don't need any of the changes here.

See our meeting notes here: https://github.com/dotnet/maui/issues/3270#issuecomment-1023724641

**Pull request closed without merging**
