### PR TITLE
appsettings json embedded resource #3446

### PR DESCRIPTION
**Pull request by hflexgrig**
@Eilon This one should have better performance though.

### CODE REVIEW

**Comment by mattleibow** [comment]
Should this be embedded into the dll or stored in the app package "assets" system? Not sure of the perf here. Probably better in the dll as we do not have to touch the filesystem - but I may be wrong. @jonathanpeppers once the dll is loded into memory on Android, is it fully loaded, or will this still read off disk? Are there any pros/cons with embedded resources vs assets?

**Comment by hflexgrig** [comment]
> Should this be embedded into the dll or stored in the app package "assets" system? 

Here I used embedded resource, which is embedded to dll and becomes in-memory, not touching file system. My previous pull request was reading from file system (build action -> Content), I've got many complains on startup performance, that's why changed to embedded resource.

**Comment by hflexgrig** [comment]
@mattleibow this is my previous pull request which reads from file system. https://github.com/dotnet/maui/pull/3844

**Comment by Redth** [comment]
Same resolution as: https://github.com/dotnet/maui/pull/3844

We'll evaluate this in the future and come up with a spec.  Tracking that here: https://github.com/dotnet/maui/issues/4408

**Comment by jonathanpeppers** [comment]
> Should this be embedded into the dll or stored in the app package "assets" system? Not sure of the perf here. Probably better in the dll as we do not have to touch the filesystem - but I may be wrong. @jonathanpeppers once the dll is loded into memory on Android, is it fully loaded, or will this still read off disk? Are there any pros/cons with embedded resources vs assets?

My initial thoughts on `appsettings.json`, is that ASP.NET uses it as a file so you can edit the file on disk after a service is deployed -- or use environment variables.

This isn't practical at all in a mobile app -- users don't open files on disk and edit values or set environment variables. Does `appsettings.json` even make sense for a mobile app? Would you be better off hardcoding settings as a `const string`? If that is the case, we should just document how to do this and plug into the ASP.NET infrastructure so you just use C# `const` values.

**Pull request closed without merging**
