### PR TITLE
Add BlazorWebView device tests and fix Android file provider bug

### LINKED ISSUE #3676: BlazorWebView on MAUI Android doesn't use custom file provider override
When the `AndroidWebKitWebViewManager` is instantiated, it ignores `customFileProvider` and always uses the `mauiAssetFileProvider`:

https://github.com/dotnet/maui/blob/ffb22d2ec13e711425bb3cbc8caa8725ba0237e9/src/BlazorWebView/src/Maui/Android/BlazorWebViewHandler.Android.cs#L95-L101

### PR DESCRIPTION
**Pull request by Eilon**
Finally getting some automated device tests for BlazorWebView. For now there's just 1 test that checks if Blazor loads and you can click on a button and interact with a component, but that alone covers a lot of ground (loading, IPC, request/response, etc.). It even found a bug in the code!

There are 3 commits:
1. Get initial test project structure based off of other device test projects
2. Fix the Android file provider bug (#3676)
3. Update the test to do actual testing

The tests work on Android and iOS, and you can run locally on Windows, too.

Fixes #3676

### CODE REVIEW

**Comment by Eilon** [comment]
The tests now run and correctly fail (I made 1 passing test and 1 failing test):

image

Now to write some more tests...

**Comment by Eilon** [comment]
Passes on CI:

image

**Comment by Eilon** [comment]
@mattleibow / @PureWeen - hopefully one of you can review this. There's a 1-line product code fix that is trivial to understand. The rest is infrastructure for Blazor tests, plus 1 new test. I don't think there's _much_ to review in that, unless you spot something I missed as far as how to set up new tests.

**Comment by Eilon** [comment]
I am officially giving up on the weird failing DeviceTests (`GetPngScreenshot`, `GetJpegScreenshot`, `DispatchFromBackgroundThread`) on Android. It's failed for other PRs, and it consistently passed in this PR, until at some point they all started randomly failing, except for all passing one time. It passes locally on literally 100+ runs.

**Comment by Eilon** [comment]
@PureWeen / @mattleibow / @SteveSandersonMS - are any of you available for a quick review?

**Review by PureWeen — APPROVED** [review]

**Pull request merged**
