### PR TITLE
Adopt chromium methodology for determining tablet on Windows

### LINKED ISSUE #22093: OnIdiom doesn't respect Desktop setting on Windows
### Description

When using this for example:

`TextColor="{OnIdiom Desktop='Red', Default='Black'}"`

Running a solution on Windows the text is Black when I would expect it to be Red.

It works as expected when running on MacCatalyst, the text is Red.
It works as expected when running on iOS, the text is Black.
It works as expected when running on Android, the text is Black.
It does not work as expected when running on Windows, the text is Black.

### Steps to Reproduce

    1. Clone the attached project
    2. Run the solution on MacCatalyst
    3. Observe the text Red (as expected)
    4. Run the solution on iOS
    5. Observe the text Black (as expected)
    6. Run the solution on Android
    7. Observe the text Black (as expected)
    8. Run the solution on Windows
    9. Observe the text Black (NOT expected, Red was expected)
  

### Link to public reproduction project repository

https://bitbucket.org/KeithBoynton/on-idiom-desktop-issue/src/master/

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

_No response_

### Did you find any workaround?

No

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by daltzctr**
### Description of Change

Uses a more conservative approach of determining tablet mode on Windows. This approach is functionally identical to [Chromium's implementation](
https://source.chromium.org/chromium/chromium/src/+/main:base/win/win_util.cc;l=537;drc=ac83a5a2d3c04763d86ce16d92f3904cc9566d3a;bpv=0;bpt=1) for determining tablet on Windows. Additionally, it adds a few documentation comments on the observed behavior.

I don't have a good idea on how to add a unit test for this, and it's a bit of an implicit breaking change (some users who had tablet layouts may have desktop layouts now), but I think that number of users affected will be near, or at 0.

### Issues Fixed

Possibly fixes #22093

### CODE REVIEW

**Comment by daltzctr** [comment]
@dotnet-policy-service agree [company="CTR Electronics"]

**Comment by daltzctr** [comment]
@dotnet-policy-service agree company="CTR Electronics"

**Comment by daltzctr** [comment]
Marking as draft until I confirm a device that is Windows that should be tablet is still tablet (I will test on my Surface Pro 7).

**Comment by daltzctr** [comment]
This is ready for review and/or merge.

**Comment by jonathanpeppers** [comment]
Can you share what device was wrong before (using stable MAUI)? Was it a Windows laptop that just always returned `Tablet` no matter what?

**Comment by daltzctr** [comment]
XPS 15 reports as tablet.

**Review by Foda — APPROVED** [review]

**Comment by daltzctr** [comment]
Can this get merged?

**Comment by daltzctr** [comment]
@Foda is this blocked on something?

**Comment by daltzctr** [comment]
@Foda just a courtesy ping

**Review by jfversluis — APPROVED** [review]
Congratulations on being a .NET MAUI contributor!

**Pull request merged**
