### PR TITLE
[iOS] Text alignment in editor - improvements

### LINKED ISSUE #24583: [iOS, macOS] Text in the Editor control disappeared when reducing the Scale of the Editor control
### Description

When reducing the Scale of the Editor control, the text on the Editor control disappeared and reappeared after the Editor.Scale increases. This works fine on Android and Windows platforms.
#### Issue reproducible video ####
- **iOS**

https://github.com/user-attachments/assets/eba7a685-c5a7-4221-badd-8001ffe5cedc

- **macOS**

https://github.com/user-attachments/assets/4364e429-26b8-4d13-954a-6d514a57ee68

### Steps to Reproduce

1. Create a new .NET MAUI application.
2. Add the Editor control and the Slider control (whose Minimum=0 and Maximum-1) inside the StackLayout.
3. Bind the Editor.Scale to the Slider.Value.
4. Run the application on either iOS or macOS platform.
5. Drag the Slider to reduce the Editor.Scale value.
6. Notice that the text will disappear.

### Link to public reproduction project repository

https://github.com/VishalOmprasad/Editor-Scale-Issue-iOS-macCatalyst

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Description of Change

Currently, text alignment in the editor is not functioning correctly when the editor's scale is adjusted. This Pr fixed this

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/24583

Editors with text start, center and end alignments with a scale of 0.5
|Before|After|
|--|--|
|||

### CODE REVIEW

**Comment by rmarinho** [comment]
Can we also add a Test without scale ? to make sure that didn t regress>?

**Comment by kubaflo** [comment]
@rmarinho sure, and done

**Comment by tj-devel709** [comment]
@kubaflo This is awesome! Thanks for fixing this issue. I did add a commit bringing some of your new changes to the way it used to be implemented. These changes get touchy with the keyboard scrolling inside editors with the contentInsets and contentOffsets and were failing some UITests. This also brought to my attention that the keyboard scrolling stuff is off when the verticalTextAlignment is Center or End. Let me know if you see issues with the change I made :)

**Comment by tj-devel709** [comment]
Link to new issue found when testing this: https://github.com/dotnet/maui/issues/24977

**Comment by kubaflo** [comment]
@tj-devel709 yay everything works after your commits. Thanks!

**Review by tj-devel709 — APPROVED** [review]

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
