### PR TITLE
Essentials.AppActions refactored to interface and singleton

### PR DESCRIPTION
**Pull request by moljac**
### Description of Change ###

Implements #

```csharps
	public interface IAppActions
	{
		bool IsSupported { get; }

		string Type { get; }

		Task<IEnumerable<Maui.Essentials.AppAction>> GetAsync ();

		Task SetAsync (IEnumerable<AppAction> actions);	

		Task SetAsync (params AppAction[] actions);		
	}
```

### Additions made ###

* Adds 

### PR Checklist ###

- [ ] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [ ] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [ ] Adds the mapping method to the WinUI, Android, iOS, and Standard aspects of the handler
- [ ] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- [ ] Does this PR introduce a new control? (If yes, add an example using SemanticProperties to the SemanticsPage)
- [ ] APIs that modify focusability?
- [ ] APIs that modify any text property on a control?
- [ ] Does this PR modify view nesting or view arrangement in anyway?
- [ ] Is there the smallest possibility that your PR will change accessibility? 
- [ ] I'm not sure, please help me

If any of the above checkboxes apply to your PR, then the PR will need to provide testing to demonstrate that accessibility still works.

### CODE REVIEW

**Comment by Redth** [comment]
@moljac please have a look at one of the reference PR's for the exact pattern we're after here: https://github.com/dotnet/maui/pull/4466

We're making the actual implementation classes instances so they can be replaced at runtime as needed (via the editorbrowseable never methods).

**Comment by moljac** [comment]
> @moljac please have a look at one of the reference PR's for the exact pattern we're after here: #4466
> 
> We're making the actual implementation classes instances so they can be replaced at runtime as needed (via the editorbrowseable never methods).

I hope noe looks better.

**Comment by moljac** [comment]
UWP error - fixed

```
D:\a\_work\1\s\src\Essentials\src\AppActions\AppActions.uwp.cs(16,15): error CS1106: Extension method must be defined in a non-generic static class
```

**Comment by moljac** [comment]
> Buhh sorry @moljac need to check what permissions are needed i think you need to be contributor

No problems. Trying. Voodoo DevOps - it might work someday. 😄

**Review by Redth — APPROVED** [review]

**Pull request merged**
