### PR TITLE
[net7.0] Revert android net7.0 workload to 33.0.68

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change

Revert android workload to stable version

### CODE REVIEW

**Review by jonathanpeppers — COMMENTED** [review]
Should we only do this on the release branch?

Or will you just let Maestro update this one later?

**Comment by rmarinho** [comment]
Yeah we will branch from net7.0 and then maestro should updated. I going to branch today if I can.

**Review by jonathanpeppers — APPROVED** [review]

**Review by PureWeen — APPROVED** [review]

**Comment by rmarinho** [comment]
we will not need this after all

**Pull request closed without merging**
