### PR TITLE
Update SecureStorage.android.cs

### LINKED ISSUE #19983: Android: SecureStorage Adding a value after calling RemoveAll() will not persist the value
### Description

When I call Microsoft.Maui.Storage.SecureStorage.Default.RemoveAll() and then add a value, the value will disappear when restarting the app. Adding a value after restart will then again persist it properly. 

### Steps to Reproduce

Start Android App
Call Microsoft.Maui.Storage.SecureStorage.Default.RemoveAll();
Call: Microsoft.Maui.Storage.SecureStorage.Default.SetAsync(key, value)
Call: Microsoft.Maui.Storage.SecureStorage.Default.GetAsync(key) ->  Returns the value
Restart App
Call: Microsoft.Maui.Storage.SecureStorage.Default.GetAsync(key) -> Value is gone
Call: Microsoft.Maui.Storage.SecureStorage.Default.SetAsync(key, value) 
Call: Microsoft.Maui.Storage.SecureStorage.Default.GetAsync(key) ->  Returns the value
Restart App: 
Call: Microsoft.Maui.Storage.SecureStorage.Default.GetAsync(key) -> Returns the value

My conclusion is, that calling RemoveAll() will somehow break the SecureStorage until next app start

### Link to public reproduction project repository

https://github.com/phillippschmedt/SecureStorageIssue (see MainPage.xaml.cs, use debugger to inspect)

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tested on Android 13

### Did you find any workaround?

Not yet

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by AnthonyNjuguna**
### Description of Change

On PlatformRemoveAll we reset the _prefs to null. So that the encrypted_prefs_key and encrypted_prefs_value are created again on next value insert so that GetAsync can decrypt said value
Reasons: 

### Issues Fixed
Fixes #19983

Issues with Android SecureStorage.GetAsync returning null

### CODE REVIEW

**Comment by jfversluis** [comment]
Hey @AnthonyNjuguna thanks for the report and immediate fix too! Is there any way we could add a test for this so we're sure this is a good fix and more importantly: it won't regress again?

**Review by jsuarezruiz — APPROVED** [review]

**Review by PureWeen — CHANGES_REQUESTED** [review]
Thoughts? We're not able to reproduce the initial issue. 

https://github.com/dotnet/maui/issues/19983#issuecomment-1927342068

**Comment by mattleibow** [comment]
I think @Redth found something, so we probably need to see what he found.

**Comment by AnthonyNjuguna** [comment]
Superseded by https://github.com/dotnet/maui/pull/20445

**Pull request closed without merging**
