### PR TITLE
[iOS] Fixed HeaderFooterGrid to pass on CV1 and CV2 

### LINKED ISSUE #25773: [iOS] Fix HeaderFooterGrid to pass on CV1 and CV2
### Description

This test was modified to only run on CV2 because it's not passing on CV1
https://github.com/dotnet/maui/pull/25719/files#diff-f0958ee62c0d1d0bd45c40bbafe319a04b51823e33fc7d4411eba9c590e391e6R19

We need to fix it so the test is passing on both sets of handlers

### PR DESCRIPTION
**Pull request by devanathan-vaithiyanathan**
### Issue details
The size of the CollectionView, including the header and footer, is not rendered correctly on the UI in CV1 but displays correctly in CV2.

### Root cause
The GetSize() method calculated the size of the CollectionView based only on its content, ignoring the header and footer sizes. This caused incorrect height or width rendering when a header or footer was used.

### Description of Change

The fix calculates the sizes of the header and footer using helper methods, This ensures the total size includes all elements, and the result is adjusted to fit within the CollectionView bounds.

### Issues Fixed

Fixes #25773 

### Tested the behaviour in the following platforms
 
- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### Output Screenshot
| Before  | After  |
|---------|--------|
|  </img>   |   </img>   |

### CODE REVIEW

**Review by StephaneDelcroix — DISMISSED** [review]

**Review by rmarinho — APPROVED** [review]
It s failing some tests..

```
https://dev.azure.com/xamarin/public/_apis/test/Runs/3418613/Results/100053/Attachments/14
```

**Review by rmarinho — CHANGES_REQUESTED** [review]
Could this be CV2 failing 

image

image

**Comment by devanathan-vaithiyanathan** [comment]
> Could this be CV2 failing
> 
> image
> 
> image

Hi @rmarinho,

In CV1, It appears that the **VerticalItemsSpacing** in the **GridItemsLayout** is creating excessive spacing in the last section of the items layout. The build failures are due to these ItemSpacing discrepancies, resulting in snapshot mismatches.
 
The following Issue was previously identified and resolved, and a separate PR was created.

PR Link Reference => https://github.com/dotnet/maui/pull/25825

In this Focused PR, We have made targeted changes specifically to resolve the VerticalItemsSpacing issue for the last section of CV items. We expect the next CI run to pass with these updates.

Code Changes :
https://github.com/dotnet/maui/blob/0e5aabf62ed9ec4213066de39b090a20f93a414d/src/Controls/src/Core/Handlers/Items/iOS/ItemsViewLayout.cs#L136C4-L141C5

Please review the PR and let us know if any further clarification.

**Comment by rmarinho** [comment]
Can we try replace the image to check if it passes?

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
