### PR TITLE
Generate rollback files

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change ###

Generate an easy rollback file for quick installs.

```
https://aka.ms/dotnet/maui/<branch-name>.json
  main = https://aka.ms/dotnet/maui/main.json
  release/6.0.1xx-rc1 = https://aka.ms/dotnet/maui/6.0.1xx-rc1.json

BASE VERSION
  https://aka.ms/dotnet/maui/preview.9.json
  https://aka.ms/dotnet/maui/6.0.101/preview.9.json

FULL VErSION
  https://aka.ms/dotnet/maui/6.0.101/preview.9.12345.json

SHA
  https://aka.ms/dotnet/maui/6.0.101/<sha>.json
  https://aka.ms/dotnet/maui/<sha>.json
```

Usage:

```
dotnet workload update --from-rollback-file https://aka.ms/dotnet/maui/main.json --source https://aka.ms/dotnet6/nuget/index.json
dotnet workload install XXX --skip-manifest-update
```

All we need now is a nice way to do the 2 commands in 1:

```
dotnet workload install --versions https://aka.ms/dotnet/maui/main.json --source https://aka.ms/dotnet6/nuget/index.json
```

### CODE REVIEW

**Review by Redth — APPROVED** [review]

**Review by jonathanpeppers — COMMENTED** [review]
General question, could we run this command instead:
```
> .\bin\dotnet\dotnet.exe workload update --print-rollback
==workloadRollbackDefinitionJsonOutputStart==
{"microsoft.net.sdk.android":"31.0.101-preview.9.6","microsoft.net.sdk.ios":"15.0.101-preview.9.20","microsoft.net.sdk.maccatalyst":"15.0.101-preview.9.20","microsoft.net.sdk.macos":"12.0.101-preview.9.20","microsoft.net.sdk.maui":"6.0.100-dev","microsoft.net.sdk.tvos":"15.0.101-preview.9.20","microsoft.net.workload.emscripten":"6.0.0-rc.2.21451.1","microsoft.net.workload.mono.toolchain":"6.0.0-rc.2.21461.1"}
==workloadRollbackDefinitionJsonOutputEnd==
```

I don't know why they have the weird `==` stuff, but maybe we could trim that off and the changes here would be a lot simpler?

**Comment by Redth** [comment]
@jonathanpeppers would that pick up the maui version for the current build as part of it ?

**Comment by jonathanpeppers** [comment]
Yes, my example above was a local build like `"microsoft.net.sdk.maui":"6.0.100-dev"`.

**Comment by mattleibow** [comment]
But we are not installing the maui in there before we build? So we will have to build, then install and then build again?

**Comment by jonathanpeppers** [comment]
@mattleibow I think you could produce the `workload.json` file in `.yaml`, so none of this MSBuild logic would be needed? Just do it after the build is done?

You don't need to produce the file locally, right?

**Comment by mattleibow** [comment]
We _could_ but we are producing 6 files using different parts of version in the msbuild props we set earlier... Hmm...

**Comment by mattleibow** [comment]
Let me try that, but I do want to access parts of the version so I can generate different filenames:

 - branch name
 - preview label (rc.1 or preview.9)
 - full label (preview.9.123456)
 - git sha

I then make several files so we can copy this to a blob storage so we can do:

```
dotnet workload install maui --rollback https://aka.ms/maui/preview.9.json
```

**Comment by Redth** [comment]
What if you just write a BuildVersionInfo.txt file with those various version parts that we can just foreach through later to save out copies of the rollback json?

**Comment by mattleibow** [comment]
I'm going to merge this now since it seems to work and I can leverage all the work already done to set variables for the other json files.

Moving to a yaml or external script means that the build steps have to be adjusted. Also, we need access to a few of the variables set via the GitInfo and out Versions.targets.

This can go away once the sdk can support installing workloads with just a single thing, rather than needing all the workloads in the rollback.

**Pull request merged**
