### PR TITLE
Fix the TFM order for VS

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change

Visual Studio doesn't like when our repository puts the WinUI TFMs first it seems

### CODE REVIEW

**Comment by mattleibow** [comment]
Is there a bug logged for this somewhere?

**Comment by PureWeen** [comment]
@mattleibow not yet? I know this was an issue at one point

Was it supposedly fixed? 

This came up after I merged [this](https://github.com/dotnet/maui/pull/9195) which reversed the TFMs and VS stopped showing devices anymore. 

I'll log an issue with tooling

**Comment by mattleibow** [comment]
Yeah... This might have been a result of some new changes.

**Comment by PureWeen** [comment]
@mattleibow it looks like this is fixed with 17.4

**Pull request merged**
