### PR TITLE
Draw Line using BackgroundColor

### LINKED ISSUE #17298: Line is not visible in .Net 8
### Description

Have tried to add line using "Microsoft.Maui.Controls.Shapes.Line" in .Net 6 and checked the same scenario in .Net 8. But the line was not visible in .Net 8.

**Sample**
[DotNetEightUnderline.zip](https://github.com/dotnet/maui/files/12575372/DotNetEightUnderline.zip)

**Screenshot**

**.Net 6 :**
image

**.Net 8 :**
image

### Steps to Reproduce

1. Run the attached sample.
2. Now you can see the output.

### Link to public reproduction project repository

https://github.com/shanmugasundar-sf3429/TextMarkupAnnotationVisibility

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, I was *not* able test on other platforms

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Applied changes to allow render a Line using BackgroundColor. Next a sample rendering the same line using Stroke, Background and BackgroundColor:
image

Applied changes with other shapes to validate the behavior using Fill, Background and BackgroundColor:
image
image

To validate the changes can use the updated shapes samples from the Gallery or the added Device Tests.
image

image

### Issues Fixed

Fixes #17298

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
Should the behavior be like this?
image
Stroke paints the color of the line, and Background/BackgroundColor the background of the View.

**Comment by jsuarezruiz** [comment]
Fixed broken tests on iOS:
image

**Comment by espenrl** [comment]
I wouldn't expect both `Stroke` and `BackgroundColor` to do the same thing. And I would never expect `Line.BackgroundColor` to be used except for debugging the layout of the Line.

**Comment by jsuarezruiz** [comment]
Unless we have new feedback or details, we are not going to modify the current behavior.

**Pull request closed without merging**
