### PR TITLE
Move MAUI Blazor template files to match ASP.NET Blazor template

### PR DESCRIPTION
**Pull request by Eilon**
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1910199

In PR https://github.com/dotnet/maui/pull/17946 an attempt was made to make the MAUI Blazor template have the same exact structure as the ASP.NET Blazor template, but a few files did not end up in the correct location.

### CODE REVIEW

**Comment by Eilon** [comment]
@Redth / @PureWeen - if we'd like to get this in for 8.0, can one of you review?

**Review by mkArtakMSFT — APPROVED** [review]
Thanks @Eilon !

**Review by danroth27 — APPROVED** [review]
LGTM

**Review by MackinnonBuck — APPROVED** [review]

**Pull request merged**
