### PR TITLE
[Windows] Fix issue using Connectivity from a background thread

### LINKED ISSUE #17270: Windows: Connectivity check sometimes return NetworkAccess.Unknown
### Description

On Windows checking connectivity returns incorrect value of NetworkAccess.Unknown.

There is this already closed issue: https://github.com/dotnet/maui/issues/9972

But this for sure is not fixed because I can still reproduce it.

### Steps to Reproduce

Here is the tricky part. I cannot provide any particular repro steps. In my app this can reproduce in some particular screens, in other happens only sometimes. 

I tried create a demo sample app but I could not reproduce there.
Of course I tried calling on the main thread the check as a suggestions made in the https://github.com/dotnet/maui/issues/9972. But sometimes it works, sometimes not.

It happens also with .Net 8 - preview 7.8842

### Link to public reproduction project repository

No sample

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

_No response_

### Did you find any workaround?

No

### Relevant log output

```shell
Exception thrown at 0x00007FFB8C31CF19 (KernelBase.dll) : The application called an interface that was marshalled for a different thread.
```

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix issue using Connectivity from a background thread.
fix-17270

### Issues Fixed

Fixes #17270

### CODE REVIEW

**Review by mattleibow — COMMENTED** [review]
One thing that is concerning is that there was an existing test and that test was passing? Not only that, this was fixed and then reverted (I think). I think the fix caused issues if there was no window present - like if you do a network check in app startup. Have we confirmed that this scenario still works?

Also, a lot of this code looks eerily similar to `MainThread` implementations. Should we be using that instead? If this implementation is different, then maybe we should move this code there and instead do thread logic over there.

How is this PR different and why was the test NOT failing before this fix? 

See also: https://github.com/dotnet/maui/issues/9972#issuecomment-1279480104

**Review by mattleibow — CHANGES_REQUESTED** [review]
One thing that is concerning is that there was an existing test and that test was passing? Not only that, this was fixed and then reverted (I think). I think the fix caused issues if there was no window present - like if you do a network check in app startup. Have we confirmed that this scenario still works?

Also, a lot of this code looks eerily similar to `MainThread` implementations. Should we be using that instead? If this implementation is different, then maybe we should move this code there and instead do thread logic over there.

How is this PR different and why was the test NOT failing before this fix? 

See also: https://github.com/dotnet/maui/issues/9972#issuecomment-1279480104

**Comment by jsuarezruiz** [comment]
> One thing that is concerning is that there was an existing test and that test was passing? Not only that, this was fixed and then reverted (I think). I think the fix caused issues if there was no window present - like if you do a network check in app startup. Have we confirmed that this scenario still works?
> 
> Also, a lot of this code looks eerily similar to `MainThread` implementations. Should we be using that instead? If this implementation is different, then maybe we should move this code there and instead do thread logic over there.
> 
> How is this PR different and why was the test NOT failing before this fix?
> 
> See also: [#9972 (comment)](https://github.com/dotnet/maui/issues/9972#issuecomment-1279480104)

If the App Window is null:
`DispatcherQueue dispatcherQueue = WindowStateManager.Default?.GetActiveWindow(false)?.DispatcherQueue;`
(line 32)

`dispatcherQueue` will be null and DispatcherQueue will not be used to access NetworkInformation. That is, the behavior is the same without Window, it only changes when it exists.

**Comment by BenBtg** [comment]
FYI I have attempted to apply the above fix to a local repro as a workaround for a NET7 project. But found this fix does not work on Windows 10. I then updated the project to NET8 and found the issues still exists even with the above fix.

**Comment by jsuarezruiz** [comment]
Let's reanalyze the problem with another approach.

**Pull request closed without merging**
