### PR TITLE
Update the Windows App SDK to 1.0

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change ###

'nuff sed!

### CODE REVIEW

**Comment by Eilon** [comment]
@javiercn - this PR is failing with some StaticWebAssets issues:

```
"D:\agent\1\s\src\BlazorWebView\samples\MauiRazorClassLibrarySample\MauiRazorClassLibrarySample.csproj" (GetCurrentProjectBuildStaticWebAssetItems target) (18:9) ->
(GetCurrentProjectBuildStaticWebAssetItems target) -> 
  D:\agent\1\s\bin\dotnet\sdk\6.0.101\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(799,7): error : Manifest file at 'obj\Release\net6.0\staticwebassets.build.json' not found. [D:\agent\1\s\src\BlazorWebView\samples\MauiRazorClassLibrarySample\MauiRazorClassLibrarySample.csproj]


"D:\agent\1\s\Microsoft.Maui-net6.sln" (Build target) (1:2) ->
"D:\agent\1\s\src\Controls\samples\Controls.Sample.SingleProject\Maui.Controls.Sample.SingleProject.csproj" (default target) (2:22) ->
"D:\agent\1\s\src\Controls\samples\Controls.Sample.SingleProject\Maui.Controls.Sample.SingleProject.csproj" (Build target) (2:23) ->
"D:\agent\1\s\src\Controls\samples\Controls.Sample\Maui.Controls.Sample-net6.csproj" (GetMauiItems target) (7:27) ->
"D:\agent\1\s\src\BlazorWebView\samples\MauiRazorClassLibrarySample\MauiRazorClassLibrarySample.csproj" (ComputeReferencedStaticWebAssetsPublishManifest;GetCurrentProjectPublishStaticWebAssetItems target) (18:10) ->
(LoadStaticWebAssetsBuildManifest target) -> 
  D:\agent\1\s\bin\dotnet\sdk\6.0.101\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(522,5): error : Manifest file at 'obj\Release\net6.0\staticwebassets.build.json' not found. [D:\agent\1\s\src\BlazorWebView\samples\MauiRazorClassLibrarySample\MauiRazorClassLibrarySample.csproj]

    55 Warning(s)
    2 Error(s)
```

Can you help take a look? We have a binlog I can share with you.

**Comment by Eilon** [comment]
Binlog sent to @javiercn .

**Comment by javiercn** [comment]
I think something has changed in the build that is causing ResizetizeCollectItems to run super early in the build pipeline before dependent projects have been built, and that's why we are seeing this issue. If I'm not wrong, ResizetizeCollectItems is running before the dependencies have been built, and that is causing the failure.

image

image

It's not clear to me what the right solution for this is, I would expect that ResizetizeCollectItems only runs after all dependent projects have been built.

**Comment by mattleibow** [comment]
Moved the reply to the other issue so we can resolve it there

**Pull request merged**
