### PR TITLE
[iOS] [Mac] Fix for Gradient background size is incorrect when invalidating parent 

### LINKED ISSUE #20218: Can't use LinearGradientBrush as Button Background on iOS
### Description

Works on Android (tested on Pixel 7 API 34 emulator)
android
but on iOS (tested on iPhone 15 Pro Max iOS 17.2 emulator)
ios
there is something wrong...

### Steps to Reproduce

1. Create a Button.
2. Set Background property to LinearGradientBrush.
3. Run on iOS.

### Link to public reproduction project repository

https://github.com/alececihs/MauiButtonsTest/

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #26057: [iOS & Mac] Gradient background size is incorrect when invalidating parent
### Description

When invalidating a parent, gradient applied to the child fills the entire screen.

In my example, I have a Grid with 2 Rows(40,*) and loaded a button as first row with LinearGradientBrush.
When calling Grid.InvalidateMeasure(), the gradient size fills the entire screen.

### Steps to Reproduce

1. Run the attached sample.
2. Click anywhere outside the Button.
[Gradient.zip](https://github.com/user-attachments/files/17870319/Gradient.zip)

### Link to public reproduction project repository

_No response_

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

_No response_

### Did you find any workaround?

Yes
Rename the gradient relevant layer name to skip size updating for this particaluar layer alone.
    private void ButtonLoaded(object? sender, EventArgs e)
    {
        #if IOS
            if(sender is Button button && button.Handler != null && button.Handler.PlatformView != null && button.Handler.PlatformView is UIKit.UIView platformView)
            {
                if(platformView.Layer != null && platformView.Layer.Sublayers != null)
                {
                    if(platformView.Layer != null && platformView.Layer.Sublayers != null)
                {
                    var layer = platformView.Layer.Sublayers.FirstOrDefault(x => x.Name == "MauiBackgroundLayer");
                    if( layer != null && layer is CALayer gradientLayer)
                    {
                        gradientLayer.Name = "GradientLayer";
                    }
                }
                }
            }
#endif

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by Tamilarasan-Paranthaman**
### Root Cause of the issue 

- During the initial and dynamic rendering of the view, the Gradient Layer frame is not applied correctly. Additionally, the Gradient Layer frame updates unnecessarily for all UIViews, causing the Gradient Layer to appear incorrectly sized.
 

### Description of Change

- The issue was resolved by retrieving the superlayer (parent) of the Gradient Layer and updating its bounds to match the Gradient Layer's frame.

### Issues Fixed

Fixes #26057
Fixes #20218

### Tested the behaviour in the following platforms

- [x] Android
- [x] Windows
- [x] iOS
- [x] Mac

### iOS
| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video width="300" height="500"  src="https://github.com/user-attachments/assets/186503c1-5185-4e9d-8427-e9530f355fec"> | <video width="300" height="500"  src="https://github.com/user-attachments/assets/ca7cf13d-aff4-4a5a-9a42-586493e9f5d9"> |

### Mac
| Before Issue Fix | After Issue Fix |
|----------|----------|
| <video width="300" height="500"  src="https://github.com/user-attachments/assets/e8500961-f16f-4758-8811-2c202845d997"> | <video width="300" height="500"  src="https://github.com/user-attachments/assets/0cc10f03-4272-49fe-859f-d016367fb826"> |

### CODE REVIEW

**Comment by kubaflo** [comment]
Hi, @albyrock87 I remember you were making some changes to this viewExtension.cs when you were working on the border fix. Does this PR look good to you?

**Comment by albyrock87** [comment]
@kubaflo my PR #24848 should already fix this, at least that's my guess.
Also note that my PR basically gets rid of `UpdateBackgroundLayers`.

**Comment by kubaflo** [comment]
@albyrock87 I see! Your PR is great! Maybe you should also include a UI test for this issue in your PR as well https://github.com/dotnet/maui/pull/24848

**Comment by albyrock87** [comment]
I will add this UI test on my PR to confirm it fixes this issue too.

**Comment by albyrock87** [comment]
@Tamilarasan-Paranthaman I've added you as co-author on #24848 where I've just included your UI test and verified it works fine

**Pull request closed without merging**
