### PR TITLE
[Android] Fix clipped text in SwipeItem under some DPIs

### LINKED ISSUE #11495: Text is clipped in SwipeItem
### Description

Some characters, like j and g, are sometimes cropped when used in an SwipeItem on Android:

image

My guess is that screen density matters in this case. I haven't seen this on screens with low pixel density. But it happens with all 440 dpi devices I have tested. Like the default Pixel 5 emulator with these settings:

image

### Steps to Reproduce

1. Create new MAUI application.
2. Update MainPage.xaml:
``` XAML
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiIssues.MainPage">

    <CollectionView x:Name="ItemsList">
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <SwipeView>
                    <SwipeView.LeftItems>
                        <SwipeItems>
                            <SwipeItem Text="&#xc5;jg &#xc5;jg!" 
                                        BackgroundColor="LightGreen" />
                        </SwipeItems>
                    </SwipeView.LeftItems>
                    <Grid HeightRequest="80" BackgroundColor="LightBlue">
                        <Label Text="&#xc5;jg &#xc5;jg!"
                                VerticalOptions="Center"/>
                    </Grid>
                </SwipeView>
            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>
</ContentPage>
```

3. Update MainPage.xaml.cs:
``` CS
public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();

		ItemsList.ItemsSource = new List<string>() { "1" };
	}
}
```
4. Run the application in a Pixel 5 emulator, with 440 dpi.

### Link to public reproduction project repository

https://github.com/pekspro/MauiIssues/tree/11495_Text_is_clipped_in_SwipItem

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11,13

### Did you find any workaround?

No.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Fix clipped text in Android SwipeItem under some DPIs.

image

To test the changes, launch the .NET MAUI Gallery and navigate to the SwipeView samples. Select the first option "Basic SwipeView" and validate that all the SwipeItems renders correctly.

### Issues Fixed

Fixes #11495

### CODE REVIEW

**Review by rachelkang — CHANGES_REQUESTED** [review]
Text definitely isn't getting clipped anymore woohoo! I do wonder though if we need to tweak the padding measuring a bit more - it seems to be a bit offset vertically. (used the code from the linked issue)

Screenshot_20221213-141626

**Comment by jsuarezruiz** [comment]
Applied changes and updated the sample from the Gallery:
image

**Review by rachelkang — CHANGES_REQUESTED** [review]
It looks to be properly aligned again, but if you look closely, the text is unfortunately still slightly clipped (See the bottoms of the j and g characters)

For reference, I'm testing on a Google Pixel 4a device

image

**Comment by rachelkang** [comment]
Just tested again, and issue from my most recent review still stands :/

> It looks to be properly aligned again, but if you look closely, the text is unfortunately still slightly clipped (See the bottoms of the j and g characters)
> 
> For reference, I'm testing on a Google Pixel 4a device
> 
> image

**Review by rachelkang — CHANGES_REQUESTED** [review]
Commented

**Review by rmarinho — CHANGES_REQUESTED** [review]
Yap if I try the sample it also shows clipped still.
 
Screenshot_1676557035

**Comment by jsuarezruiz** [comment]
I have applied changes and I have also done tests on emulators with different densities from 120 to 560. 
image

This is the result at 560.
image

Could I have another review? In case of issues, can we share information such as the device and data like the screen density etc?

**Review by rachelkang — APPROVED** [review]
LGTM! :)

image

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
