### PR TITLE
Enable Window Sizing

### LINKED ISSUE #5509: How to set app launch window size
### Description

I wonder how to set launch window size in maui。
When I search for Issues and DIscussion，I found there is no universal way to set  launch window size in maui, https://github.com/dotnet/maui/discussions/2370 ,someone says in windows we can get the window handler first and change window size,  but in macOS there is no workaround way.
And I also find https://github.com/dotnet/maui/pull/4942 , this work will allow us to set window size to a fixed value while targeting Windows, What about MacOS? I think it's not an uniform solution for maui framework。

### Public API Changes

setWindowSize()
setWindowLocation()

### Intended Use-Case

I want to show different window size when using multi-window,  so I need to set app launch window size。

### LINKED ISSUE #7592: Ability to set initial window size and position and restore previous values
### Description

I wish to be able to define a default starting size and position for the MAUI application and to restore the window position and size the next time the application is launched.

While I understand the paradigm of starting MAUI apps as full-screen (or close to full screen), it is very impractical for users to have ultra-wide monitors (in my case a 49" 5440x1440 monitor); I literally have to turn my head to change from the left side to the right side of the monitor.

I have a work-around for the initial window size and position* (except for not being able to determine the screen size, so I cannot do bounds checking to make sure the window is wholly within the screen for different resolutions / monitor sizes) but would prefer to have official support, cross platform to MacOS, for this functionality.

### Public API Changes

```csharp
int initialWidth = 1024;
int initialHeight = 726;

Screen primary = Screen.GetPrimaryScreen(); // New API
RectInt32 sizeAndPosition = new RectInt32(
   primary.Width/2 - initialWidth/2,
   primary.Height/2 - initialHeight/2,
   initialWidth,
   initialHeight);
Window window = new Window(new SomePage(), sizeAndPosition); // New API
```

### Intended Use-Case

My app has two distinct modes of operation; Full mode for Desktop environments (Windows / MacOS) and Player for mobile devices (Android / iOS). On desktop environments (Windows / MacOS), full screen is not a desired initial state for the application.

If the user has resized and positioned the window in a specific location of the screen - as long as that position + size is still valid the application should re-launch to that position and size.

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change ###

Add the ability to set window size and read size and position.

 - Related to #7592
 - Fixes #5509

Depends on:

 - #9641
 - #9614

Known Issues:

 - #9704
 - #9703 
 - https://github.com/dotnet/maui/issues/9707
 - https://github.com/dotnet/maui/issues/9708

Platforms:

- [x] Windows
    - [x] X\Y
    - [x] Width\Height
    - [x] Minimum Width\Height
    - [x] Maximum Width\Height
    - [x] Get window size and updates
    - [x] SizeChanged event
- [x] Mac Catalyst (macOS)
    - [ ] ~X\Y~ (not supported)
    - [ ] ~Width\Height~ (not supported)
    - [x] Minimum Width\Height
    - [x] Maximum Width\Height
    - [x] Get window size and updates
    - [x] SizeChanged event

### Additions made ###

One notable difference in API is that the views have a Width/HeightRequest and then a Width/Height for the actual bounds. Window does not need this because no matter what the user sets, that is the value. And, if the user doe not set any value, the OS will assign one. You cannot have a window without bounds. Views have bounds too, but there is a layout system that interprets it. For example, a view can be set to fill a space in a Grid, and then when moved to a new cell, it resizes. Window is the opposite - the OS ensures that the size is set and nothing updates it unless the user resizes it.

**Core:**
```cs
interface IWindow {
    // "request" values
    double X { get; }
    double Y { get; }
    double Width { get; }
    double Height { get; }
    double MinimumWidth { get; set; }
    double MinimumHeight { get; set; }
    double MaximumWidth { get; set; }
    double MaximumHeight { get; set; }

    // platform value
    void FrameChanged(Rect frame);
}
```

**Controls:**
```cs 
class Window {
    // bindable properties
    public static readonly BindableProperty XProperty;
    public static readonly BindableProperty YProperty;
    public static readonly BindableProperty WidthProperty;
    public static readonly BindableProperty HeightProperty;
    public static readonly BindableProperty MinimumWidthProperty;
    public static readonly BindableProperty MinimumHeightProperty;
    public static readonly BindableProperty MaximumWidthProperty;
    public static readonly BindableProperty MaximumHeightProperty;

    // properties
    public double X { get; set; }
    public double Y { get; set; }
    public double Width { get; set; }
    public double Height { get; set; }
    public double MinimumWidth { get; set; }
    public double MinimumHeight { get; set; }
    public double MaximumWidth { get; set; }
    public double MaximumHeight { get; set; }

    // events
    public event EventHandler? SizeChanged;
```

**Usage:**
```cs
const int newWidth = 800;
const int newHeight = 600;

// get screen size
var disp = DeviceDisplay.Current.MainDisplayInfo;

// center the window
Window.X = (disp.Width / disp.Density - newWidth) / 2;
Window.Y = (disp.Height / disp.Density - newHeight) / 2;

// resize
Window.Width = newWidth;
Window.Height = newHeight;
```

### NOTES

Mac Catalyst does not support window sizing or positioning, however sizing could happen via setting both the min and max sizes on the window. This will then trigger a resize and you can then reset back to mon=0 and max=maxvalue.

Not perfect, but works.

```cs
Window.MinimumWidth = 700;
Window.MaximumWidth = 700;

Window.MinimumHeight = 500;
Window.MaximumHeight = 500;

// dispatcher is used to give the window time to actually resize
Dispatcher.Dispatch(() =>
{
	Window.MinimumWidth = 0;
	Window.MaximumWidth = double.PositiveInfinity;
	Window.MinimumHeight = 0;
	Window.MaximumHeight = double.PositiveInfinity;
});
```

### PR Checklist ###

- [x] Targets the correct branch 
- [x] Tests are passing (or failures are unrelated)
- [x] Targets a single property for a single control (or intertwined few properties)
- [x] Adds the property to the appropriate interface
- [x] Avoids any changes not essential to the handler property
- [x] Adds the mapping to the PropertyMapper in the handler
- [x] Adds the mapping method to the WinUI, Android, iOS, and Standard aspects of the handler
- [ ] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

### CODE REVIEW

**Comment by akanieski** [comment]
Will this work allow me to set window size to a fixed value while targeting Windows? What about MacOS? If I set `MainPage.WidthRequest` or `MainPage.HeightRequest` it gets the below.. is there some other way to achieve this? Or is this PR something I should look out for?
image

**Comment by mattleibow** [comment]
That might be a bug because the root page always fills the window... Right, @hartez?

Maybe we also need a min/max on the window? And maybe the option to set flags, like the nosizing and toolwindow... Maybe these are for separate PRs.

Need to figure out the wiggle first.

And yeah, macos should respect bounds too. I don't think I implemented it yet as the Windows wiggle put a stop to that. I'll get back to it as soon as p14 is out the door.

**Comment by mattleibow** [comment]
After much playing around and learning about WinUI I see we now have a nice API that works well - trick is to use `AppWindow`.

**Review by PureWeen — DISMISSED** [review]
https://github.com/dotnet/maui/issues/9703

**Review by PureWeen — APPROVED** [review]

**Comment by davidbuckleyni** [comment]
In winforms days we also had screen position this could be centered minimised and maximised in the more modern word be great if we could that and tell which montior to start a particular screen on ?

**Comment by CartBlanche** [comment]
@mattleibow in which version of MAUI is this fix available in? When will it be public (my Maui.Controls.Window object doesn't contain Width, Height etc properties)?

**Comment by Redth** [comment]
This arrives in .NET 7

Already available in RC2, soon in GA :)

**Comment by CartBlanche** [comment]
@Redth thanks!

**Comment by BlueHippoGithub** [comment]
Right now the general solution for setting the window size of a maui application seems to be by calling .Resize on the AppWindow at window creation. This however, causes a "flicker" because it resizes after window creation.

Will this have the same issue of flickering or will the window size be set properly before showing it?

**Pull request merged**
