### PR TITLE
[ci] Use drop service for SDK insertion artifacts

### PR DESCRIPTION
**Pull request by pjcollins**
Context: xamarin/yaml-templates@8759ec9

Steps to upload release artifacts to custom blob storage have been
replaced with azure-artifacts-drop (aka.ms/drop).

A new version of nuget-msi-convert has been added that will create a set
of artifact drops for the following shipping artifacts:
  * nugets
  * vs-components
  * vs-packs

The nugets drop contains all shipping packages that should be pushed to
various feeds or NuGet.org.

The components and packs drops are used for VS insertions.

### CODE REVIEW

**Comment by pjcollins** [comment]
Test build here looks good: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9897796&view=results

**Comment by rmarinho** [comment]
lets retarget this to main, and I will then merge to net9.0

**Comment by pjcollins** [comment]
> lets retarget this to main, and I will then merge to net9.0

@ruiminhu I'd rather scope this to .NET 9+ for now, we can continue with the old approach for .NET 8 servicing and hopefully not need to backport this.

**Review by rmarinho — APPROVED** [review]

**Comment by pjcollins** [comment]
I've mentioned this a few times but we should not backport this unless it is strictly necessary as it will break our VS insertion workflow.

**Pull request merged**
