### PR TITLE
Resize internal content container when ScrollView content is resized

### LINKED ISSUE #12727: ScrollView with BindableLayout.ItemsSource is not recalculate new size on iOS
### Description

I have this code, and after I changed Slots collection, ScrollView is not recalulate it's size.

``` xaml
<ScrollView x:Name="scrollView" VerticalScrollBarVisibility="Default">
<Grid>
<StackLayout Margin="16,0">
<StackLayout x:Name="DaysCollection" BindableLayout.ItemsSource="{Binding Days}" Spacing="18">
	<BindableLayout.ItemTemplate>
		<DataTemplate x:DataType="general:AvailabilityDayModel">
			<StackLayout Spacing="20">
				<StackLayout x:Name="AvailabilitySlot" BindableLayout.ItemsSource="{Binding Slots}" Spacing="4">
					<BindableLayout.ItemTemplate>
						<DataTemplate x:DataType="general:AvailabilitySlotModel">
							<HorizontalStackLayout>
								<Label Text="-" Style="{StaticResource ParagraphRegular}" Margin="8" VerticalOptions="Center" />
								<Button ImageSource="trash.png" Clicked="RemoveAvailability_Clicked" Margin="-8"
														  CommandParameter="{Binding .}" BackgroundColor="Transparent" VerticalOptions="Center"
														  Style="{StaticResource SecondaryDefaultSmall}"   />

								<Button ImageSource="plus_big.png"  Clicked="AddAvailability_Clicked" Margin="-8"
									CommandParameter="{Binding ParentDay}"  BackgroundColor="Transparent" VerticalOptions="Center"
									Style="{StaticResource SecondaryDefaultSmall}"  />
							</HorizontalStackLayout>
						</DataTemplate>
					</BindableLayout.ItemTemplate>
				</StackLayout>

			</StackLayout>
		</DataTemplate>
	</BindableLayout.ItemTemplate>
</StackLayout>

<Button IsVisible="{OnIdiom false, Phone=true}" Text="Save" Command="{Binding SaveChangesCommand}" Margin="16,32,16,0" Style="{StaticResource MainDefaultBig}" />
</StackLayout>
</Grid>
</ScrollView>
```

### Steps to Reproduce

1. Create ScrollView
2. Inside ScrollView add  Grid, then StackView
3. Add one more StackView with BindableLayout.ItemsSource
4. add one more butto wich will add new item into BindableLayout.ItemsSource and will rise event to add one more item
5. on iOS after adding items ScrollView will not recalulate size and you will not see scroll
6. on Android all is ok

### Link to public reproduction project repository

no

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16

### Did you find any workaround?

If I will call InvalidateMeasure(); after adding items in Page all is fine, so it looks like ScrollView not notified about chagin size of childrens

### Relevant log output

_No response_

### LINKED ISSUE #14257: VerticalStackLayout inside Scrollview: Button at the bottom not clickable on IOS
### Description

When you put a VerticalStackLayout inside a ScrollView and load some data dynamically (i.e. some Text using an async function) and then put a button on the end of the VerticalStackLayout, the Button-Handler never gets called.
This works on Android without any problem.
For me related to: #8820 

### Steps to Reproduce

1. Clone the repo
2. Run the app on IOS
3. Click on the "Button at bottom" Button
4. Scroll to the bottom of the page and try to click the button

### Link to public reproduction project repository

https://github.com/FM1973/RefreshGridRepo.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 14.x +

### Did you find any workaround?

Yes, there is a workaround. It´s the same as before having the general ScrollView-problem stated in #8820 
Look there: [https://github.com/dotnet/maui/issues/8820#issuecomment-1352923013](https://github.com/dotnet/maui/issues/8820#issuecomment-1352923013) 

### Relevant log output

```shell
-
```

### LINKED ISSUE #14624: [regression/7.0.81] ScrollView content with Buttons rendered offscreen do not respond on iOS
This is related to issue #9236, the issue appear again on the latest MAUI release 7.0.81 and 7.0.200 on iOS only. Every button that doesn’t appear directly on the screen after render will never get clicked. It appear in the following 3 scenarios: button in a scrollview, bindable stacklayout and ListView. It is tested using iOS 13.* and 16.* using a simulator and real devices.

### LINKED ISSUE #15762: ScrollView with dynamically added Entries are not clickable
### Description

When an `Entry` is added dynamicaly with `BindableLayout` in a `StackLayout` in a `ScrollView`, if it increases the height to where the ScrollView must be scrolled the `Entry` cannot be selected.

[screen-capture.webm](https://github.com/dotnet/maui/assets/60721064/3cf98e3b-0630-4221-ae87-e4754e8362ad)

It is possible on the simulator to press tab to select the `Entry`, but it still cannot be selected by a click/press

### Steps to Reproduce

Create a `ScrollView` that contains a `StackLayout` that contains a `BindableLayout.ItemsSource` where the ItemSource is an `ObservableCollection`. Ex:

```
<ScrollView>
    <StackLayout BindableLayout.ItemsSource="{Binding StringList}">
        <BindableLayout.ItemTemplate>
            <DataTemplate>
                <StackLayout HorizontalOptions="FillAndExpand">
                    <Entry Text="{Binding .}" WidthRequest="100"/>
                </StackLayout>
            </DataTemplate>
        </BindableLayout.ItemTemplate>
    </StackLayout>
</ScrollView>
```

See repo for full example

### Link to public reproduction project repository

https://github.com/Jake-Derrick/EntryIssue

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS 16

### Did you find any workaround?

CollectionView and ListView will make the Entry selectable, but then you have a nested scrolling

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by hartez**
### Description of Change

The iOS ScrollView's internal content container was correctly sized for off-screen content at first layout, but was failing to update correctly when the content was resized (possibly because of a data binding change).

These changes correct that problem, and add automated UI tests to verify this scenario.

### Issues Fixed

Fixes #14257
Fixes #15762
Fixes #14624
Fixes #12727

### CODE REVIEW

**Review by rmarinho — APPROVED** [review]

**Comment by gerhartz** [comment]
@hartez will this be backported to .net7 like the first part was? https://github.com/dotnet/maui/pull/15424

**Comment by Ghostbird** [comment]
This claims to have fixed https://github.com/dotnet/maui/issues/15762, so we removed our workaround in our MAUI 8 app. Immediately everything broke again. Do we need to do anything special to make this work?

**Comment by Ghostbird** [comment]
Ah never mind, it's broken too when we keep our workaround. It seems the move to MAUI 8 works just fine on Android, but the iOS app is borked in many places. So it's probably not directly related to this issue.

**Comment by PureWeen** [comment]
@Ghostbird can you test out nightly https://github.com/dotnet/maui/wiki/Nightly-Builds ?

If you're still seeing an issue please log a new bug with a repro.

**Comment by Ghostbird** [comment]
@PureWeen Sorry, I think this was mostly a mistake on my part. It turns out that `TapGestureRecognizer` is broken in MAUI 8 at least on `Button`s. I've created #19099

**Pull request merged**
