### PR TITLE
[iOS] FlyoutHeader size change fix

### LINKED ISSUE #20696: FlyoutHeader on iOS does not change its size after adding new content
### Description

Adding new content does not change the size of the FlyoutHeader on iOS. Even setting the RequestHeight or making parts of the content visible/invisible does not trigger a size change. On Android, the Flyoutheader adjusts it's size perfectly.

iOS:
image

Android:
image

### Steps to Reproduce

1. Open the reproduction project.
2. Start the App on a iOS device.
3. Click the Button.

### Link to public reproduction project repository

https://github.com/MatthewJer/TestDynamicFlyoutMenuHeader

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kubaflo**
### Description of Change

|Before|After|
|--|--|
|<video src="https://github.com/dotnet/maui/assets/42434498/e9411d92-3a1d-4a00-a0fb-3f5b93e58bc3" width="300px"/>|<video src="https://github.com/dotnet/maui/assets/42434498/0de61c20-e839-4e12-a892-ac7b147a1530" width="300px"/>|

### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/20696

### CODE REVIEW

**Comment by dustin-wojciechowski** [comment]
I pulled this down and looks good to me, I just noticed that the number stopped incrementing after 2 in the test case (although it doesn't in your video demonstration)

https://github.com/dotnet/maui/assets/89540402/0120e898-002c-447b-8418-5441efdb6347

**Comment by kubaflo** [comment]
> I pulled this down and looks good to me, I just noticed that the number stopped incrementing after 2 in the test case (although it doesn't in your video demonstration)
> 
>  Simulator.Screen.Recording.-.iPhone.15.-.2024-04-23.at.15.40.30.mp4

Ah right. It is because I've hardcoded the text of the button to be the 'Test button 2'

**Review by jsuarezruiz — APPROVED** [review]

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
