### PR TITLE
Add `DisplayDensity` to `IWindow`

### PR DESCRIPTION
**Pull request by Redth**
This adds a way to access the display density for a given Window.

Adds an implementation for https://github.com/dotnet/maui/issues/1811

@etvorun does this API look reasonable for your needs? It doesn't address DPI change notifications, which may be more of a challenge, but I think it's worth starting with this at least.

### CODE REVIEW

**Comment by rmarinho** [comment]
```
  "D:\a\_work\1\s\Microsoft.Maui.sln" (Build target) (1:2) ->
       "D:\a\_work\1\s\src\Core\tests\DeviceTests\Core.DeviceTests.csproj" (default target) (34:22) ->
       "D:\a\_work\1\s\src\Core\tests\DeviceTests\Core.DeviceTests.csproj" (Build target) (34:24) ->
       (CoreCompile target) -> 
         D:\a\_work\1\s\src\Core\tests\DeviceTests\Stubs\WindowStub.cs(6,28): error CS0535: 'WindowStub' does not implement interface member 'IWindow.DisplayDensity' [D:\a\_work\1\s\src\Core\tests\DeviceTests\Core.DeviceTests.csproj]
```

**Review by drasticactions — APPROVED** [review]
I'm cool with this. The only thing I think would be cool is if we add method comments to where some of these numbers come from to generate these values.

Like, Windows gets its DPI from the platform, divided by `96f`. I don't know where that value comes from, and if we ever need to change it we should have some context to why it's there.

Otherwise, looks good to me 👍

**Comment by Redth** [comment]
I'm trying to smooth out these values so they are all a 'scale' type value.  So I'm doing the `/ 96f` in the cases to make it a similar scale value.

**Comment by mattleibow** [comment]
@drasticactions  I think you may just want a comment to this type of doc? https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/dpi-related-apis-and-registry-settings?view=windows-11#table-2-dpi-scale-factors

**Review by mattleibow — COMMENTED** [review]
So the code looks valid, but the first thing that popped out to me was the proliferation of platform specific code in the XAML objects.

Not only is this un-testable and un-extendable, but it is going to make all the things hard.

Is it possible to maybe use a Command for this? I think the times where you start working in partial classes with custom platform code means this should be handler work.

Let me make a PR based on what i think to this branch and see if it will actually work...

**Comment by mattleibow** [comment]
This is what I am working on based off this PR: https://github.com/dotnet/maui/pull/5185

**Pull request closed without merging**
