### PR TITLE
Move `WeakEventManager` to `Core.csproj`

### PR DESCRIPTION
**Pull request by TheCodeTraveler**
### Description of Change

This PR moves `WeakEventManager` to the `Core.csproj` project and updates its namespace:
- Moving `WeakEventManager.cs`
  - `src/Controls/src/Core/WeakEventManager.cs` -> `src/Core/src/WeakEventManager.cs`
- Updating `WeakEventManager` Namespace
  - `namespace Microsoft.Maui.Controls` -> `namespace Microsoft.Maui`

Additionally, this PR moves the associated Unit Tests to `Core.UnitTests.csproj` and updates its namespace:
- Moving `WeakEventManagerTests.cs`
  - `src/Controls/tests/Core.UnitTests/WeakEventManagerTests.cs` → `src/Core/tests/UnitTests/WeakEventManagerTests.cs`
- Updating `WeakEventManagerTests` Namespace
  - `Microsoft.Maui.Controls.Core.UnitTests` -> `Microsoft.Maui.UnitTests`

### Additional Information

On the [.NET MAUI Community Toolkit](https://github.com/communitytoolkit/maui) team, we strive to keep the .NET MAUI Community Toolkit architecture aligned with the .NET MAUI architecture. To accomplish this, we have a `CommunityToolkit.Maui.Core` project that maps to the .NET MAUI code in `Core.csproj` (aka `/src/Core/`).

Mimicking .NET MAUI's architecture ensures a frictionless process to promote features from the .NET MAUI Community Toolkit into .NET MAUI once the features have matured and been approved.

We'd really love to use WeakEventManager with our Core project, but right now we can't because it's in the *.Controls namespace.

Moving `WeakEventManager` to `Core.csproj` also allows other Frameworks built using .NET MAUI (e.g. Comet, BlazorWebView) to also leverage `WeakEventManager`.

**.NET MAUI Community Toolkit Contributions Guide**

https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#where-to-make-your-changes

[MicrosoftTeams-image](https://github.com/CommunityToolkit/Maui/blob/main/CONTRIBUTING.md#where-to-make-your-changes)

### CODE REVIEW

**Comment by Clancey** [comment]
I am fine with this being in Core. It might come in handy with our handlers and native events. As long as this doesn't encourage/have us adding events on our interfaces.

**Review by Clancey — APPROVED** [review]

**Comment by brminnick** [comment]
I've updated this PR to fix the CI errors caused by not previously updating the XML docs references 👍

**Review by mattleibow — APPROVED** [review]
Approving this as we probs need it in core and should use it for platform subscriptions.

But, is approval only applies if this feature does not exist in the BCL. It has been years since forms was created, have we added something like this to the BCL yet? Either an API or a language feature?

**Comment by brminnick** [comment]
Thanks @mattleibow!

`WeakEventManager` is not yet in the .NET BCL, but there is an open Issue requesting it to be added based on our implementation: https://github.com/dotnet/runtime/issues/61517#issue-1052189789

**Review by mattleibow — APPROVED** [review]

**Comment by brminnick** [comment]
Can I get another `/azp run` to see if the docs build script is fixed?

**Pull request merged**
