### PR TITLE
Refactored Preferences into an Interface

### PR DESCRIPTION
**Pull request by sps014**
### Description of Change ###

Implements #
```cs
        public interface IPreferences
	{
		bool ContainsKey(string key, string? sharedName);
		void Remove(string key, string? sharedName);
		void Clear(string? sharedName);
		void Set<T>(string key, T value, string? sharedName);
		T Get<T>(string key, T defaultValue, string? sharedName);
	}
```
Part of https://github.com/dotnet/maui/issues/4497

### CODE REVIEW

**Comment by sps014** [comment]
@Redth @mattleibow  
Can you please review it.
Thanks

**Review by Redth — APPROVED** [review]

**Comment by sps014** [comment]
> @sps014 is failing to build
> 
> ```
> D:\a\_work\1\s\src\Essentials\test\DeviceTests\Tests\SecureStorage_Tests.cs(70,26): error CS0117: 'Preferences' does not contain a definition for 'GetSharedPreferences' [D:\a\_work\1\s\src\Essentials\test\DeviceTests\Essentials.DeviceTests.csproj]
> ```

thanks can you please rerun the pipeline.

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
