### PR TITLE
Remove unused FileProviders.Embedded reference from templates

### PR DESCRIPTION
**Pull request by Eilon**
This package is no longer used in .NET MAUI + Blazor Desktop scenarios.

### CODE REVIEW

**Comment by Redth** [comment]
@Eilon  Can you retarget this to main? it's not critical for p7 right?

**Comment by Eilon** [comment]
Not truly critical, but it's definitely not needed in p7. If it's too late for p7 we can easily just clean this in main.

**Comment by Eilon** [comment]
Looks like other stuff is missing, I'm fixing.

**Comment by Eilon** [comment]
@jonathanpeppers can you take a look at the change to the Workload here? We're removing all usage of FileProviders.Embedded because it was only used by Blazor Desktop (as far as I know), and now it's no longer needed. I did a search and tried removing all other usage.

**Comment by Eilon** [comment]
OK the CI is happy, so just need reviews.

**Review by javiercn — APPROVED** [review]

**Review by jonathanpeppers — APPROVED** [review]
This looks right. I think only Maui + BlazorWebView actually needed `Microsoft.Extensions.FileProviders.Embedded`.

If you can run a `maui-blazor` template, with these changes we should be good.

**Comment by Eilon** [comment]
@jonathanpeppers yeah the template/product code doesn't use it at all.

**Pull request merged**
