### PR TITLE
Implements LineHeight on Label

### PR DESCRIPTION
**Pull request by AmrAlSayed0**
### Description of Change ###
Implements #368
### Additions made ###
- Adds `double LineHeight { get; }` to the `ILabel` interface
- Adds LineHeight property map to LabelHandler
- Adds LineHeight mapping methods to LabelHandler for Android and iOS
- Adds extension methods to apply LineHeight on Android/iOS
- Adds DeviceTests for initial LineHeight values on iOS and Android
### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [x] Targets a single property for a single control (or intertwined few properties)
- [x] Adds the property to the appropriate interface
- [x] Avoids any changes not essential to the handler property
- [x] Adds the mapping to the PropertyMapper in the handler
- [x] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [x] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [x] Tags ported renderer methods with [PortHandler]
- [x] Adds an example of the property to the sample project (MainPage)
- [x] Adds the property to the stub class
- [x] Implements basic property tests in DeviceTests

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
@AmrAlSayed0 Could you rebase main to fix the conflict?. Thanks!.

**Comment by AmrAlSayed0** [comment]
@jsuarezruiz I was trying to rebase the latest but there was a HUGE commit that moved things around. Where did ```LabelExtensions.cs``` go? https://github.com/dotnet/maui/tree/main/src/Core/src/Platform/Android 😂

**Comment by jsuarezruiz** [comment]
@AmrAlSayed0 Sorry, but I think there must have been some problem with the rebase. There are more than 5000 changed files. Let me know if can help with something!

**Comment by AmrAlSayed0** [comment]
@jsuarezruiz Yes, that's because there was a huge commit between me making a fork and the pull request. I will close this PR and reapply the changes on a new fork tonight.

**Pull request closed without merging**
