### PR TITLE
Attempt to fix crash in MauiApplication.OnCreate()

### LINKED ISSUE #21973: Android crash at startup with System.ArgumentNullException: ArgumentNull_Generic Arg_ParamName_Name, services on MauiApplication
### Description

Can't reproduce, but see multiple analytics crashes on startup. It seems, during OnApplicationCreating event IPlatformApplication.Current.Services set to null(althought it filled before)

```
Microsoft.Maui.MauiContext..ctor(IServiceProvider services)
Microsoft.Maui.MauiContext..ctor(IServiceProvider services, Context context)
Microsoft.Maui.Controls.Compatibility.Hosting.AppHostBuilderExtensions.<>c.<OnConfigureLifeCycle>b__1_0(Application app)
Microsoft.Maui.MauiApplication.<OnCreate>b__2_0(OnApplicationCreating del)
Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents[OnApplicationCreating](IServiceProvider services, Action`1 action)
Microsoft.Maui.MauiApplication.OnCreate()
PF.Forms.PlanetFitnessApplication.OnCreate()
Android.App.Application.n_OnCreate(IntPtr jnienv, IntPtr native__this)
```

### Steps to Reproduce

Appears immediately after launch(or, maybe, after app restart)

### Link to public reproduction project repository

_No response_

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12-Android 14

### Did you find any workaround?

No

### Relevant log output

```shell
Have only stacktrace
Microsoft.Maui.MauiContext..ctor(IServiceProvider services)
Microsoft.Maui.MauiContext..ctor(IServiceProvider services, Context context)
Microsoft.Maui.Controls.Compatibility.Hosting.AppHostBuilderExtensions.<>c.<OnConfigureLifeCycle>b__1_0(Application app)
Microsoft.Maui.MauiApplication.<OnCreate>b__2_0(OnApplicationCreating del)
Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents[OnApplicationCreating](IServiceProvider services, Action`1 action)
Microsoft.Maui.MauiApplication.OnCreate()
PF.Forms.PlanetFitnessApplication.OnCreate()
Android.App.Application.n_OnCreate(IntPtr jnienv, IntPtr native__this)
Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz)
```

### PR DESCRIPTION
**Pull request by PavloLukianets**
### Description of Change
Just for test purposes to see app behavior when adding this null check

### Issues Fixed
Fixes #21973 
(not sure if fixes)

### CODE REVIEW

**Comment by mattleibow** [comment]
An app without services is a really broken app and noting will actually launch. 

In fact, this error is really weird because:

```
var mauiApp = CreateMauiApp();
var rootContext = new MauiContext(mauiApp.Services, this);
var applicationContext = rootContext.MakeApplicationScope(this);

_services = applicationContext.Services;
```

The `CreateMauiApp` should _always_ create a new services instance. This is where you are registering your app services.

However, if you look at the exception, you can see the real issue is coming from Compatibility:

https://github.com/dotnet/maui/blob/a3c872dfbf6101a3fdaf449f0c09899774593b21/src/Compatibility/Core/src/AppHostBuilderExtensions.Android.cs#L22-L23

Are you using anything from compatibility?

But, this still gets more weird. The constructor of MauiApplication is setting `IPlatformApplication.Current = this` and by the time this event is fired, the services are set so `IPlatformApplication.Current.Services` should not be null.

I am going to add some more comments to the linked issue for duscussion and see if we can figure out some repro and/or info on the scenarios that cause this to happen - it seems impossible.

**Comment by PavloLukianets** [comment]
.UseMauiCompatibility()

**Comment by mattleibow** [comment]
Yeah, you might be able to use renders still, if you manually register them. 

@PureWeen do we have docs on how to migrate the old renderers to the rendlers or handerers (the renderer-looking handlers).

**Pull request closed without merging**
