### PR TITLE
Adding ContentInsets to iOS Keyboard Scrolling

### LINKED ISSUE #14043: [iOS] After lower positioned text entry item selected and scrolled, you can't scroll back to it.
### Description

This is an after-effect of [this PR](https://github.com/dotnet/maui/commit/16fcd7e481c1b883aca9fe3533aebd445e212ead).

https://user-images.githubusercontent.com/898335/226108233-81b10d16-fbd0-4d20-be93-709e800897da.mp4

If you select the lowest positioned item, the view compensates and shows that item with the keyboard under it. However, if you scroll up, the view resets, and the item is now positioned under the keyboard, with no way to scroll back down. The only way to access it is to disable and reenable the keyboard.

### Steps to Reproduce

1. Open the Control Sample
2. Go to the entry page.
3. Select the lowest entry item
4. Scroll up.

### Link to public reproduction project repository

https://github.com/dotnet/maui/tree/main/src/Controls/samples/Controls.Sample

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

All Versions

### Did you find any workaround?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by tj-devel709**
### Description of Change

Maui iOS does not apply any ContentInsets to the appropriate scrolling view when the screen scrolls up for the keyboard. While this is not a regression from the new Keyboard Scrolling feature, IQKeyboard does handle this and will allow us to focus an entry or editor, scroll around the page (with the keyboard still up) and still be able to scroll back down and see our focused view.

IQKeyboard has logic [here](https://github.com/hackiftekhar/IQKeyboardManager/blob/7399efb730eea084571b45a1a9b36a3a3c54c44f/IQKeyboardManagerSwift/IQKeyboardManager%2BPosition.swift#L511) to update the ContentInset when we scroll for the keyboard. 
This PR brings over this functionality. 

https://user-images.githubusercontent.com/50846373/229630715-4197f783-50cd-4d0a-b7fe-9adda61d21b9.mov

### Issues Fixed

Fixes #14043

### CODE REVIEW

**Comment by tj-devel709** [comment]
Please note, when we click an entry or editor that does not require the screen to scroll (the last part of the demo in the description), there is no ContentInset added to the scrollview and we cannot reach the bottom of the scrollview. It is most likely possible to still add this ContentInset to every Entry and Editor inside a scrollview, however, this PR reflects how Android handles this situation as shown in this video below. Let me know if there are concerns or opinions on which way is best to handle this.


https://user-images.githubusercontent.com/50846373/229631988-442cd924-7170-4c62-b08c-ced84234d945.mov

**Review by mandel-macaque — APPROVED** [review]

**Comment by rmarinho** [comment]
Did you tested with a CollectionView with entries ?

**Comment by tj-devel709** [comment]
> Did you tested with a CollectionView with entries ?

Did run into some issues with collectionview and spending more time investigating them!

**Comment by tj-devel709** [comment]
@ruiminhu there were some changes needed from IQKeyboard since I changed some of the scrolling behavior to fit MAUI's controllers better. Looks good to me now with Collectionview! (android for comparison)

https://user-images.githubusercontent.com/50846373/231260661-d477e165-2798-44e4-85df-acaae505ac71.mov




https://user-images.githubusercontent.com/50846373/231260633-1799c7b3-ba6c-46f3-850f-e683506f7d38.mov

**Comment by rmarinho** [comment]
Why do the scrolls have a large padding (inset) in the beginning on your videos? What's the sample code for that example?

**Comment by tj-devel709** [comment]
> Why do the scrolls have a large padding (inset) in the beginning on your videos? What's the sample code for that example?

Hey @ruiminhu, yeah I just had an empty boxview to test having the items towards the bottom of the screen. Here is the sample code: 
https://gist.github.com/tj-devel709/4830ccaa3cbbb97de9df0b2ffb622ba0

**Review by rmarinho — APPROVED** [review]

**Comment by SarthakB26** [comment]
@tj-devel709 why we are putting CollectionView in ScrollView In you sample?. Shouldn't we could add ContentInset to Collectiontion view if entry which is opening a keyboard is inside CollectionView in case of iOS.

I was able to do that previously I couldn't find the code but I was subscribing to KeyboardOpen event and checking if keyboard would overlap entry in that case I was adding appropriate ContentInset to CollectionView.

My requirement was different though I was having Editor(AutoSize=true) inside CollectionView. The issue in this I was having was since Editor AutoSize was true when user writing long multiple line text, after adding few line editor would go under the keyboard after this user cannot see what he was typing. Yes user can scroll up the collection view manually with interaction but still customer was not happy with the behviour in iOS. On Android though collection view was moving up automatically on every next line if editor is about to go under keyboard.

**Pull request merged**
