### PR TITLE
Merge main into net8.0

### PR DESCRIPTION
**Pull request by pjcollins**
Merges the latest changes from main back into the net8.0 branch.

### CODE REVIEW

**Review by mattleibow — APPROVED** [review]

**Comment by rmarinho** [comment]
seem test failing for templates iOS @pjcollins

**Comment by pjcollins** [comment]
@rmarinho looks like we're green now. The net8.0 template creation was seemingly taking 90+ seconds to complete which may be a sort of performance regression to keep an eye out for.

**Comment by mattleibow** [comment]
Are you also seeing this locally? Was it both Mac and windows or just one platform?

**Review by mattleibow — APPROVED** [review]

**Comment by pjcollins** [comment]
@mattleibow I only saw this in CI on macOS when creating a template with `-f net8.0`.

**Pull request merged**
