### PR TITLE
CONTRIBUTING.md added

### PR DESCRIPTION
**Pull request by Suplanus**
### Description of Change ###
I added the CONTRIBUTING.md from [Xamarin.Forms](https://github.com/xamarin/Xamarin.Forms/blob/main/.github/CONTRIBUTING.md) and replaced it with MAUI texts. I removed some parts where files or infos are missing.

### Issues Resolved ### 
The CONTRIBUTING.md was missing, and linked in the README.md.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=253) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=253) before we can accept your contribution.<br/><br/>:x: Suplanus [sign now](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=253)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/maui?pullRequest=253) it.</sub>

**Comment by Suplanus** [comment]
Issue #255 and PR #264

**Comment by rmarinho** [comment]
Seems we alrelady have that file, do you want to update it?

**Comment by hartez** [comment]
Closing this for now, we've moved the file and the contribution stuff is changing with MAUI anyway.

**Pull request closed without merging**
