### PR TITLE
[macios] Bump .NET 8 to support Xcode 16.0

### PR DESCRIPTION
**Pull request by dalexsoto**

### CODE REVIEW

**Comment by rmarinho** [comment]
We need to update the feed for this version no ?

```
/Users/builder/azdo/_work/1/s/src/DotNet/Dependencies/Workloads.csproj : error NU1102: Unable to find package Microsoft.NET.Sdk.macOS.Manifest-8.0.100 with version (= 15.0.8302) [/Users/builder/azdo/_work/1/s/src/DotNet/DotNet.csproj]
```

**Comment by dalexsoto** [comment]
@rmarinho done

**Comment by dalexsoto** [comment]
Well this is weird... we have one passing macOS test... https://dev.azure.com/xamarin/public/_build/results?buildId=124069&view=logs&j=5e776fb8-e507-5143-ec45-2ba2180b6038&t=7b73c696-7508-5d9b-4366-d55275bcfb06&l=11

image

**Comment by samhouts** [comment]
Are we going to want https://github.com/dotnet/maui/pull/20398 here, too?

**Review by rmarinho — CHANGES_REQUESTED** [review]
@dalexsoto  should we clean this PR and with xharness bump ?

**Comment by dalexsoto** [comment]
@rmarinho done

**Comment by dalexsoto** [comment]
superseded by https://github.com/dotnet/maui/pull/25140

**Pull request closed without merging**
