### PR TITLE
[iOS] Fixes carouselview layout on iOS

### LINKED ISSUE #18223: CarouselView layout bugs in iOS
### Description

A basic CarouselView, in a fresh .NET MAUI project, with 4 sample items, will render as expected on Windows and Android. On iOS the initial layout is off the bottom of the screen, and then when dragging starts it relayouts, but the content is laid out too high and clips off the top of the screen. 

https://github.com/dotnet/maui/assets/72052/4d62f0c0-1dc7-47e3-bb9f-14b9faee079d

### Steps to Reproduce

1. Create a new MAUI project in Visual Studio
2. Replace the MainPage content with a CarouselView that has some basic template and a few items.

### Link to public reproduction project repository

https://github.com/halfninja/CarouselDemo

### Version with bug

7.0.96

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

Tested iOS 14 and 17

### Did you find any workaround?

Remove `Loop="False"` if you can deal with looping.

### Relevant log output

This gets logged after you start dragging and it figures out the correct layout

```
2023-10-21 23:26:45.768227+0100 AppName[79937:653172] The behavior of the UICollectionViewFlowLayout is not defined because:
2023-10-21 23:26:45.768383+0100 AppName[79937:653172] the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.
2023-10-21 23:26:45.768641+0100 AppName[79937:653172] The relevant UICollectionViewFlowLayout instance is <Microsoft_Maui_Controls_Handlers_Items_CarouselViewLayout: 0x10dd629d0>, and it is attached to <UICollectionView: 0x11797ba00; frame = (0 0; 320 504); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x600000c75530>; backgroundColor = UIExtendedGrayColorSpace 0 0; layer = <CALayer: 0x60000067a960>; contentOffset: {254, 0}; contentSize: {1280, 504}; adjustedContentInset: {0, 0, 0, 0}; layout: <Microsoft_Maui_Controls_Handlers_Items_CarouselViewLayout: 0x10dd629d0>; dataSource: <Microsoft_Maui_Controls_Handlers_Items_CarouselViewController: 0x10dd5f450>>.
2023-10-21 23:26:45.768777+0100 AppName[79937:653172] Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.
```

### LINKED ISSUE #19657: CarouselView - Content disappears when 'Loop' is false and inside ScrollView
### Description

When utilizing CarouselView that is nested in a `ScrollView`, the content does not display/disappears on scroll when the `Loop` property is set to false.

## With Outer ScrollView
Xamarin Simulator Windows_K8naRGFpFx

## Without Outer ScrollView
Xamarin Simulator Windows_rq50ynOxX4

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage">
    <ScrollView>
        <Grid x:Name="contentGrid">
            <Grid.RowDefinitions>
                <RowDefinition Height="220" />
            </Grid.RowDefinitions>

            <Grid.Resources>
                <DataTemplate x:Key="SampleItemTemplate">
                    <VerticalStackLayout Spacing="4">
                        <Label Text="{Binding Title, Mode=OneWay}" FontAttributes="Bold" />
                        <Label Text="{Binding Description, Mode=OneWay}" />
                    </VerticalStackLayout>
                </DataTemplate>
            </Grid.Resources>

            <CarouselView x:Name="carousel"
                         ItemTemplate="{StaticResource SampleItemTemplate}"
                         Loop="False"
                         HeightRequest="220"
                         Grid.Row="0"
                         BackgroundColor="LightBlue" />
        </Grid>
    </ScrollView>
</ContentPage>
```

```csharp
private class SampleCarouselItem
{
    public SampleCarouselItem( string title, string description )
    {
        Title = title;
        Description = description;
    }

    public string Title { get; set; }
    public string Description { get; set; }
}

var exampleItems = new List<SampleCarouselItem>
{
    new SampleCarouselItem( "First", "First CarouselView item" ),
    new SampleCarouselItem( "Second", "Second CarouselView item" ),
    new SampleCarouselItem( "Third", "Third CarouselView item" ),
    new SampleCarouselItem( "Fourth", "Fourth CarouselView item" ),
    new SampleCarouselItem( "Fifth", "Fifth CarouselView item" ),
};

carousel.ItemsSource = exampleItems;
```

### Steps to Reproduce

1. Create a new MAUI app
2. Add a new CarouselView inside of a ScrollView
3. Set the `Loop` property to `False`
4. Observe bug

### Link to public reproduction project repository

https://github.com/bradencohen/MauiRepros/

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17+ (maybe earlier)

### Did you find any workaround?

Setting `Loop` to true.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by NielsKnaap**
### Description of Change

After this fix https://github.com/dotnet/maui/pull/14951 (https://github.com/dotnet/maui/pull/15652) to make to collectionview get the size of its contents instead of filling the whole screen, the size of the carouselview was impacted aswell. This introduced some layout bugs with the carouselview on iOS. 

This PR will make sure the carouselview will use the default implementation of the GetDesiredSize() method.

### Issues Fixed

- Fixes https://github.com/dotnet/maui/issues/18223
- Fixes https://github.com/dotnet/maui/issues/19657

## Before

- Example issue 18223: 

https://github.com/dotnet/maui/assets/15660304/8955b56b-5b98-4dd2-b49e-2ef1acfd262b
- Example issue 19657: 

https://github.com/dotnet/maui/assets/15660304/25e5aebe-2e80-4e07-a94d-9b6d1fe67fa7

## After

- Example issue 18223: 

https://github.com/dotnet/maui/assets/15660304/c2eeb05e-ed09-4b63-9ff9-7016c27ad071

- Example issue 19657: 

https://github.com/dotnet/maui/assets/15660304/3f24e8bb-9231-4d40-a66a-14741f4cd442

### CODE REVIEW

**Comment by NielsKnaap** [comment]
@dotnet-policy-service agree

**Comment by NielsKnaap** [comment]
hi @rmarinho, why are some of the pipelines failing? Can I do something about it?

**Comment by NielsKnaap** [comment]
@rmarinho @mattleibow, Is there anything to be done for this PR?

**Review by rmarinho — APPROVED** [review]

**Review by mattleibow — APPROVED** [review]

**Pull request merged**
