### PR TITLE
[WinUI] Add workaround for Connectivity check on Win10 

### LINKED ISSUE #15843: [regression/7.0.0] Connectivity.ConnectivityChanged Event throws exception at network change
### Description

This exception is thrown at network connection change after I subscribe to Connectivity.ConnectivityChanged event

**"The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD))"**

### Steps to Reproduce

1. Create a new . NET MAUI App, framework .NET 7.0 
2. Subscribe to Connectivity.ConnectivityChanged event
3. `Connectivity.ConnectivityChanged += (sender, e) => 
		{ 
			// never reach this point
		};`
4. start the app in Debug mode and change network connection to see the exception. This exception does not crash the app. 

**"The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD))"**
Screenshot (213)

In Release mode it seems the only problem is if the event never get called.

If I change Windows target framework to .NET 6.0, event is called and it seems fine, but exception message is there

Screenshot (215)

It works fine on Android.

### Link to public reproduction project repository

https://github.com/mrherkar/MauiAppWithConnectivityChangedIssue

### Version with bug

7.0.86

### Last version that worked well

6.0

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

no

### Relevant log output

```shell
C:\Windows\system32>dotnet workload list

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui-windows               7.0.86/7.0.100         VS 17.6.33815.320
maui-maccatalyst           7.0.86/7.0.100         VS 17.6.33815.320
maccatalyst                16.4.7067/7.0.100      VS 17.6.33815.320
maui-ios                   7.0.86/7.0.100         VS 17.6.33815.320
ios                        16.4.7067/7.0.100      VS 17.6.33815.320
maui-android               7.0.86/7.0.100         VS 17.6.33815.320
android                    33.0.46/7.0.100        VS 17.6.33815.320
```

### LINKED ISSUE #17270: Windows: Connectivity check sometimes return NetworkAccess.Unknown
### Description

On Windows checking connectivity returns incorrect value of NetworkAccess.Unknown.

There is this already closed issue: https://github.com/dotnet/maui/issues/9972

But this for sure is not fixed because I can still reproduce it.

### Steps to Reproduce

Here is the tricky part. I cannot provide any particular repro steps. In my app this can reproduce in some particular screens, in other happens only sometimes. 

I tried create a demo sample app but I could not reproduce there.
Of course I tried calling on the main thread the check as a suggestions made in the https://github.com/dotnet/maui/issues/9972. But sometimes it works, sometimes not.

It happens also with .Net 8 - preview 7.8842

### Link to public reproduction project repository

No sample

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

_No response_

### Did you find any workaround?

No

### Relevant log output

```shell
Exception thrown at 0x00007FFB8C31CF19 (KernelBase.dll) : The application called an interface that was marshalled for a different thread.
```

### PR DESCRIPTION
**Pull request by Foda**
### Description of Change

This PR adds a work-around for an issue only present on Windows 10 (21H2/22H2) where calling and accessing data from `Windows.Networking.Connectivity.NetworkInformation` is only permitted on the first thread that accesses it. See: https://github.com/microsoft/WindowsAppSDK/issues/2965

The work-around uses the same underlying APIs (Win32 NLM) as the ones used by WinRT combined with the native .NET Networking APIs.

### Issues Fixed

- Fixes #17270
- Fixes #15843

### CODE REVIEW

**Comment by rmarinho** [comment]
Should we add a manual test to our plan to test the connectivity in all platforms ?

**Review by PureWeen — CHANGES_REQUESTED** [review]
The state of the connectivity variable looks to be backwards inside the event. 

If I enable my network connection, then the state is "None"
If I disable my network the connection, goes to "Internet"

It does look like this code fixes the threading crash issue. 

image

**Comment by mattleibow** [comment]
I ran the essentials sample on Win 11 using the Win 10 code (removed the win 11 code path) and I got the correct values. @PureWeen do you have a snippet of code that you ran just to make sure I get the same thing. 

I wonder if the VM is causing issues...

**Comment by mattleibow** [comment]
@Foda I see you reverted the events, are you doing something more or is this ready to review/test again?

**Comment by mattleibow** [comment]
This PR seems to work on 22H2 in a VM, I am testing now on 21H2

**Comment by Foda** [comment]
I was actually unable to get the event to fire on my machine, so I reverted it to use the old event. After testing it seemed to work fine on my Win10 VM and Win11 main machine.
________________________________

**Comment by mattleibow** [comment]
Seems to work here too. Looking good!

**Review by mattleibow — DISMISSED** [review]

**Review by mattleibow — APPROVED** [review]

**Review by PureWeen — APPROVED** [review]

**Comment by PureWeen** [comment]
Failing test on Android is unrelated to this PR. This PR doesn't touch anything android related.

**Pull request merged**
