### PR TITLE
[Housekeeping] Added UI Test to validate project template

### LINKED ISSUE #17801: Add Manual Test to Validate the ScrollView behavior of our templates
### Description

Manual assessments failed to catch https://github.com/dotnet/maui/issues/17224

We need to add a manual test that validates correct operation of the scrollview on the templates.
The test will need to be disabled until 17224 is resolved. We can keep it activated against NET7 for now

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

Already added a manual test to validate the .NET MAUI project template (scrollbars). However, we can validate it also with a golden test and a reference snapshot. This PR includes the UI Test.

### Issues Fixed

Fixes #17801

### CODE REVIEW

**Comment by rmarinho** [comment]
Won't the scrollbars only appear when you interact with the app?

**Comment by jsuarezruiz** [comment]
> Won't the scrollbars only appear when you interact with the app?

That must be the behavior, but we had an issue https://github.com/dotnet/maui/issues/17224 related to it.

**Review by PureWeen — CHANGES_REQUESTED** [review]
- The original issue with the scrollbars I think was unique to shell so I think we should get this PR merged first with shell support https://github.com/dotnet/maui/pull/19444.
- Can we create screen shots for all platforms here? maybe even add some interactions? We could even add an interaction on this one to try and scroll the page and then compare that screen shot

**Comment by jsuarezruiz** [comment]
> * The original issue with the scrollbars I think was unique to shell so I think we should get this PR merged first with shell support [[Testing] Added appium UITest for FlyoutNavigationBetweenItemsWithNavigationStacks #19444](https://github.com/dotnet/maui/pull/19444).
> * Can we create screen shots for all platforms here? maybe even add some interactions? We could even add an interaction on this one to try and scroll the page and then compare that screen shot

Added and validating snapshots for all the platforms here.

**Comment by jfversluis** [comment]
We're focussing on other areas of the testing right now. Lets close this in the meantime and revisit later.

**Review by PureWeen — CHANGES_REQUESTED** [review]
iOS test is failing

**Review by rmarinho — DISMISSED** [review]

**Review by PureWeen — APPROVED** [review]

**Review by Redth — APPROVED** [review]

**Pull request merged**
