### PR TITLE
Fix project references for GTK projects

### PR DESCRIPTION
**Pull request by trampster**
This pull request fixes the project reference paths for the GTK projects, which currently point at the wrong folders.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=362) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=362) before we can accept your contribution.<br/><br/>:x: trampster [sign now](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=362)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/maui?pullRequest=362) it.</sub>

**Comment by trampster** [comment]
I'm confused about the iOS/Android build failures. I only changed GTK projects so havn't touch anything anything that could affect these. 

I also can't get to see why they failed because when I try to view the azure pipeline I get

> 401 - Uh-oh, you do not have access.

**Comment by itsme-alan** [comment]
I guess a maintainer will have to do that.

**Comment by rmarinho** [comment]
Needs rebase

**Comment by trampster** [comment]
Project structure has changed to significantly for this merge request to work.

**Pull request closed without merging**
