### PR TITLE
Update GridExtensions.cs to compatible with Xamarin

### PR DESCRIPTION
**Pull request by evolcano**
compatible with add method of Grid  in Xamarin.

### Description of Change

Add view to gird with specified row & col range simultaneously,  and compatible with Xamarin to avoid change much.

### Issues Fixed

None.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=9891) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=9891) before we can accept your contribution.<br/><br/>:x: evolcano [sign now](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=9891)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/maui?pullRequest=9891) it.</sub>

**Comment by rmarinho** [comment]
It's to late to NET7 but for NET8 we could try to add this.. Can you please also add some unit tests please? 

Thanks

**Comment by jfversluis** [comment]
@evolcano could you please let us know if you still have any interest to finish this? Thank you!

**Comment by hartez** [comment]
@jfversluis  #13408 has the same thing, but with tests and docs. We can probably close this one.

**Comment by jfversluis** [comment]
@hartez yep I already updated your initial comment to close this PR when yours gets merged!

**Pull request closed without merging**
