### PR TITLE
Review of the "Essentials" interface API

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change

As I was working through #5562, I noticed that as a result of the first pass of the Essentials API from statics to interfaces, we did not correctly updated the initial changes.

There are several cases where the API of the interface was geared towards swapping out the implementation of the static API:

```cs
interface IClipboard {
    Task<string> GetTextAsync();
    void StartListeners();
    void StopListeners();
}
```

However, this is incorrect and unhelpful in the new world where the interface is supposed to be self contained an mockable:

```cs
interface IClipboard {
    Task<string> GetTextAsync();
    event EventHandler<EventArgs> ClipboardContentChanged;
}
```

### API Changes

> Originally we were going to make the new API be instance based and remove (then we changed to just obsolete) the static methods, however, this is a massive change and no benefit. Sure, it is a bit _weird_ to have a `Accelerometer.Start()` AND `Accelerometer.Default.Start()`, however, as can be seen from the diff - this means no code changes for anyone that was using essentials and then Maui.

However, with the work we have been doing with these APIs over the month, we now have a useful as well as "opt-in" way of using essentials.

Previously there was no way to mock/test using essentials, and thus you either had to roll your own abstraction or get someone else to do it. 

Now, we have all that work in the box, thanks to several PRs and adjustments. And no code changes for existing usage.

#### Static APIs

If you are writing a simple app and don't believe in testing, you can write code like this using the static APIs `Geolocation.GetLocationAsync()`:

```cs
class MyViewModel
{
    public async Task UploadLocationAsync()
    {
        var location = await Geolocation.GetLocationAsync();
        var uploader = MyUploader();
        await uploader.UploadLocationAsync(location);
    }
}
```

#### Instance / DI-Friendly APIs

However, if you _want_ to create a testable system or use DI, you now can using the instance APIs `Geolocation.Default.GetLocationAsync()`:

```cs
class MyViewModel
{
    public MyViewModel(IGeolocation geolocation, IUploader uploader)
    {
        // TODO: set fields
    }

    public async Task UploadLocationAsync()
    {
        var location = await deolocation.GetLocationAsync();
        await uploader.UploadLocationAsync(location);
    }
}
```

Now you an also use DI or write tests:

```cs
async Task TheBigTest()
{
    var vm = new MyViewModel(new StubGeolocation(), new StubUploader());
    await UploadLocationAsync();

    // TODO: assert location was retrieved and then uploaded
}
```

### CODE REVIEW

**Comment by mattleibow** [comment]
Based on some preliminary discussions offline, maybe we can compromise as well as organize and prepare for net7 by keeping the static classes in the Essentials namespace, but move the things we want to move in future into the new namespaces:

```cs
namespace Maui.Essentials {
    static class Accelerometer {
        static IAccelerometer Current { get; }
        static void Start() => Current.Start();
    }
}
```
```cs
namespace Maui.Devices.Sensors {
    interface IAccelerometer {
        void Start();
    }
    class AccelerometerChangedEventArgs { }
    struct AccelerometerData { }
}
```

We can keep the `Current` APIs public for now, but make the `SetCurrent` and `XxxImplementation` internal because we will move them. This will allow people to start using the interfaces for testing, and then get the perfect experience in .NET 7.

```cs
class MyViewModel {
    public MyViewModel (IAccelerometer accl) {}
}
```

```cs
class Tests {
    void TestMyVM() {
        var mockAcc = GetMockedThing();
        var myvm = new MyViewModel(mockAccl);
    }
}
```

But, in .NET 7, we obsolete the Essentials namespace, and create equivalent APIs in the new namespaces:

```cs
namespace Maui.Essentials {
    [Obsolete]
    static class Accelerometer {
        static IAccelerometer Current => Maui.Devices.Sensors.Accelerometer.GetDefault();
        static void Start() => Current.Start();
    }
}
```

```cs
namespace Maui.Devices.Sensors {
    class Accelerometer {
        static SetFactory(IAccelerometerFactory factory);
        static IAccelerometer GetDefault();
        static IEnumerable<IAccelerometer> GetAll();
    }
    interface IAccelerometer {
        void Start();
    }
    interface IAccelerometerFactory {
        IAccelerometer GetDefault();
        IEnumerable<IAccelerometer> GetAll();
    }
    class AccelerometerChangedEventArgs { }
    struct AccelerometerData { }
}
```

**Comment by Redth** [comment]
@mattleibow  I wonder if we still want all the Implementation classes to live in the .Implementation namespace?

**Comment by mattleibow** [comment]
Right now I am moving them internal and back into the nice namespace.

In net7 we can figure out a nice way for users to set this.

The plan now is to make Accelerometer.Default return the OS accelerometer, but via an interface. If you want code to be testable, do t use the static in vms, use the interface and DI using .Default.

Think of the static as a way to get the OS instance, but in reality you need to make your apis testable, not our initial idea to make the core OS testable.

See for example things starting with A to F. Done that half first and will continue tomorrow.

**Comment by Redth** [comment]
I missed that you made them internal, that works for me for net6 timeframe

**Review by Redth — APPROVED** [review]

**Comment by drasticactions** [comment]
As @mattleibow asked me about it, Hot Reload (currently) doesn't use the Essentials API directly. We only call into Core or Controls (and we're trying to move more calls we make to use Core for compatibility reasons). As long as the Core APIs and namespaces stay the same, we should be fine.

**Comment by mattleibow** [comment]
I am moving MainThread out of Essentials into compatibility because of https://github.com/dotnet/maui/issues/5536

We can move it back in rc2 if we get a better solution, but for now, main thread things will crash in multi-window on multi-thread. This is not the _default_, but is also not some weird concept.

**Review by Redth — APPROVED** [review]

**Review by drasticactions — APPROVED** [review]

**Pull request merged**
