### PR TITLE
[iOS] Added DidPopItem to the navigation renderer

### LINKED ISSUE #26216: iOS - OnNavigatedFrom is not fired when navigating back by swiping
### Description

On iOS devices, OnNavigatedFrom is not fired when navigating back from a page by swiping.

It does work when navigating back using the back button.

Video:
Image

### Steps to Reproduce

Steps:
1. Open the repro app
2. Tap the navigate button
3. Navigate back by swiping
4. The navigated from alert is not shown

The alert is show if navigating back using the back button.

### Link to public reproduction project repository

https://github.com/eth-ellis/Issue-Repro/tree/main/OnNavigatedFromAfterSwipe

### Version with bug

8.0.100 SR10

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

_No response_

### Did you find any workaround?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by kubaflo**
### Issues Fixed

Fixes https://github.com/dotnet/maui/issues/26216

|Before|After|
|--|--|
|<video src="https://github.com/user-attachments/assets/114b8d87-2beb-4ff3-afcb-bb796df95f04" width="300px"/>|<video src="https://github.com/user-attachments/assets/1d48909f-7144-41a2-81b7-785ae486973a" width="300px"/>|

### CODE REVIEW

**Comment by eth-ellis** [comment]
@kubaflo Does this fix the linked issue?
The issue refers to navigating back by the user swiping, but the before and after videos above only show the back button being used.

**Comment by kubaflo** [comment]
> @kubaflo Does this fix the linked issue? The issue refers to navigating back by the user swiping, but the before and after videos above only show the back button being used.

Yeah, I see, the simulator screed didn't capture my swipe gesture, but the first navigation back was performed using the swipe. However, I think it would be best if you also tried it with a build generated by this PR :)

**Comment by jfversluis** [comment]
Could it be that you switched the videos for before and after? 😄

**Review by jfversluis — APPROVED** [review]

**Comment by kubaflo** [comment]
> Could it be that you switched the videos for before and after? 😄

Oh yes, my bad😅

**Comment by kubaflo** [comment]
@jfversluis could you also please have a look at this one: https://github.com/dotnet/maui/pull/24003
It is very similar but for shell pages

**Pull request merged**
