### PR TITLE
[Trimming] Enable analyzers in Controls.Core on Tizen

### PR DESCRIPTION
**Pull request by simonrozsival**
### Description of Change

This PR enables analyzers on Tizen and fixes all the warnings that were reported by these analzyers.

### Issues Fixed

Contributes to #18658

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
@JoonghyunCho @rookiejava maybe you can review? Thanks!

**Review by rookiejava — APPROVED** [review]
Thanks!

**Review by JoonghyunCho — APPROVED** [review]
Thanks for the fixes!

**Review by PureWeen — APPROVED** [review]

**Review by jonathanpeppers — APPROVED** [review]

**Pull request merged**
