### PR TITLE
Optimize TemplateUtilities

### PR DESCRIPTION
**Pull request by symbiogenesis**
This is a utility file that is going to ultimately be used by any control that inherits from IControlTemplated

It is doing a lot of unnecessary casting.

Each commit is hopefully doing something uncontroversial.

### CODE REVIEW

**Comment by mattleibow** [comment]
Is it possible to add a benchmark?

**Comment by symbiogenesis** [comment]
Wasn't able to make much of a difference on performance here, but these are some worthwhile cleanups, and the benchmark may be useful.

**Comment by symbiogenesis** [comment]
Latest version that drops the Queue collection

Before:

| Method                              | Mean      | Error     | StdDev    | Gen0      | Gen1      | Gen2     | Allocated |
|------------------------------------ |----------:|----------:|----------:|----------:|----------:|---------:|----------:|
| ChangeContent                       | 13.335 ms | 1.0091 ms | 2.9754 ms | 1000.0000 |         - |        - |   9.11 MB |
| ChangeTemplate                      | 37.803 ms | 0.7499 ms | 0.8024 ms | 3642.8571 | 3571.4286 |        - |  32.76 MB |
| ChangeTemplateContentPresenters |  7.586 ms | 0.1413 ms | 0.1252 ms |  734.3750 |  726.5625 | 179.6875 |   6.63 MB |

After:

| Method                              | Mean      | Error     | StdDev    | Gen0      | Gen1      | Gen2     | Allocated |
|------------------------------------ |----------:|----------:|----------:|----------:|----------:|---------:|----------:|
| ChangeContent                       | 10.138 ms | 0.1931 ms | 0.4700 ms | 1000.0000 |         - |        - |   9.11 MB |
| ChangeTemplate                      | 37.410 ms | 0.7270 ms | 0.8372 ms | 3538.4615 | 3461.5385 |        - |  31.85 MB |
| ChangeTemplateContentPresenters |  7.796 ms | 0.1541 ms | 0.1892 ms |  703.1250 |  687.5000 | 156.2500 |   6.44 MB |

**Pull request closed without merging**
