### PR TITLE
Allow CommunityToolkit to avoid reflection to access the CollectionView controller

### PR DESCRIPTION
**Pull request by VladislavAntonyuk**
### Description of Change

Update protected to internal

### Issues Fixed

Fixes https://github.com/CommunityToolkit/Maui/pull/751

### CODE REVIEW

**Comment by inforithmics** [comment]
Shouldn't this be protected internal

**Comment by brminnick** [comment]
Specifically, this PR allows us to avoid needing to implement [this specific use of reflection](https://github.com/CommunityToolkit/Maui/pull/751#discussion_r1029940985) to fix a bug around `Expander` + `CollectionView`

**Review by rmarinho — APPROVED** [review]

**Comment by curia-damiano** [comment]
Hi all,
Thank you for your support!
In which version of .NET 7 will this PR be published? Do you have an idea when?
Regards, Damiano

**Pull request merged**
