### PR TITLE
Maps

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Add Maps support for Android and iOS.

### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)

#### Does this PR touch anything that might affect accessibility?
- No

### CODE REVIEW

**Comment by mattleibow** [comment]
I added the Maps to my net6 PR #1099

**Comment by jsuarezruiz** [comment]
@mattleibow Ok, then, better remove the changes in this PR and only leave the Maps sample in the Gallery?

**Comment by mattleibow** [comment]
The projects and solution was merged in with #1359 
We can just keep the sample now

**Comment by davidbuckleyni** [comment]
It would be great if a way we could give a series of pints and be able to hook the map up to a timer some way and gps like apps like map my run and such.

**Pull request closed without merging**
