### PR TITLE
Bump Appium version to 2.11

### PR DESCRIPTION
**Pull request by PureWeen**

### CODE REVIEW

**Review by jfversluis — DISMISSED** [review]

**Comment by jfversluis** [comment]
Do we want to update our internal provisioning template too?

Anyway, this looks good!

**Review by jfversluis — DISMISSED** [review]
I still approve 🌮

**Review by Redth — DISMISSED** [review]

**Comment by PureWeen** [comment]
There's still one test failure on Android we need to resolve. We'll fix that in a separate PR since this fixes the issue with none of our UITests running.

**Pull request merged**
