### PR TITLE
Implement InputView IsSpellCheckEnabled property

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Implement InputView `IsSpellCheckEnabled` property.
- Entry
- Editor
- SearchBar

### PR Checklist ###

- [x] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)

#### Does this PR touch anything that might affect accessibility?
- No

### CODE REVIEW

**Comment by rmarinho** [comment]
Seems tests are failing here

**Comment by rmarinho** [comment]
needs rebase

**Comment by Redth** [comment]
@jsuarezruiz can you please fix conflicts and rebase

**Review by Redth — APPROVED** [review]

**Comment by rmarinho** [comment]
needs rebase again @jsuarezruiz

**Comment by rmarinho** [comment]
@jsuarezruiz  can you fix thsi build ?

```
     (CoreCompile target) -> 
         D:\a\_work\1\s\src\Core\src\Handlers\Editor\EditorHandler.cs(24,44): error CS0103: The name 'MapIsSpellCheckEnabled' does not exist in the current context [D:\a\_work\1\s\src\Core\src\Core.csproj]
         D:\a\_work\1\s\src\Core\src\Handlers\Entry\EntryHandler.cs(30,43): error CS0103: The name 'MapIsSpellCheckEnabled' does not exist in the current context [D:\a\_work\1\s\src\Core\src\Core.csproj]
         D:\a\_work\1\s\src\Core\src\Handlers\SearchBar\SearchBarHandler.cs(30,47): error CS0103: The name 'MapIsSpellCheckEnabled' does not exist in the current context [D:\a\_work\1\s\src\Core\src\Core.csproj]

```

**Pull request closed without merging**
