### PR TITLE
Align the controls used in the different templates

### LINKED ISSUE #7424: [BUG] GA Fix Source Generation for when Adding new Maui Pages as still using old Stack Layout and not  VerticalStackLayout
### Description

When a new project is created it creats the MainPage.Xaml which is fine  as you can see it has the right stacklayout name 

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp2.MainPage">
             
    <ScrollView>
        <VerticalStackLayout 
            Spacing="25" 
            Padding="30,0" 
            VerticalOptions="Center">

            <Image
                Source="dotnet_bot.png"
                SemanticProperties.Description="Cute dot net bot waving hi to you!"
                HeightRequest="200"
                HorizontalOptions="Center" />
                
            <Label 
                Text="Hello, World!"
                SemanticProperties.HeadingLevel="Level1"
                FontSize="32"
                HorizontalOptions="Center" />
            
            <Label 
                Text="Welcome to .NET Multi-platform App UI"
                SemanticProperties.HeadingLevel="Level2"
                SemanticProperties.Description="Welcome to dot net Multi platform App U I"
                FontSize="18"
                HorizontalOptions="Center" />

            <Button 
                x:Name="CounterBtn"
                Text="Click me"
                SemanticProperties.Hint="Counts the number of times you click"
                Clicked="OnCounterClicked"
                HorizontalOptions="Center" />

        </VerticalStackLayout>
    </ScrollView>
 
</ContentPage>
```
But this is produced from the right click add new .net Maui Content Page.Xaml with code behind file

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp2.NewPage1"
             Title="NewPage1">
    <StackLayout>
        <Label Text="Welcome to .NET MAUI!"
                VerticalOptions="Center" 
                HorizontalOptions="Center" />
    </StackLayout>
</ContentPage>
```

### Steps to Reproduce

1. Create a new Maui App
2. Right Click on MauiApp click add new item
3. Select New Content Page Xaml
.
4 image

5. Click add inspect the xaml their
```

<?xml version="1.0" encoding="utf-8" ?>
<ContentView xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp2.NewContent1">
    <StackLayout>
        <Label Text="Welcome to .NET MAUI!"
                VerticalOptions="Center" 
                HorizontalOptions="Center" />
    </StackLayout>
</ContentView>

```

The issue is that the stack layout tag is wrong and should be using the new VerticalStackLayout tag as per MainPage.xaml

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Xaml Issue only

### Did you find any workaround?

This appears to be a xaml issues only yes one can simply replace the tag but the source generator should be updated.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change

While creating an App from template we use `VerticalStackLayout`, when creating a ContentPage or ContentView we use `StackLayout`. This PR adds changes to align the templates and use the same in all cases.

### Issues Fixed

Fixes #7424

### CODE REVIEW

**Comment by rmarinho** [comment]
I would do everything using StackLayout tbh

**Comment by davidbuckleyni** [comment]
@jsuarezruiz Man ur to quick I was going to do it if was an easy fix lol

**Comment by jsuarezruiz** [comment]
> @jsuarezruiz Man ur to quick I was going to do it if was an easy fix lol

Oops. Thanks for the interest in fixing it in any way!

**Comment by jsuarezruiz** [comment]
> I would do everything using StackLayout tbh

@davidortinau What should we use everywhere, `StackLayout` or `VerticalStackLayout`?

**Comment by davidortinau** [comment]
I suggest using the new, specific layouts when there is no reason to toggle between orientations. It's explicit.

**Comment by jamesmontemagno** [comment]
I would use VerticalStackLayout to show it as new in there IMHO

**Review by jamesmontemagno — APPROVED** [review]

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
