### PR TITLE
Changes requires to effectively use the Blazor controls as a base class

### PR DESCRIPTION
**Pull request by budcribar**
### Description of Change ###

Implements #1603 

### Additions made ###

Added IWebViewManager  to both Maui and Wpf/WinForms
Created a new virtual method CreateWebViewManager so that subclasses can override the WebViewManager and the FileProvider
Made the corresponding changes needed to implement IWebViewManager

Ooops- accidently changed the white space on lines 180-193 of WindowsForms BlazorWebView.cs This should be reverted 
also lines 56-59, 115-118 of Wpf BlazorWebView.cs and lines 11-20 on RootComponent.cs

### PR Checklist ###

- [ ] Targets the correct branch 
- [ ] Tests are passing (or failures are unrelated)
- [ ] Targets a single property for a single control (or intertwined few properties)
- [ ] Adds the property to the appropriate interface
- [ ] Avoids any changes not essential to the handler property
- [ ] Adds the mapping to the PropertyMapper in the handler
- [ ] Adds the mapping method to the Android, iOS, and Standard aspects of the handler
- [ ] Implements the actual property updates (usually in extension methods in the Platform section of Core)
- [ ] Tags ported renderer methods with [PortHandler]
- [ ] Adds an example of the property to the sample project (MainPage)
- [ ] Adds the property to the stub class
- [ ] Implements basic property tests in DeviceTests

#### Does this PR touch anything that might affect accessibility?
- [ ] Does this PR introduce a new control? (If yes, add an example using SemanticProperties to the SemanticsPage)
- [ ] APIs that modify focusability?
- [ ] APIs that modify any text property on a control?
- [ ] Does this PR modify view nesting or view arrangement in anyway?
- [ ] Is there the smallest possibility that your PR will change accessibility? 
- [ ] I'm not sure, please help me

If any of the above checkboxes apply to your PR, then the PR will need to provide testing to demonstrate that accessibility still works.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=1636) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=1636) before we can accept your contribution.<br/><br/>:x: budcribar [sign now](https://cla.dotnetfoundation.org/dotnet/maui?pullRequest=1636)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/maui?pullRequest=1636) it.</sub>

**Comment by Eilon** [comment]
Hi @budcribar thanks for sending the PR! I'm not sure I understand why the new `IWebViewManager` is necessary instead of making more things public/virtual on WebViewManager itself. Would that instead be simpler but sufficient? (This might mean we need to make changes in https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebView/WebView/src/WebViewManager.cs, but that's fine.)

**Comment by budcribar** [comment]
Hi @Eilon,

I  need to override a couple of methods such as SendMessage and NavigateCore in WebView2WebViewManager. However, for  example, in Winforms  BlazorWebView.cs there is nothing I can override to be able to inject my derived  WebView2WebViewManager because line 142 creates an instance  _webviewManager = new WebView2WebViewManager

So, instead I propose 
_webviewManager = CreateWebViewManager

where
protected virtual IWebViewManager CreateWebViewManager 
can be overridden.

Since I have derived the RemoteWebView2Manager from WebView2WebViewManager the _webviewManager instance variable  in BlazorWebView.cs could stay typed as WebView2WebViewManager but I noticed that you were moving to using interfaces instead of concrete classes, so I followed suit.


With the ability to specify my version of the WebView2Manager.cs and use the BlazorWebView,cs, I have to implement just a 
couple of things to be able to add the remoting features and also embed the wwwroot files.

Let me know what you think...


**So, here is my RemoteWebView2Manager.cs**
public class RemoteWebView2Manager : WebView2WebViewManager, IWebViewManager
    {
        Uri url;
        public RemotableWebWindow RemoteableWebView { get; set; }
       
        public RemoteWebView2Manager(IWebView2Wrapper webview, IServiceProvider services, Dispatcher dispatcher, IFileProvider fileProvider, string hostPageRelativePath, Uri url, Guid id) : base(webview, services, dispatcher, fileProvider, hostPageRelativePath)
        {
            RemoteableWebView = new RemotableWebWindow(
                url,
                hostPageRelativePath,
                dispatcher,
                new CompositeFileProvider(StaticWebAssetsLoader.UseStaticWebAssets(fileProvider), new EmbeddedFileProvider(Assembly.GetExecutingAssembly())),
                id == default ? Guid.NewGuid() : id
                );

            RemoteableWebView.OnWebMessageReceived += RemoteOnWebMessageReceived;
            RemoteableWebView.Initialize();
            this.url = new Uri("https://0.0.0.0/");
        }

        private void RemoteOnWebMessageReceived(object? sender, string e)
        {
            var url = sender?.ToString() ?? "";
            if (RemoteableWebView.ServerUri != null && url.StartsWith(RemoteableWebView.ServerUri.ToString()))
            {
                url = url.Replace(RemoteableWebView.ServerUri.ToString(), this.url?.ToString() ?? "");
                url = url.Replace(RemoteableWebView.Id.ToString() + $"/", "");
                if (url.EndsWith(RemoteableWebView.HostHtmlPath)) url = url.Replace(RemoteableWebView.HostHtmlPath, "");
                MessageReceived(new Uri(url), e);
            }
            else
                MessageReceived(new Uri(sender?.ToString() ?? ""), e);
        }

        protected override void NavigateCore(Uri absoluteUri)
        {
            this.url = absoluteUri;
            RemoteableWebView.NavigateToUrl(absoluteUri.AbsoluteUri);
        }

        protected override void SendMessage(string message)
        {
            RemoteableWebView.SendMessage(message);
        }
    }


**and here is my derrived BlazorWebView.cs**

 public override IWebViewManager CreateWebViewManager(IWebView2Wrapper webview, IServiceProvider services, Dispatcher dispatcher)
        {
            // We assume the host page is always in the root of the content directory, because it's
            // unclear there's any other use case. We can add more options later if so.
            var contentRootDir = Path.GetDirectoryName(Path.GetFullPath(HostPage));
            if (contentRootDir == null) throw new Exception("No root directory found");
            var hostPageRelativePath = Path.GetRelativePath(contentRootDir, HostPage);

            // TODO Extract to method
            IFileProvider provider;

            var root = Path.GetDirectoryName(HostPage) ?? string.Empty;
            try
            {
                EmbeddedFilesManifest manifest = ManifestParser.Parse(new FixedManifestEmbeddedAssembly(Assembly.GetEntryAssembly()!));
                var dir = manifest._rootDirectory.Children.Where(x => (x as ManifestDirectory)?.Children.Any(y => y.Name == root) ?? false).FirstOrDefault();

                if (dir != null)
                {
                    var manifestRoot = Path.Combine(dir.Name, root);
                    provider = new ManifestEmbeddedFileProvider(new FixedManifestEmbeddedAssembly(Assembly.GetEntryAssembly()!), manifestRoot);
                }
                else provider = new PhysicalFileProvider(contentRootDir);
            }
            catch (Exception) { provider = new PhysicalFileProvider(contentRootDir); }

            if (ServerUri == null)
                WebViewManager = new WebView2WebViewManager(webview, services, dispatcher, provider, hostPageRelativePath);
            else
                WebViewManager = new RemoteWebView2Manager(webview, services, dispatcher, provider, hostPageRelativePath, ServerUri, Id);

            return WebViewManager;
        }

**Comment by budcribar** [comment]
@Eilon , Closing this request and reopened new one with the minimal changes required. (i.e. No additional interface just a couple of changes to BlazorWebView.cs (both Wpf and WinForms)

**Comment by Eilon** [comment]
OK thanks!

**Comment by sbwalker** [comment]
@budcribar the changes in this PR appear to allow a BlazorWebView to handle remote static assets ie. if I wanted my shared razor components to use relative URLs when running on Blazor Server or Blazor WebAssembly, and absolute URLs when running in Blazor Hybrid. Did the concepts in this PR ever materialize in BlazorWebView? Currently the only guidance I have seen is to maintain duplicate copies of all static assets (and manually keep them in sync) or use ugly hacks to construct the URLs in the appropriate format with the components themselves. This seems to be a huge gap in delivering the component re-usability which Microsoft claims as a primary benefit of Blazor as a cross platform solution. I am hoping you are able to shed light on a solution which is supported but not documented. Keeping my fingers crossed…

**Comment by Eilon** [comment]
@sbwalker - hi Shaun, can you log a new issue to discuss that? Static Web Assets that are in a Razor Class Library (RCL) should always have exactly the same URL no matter where they are used, because their URL is based on the package name they are in.

**Comment by sbwalker** [comment]
@Eilon I created the issue here https://github.com/dotnet/maui/issues/10898

**Pull request closed without merging**
