### PR TITLE
[Windows] Fix for the screen does not display when changing the CurrentPage of a TabbedPage

### LINKED ISSUE #25518: [Windows] The screen does not display when changing the CurrentPage of a TabbedPage.
### Description

When changing the `CurrentPage` of a `TabbedPage`, the screen displays as expected on Android and iOS, but it does not display on Windows.
This issue started occurring from MAUI 8.0.90.
Is there a solution to this problem?

I have created an example project that reproduces the issue here: https://github.com/matomsan/Maui.Sample.TabbedPage

TabMultiPage.cs :
```c#
public class TabMultiPage : TabbedPage {
    public TabMultiPage()
    {
        var page = new MainPage() { Title = "One" };
        Children.Add(page);
        CurrentPage = Children[0];
    }

    public async Task SwitchTabMultiPageAsync()
    {
        var page = new NewPage1() { Title = "Two" };
        Children.Add(page);
        CurrentPage = Children[1];
    }
}
```

**However, there are some important notes.**
In my project, I am layering `ContentPage` elements on top of each other.
I add two `ContentPage` elements to an `ObservableCollection` and use a handler to add them to the native controls.
On Windows, it seems there is an issue with this handler.

MultiLayerPage.cs :
```c#
public class MultiLayerPage : ContentPage {
    public MultiLayerPage()
    {
        Children = new ObservableCollection<Page>();
        Children.CollectionChanged += Children_CollectionChanged;
    }

    public ObservableCollection<Page> Children { get; }
}
```

MultiLayerPageHandler.Windows.cs :
```c#
public partial class MultiLayerPageHandler : ViewHandler<Views.MultiLayerPage, ContentPanel> {

    public static PropertyMapper<Views.MultiLayerPage, MultiLayerPageHandler> PropertyMapper = new PropertyMapper<Views.MultiLayerPage, MultiLayerPageHandler>(ViewHandler.ViewMapper) {
    };

    public MultiLayerPageHandler() : base(PropertyMapper)
    {
    }

    protected override void ConnectHandler(ContentPanel platformView)
    {
        base.ConnectHandler(platformView);
        platformView.Loaded += OnLoaded;

        foreach (var child in VirtualView.Children) {
            var element = child.ToPlatform(MauiContext);
            platformView.Children.Add(element);
        }
    }
}
```

### Steps to Reproduce

When dynamically updating the CurrentPage of a TabbedPage, a yellow screen is displayed in v8.0.82. However, in v8.0.90, nothing is displayed. In v8.0.90, resizing the window causes the yellow screen to appear.

|v8.0.82|v8.0.90|
|:-:|:-:|
|<video src="https://github.com/user-attachments/assets/09fffc02-32d8-4e0e-aa97-fa3032436ec8">|<video src="https://github.com/user-attachments/assets/5d294bff-b636-411e-b07d-e5b20e687389">|

### Link to public reproduction project repository

https://github.com/matomsan/Maui.Sample.TabbedPage

### Version with bug

8.0.90 SR9

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.82 SR8.2

### Affected platforms

Windows

### Affected platform versions

_No response_

### Did you find any workaround?

Unfortunately I haven't found any good workaround for this issue.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Tamilarasan-Paranthaman**
### Root cause
While navigating to the next page, the MeasureOverride method is repeatedly called on the parent, which prevents the Arrange method from being called.
 
### Description of change
 
The OnChildMeasureInvalidatedInternal method has been modified to ensure that measure invalidation is only propagated to the parent when necessary, preventing unnecessary repeated calls to OnChildMeasureInvalidatedInternal.

### References

- Breaking PR: https://github.com/dotnet/maui/pull/23052
- Fix Reference: https://github.com/dotnet/maui/pull/24823

### Issues Fixed

Fixes #25518

### Tested the behaviour in the following platforms

- [x] Android
- [x] Windows
- [ ] iOS
- [ ] Mac

### Screenshot

https://github.com/user-attachments/assets/f722f3d0-fc58-40b1-a81e-518ee8c81faa

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
Could you rebase to fix the conflicts? Thanks in advance.

**Comment by albyrock87** [comment]
@Tamilarasan-Paranthaman may you check if https://github.com/dotnet/maui/pull/25664 solves this issue too?

**Review by PureWeen — CHANGES_REQUESTED** [review]
Add a test

**Comment by Shalini-Ashokan** [comment]
@PureWeen, I have added test cases

**Comment by PureWeen** [comment]
Closing this for now

https://github.com/dotnet/maui/issues/25518#issuecomment-2465929039

**Pull request closed without merging**
